### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by dvv** [visionmedia/superagent#1]
Hi!

Please, consider taking care of those who behind proxies ;) Say, https://github.com/dvv/F/blob/master/lib/wget.js

TIA,
--Vladimir

**Comment by PeterDaveHello** [comment]
hmmm ... sorry to comment on an old issue, but I have a question, no offense, can't we just respect the environment variable `http_proxy` but can only rely on another package?

**Comment by pornel** [comment]
AFAIK node's own http request handling doesn't automagically pick the proxy, and superagent behaving differently could surprising, so an explicit `superagent-proxy` call seems like an OK solution to me.
