### ISSUE TITLE
.end reports client-side errors if they occur in the callback

### ISSUE THREAD

**Issue by YeahButHats** [visionmedia/superagent#1000]
Version 2.0.0

Assuming you have the code:

```
Request.get(/* location that returns with 2xx */)
  .end((error, response) => {
    if (error) {
      console.log(error)
      return
    }
    if(response.ok) {
      console.log('ok')
      nonExistantThing.go();
    }
  })
```

You get the following log messages after making a single request:

```
ok
ReferenceError: nonExistantThing is not defined(…)
```

When the error occurs in the callback, it's still in the second try/catch block in the Request function (client.js:504-517, specifically line 506). What happens is that it swallows the JS error, and re-reports it through the same callback function. When this happens, you lose any context for the error (Stack trace, line number, etc).

My testing indicates that moving the callback functions out of the try block fixes the issue, but I don't know if the callbacks are in the try block for a reason.

**Comment by pornel** [comment]
That was done for #985 I think we can shuffle things around a bit
