### ISSUE TITLE
Does superagent have a standalone version for browser?

### ISSUE THREAD

**Issue by littlee** [visionmedia/superagent#1004]
Do I have to use module bundler to use superagent in browser?

Is there somthing like below?
```html
<script src="/path/to/superagent.js"></script>
<script>
var request = new superagent();
request.get('some/end/point').end(function(err, res){/*...*/});
</script>
```

**Comment by pornel** [comment]
Yes. `node_modules/superagent/superagent.js` works in the browser as-is.

**Comment by AlexZeitler** [comment]
For me `var request = superagent;` instead of `var request = new superagent();` did the trick.

**Comment by anonym24** [comment]
@pornel I installed superagent with npm but I don't have such fodler

**Comment by pornel** [comment]
@anonym24 `npm i superagent; ls -l node_modules/superagent/superagent.js` works for me. You definitely should have that after successful install.
