### ISSUE TITLE
concatenate calls

### ISSUE THREAD

**Issue by cancerberoSgx** [visionmedia/superagent#1006]
So, I can't find the following in open issues or documentation so I ask. For me it would be awesome if I could concatenate calls in the same statement, for example make a post and then make a get so I can use superagent calls to manage async and not having to play with promises/async, something like:

```
request

	//first obtain the token
	.post('http://localhost:3000/api/authenticate')
	.send({name: 'sg', password: 'test123'})
	.end(function(err, res)
	{
		mytoken = res.body.token;
	})

	.get('http://localhost:3000/api/utility1')
	.set('x-access-token', mytoken)
	.end(function(err, res)
	{
		console.log('operation result is: ', res.body.result);
		cb();
	});
```

Unfortunately this is not working.

**Comment by cancerberoSgx** [comment]
So I'm doing it like this, but I think the syntax would be more clear if superagent calls manage promises automatically:

````
new Promise(function(resolve, reject)
{
	//first obtain the token
	request
	.post('http://localhost:3000/api/authenticate')
	.send({name: 'sg', password: 'test123'})
	.end(function(err, res)
	{
		err ? reject(err) : resolve(res.body.token);
	})
})
.then(function(token)
{
	//now make the api call passing the token
	return new Promise(function(resolve, reject)
	{
		request
		.get('http://localhost:3000/api/utility1')
		.set('x-access-token', token)
		.end(function(err, res)
		{
			err ? reject(err) : resolve(res.body.result);
		});
	});
})
.then(function(result)
{
	//we have the api call result :)
	// console.log('operation result is: ', result);
	cb()
})
.catch(function(err)
{
	console.log('ERROR', err.toString())
	cb()
})

```

**Comment by pornel** [comment]
Superagent is a "thenable" object, so you never need `new Promise()` when interacting with it.

This works:

```js
request.post(…)
.then(postResult => {
    return request.get(…);
}.then(getResult => {
});
```

**Comment by cancerberoSgx** [comment]
Thanks, I understand, but unfortunately it is not a promise. For example, If I would like to use generators, yield, co etc, this works: 

co(function*() 
{
	var token = yield new Promise(function(resolve, reject)
	{
		request
			.post('http://localhost:3000/api/authenticate')
			.send({name: 'sgurin', password: 'test123'})
			.end(function(err, res)
			{
				err ? reject(err) : resolve(res.body.token);
			})
	});

	console.log('token obtained', token);

	var result = yield new Promise(function(resolve, reject)
	{
		request
		.get('http://localhost:3000/api/utility1')
		.set('x-access-token', token)
		.end(function(err, res)
		{
			err ? reject(err) : resolve(res.body.result);
		});
	});
	console.log('result obtained', result);
})
.catch(function(err) 
{
	expect(err).toBe(undefined); 
	console.log(err.stack);
});



but unfortunately 

var result = yield request.get(..).end(..)

won't work - that's kind of the point of this issue.

**Comment by pornel** [comment]
It is a real promise, and it works with generators.
