### ISSUE TITLE
request.get(url).pipe(stream) doesn't work for me - pipe is undefined

### ISSUE THREAD

**Issue by StMarcusDE** [visionmedia/superagent#1010]
Hi, 
I use webpack and node. When I require the superagent and start a request, the pipe method is totally missing. What am I doing wrong? Something special to configure or how to handle this?
Every help or idea is really appreciated!
Thank you!

**Comment by focusaurus** [comment]
`.pipe()` is a node-only API. Streaming is not supported in the browser. Are you using webpack to bundle your code for the browser? If you are actually running your code in node, there is no need for webpack, so don't use it on node code.

**Comment by StMarcusDE** [comment]
Hi, 
we’re using webpack for both, a mobile version of our app and a node-webkit version as desktop app. We bundle the sources to get a better loading time. We need to download hugh packages in our app, so that is why we preferred to pipe() the request. And we choose superagent, because it works on mobile and desktop. Can you point me to a solution on how to realize a download with superagent without the pipe function? Or is there a workaround?
Thank you so much
 
 
Von: Peter Lyons [mailto:notifications@github.com] 
Gesendet: Mittwoch, 22. Juni 2016 15:59
An: visionmedia/superagent <superagent@noreply.github.com>
Cc: StMarcusDE <marcus.ziegelmeier@gmail.com>; Author <author@noreply.github.com>
Betreff: Re: [visionmedia/superagent] request.get(url).pipe(stream) doesn't work for me - pipe is undefined (#1010)
 
.pipe() is a node-only API. Streaming is not supported in the browser. Are you using webpack to bundle your code for the browser? If you are actually running your code in node, there is no need for webpack, so don't use it on node code.

**Comment by focusaurus** [comment]
Just to clarify, you are using webpack to build a bundle, and then running
that bundle in node.js on a desktop via node-webkit? If so, my guess is
webpack is reading the superagent package.json browser field and bundling
the browser code instead of the node code. Could you try loading superagent
into node-webkit without browserify to test that theory? You may be able to
work around it by removing the index client line
<https://github.com/visionmedia/superagent/blob/164585fc55ca0186ad052f8f23a49f3387353599/package.json#L54>
from
superagent's package.json before bundling as well.

**Comment by pornel** [comment]
When you bundle superagent for node, you must specify [`target: "node"`](https://webpack.github.io/docs/configuration.html#target).

**Comment by pornel** [comment]
To help diagnose these surprises, maybe we should add something like:

```js
if ('undefined' === typeof window) throw Error("You've using browser version in node")
```

@focusaurus ?

**Comment by focusaurus** [comment]
Well I'd say first step would just be to document this. Throwing an error doesn't immediately strike me as a great thing to do, but I don't have any better suggestions beyond either console.log a warning or throw an error as you have above.

**Comment by bendman** [comment]
It would be nice to have documentation of the difference between the browser/standalone version and the node version.  Even something as simple as `request.get(url).end` is undefined in the browser standalone version.

**Comment by focusaurus** [comment]
@bendman `request.get(url).end(callback)` should work fine in both the browser and node. If you are seeing reproducible issues with that maybe file a separate bug.

**Comment by focusaurus** [comment]
@bendman If you want to update the docs, [this issue](https://github.com/visionmedia/superagent/issues/830#issue-124979435) goes through all the APIs and talks about which are node only etc. That would be a good starting point for a PR to update `docs/index.md`.
