### ISSUE TITLE
agent.attachCookies is not a function

### ISSUE THREAD

**Issue by sharique123** [visionmedia/superagent#1014]
After the update agent.attachCookies is not a function.

**Comment by pornel** [comment]
Yes, this was a private function and was never supported.

How did you run into this problem?

**Comment by sharique123** [comment]
Version 1 works 
agent.saveCookies(res);

**Comment by sharique123** [comment]
http://jaketrent.com/post/authenticated-supertest-tests/

**Comment by pornel** [comment]
It worked, but working doesn't mean it's supported. This API was not documented in 1.0 manual, and in the source it was marked as `@api private`, meaning it was not for use.

Removal of all such private function is one of the [breaking changes in 2.0](https://github.com/visionmedia/superagent/releases/tag/v2.0.0).

The function has been renamed to `_attachCookies`, but this is private too, and sooner or later it will break too.

**Comment by pornel** [comment]
Try this:

```js
const jar = new CookieJar;
jar.setCookies(res.headers['set-cookie']);

…

const access = CookieAccess(url.hostname, url.pathname, 'https:' == url.protocol);
req.set('cookie', jar.getCookies(access).toValueString());
```

**Comment by dpolivy** [comment]
@pornel Is there a better solution for more complex cases, including redirects and adding incremental cookies?

**Comment by pornel** [comment]
It depends what do you need it for. Do you only need to fake cookies in supertest tests?

**Comment by dpolivy** [comment]
@pornel Yes; before doing certain tests I need to have the agent "login", which saves a cookie from the server that is used by subsequent tests. Sometimes the cookies are set or cleared through the use of redirects. And sometimes they are changed by the tests, and need to be propagated through subsequent tests.

**Comment by pornel** [comment]
Setting cookies for tests sounds like a strong use-case. Can you open a feature request for it in [supertest](https://github.com/visionmedia/supertest) project? I think it's better to create a unit-test-specific API there.

**Comment by dpolivy** [comment]
I found an existing issue that captured the scenario pretty well. Let's use that to track the feature request.

**Comment by pornel** [comment]
That should be tracked in supertest.
