### ISSUE TITLE
On iOS react-native, POST multipart/form-data, filename is not set

### ISSUE THREAD

**Issue by jadidian** [visionmedia/superagent#1015]
I'm using superagent on a react-native project, running on iOS I have this call:
```js
superagent.post(`${ baseURL }/avatars`).accept('json').set('Authorization', `Bearer ${ accessToken }` ).attach('avatar', file, 'avatar.jpg');
```
The request will look like:
```
...
Content-Length: 109525

--plwLXsprfKExui80ZcsYXYDOzXm_Cbtau-b9Jh_cBolAMq6rbyMLIyFt0/zFYRb70/kao-
content-disposition: form-data; name="avatar"
content-type: image/jpeg

�����JFIF���H�H�����
...
```
So `filename="avatar.jpg"` is missing in content disposition. I've used the same call in a web react project and it works fine, this happens on an iOS react-native project.

**Comment by jadidian** [comment]
Versions: superagent: 2.0.0, superagent-promise-plugin: 3.2.0, iOS: 9.3, react-native: 0.28.0

**Comment by jadidian** [comment]
UPDATE:
I attached a `file.name = 'avatar.jpg'` to the `file` object I'm passing to `.attach()` and now it shows up in the request, which is weird, I was guessing `.attach([fieldname], [data], [filename])` should have set (or overrided) the filename in content disposition...
```
...
Content-Length: 93108

--dj/YL9pno2_FjeGb10D.VWrTo_serRiSPD3KneuZvWESgt2_LKp2EOiPFD2ulKG9aVUluo
content-disposition: form-data; name="avatar"; filename="avatar.jpg"
content-type: image/jpeg

����JFIFHH��XExifMM*
...
```

**Comment by pornel** [comment]
Is react-native loading superagent from lib/client.js or lib/node/index.js?

**Comment by jadidian** [comment]
I'm not sure, I did `npm install superagent --save` and then imported the npm module in my project
```js
import superagent from 'superagent';
```

**Comment by jadidian** [comment]
OK, it seems that its loading the `lib/client.js`

**Comment by pornel** [comment]
In that case we don't build the line with the filename, the "browser" does — we use native `FormData` object. Perhaps React doesn't emulate the [third argument](https://developer.mozilla.org/en-US/docs/Web/API/FormData/append)?

**Comment by jadidian** [comment]
You're right, I also did:
```js
var formData = new FormData();
formData.append('avatar', file, 'avatar.jpg');
```
then tried to send it either with `fetch()` or `superagent.post().attach()`... Neither would set a `filename`, so the workaround for having a `filename` in `content-disposition` on iOS Safari is to explicitly set `file.name = 'something.jpg'` then pass it to superagent or fetch...
Btw, thanks for the awesome job on superagent, its one of my most favourite JS libraries.

**Comment by sidhijakpat** [comment]
Hi @jadidian , how did you load the `file`? I try to upload image file to server using `superagent.attach` but always failed, can you help me?

I submit the issue here: https://github.com/visionmedia/superagent/issues/1444

Thank you
