### ISSUE TITLE
Can't submit POST with g-recaptcha-response (and perhaps all variables with dashes)

### ISSUE THREAD

**Issue by blindbox** [visionmedia/superagent#1018]
I tried with the code below:-
```js
var server = supertest.agent('http://localhost:5001')

server.post('/InsertApiHere')
	.send({
		someApi: 'Values',
		'g-recaptcha-response': 'captchaBypass',
})
```
When I check the server side, g-recaptcha-response is empty. someApi returns the expected value.

I tried the same parameters using using Postman, it works perfectly.

This is on supertest version 1.2.0 / superagent 1.8.3

**Comment by pornel** [comment]
Does it work without `supertest`?

I don't see anything special about this code, and `.send()` with objects works.

**Comment by blindbox** [comment]
I see the issue now. request.send() is sending the data as JSON, while my POST api accepts form-data.

**Comment by pornel** [comment]
OK
