### ISSUE TITLE
nock and superagent 2.0.0

### ISSUE THREAD

**Issue by viktorlarsson** [visionmedia/superagent#1019]
Hi!

I am using Superagent 2.0.0 in combination with React + redux and it has been working great.

Now I'm trying to intercept the xhr request from zombie.js and cucumber using Nock, and i'm not getting it to work.

world.js (cucumber)

` this.backend = nock(
    'https://api-url/'
  )
  .defaultReplyHeaders({
   'Content-Type': 'application/json',
 })
 .persist();
`

step definition (cucumber)

`this.backend
       .get('/api/endpoint/')
       .reply(200, {});
`

And the actions in React:

`export function fetch() {
  return dispatch => {
    dispatch(requestAction())
    return request
        .get( `${config.apiUrl}endpoint`)
        .on('error', requestActionFailure)
        .end(function(error, result){
          console.log(error);
          console.log(result);
          if(result) {
            dispatch(requestActionSuccess(result.body));
          }
        });
  };`

In the end() function, there is error and result. The only args i'm receiving is error, and the following comes out of the cli when trying to console.log(error)

`{ [Error: Parser is unable to parse the response]
  parse: true,
  original: [TypeError: Cannot read property 'split' of null],
  rawResponse: null,
  statusCode: null }
`

I found this [thread](http://stackoverflow.com/questions/14689252/how-can-superagent-and-nock-work-together), but buffer() seems to be removed in superagent 2. Any ideas why this might be?

**Comment by viktorlarsson** [comment]
Well, I figured out one of the issues. I've only spent like a total of 8 hours trying to wrap my head around this. Hope this helps someone else. You have to use trailing slash 

'.get(${config.apiUrl}endpoint)' // wrong

'.get(${config.apiUrl}endpoint/)' // right

**Comment by pornel** [comment]
Ouch. That's a gotcha. Thanks for sharing the solution.

**Comment by pornel** [comment]
BTW: buffer() should still be available in superagent. It was always only available in the Node version, not in the browser version (since we can't control how browser buffers).
