### ISSUE TITLE
Order of delivery for multipart/form-data

### ISSUE THREAD

**Issue by furkanmustafa** [visionmedia/superagent#1021]
I am trying to maintain order of delivery in `multipart/form-data` request, for processing a large payload as a stream without buffering much.

When I do;

```
req
 .set('Authorization', "blah blah")
 .type('form')
 .field('meta_field', "some prior meta data")
 .field('key', "some more prior meta data required before the file stream")
 .attach('blob', filepath)
 .end(function(err, res) { .. });
```

On the other side, I am receiving the `blob` first, and this is forcing me to buffer the whole `blob` until I receive other fields I expect to receive before the `blob`.

My question is; is this `superagent`'s doing or `form-data`'s doing? and is this intentional? (I have tried to understand it myself, but it proved difficult to figure out where it's getting mixed up)

This'd be a bugfix/feature-request if this is not intentional.

**Comment by pornel** [comment]
We don't handle multipart ourselves. In browser we use XHR2 native `FormData`. In Node we use `form-data` module.

**Comment by furkanmustafa** [comment]
This turned out to be a problem on my side, when evaluating the request stream on the receiving end.

I could confirm that `superagent` and `form-data` does not mess with the order of delivery and delivers multi-part data stream as-is. (in node)

Sorry for the inconvinience.
