### ISSUE TITLE
Unhandled rejection Error: timeout of 10000ms exceeded

### ISSUE THREAD

**Issue by loretoparisi** [visionmedia/superagent#1022]
I'm getting a unhandled rejection error due to a timeout error while having

```coffeescript
req.on 'error', ->
    reject new Error "request timed out"
  req.on 'abort', ->
    reject new Error "request aborted"
```

so it seems the `error` event is not triggered at timeout.

Now looking at the code [here](https://github.com/visionmedia/superagent/blob/master/lib/node/index.js#L529)

```javascript
// expose events
  req.on('drain', function(){ self.emit('drain'); });

  req.on('error', function(err){
    // flag abortion here for out timeouts
    // because node will emit a faux-error "socket hang up"
    // when request is aborted before a connection is made
    if (self._aborted) return;
    self.callback(err);
  });
```

I should have the rejection ok in the `error` event.
Logging response object I catch this error

```javascript
{ [Error: timeout of 5000ms exceeded] timeout: 5000, code: 'ECONNABORTED', response: undefined }
```

in the `end` callback:

```coffeescript
.end (err, res) ->
```

Shall I do the `reject` here based on `res` and `err` returned objects?

**Comment by loretoparisi** [comment]
**[UPDATE]**

I came out with this possible solution:

```coffeescript

HTTPClient = 
  # http get
  # support https and http
  # @return Promise
  get: (url) -> new Promise (resolve, reject) ->

    headers=
      'Accept': 'application/json'
    
    req = request.get url
    req
    .set headers
    .timeout(3000)
    .end (err, res) ->
      if res?.ok
        console.log res.header
        console.log 'API:'+req.url
        try
          data = JSON.parse(res.text)
          resolve data
        catch
            reject new Error "request malformed"
      else
        #console.log req
        reject new Error err
    req.on 'error', (error) ->
      reject error
```

So that I therefore handle it in the `catch`

```coffeescript
HTTPClient.get(url)
      .then (res) ->
        console.log res
      .catch (error) ->
        console.log 'error:%s', error
```

catching the original timeout error: `error:Error: timeout of 1000ms exceeded`

**Comment by loretoparisi** [comment]
**[UPDATE]**
Investigating the callbacks fired by the library, it seems that both the

```coffeescript
req.on 'error', (error) ->
      reject error
```

and the

```coffeescript
.end (err, res) ->
```

will be fired in case of errors, so the solution will be to avoid to handle both.

**Comment by pornel** [comment]
Since superagent 2 *do not use `.end()`. Use `.then()` instead.

**Comment by loretoparisi** [comment]
@pornel thank you I'm using `superagent@1.2.0` due to other dependencies requirements.

**Comment by pornel** [comment]
Superagent 1.2 is quite old. It has known bugs, which we have fixed — in later versions.
