### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by matansh** [visionmedia/superagent#1025]
Hi, i am running a simple GET that returns a JSON, i want to extract a value from the returned JSON and use it later on in my code but no mater what i do i cant seem to use the wanted value out side of superagent's "end" function
my code looks like this-
```
var request = require('superagent');
var id = 'empy';
request
      .post('http://URL/getjson')
      .end(function (err, res) {
            id = res.body.id;
            console.log('id is- '+id); // prints "id is- XXX"
            return id;
      });
 console.log('id is- '+id); // prints "id is- empty"
```
Thanks in advance for any help

**Comment by pornel** [comment]
Indeed, and this is a typical behavior for asynchronous code in Javascript. There is no short simple solution for this. 

This is a way most "long" operations work in JavaScript. You will have to restructure your code to accommodate that. The function that needs the result will have to use callbacks itself (be called from inside of the `end` callback).

Management of callbacks is a little bit simplified with Promises, and then with async/await, but none of these things really remove callbacks, they just hide them, so you'll have to embrace callback-style programming.

**Comment by vinnymac** [comment]
This is just how javascript works right now. But the future is bright [async and await](https://zeit.co/blog/async-and-await) should make this a bit easier for us. You can do this today if you use [babel with some transforms](https://babeljs.io/docs/plugins/syntax-async-functions/).
