### ISSUE TITLE
So weird behavior

### ISSUE THREAD

**Issue by thanhthang20** [visionmedia/superagent#1028]
I call `request` one time but `.end()` is executed twice. And  `.end()` is executed twice only when the callback generated an exception.

http://prntscr.com/bta1qx

FYI: https://www.facebook.com/groups/228321510706889/permalink/488046104734427/?comment_id=488054721400232&reply_comment_id=488057098066661&notif_t=group_comment&notif_id=1468594595902645

**Comment by TimBuckley** [comment]
FYI you can drag/drop the image into this github issue to make it show up.

![](http://image.prntscr.com/image/7e36c4fd944b4d50b82e08dede88b25a.png)

**Comment by thanhthang20** [comment]
![screen shot 2016-07-15 at 10 36 38 pm](https://cloud.githubusercontent.com/assets/5382700/16879851/a96a6590-4adc-11e6-891d-54e1de8271a6.png)

**Comment by thanhthang20** [comment]
![screen shot 2016-07-15 at 10 44 20 pm](https://cloud.githubusercontent.com/assets/5382700/16880103/dd62b2b6-4add-11e6-909c-7461674d9ec6.png)

**Comment by pornel** [comment]
Please try version 2.1, it includes a fix for doubled callbacks.
