### ISSUE TITLE
Piping superagent response to express response doesn't work

### ISSUE THREAD

**Issue by kharandziuk** [visionmedia/superagent#1031]
The issue described [on stackoverflow](http://stackoverflow.com/questions/38478034/pipe-superagent-response-to-express-response)

Any ideas? Do I need to copy the issue here?

**Comment by pornel** [comment]
If you want to pipe the response, then don't use `end()`.

Response given in the `end()` callback is already complete and finished, so there's nothing to pipe - the piping process has already ended.

**Comment by kharandziuk** [comment]
Thanks! It works.
But what does `_res.pipe` function do in the case?

**Comment by pornel** [comment]
In the `.end()` callback `_res.pipe()` causes errors, nothing else. You *can't* use `.pipe()` if you call `.end()`. It's either one or the other, never both.
