### ISSUE TITLE
Custom method on Object.prototype may cause error in Request.send method.

### ISSUE THREAD

**Issue by xieranmaya** [visionmedia/superagent#1032]
I've added a convenient method on Object.prototype in my project(which is based on Electron):

``` js
Object.prototype.toImmutable = function() {
  return Immutable.fromJS(this)
}
```

when I use `superagent.post(url).send({a:2}).end()`, it will cause some error in the console.
the code in https://github.com/visionmedia/superagent/blob/84da7c8d50a83badd5a88598b150664ca2fe9971/lib/request-base.js#L324 this line did not check to get the own property of the object which pass to  the `send` method, the expected behavior is the `send` method should use hasOwnProperty to send just the own property.

**Comment by pornel** [comment]
This is a common problem, and it never ends. I suggest that you add custom properties on Object prototype as non-enumerable (or don't modify Object prototype at all).
