### ISSUE TITLE
.set('Authorization', 'foo') is not adding an Authorization header to a request

### ISSUE THREAD

**Issue by alexanderbanks** [visionmedia/superagent#1034]
```javascript
  su.post(uri)
    .set({'Content-Type': 'application/json', 'Authorization': 'Bearer ' + token})
    .send(body)
    .end(function(err, res) {
      console.log('RES', res);
      if (err || !res.ok) {
        def.reject(err || res);
      } else {
        def.resolve(res.body || res.text);
      }
    });
```

`.set()` is not applying the custom headers. I tried both with the individual header per `.set()` call, as well as passing in a headers object. Neither was successful.

**Comment by pornel** [comment]
I guess you've managed to solve it?

**Comment by alexanderbanks** [comment]
Yes, my own relentless stupidity. I forgot to add:

```
  if ('OPTIONS' == req.method) {
    res.send(200);
  }
  else {
    next();
  }
```

To my node app. It was failing on the options preflight. Thanks for responding and I apologize for the illegitimate issue raising.

**Comment by pornel** [comment]
No problem
