### ISSUE TITLE
How to send Multipart form data

### ISSUE THREAD

**Issue by jwingo1015** [visionmedia/superagent#1035]
I cant seem to get the following to work with supertest:
Content-Type:multipart/form-data; boundary=----WebKitFormBoundaryKPzoKfSfBvBzfvZa

body of post call
------WebKitFormBoundaryKPzoKfSfBvBzfvZa
Content-Disposition: form-data; name="json"

{"categoryId":1}
------WebKitFormBoundaryKPzoKfSfBvBzfvZa

**Comment by pornel** [comment]
Does it work with actual superagent request?

This project doesn't handle simulated requests done by supertest.

**Comment by jwingo1015** [comment]
@pornel  No it doesnt i want to know how to make it work

**Comment by pornel** [comment]
So when super*test* is *not* used:

- in the browser, superagent uses native `FormData` object. Do request from the browser work? Do you have the same problem with native XHR?

- in node superagent uses form-data module. If your request works from browser, but not from node, please file a bug for form-data.

**Comment by jwingo1015** [comment]
I tried the following but get an error message:'TypeError: first argument must be a string or Buffer' 

var form = new FormData();
      form.append('json', '{"categoryId":1}')
        api.post('/1_0/callrequests')
        .set({
          'Authorization': token
          'Content-Type': 'multipart/form-data; boundary=----WebKitFormBoundaryKPzoKfSfBvBzfvZa'
        })
        .send(form)

**Comment by jwingo1015** [comment]
@pornel

**Comment by pornel** [comment]
I'm not sure if it'll work if you set `Content-Type` - you may be overwriting the correct one.

**Comment by pornel** [comment]
as for `FormData`, we don't support it set that way, we only use it internally via `.attach()`, `.field()`, etc.

**Comment by jwingo1015** [comment]
@pornel  ok so i need to do this:

api.post('/1_0/callrequests')
        .set({
          'Authorization': token
        })
        .field('json','{"categoryId":1}')
        .expect(200)
        .end(function(err, res) {

**Comment by jwingo1015** [comment]
@pornel b/c this way doesnt work either. I was able to get this call to work in postman but no luck with supertest

**Comment by pornel** [comment]
**Please don't confuse supertest with superagent**. These are separate projects.

**Comment by pornel** [comment]
Sorry, it's still unclear to me whether you have a bug with superagent or supertest. Previously we've had both issues with superagent's multipart handling as well as incompatibilities with supertest.

If you have a reproducible code that fails, please add it as a unit test in superagent and I'll try to make it work.

**Comment by jwingo1015** [comment]
describe('post_callrequest', function() {
      it('should respond with 201 201 response', function(done) {
        api.post('/test/callrequests')
        .set({
          'Authorization': token,
          'Content-Type': 'multipart/form-data'
        })
        .field('json','{"categoryId":1}')
        .expect(201)
        .end(function(err, res) {
          callId = res.body.id
          console.log(res.status+'   '+res.body.id)
          if (err) return done(err);
          done();
        });
      });

This still is not working for me @pornel

**Comment by pornel** [comment]
In my previous comment I specifically mentioned superagent's test suite, because superagent's test suite makes real requests, and does not use supertest.

If you're seeing a bug while using supertest (fake requests, not real ones going over the network), then please file the bug in the supertest project.
