### ISSUE TITLE
Mimicking Ajax requests for testing 

### ISSUE THREAD

**Issue by mattcodez** [visionmedia/superagent#1046]
I'm using Supertest (and thus Superagent) for some API testing on a Node.js project. I have a particular route that returns different content based on the type of request. Using expressJS's `req.xhr`, the code will return JSON if true or issue a redirect if false. I want to account for this in my tests but I'm struggling to get Superagent to mimic an XHR GET request.

According to ExpressJS documentation, it's looking for the `X-Requested-With` header in the request to be set to the value `XMLHttpRequest`. When I try to set this header using `.set('X-Requested-With', 'XMLHttpRequest')` I get 

    Unhandled rejection Error: Can't set headers after they are sent.
        at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)

Odd thing is, I can set other headers, even before this one, just fine
`.set('Accept', 'application/json')`. If the headers have already been written, this should fail too, but it doesn't. Also, checking `res.request.req._headers`, it appears nothing else is setting `X-Requested-With` so it's not like something else gave it a value either.

Using supertest@2.0.0->superagen@2.1.0

**Comment by pornel** [comment]
That's not a message from superagent. It looks like an error from express.js. Are you sure you're calling it on superagent, and not express' request?

**Comment by mattcodez** [comment]
Thanks for the reply. I believe it's actually deeper than express even, [going down ](http://stackoverflow.com/questions/7042340/node-js-error-cant-set-headers-after-they-are-sent)to Node's native http.serverResponse. I'm running it on SuperTest which [claims  ](https://github.com/visionmedia/supertest#api) I can make any SuperAgent call with it.

```
agent = request.agent(sails.hooks.http.app);
describe('index - ajax', function(){
    it('should return JSON for XHR request', function(done){
      agent
        .get('/survey')
        .set('X-Requested-With', 'XMLHttpRequest')
        .set('Accept', 'application/json')
        //         .expect(200)         .expect('Content-Type', /json/)
        .expect(function(res){
          if (Array.isArray(res.body.questions)){
            return;
          }
          else{
            return 'questions property is not an array';
          }
        })
        .end(function(err, res){
          if(err) return done(err);
          done();
        });
    });
  });
```
Note I've tried changing the order of and even removing the `.set('Accept'...` and it doesn't help. There's something about setting that `X-Requested-With` header specifically that something doesn't like.

**Comment by pornel** [comment]
If you're running it under supertest, please file a bug there. Supertest changes/bypasses superagent, so I can't help you here.

**Comment by mattcodez** [comment]
Have done so, I know superagent is being used but didn't realize it's also being bypassed by supertest?

**Comment by pornel** [comment]
supertest has to prevent requests actually going to the network, so it patches/replaces superagent's request-making logic with its own.

OTOH if you can reproduce the error without supertest involved, then it's definitely a superagent bug.
