### ISSUE TITLE
No event emitted for cross domain errors.

### ISSUE THREAD

**Issue by nickclaw** [visionmedia/superagent#1050]
There's an event emitted for `abort` and `end`, but nothing is emitted when a request fails during a preflight check.

**Comment by pornel** [comment]
As far as I know, the XHR interface does not expose existence of preflight checks in any way, and a failed preflight gives us a generic error with status = 0, which we can't distinguish from DNS, TCP connection or offline errors.

Do you know how a better error could be implemented?

**Comment by nickclaw** [comment]
I guess don't really care whether or not I know exactly why the request didn't complete. It's more that I can't tell the request is "over" strictly using the events.

**Comment by pornel** [comment]
You should be getting the `end()` callback on CORS failure.

**Comment by nickclaw** [comment]
Indeed it does. And that's fine when you're the originator of the request. My use case is a higher order react component that manages and keeps track of one-off requests. I could always overwrite the `end` function with my own hook, but that seems like a bad solution -- and I think any module that needs to keep track of requests could benefit from more thorough events.

**Comment by ratiotile** [comment]
I would like to get better error messages. For example, Chrome prints out in the console: `XMLHttpRequest cannot load http://192.168.1.192:23297/submit_registration. Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header has a value 'http://localhost:8080' that is not equal to the supplied origin. Origin 'http://192.168.1.192:8080' is therefore not allowed access.`

but the error supplied in `end` is only `Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
    at Request.crossDomainError (http://192.168.1.192:8080/build/bundle.js:80988:14)
    at XMLHttpRequest.xhr.onreadystatechange (http://192.168.1.192:8080/build/bundle.js:81058:20)`

**Comment by pornel** [comment]
@ratiotile do you know if this message is exposed to JS somehow?

**Comment by pornel** [comment]
I can't change when `end` is fired – apparently we have tests that check it's *not* fired on CORS error.

I've added an `error` event, so if you catch `error`, `abort` and `end` you should be covered.

**Comment by ratiotile** [comment]
@pronel, If I knew, I would have provided a solution. Chrome unhelpfully points to my index.html as the source for that log statement, so I have been unable to trace its origin.

**Comment by nickclaw** [comment]
@pornel that's fantastic thanks

**Comment by nickclaw** [comment]
Hey @pornel, I see this fix is still sitting in a branch. Is there any reason it hasn't been merged yet?
