### ISSUE TITLE
Memory related crash when uploading large objects in browser

### ISSUE THREAD

**Issue by acgourley** [visionmedia/superagent#1051]
I have a large (sometimes 100mb) objected generated in javascript stored as an object with many base64 encoded fields. 

I can use a simple super agent .send(largeObject) and things work most of the time, but often the browser will run out of memory and chrome will show the dreaded, "Aw, snap!" message to the user and crash the tab. 

Can anyone suggest a better way to use superagent to put/post large data objects like this?

**Comment by pornel** [comment]
You could avoid base64 overhead by using a `Blob` created from an `ArrayBuffer`.

AFAIK XHR can't stream uploads. If you wanted to avoid having whole object in memory at the same time you would need to upload it using multiple requests and reassemble on the server.

**Comment by acgourley** [comment]
I'll look into that now, thanks. 

I want to clarify that there is no problem having the object in memory before the request, but once the request starts the crash is likely to occur. So something about my approach increases the memory usage of the app - maybe a serialization of the object occurs?
