### ISSUE TITLE
Blob/Stream/Buffer request support?

### ISSUE THREAD

**Issue by acrazing** [visionmedia/superagent#1052]
How to request with a binary body directly, I cannot find this in document?

For example:

``` js
// node stream
const file = fs.createReadStream('./example.png')
// node buffer
const file = fs.readFileSync('./example.png')
// browser
const file = document.querySelector('input[type=file]').files[0]

request
  .post('/proxy')
  .set('Content-Type', 'application/octet-stream')
  .send(file)
  // attach a blob/stream/buffer directly to request body like node node core http module
  .end()
```

**Comment by focusaurus** [comment]
Have at look at the `stream.pipe(req)` docs: http://visionmedia.github.io/superagent/#piping-data

**Comment by acrazing** [comment]
But, how to handle `Blob` in browser?

**Comment by acrazing** [comment]
Maybe add a method like `req.bin(blob|buffer|stream|path)` is more friendly? And then we can call as follow:

```js
// node buffer
const file = fs.readFileSync('./example.png')
// node stream
const file = fs.createReadStream('./example.png')
// file path
const file = './example.png'
// browser blob file
const file = document.querySelector('input[type=file]').files[0]

request
  .post('/proxy')
  .bin(file)
  .end()
```

**Comment by pornel** [comment]
We have `attach()` for sending Blobs (as multipart).

**Comment by acrazing** [comment]
@pornel But sometimes we need to deal with this situation:

```js
const file = document.querySelector('input[type=file]').files[0]
const xhr = new XMLHttpRequest
xhr.open('POST', '/file')
xhr.send(file)
```

The `XMLHttpRequest` support send a `Blob`/`Document`/`ArrayBuffer` directly, rather than wrap to `FormData`. See <https://www.w3.org/TR/2012/WD-XMLHttpRequest-20120117/#the-send-method>.

**Comment by pornel** [comment]
I see. I think it'd make sense to support it as `superagent.send(blob)`. Would you like to make a pull request for this?

**Comment by jedwards1211** [comment]
Is there any way to pipe only the response body?  I'm trying to parse it as a stream with `htmlparser`.

**Comment by pornel** [comment]
@jedwards1211 are you using htmlparser in the browser? If so, then there's no way, because we don't support the whatwg stream standard yet.

**Comment by jedwards1211** [comment]
No, I'm using it in node.  Just using it to slurp tabular data out of html pages.  It works in some cases (I assume because nothing looks like a tag until the parser reaches the body) but not in others.

On the other hand, the case where I've seen it fail is a ucs2-encoded gzipped response.  Does `.pipe()` send the data without expanding it?  If not, I guess `superagent-charset` isn't intercepting `.pipe()` to decode the body before it reaches the destination stream.

**Comment by pornel** [comment]
In node `request.pipe(htmlparser)` should work.

**Comment by jedwards1211** [comment]
@pornel oh...you know what I think my problem was?  I just noticed that the headers of the response I'm consuming include `X-UA-Compatible:IE=EmulateIE9`.  I didn't realize it was lacking the usual compression and encoding headers.

Request URL:http://hydromet.lcra.org/data/datafull.xml?9:20
Request Method:GET
Status Code:304 Not Modified
Remote Address:198.214.246.3:80

**Response Headers**
Accept-Ranges:bytes
Date:Tue, 13 Dec 2016 15:20:16 GMT
ETag:"80a6335f5455d21:0"
Last-Modified:Tue, 13 Dec 2016 15:20:01 GMT
Set-Cookie:(redacted)
X-UA-Compatible:IE=EmulateIE9

**Comment by bigman73** [comment]
I'm using node with a a 3rd party web service that expects a application/octet in its body. I don't have a local file but a base64 string (which I converted to a memory Buffer)
Is there a way to send the binary buffer with the POST request?

Saving the Buffer to a local file won't work (by attaching or piping it) since the web service doesn't support files/attachments.

**Comment by bigman73** [comment]
Thanks. I couldn't get attach() to work, and actually ended up using send(), which to my surprise worked fine

The buffer was created with:
`
const buffer = Buffer.from(base64Data, 'base64');  

const response = await request
        .post('<URL>')
        .send(buffer)
        .set('SubscriptionKey', '<XYZ>')
        .set('Content-Type', 'application/octet-stream')
        .set('Accept', 'application/json');
`

**Comment by kornelski** [comment]
Yeah, that works too.

**Comment by gap1994** [comment]
how did you used 'application/octet-stream' to uploading?
