### ISSUE TITLE
Request.parse / this._parser not used for browser?

### ISSUE THREAD

**Issue by benmosher** [visionmedia/superagent#1053]
`this._parser` is set in `request-base.js` via `parse` method, but is only used in `lib/node/index.js`.

It seems like `_parseBody` in `client.js` should use it, but it doesn't.

Is this a bug? It appears that maybe this is similar to (or a continuation of) #805?

Also noteworthy and related: `buffer(true|false)` is not available in the browser.

**Comment by pornel** [comment]
Neither buffering, nor response body parsing are available in the browser. These things are handled natively by XHR.

In Node parser is expected to listen to events on response stream, but in the browser we don't have a stream (we could #1033)

**Comment by benmosher** [comment]
Ah, so makes sense that `buffer(...)` would be unavailable within browser.

It still seems like providing a parser via `#parse` should be used [within `_parseBody`](https://github.com/visionmedia/superagent/blob/4eee1696e2fe3cfea6e8d641579943525c046d82/lib/client.js#L376) as an override for the global `request.parse` map?

Current code:
```js
// lib/client.js:375
Response.prototype._parseBody = function(str){
  var parse = request.parse[this.type];
  if (!parse && isJSON(this.type)) {
    parse = request.parse['application/json'];
  }
  return parse && str && (str.length || str instanceof Object)
    ? parse(str)
    : null;
};
```

What I thought I'd find based on [`#parse` docs](https://visionmedia.github.io/superagent/#parsing-response-bodies):
```js
// lib/client.js:375
Response.prototype._parseBody = function(str){
  var parse = this._parser || request.parse[this.type]; // only changed this line
  if (!parse && isJSON(this.type)) {
    parse = request.parse['application/json'];
  }
  return parse && str && (str.length || str instanceof Object)
    ? parse(str)
    : null;
};
```

**Comment by niftylettuce** [comment]
v5.0.0 was released and should fix this issue, see the updated docs
