### ISSUE TITLE
this._formData.on is not a function

### ISSUE THREAD

**Issue by acomito** [visionmedia/superagent#1054]
Any clue what is going on? Stack trace looks like it gets thrown at `.field`?

```
  handleImageUpload(file) {
        let upload = request.post(CLOUDINARY_UPLOAD_URL)
                            .field('upload_preset', CLOUDINARY_UPLOAD_PRESET)
                            .field('file', file);

        upload.end((err, response) => {
          if (err) {
            console.error(err);
          }
          console.log(response);

          if (response.body.secure_url !== '') {
            this.setState({
              uploadedFileCloudinaryUrl: response.body.secure_url
            });
          }
        });
      }
```

**Comment by pornel** [comment]
This could only happen here, in Node-JS-only bit of code:

```js
    this._formData = new FormData();
    this._formData.on('error', function(err) {
```

which would happen if FormData was incorrectly imported. Are you perhaps using Webpack or something similar that could accidentally create a mix of Node-only and browser-only modules?

**Comment by pornel** [comment]
We now have a getter that creates this object automatically. Hopefully it'll work.

**Comment by sean-stanley** [comment]
@pornel 

Having this exact same issue on both 3.5.3-beta.1 and 3.5.2

I'm on the meteor framework so using Meteor's webpack build compiler. Do you have any suggestions on tweaking an image upload request like in acomito's example for when this._formData is undefined?

Thanks for your help.

**Comment by pornel** [comment]
Webpack has a `target` setting, which has to be `"browser"` or `"node"` accordingly to the environment the code is going to run in.
