### ISSUE TITLE
Array parsing 

### ISSUE THREAD

**Issue by cristian-sima** [visionmedia/superagent#1055]
Let's take this simple example:

```js
const data = {
    "Date": "29.08.2016",
    "InverseTax": false,
    "Items": [{
        "Name": "First item",
        "Quantity": "1",
        "Unit": "buc",
        "UnitPrice": "1",
        "Vat": "20"
    }, {
        "Name": "Second item",
        "Vat": "5",
        "UnitPrice": "12",
        "Quantity": "2",
        "Unit": "l"
    }],
    "Paid": 1,
    "VatAtCashing": false,
    "ClientID": "19"
}

agent.
        put(`/api/cube/${getCompanyID()}/invoices`).
        type("form").
        send(data).
        ...
```

I went to Chrome dev tool and I got this 

![image](https://cloud.githubusercontent.com/assets/12199042/18055161/6c7ea6c2-6e0f-11e6-9a62-7704c9f3f786.png)

And there is a problem with the `Items` array. It does not specify the indexes, so on server I do not understand what to which belogs.

Rather than that, I was expecting this:

```
...
Items[0][Name]:First item
Items[0][Quantity]:1
Items[0][Unit]:buc
Items[0][UnitPrice]:1
Items[0][Vat]:20
Items[1][Name]:Second item
Items[1][Vat]:5
Items[1][UnitPrice]:12
Items[1][Quantity]:2
Items[1][Unit]:l
...
```

**Comment by pornel** [comment]
We have only very basic support for mapping of JSON to form-data. If you want to send complex data I suggest sending it as JSON.

**Comment by cristian-sima** [comment]
Is the length the only disadvantage of using JSON instand of Form?

**Comment by cristian-sima** [comment]
Or in other words why is the `FormData` a standard rather than using JSON?

**Comment by pornel** [comment]
Efficiency of both encodings is similar. Mostly it's a matter of compatibility with your server, and most servers accept form data out of the box.
