### ISSUE TITLE
Attach files dynamically

### ISSUE THREAD

**Issue by theDanielK** [visionmedia/superagent#1063]
I may just be being silly, but I am making a post call with multiple attachments.
The only issue is that the number of attachments are variable.

I'd like to be able to create a request object and run a foreach over the files and call .attach() on the superagent request.
Either this or being able to specify a list of files as a the value for an .attach() call.

I can't find a way to achieve this currently.

**Comment by pornel** [comment]
I think calling `.attach()` multiple times should work already.

**Comment by theDanielK** [comment]
Not working being called out of the chain. How would you call that function dynamically?
ie. call it (n) number of times.

**Comment by focusaurus** [comment]
A forEach should work fine:

    const request = require('superagent')

    const req = request.post('http://localhost:3000')
    const files = ['1.txt', '2.txt', '3.txt']
    files.forEach((file) => req.attach(file, file))
    req.end((error, res) => {
      console.log(error, res)
    })
