### ISSUE TITLE
parsing response from Google Open Spherical Camera API

### ISSUE THREAD

**Issue by wowzaaa** [visionmedia/superagent#1064]
Hey

I am having problems implementing Google's OSC Api ...
i am making a post with { name: "camera.getLivePreview" } as parameters and i am getting back a stream of jpegs as binary data
https://developers.google.com/streetview/open-spherical-camera/reference/camera/getlivepreview

is there a way i can use this library to handle the response? i tried in vanilla js with no luck :(

thanks

**Comment by pornel** [comment]
Superagent can only fetch things of finite size. The documentation says "Continuous video stream.", which I assume means a stream that never ends, so you'll never get the end() callback in superagent.

You must use a different library for this.

**Comment by wowzaaa** [comment]
thanks @pornel 
i can officially say i am lost :/

**Comment by pornel** [comment]
Search for tools for dealing with `multipart/x-mixed-replace`. The format is quite obscure.

**Comment by wowzaaa** [comment]
being doing that for the past 3 days and counting :)
