### ISSUE TITLE
Is there a way to config the 4xx & 5xx statusCode as normal response but not error

### ISSUE THREAD

**Issue by magicdawn** [visionmedia/superagent#1069]
As the title presents. 

I'm tired of writing code like this

``` js
const getDataAsync = co.wrap(function*(){
  let res;
  try {
    res = yield request.get('some_url')
  } catch(err) {
    if(!err.original && err.response) {
      res = err.response
    } else {
      throw err;
    }
  }
});
```

I have to test `!err.original && err.response` exists, and treat it as success response, I'm tired of writing this. 
So I'm asking is there a way to config that and if not can this issue be a feature request?

**Comment by magicdawn** [comment]
Actually I'm talking about this: https://github.com/visionmedia/superagent/blob/v2.2.0/lib/node/index.js#L594-L601

**Comment by focusaurus** [comment]
I think this is one of those API decisions that could go either way. Either you write application code like that to treat responses with error status codes as successful responses or you change the superagent API to treat them as success, but then you have to write application code to look at the status code in the application and respond accordingly. For example, detecting a 404 with HTML in the body when you were expecting a 200 with JSON.

I personally wish the original superagent API was "any HTTP response is success" semantics, but it's not. This is something that would be such a breaking change I'd hesitate to change it without something as drastic as forking and renaming the project. I believe that has been discussed on github issues in the past so you might get some insight searching through closed issues for discussion.

I know of at least `request-promise` which has this behavior configurable:

> By default, http response codes other than 2xx will cause the promise to be rejected. This can be overwritten by setting options.simple = false.

I would hesitate to make the core API configurable in this way, but I do understand your frustration.

**Comment by magicdawn** [comment]
So since request-promise add configuration to this, how about superagent 🎉

**Comment by focusaurus** [comment]
Well, if we do it, I'd rather do it with a different API like adding a
`req.getResponse()` method.

**Comment by pornel** [comment]
I think we could make the logic configurable by allowing user to supply a callback to judge whether the response is OK.

https://github.com/visionmedia/superagent/blob/v2.2.0/lib/node/index.js#L590

```js
request.get().ok(res => res.status < 500).then(…)
```

**Comment by magicdawn** [comment]
ping

**Comment by magicdawn** [comment]
## idea: global staticProperty
add a static property `superagent.detectStatusCode`
- defaults to `true`, so we treat 4xx & 5xx response as error
- when set to `false`, wo do not care the statusCode

**Comment by magicdawn** [comment]
## idea: per req config
add a property or method to the `superagent.Request` class
e.g add `Request.prototype.config`

```js
request
  .get('https://www.google.com.hk')
  .config({ detectStatusCode: false }) //  <- turn off detectStatusCode here
  .end((err, res) => {
    // ... blabla
  });
```

**Comment by magicdawn** [comment]
`.ok` is also ok

but add support short version like `.ok(true)` would be more nice

**Comment by magicdawn** [comment]
ping

**Comment by keithamus** [comment]
```
request.get().ok(res => res.status < 500).then(…)
 ```

Very much works for me. I think if you want all to pass, `request.get().ok(_ => true)` is very succinct.

**Comment by Joshua-Swain** [comment]
I'm trying to use this function for to test an invalid post request. The function goes like this: `chai.request(app).post(...).set(...).send(...).end((err, res) => {...});`
I tried putting `.ok(...)` at every point in that chain, but I always received the error `TypeError: chai.request(...).post(...).set(...).send(...).end(...).ok is not a function`

I am expecting this to cause validation errors. Any advice on how to use this `ok()` feature?

**Comment by pornel** [comment]
This feature is in superagent. Are you using supertest perhaps?

**Comment by Joshua-Swain** [comment]
I'm pretty sure I'm using superagent, because I'm using chai out of the box.

**Comment by pornel** [comment]
Then `request.post(url).ok(cb)` should work. `chai.request(app)` is not superagent, so maybe chai has a wrapper that doesn't expose it yet?

**Comment by focusaurus** [comment]
I believe the [chai-http plugin](https://github.com/chaijs/chai-http/blob/master/package.json#L54) is in use here. That has superagent 3.7 which should have `.ok` I believe so not sure what's wrong.

**Comment by keithamus** [comment]
We've yet to add support for this feature in a released version of chai-http. We'll be making a release soon. Thanks for everyone's input here.

**Comment by svicalifornia** [comment]
@keithamus Any update? What should we be doing until `ok` is added to chai-http?

**Comment by keithamus** [comment]
@svicalifornia we should take this off of the superagent tracker. Please track https://github.com/chaijs/chai-http/pull/202 for updates.
