### ISSUE TITLE
Incorrect handling of gzip-encoded response

### ISSUE THREAD

**Issue by g7r** [visionmedia/superagent#1070]
Hi!

It seems that `superagent` ignores actual encoding specified in `Content-Encoding` header. It always uses `deflate` algorithm to decode response.

As a quickfix I suggest removing `gzip` from `Accept-Encoding` header.

**Comment by pornel** [comment]
Can you provide a URL that shows the error?

**Comment by g7r** [comment]
Sorry, false alert.
