### ISSUE TITLE
How to get message body for 4xx response? Or is it expected behaviour?

### ISSUE THREAD

**Issue by kroko** [visionmedia/superagent#1074]
Server is set up to return 200 and json object when server side validation and all further server work passes.
It returns 400 on server side validation error
It returns 500 on server side logic/DB/whatever error

Returning 400 is good praxis for server side validation failure (http://stackoverflow.com/a/34324179, http://stackoverflow.com/a/3290198, a.o.)
_Of course in real world there is also client side validation which forbids sending invalid form_

Example for 400

Client

``` javascript
import request from 'superagent';

...
    let sendToServerData;
    // sendToServerData = {one: 'isOne', two: 'isTwo'}; // test with data
    sendToServerData = {}; // test with no data

    request
    .post('/')
    .send(sendToServerData)
    .set('Accept', 'application/json')
    .then((sucess) => {
      console.log('we have sucsess', sucess);
    }, (faulure) => {
      console.log('we have failure', faulure);
    });
```

Server

``` php
if ($_SERVER['REQUEST_METHOD'] === 'POST') {

  // get input
  $rest_json = file_get_contents("php://input");
  // decode and put in post
  $_POST = json_decode($rest_json, true);

  // set header
  header_remove();
  header('Content-type:application/json;charset=utf-8');

  // if empty return 400 and json explaining things
  if(empty($_POST)) {
    http_response_code(400);
    header('Status: 400');
    exit(json_encode(array(
        'status' => 400,
        'message' => 'no empty posts my friend'
        )));
  }

  // just return back 200 and json explaining things
  http_response_code(200);
  header('Status: 200');
  exit(json_encode(array(
        'status' => 200,
        'message' => 'all fine!'
        )));

}
```

when `sendToServerData` is populated, all fine as expected - `sucess` contains all the payload. when `sendToServerData` is empty console prints `we have failure Error: Bad Request(…)` thus `faulure` object does not contain any server payload, it does not even contain status code. 

Is it expected (like "superagent way" would be returning 200 also on server side validation error, just set the payload to contain that there is actually server side validation error)? Or am I missing something? is it possibe to get object (`failure`) that contains server code and message on non 2xx status?

superagent@2.2.0

Thanks!

**Comment by kroko** [comment]
I just tried dropping ES6 promises for this 

```javascript
    request
    .post('/')
    .send(sendToServerData)
    .set('Accept', 'application/json')
    .end((err, res) => {
      console.log(err, res);
    });
```
and it works - `res` body contains payload.

So to rephrase the question - how to get error payload when using ES6 promises?

**Comment by focusaurus** [comment]
Use `request.post('/').send(sendToServerData).type('json').then(handleSuccess).catch((error) => {console.log(error.response.body)})`

**Comment by kroko** [comment]
```javascript
    request
    .post('/')
    .send(sendToServerData)
    .type('json')
    .set('Accept', 'application/json')
    .then((sucess) => {
      console.log('we have sucsess', sucess);
    })
    .catch((error) => {
      console.log('we have error', error);
    });
```

same,  the catched object does not contain payload, only `Bad Request(…)`

**Comment by pornel** [comment]
```js
.catch(error => error.response.body)
```

should work

**Comment by kroko** [comment]
but it does not. :)
currently falling back to
```javascript
.end((err, res) => {})
```

**Comment by kroko** [comment]
yes, I always tested in a situation where there is response from the server.

```javascript
request
    .post('/')
    .send(sendToServerData)
    .type('json')
    .set('Accept', 'application/json')
    .then((sucess) => {
      console.log('we have sucsess', sucess);
    })
    .catch((error) => {
      console.log('we have error', Object.keys(error), error.response, error);
    });
```

`error.response` exists!  
previously i just tested `error` that seemed not to contain any keys (and i just assumed it will behave same as `success` as on the server side both responses 200 & 400 are constructed the same way).  
i did not test `error.response.  
pardon for my laziness. :(  
this is probably due to different object enumerability for `sucess` and `error` (isn't it?).

so note to myself, when using promise, use catch for non 200 statuses and callback object will contain keys `original`, `response`, `status`.

**Comment by kroko** [comment]
should i clone, change, commit and pullrequest correction to https://github.com/visionmedia/superagent/blob/master/docs/index.md `ES6 promises are supported...` block, reflecting that `.catch()` should be used; or maybe it is at someones fingertips already :) ?

**Comment by pornel** [comment]
The success/error returned by `.then()`/`.catch()` is generally in line with how promises work. But if you think the docs can be improved here, then a PR is very welcome.

BTW: `error.response` only exists when we received a response. There are some edge cases when request fails even before we get any response from the server, and in such case there's no response at all (equivalent to `.end(error, undefined)`.

**Comment by kromit** [comment]
I can confirm this behavior. When promises are used `error.response` is not there. 

In my case I am getting 401 response from the server, but not even the status code is there.

In `.catch(function (err){`  I am getting
```
err={
crossDomain:true
message:"Request has been terminated↵Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc."
method:"GET"
stack:(...)
get stack:stack()
set stack:stack()
status:undefined
url:"http://...."
}
```

The corresponding preflight OPTIONS was returned with 200 so even the message seems to be false.

**Comment by pornel** [comment]
@kromit CORS error is *very* different from all other errors, because in this case the browser *deliberately* tries to pretend that the response does not exist! We don't get any information at all. No headers. No status. This is intentional by design of the HTML Standard to prevent information leak across origins. Until you fix CORS headers you won't get any information from the server at all.

**Comment by pmcavoy89** [comment]
I can confirmed that `.catch(error => error.response.body)` works for me. I'm using ES6 and Babel. But we are using the superagent library. Not sure if that makes a difference or not.

**Comment by pornel** [comment]
Still, `.catch(error => error.response.body)` (and `.catch(function(error) {error.response.body})`) should work whenever response *exists* (i.e. on 404, but not on DNS errors, CORS, timeouts, offline, etc).

**Comment by pmcavoy89** [comment]
Ah gotcha. I see the difference that you all are talking about now. I appreciate this GitHub issue. It actually helped me solve the issue I was facing. Can we update the documentation on the both error handling and generators to include information along these lines?

Yea, that code was working fine on the HTTP statuses of 400-500.

**Comment by pornel** [comment]
I think it is documented. Feel free to add to it:

http://visionmedia.github.io/superagent/#error-handling

**Comment by jedwards1211** [comment]
@kornelski is there any way (/plugin) to make superagent automatically include the response body in its error message for certain status codes?

**Comment by jedwards1211** [comment]
@kornelski I haven't found anything, so I'm thinking of making a plugin that works something like this:
```js
  superagent.use((req: Superagent) => {
    req.on('error', (err: Error) => {
      if (err.response && err.response.text) {
        err.message += '\n' + err.response.text
      }
    })
    return req
  })
```

**Comment by jedwards1211** [comment]
@kornelski true, though an error response that large would be pretty unusual

**Comment by dschinkel** [comment]
```js
export async function getGravatarImage(emailUrl: string) {
  let response;
  try {
    response = await request.get(emailUrl);
  } catch (err) {
    response = err;
  }

  return response;
}
```

**Comment by Killea** [comment]
I don't like this. I think this is a bug.
![image](https://user-images.githubusercontent.com/5551824/215529641-be3762ac-4ef7-4e0e-860d-488ec3962f4f.png)
The error should be an object, but not a `Error: BAD REQUEST`
How can I get aware of that I should access  ` err.response`?

**Comment by arthas207** [comment]
.post('/')
    .send(sendToServerData)
    .set('Accept', 'application/json')
    .ok(res=>res.status===400) 
    this works. superagent recognize http status not equal to 200 as error, equal to 200 as ok.
