### ISSUE TITLE
I use it to react-native. But sometimes garbled on its response data， just on ios platform has this problem. 

### ISSUE THREAD

**Issue by MingYe-dz** [visionmedia/superagent#1077]

**Comment by pornel** [comment]
Please provide HTTP request headers and the response so we can investigate the problem

**Comment by MingYe-dz** [comment]
sorry, i find this problem is  due to react-native`s bug.

**Comment by sunhjie** [comment]
How did you solve the problem, I have the same question. 很急

**Comment by sunhjie** [comment]
@MingYe-dz
