### ISSUE TITLE
`Request#attach()` should allow access to more options

### ISSUE THREAD

**Issue by lapo-luchini** [visionmedia/superagent#1079]
#520 added an optional `filename` parameter, allowing access to only one of the underlying options, but it would be useful to use other at times, as sometimes a specific mime-type is required (and pre-known length might help too).

I suggest accepting an object in that parameter and use it straight as an `options` object, while keeping the current `{filename: param}` when a string is given.

E.g. [FormData example](https://github.com/form-data/form-data):

```javascript
form.append('file', stdout, {
    filename: 'unicycle.jpg',
    contentType: 'image/jpg',
    knownLength: 19806
});
```

**Comment by pornel** [comment]
That's a good idea. It may need some care to keep compatibility with the browser. 

Would you make a PR for this?

**Comment by lapo-luchini** [comment]
I'm very willing to PR for the node version (as that's what I'm currently using), but I'm not sure when I'd be able to check it in the browser too.

**Comment by pornel** [comment]
AFAIK in browser there's no control beyond filename, so it'd be fine to ignore extra parameters. As long as you don't break 

```sh
make test-browser-local
```

it's fine :)

**Comment by lapo-luchini** [comment]
Oh, I noticed that [in the browser code](https://github.com/visionmedia/superagent/blob/master/lib/client.js#L651) while the third field is called `filename` the example it's already using it as an object to specify the content type (though it seems strange that it's using `type` instead of `contentType` [as accepted by the library](https://github.com/form-data/form-data/blob/master/lib/form_data.js#L234); maybe there is a conversion somewhere in the code path, but I didn't find it).

Also, the browser tests won't break, as [the only test](https://github.com/visionmedia/superagent/blob/master/test/client/request.js#L64) doesn't cover the third parameter.
