### ISSUE TITLE
Calling .query() after .set() is ignored

### ISSUE THREAD

**Issue by TooTallNate** [visionmedia/superagent#108]
The query parameter here get's dropped on the floor, since `set()` internally calls `request()` which processes the internal _query queue.

``` javascript
request.get('http://blah.com/')
  .set('Accept', '*/*')
  .query({ 'foo': 'bar' })
  .end()
```

Recommendation is to move the _query processing logic into `end()`.

**Comment by defunctzombie** [comment]
Is this still an issue? This is really old.

**Comment by defunctzombie** [comment]
Closing. Let me know if I need to re-open.
