### ISSUE TITLE
Feature request: augment the Request's promise interface with prototype methods (abort, timeout, etc)

### ISSUE THREAD

**Issue by willmorgan** [visionmedia/superagent#1080]
Sorry if this has already been asked - I've had a look through and couldn't find a similar issue.

My code currently uses the `.then` method to get a Promise back from the request, however if I return the resulting Promise, it doesn't include the rest of the methods from the Request prototype such as `abort`, `timeout`, `withCredentials` and so on.

This is my issue, basically:

```
function fetchManyFilesByGuid(serviceURL, guids) {
    return agent.get(getFilesInfoURL(serviceURL, ...guids)).query(withTransform()).then(res => res.body);
}
const fileRequest = fetchManyFilesByGuid('someUrl', 'guid1', 'guid2'); // --> Promise
fileRequest.abort(); // --> triggers error
```

I've tried augmenting the generated Promise object by setting `.abort` on it like below:

```
function fetchManyFilesByGuid(serviceURL, guids) {
    const request = agent.get(getFilesInfoURL(serviceURL, ...guids)).query(withTransform());
    const op = new Promise((resolve, reject) => {
        request.end((err, res) => {
            if (err) {
                reject(err);
            } else {
                resolve(res.body); // just need the body here
            }
        });
    });
    op.abort = request.abort.bind(request);
    return op;
}
```

But this fails if you perform another `.then`, because you get a new Promise object without the attached `.abort`.

Is this a sensible request? My workaround for now is going to involve using `.end` instead.

**Comment by pornel** [comment]
I feel your pain, but I think it's not the right solution. The problem is that as soon as you use this promise, it'll lose the added methods, e.g. `req.get().then().then().abort()` wouldn't work, neither would `Promise.all([req.get()])`.

Personally I use workaround of `return {promise: req.then(), abort() {req.abort()}}`.

There is a proposal for cancellable promises, so when it lands, it'll be possible to add it to superagent.

**Comment by willmorgan** [comment]
@pornel That's a pretty good workaround and I see the rationale - thought that augmenting Promise objects might not be the best thing to do (like extending built-ins 😄 )

I will close this for now. Thanks!
