### ISSUE TITLE
travis.yml secrets

### ISSUE THREAD

**Issue by serbanghita** [visionmedia/superagent#1083]
https://github.com/visionmedia/superagent/blob/master/.travis.yml - you should replace the value of `SAUCE_ACCESS_KEY` with $SAUCE_ACCESS_KEY and keep it safe hidden in Travis.
https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings - this is under `/settings`

PS: forks will not be able to run tests in TravisCI

**Comment by pornel** [comment]
1. The secret is already out.
2. Last time I checked this it would break checks on pull requests from other people's repos. This is a dealbreaker.
