### ISSUE TITLE
make post request wrong

### ISSUE THREAD

**Issue by nicolelovecoding** [visionmedia/superagent#1085]
I found a bug recently for superagent. 
So when I made a post request by using superagent, my post request magically becomes get request. 
And then if I add "https://" to the beginning of the url, it works fine.

**Comment by pornel** [comment]
Can you show example code? Are you using it in Node or browser? Is it a CORS request?

**Comment by nicolelovecoding** [comment]
I think I found the problem, it is not related to superagent. Thanks!
