### ISSUE TITLE
CI Test Stability

### ISSUE THREAD

**Issue by focusaurus** [visionmedia/superagent#1090]
For a while now it seems like our CI stack is unable to consistently pass test builds. I'm filing this issue to try to figure out exactly what the issue(s) are and see if it can be fixed.

First, some notes on how things work as I understand them:

- Key files are `Makefile`, `.travis.yml`, `.zuul.yml`
- Automated CI test builds are run by Travis CI whenever a pull request is created or updated
- Travis runs the same test suite in several environments including node versions 0.12, 4.6, and 6.7
- The node tests on Travis seem stable and consistently pass
- One configuration travis runs sets `BROWSER=1` to trigger saucelabs automated browser testing
  - This is handled via `zuul` and amounts to
  - starting up a local express server on the travis worker instance
  - using zuul to open up a port on localtunnel.me so that local express instance is Internet-accessible
  - launching a suite of saucelabs headless/automated browser tests running the superagent client tests pointing at the localtunnel URL
  - In Travis, I think we experience 3 types of failures
   - Some saucelabs OS/browser combos fail by exceeding a 2s timeout
   - Some saucelabs OS/browser combos fail by exceeding a 10s timeout
   - Some saucelabs fail with connection refused from travis worker out to localtunnel

## Local Behavior

- Trying to run `make test-browser` from my laptop seems to start/wait/restart saucelabs instances for a very very long (forever?) time. Many many minutes go by without seeing any successful runs.

## Open Questions

- Why don't the zuul/saucelabs tests work when run locally
- Why do the zuul/saucelabs tests fail when run within Travis?
- Should we consider switching to [the Travis Sauce Connect Addon](https://docs.travis-ci.com/user/sauce-connect/)?
- Should we switch to a saucelabs alternative?

**Comment by pornel** [comment]
Most failures I've seen are either timeouts or connection refused by localtunnel. This makes me suspect that flakiness is mainly because localtunnel.me is slow/unreliable: #972 (although it could also be connectivity issue between saucelabs<>localtunnel or travis<>localtunnel)

**Comment by focusaurus** [comment]
Closing. Will comment on 972.
