### ISSUE TITLE
Why can't we get set-cookie header? 

### ISSUE THREAD

**Issue by ceremcem** [visionmedia/superagent#1091]
I'm using superagent in the browser and I can not get `set-cookie` header field in the response. It's dropped in somewhere. Is it on purpose, or is it a bug?

**Comment by focusaurus** [comment]
I believe the `Set-Cookie` response header is explicitly not exposed to javascript on the page by the browser itself. There's mention of this [in the MDN getAllResponseHeaders documentation](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/getAllResponseHeaders) but I couldn't quickly find any additional detail.
