### ISSUE TITLE
How to see per-version download distribution?

### ISSUE THREAD

**Issue by jpodwys** [visionmedia/superagent#1092]
I'd like to be able to see download metrics for each major release of superagent. For example, I'd like to know what percentage of downloads [listed on NPM](https://www.npmjs.com/package/superagent) are from superagent `0.x`, `1.x`, and `2.x`.

Is there any way I can find this information?

Thanks!

**Comment by pornel** [comment]
I don't have that information. I vaguely remember that there was a 3rd party project which allowed you to download and query a massive data dump of npm stats, but I forgot how it was called.

**Comment by jpodwys** [comment]
OK thanks for the fast response.
