### ISSUE TITLE
Patch Version Bump?

### ISSUE THREAD

**Issue by duereg** [visionmedia/superagent#1093]
You merged in a bunch of bug fixes... could you release a patch version with the new changes?

**Comment by jknight12882** [comment]
👍  on this, looks like it fixed a fairly nefarious memory leak

**Comment by pornel** [comment]
_Potential_ memory leak. Nobody complained about leaks before, so I think it's more of a good practice than a fix for a nefarious problem.

**Comment by pornel** [comment]
npm i superagent@next
