### ISSUE TITLE
"double callback!" warning needs more details

### ISSUE THREAD

**Issue by pkaminski** [visionmedia/superagent#1094]
I'm getting the infamous `double callback!` warning regularly in production and can't figure out how to track it down.  There's no way to tell which requests are causing it (there's many dozen varied ones running at any given time), or even which version of `superagent` it's coming from (I'm running 2.3.0, but a dependency still uses 1.8.3).  Including the request's URL in the warning would help a lot and may allow me to spot a pattern that will lead to a repro; adding some indication that the warning is from `superagent` would be a nice touch too.  Thanks.

**Comment by pornel** [comment]
Please try overriding the dependency version (or better, as dep author to upgrade) and see if the warning still appears. There's ~90% of chance that the warning comes from the old version and that we've already fixed the bug.

**Comment by pkaminski** [comment]
I opened https://github.com/segmentio/analytics-node/issues/72 but it's not clear how well that project is maintained.  I still think improving the warning message would be a good thing to do since right now it takes a fair bit of Googling (and luck) to find the source.

**Comment by pkaminski** [comment]
Actually, I think the `double callback` warnings are coming from `superagent` 2.3.0.  Take a look at the log histograms below, the first for request timeouts that I know were made through `superagent` 2.3.0, and the second for `double callback!` warnings:
![image](https://cloud.githubusercontent.com/assets/1646896/19916483/773748ea-a077-11e6-867d-e4406046661f.png)
![image](https://cloud.githubusercontent.com/assets/1646896/19916491/84d39c10-a077-11e6-94ff-20cf77ace1fc.png)
Not an exact match, but definitely a strong correlation that's exceedingly unlikely to be coincidental.

**Comment by DWboutin** [comment]
I got the `double callback` too, is it possible to get rid of this?

**Comment by focusaurus** [comment]
If you can reproduce on demand, it would be great to get a stack trace. Edit the `node_modules/superagent/lib/node.js` file and replace this line:

     if (this.called) return console.warn('superagent: double callback bug');

with this line:
 
     if (this.called) throw new Error('superagent: double callback bug');

Then reproduce it and post the stack trace here.

**Comment by DWboutin** [comment]
Ok, i'll try it this evening!

**Comment by pornel** [comment]
I've added more info in 1.8.5 and 3.2.0
