### ISSUE TITLE
withCredentials only works in browser(?)

### ISSUE THREAD

**Issue by delenius** [visionmedia/superagent#1109]
It seems that `withCredentials()` has no effect when running a Node.js desktop app. It works as expected when running from a browser. Is this to be expected, and if so, is there any way to have a desktop client set cookies in the requests?

**Comment by pornel** [comment]
`withCredentials` exists only because of [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS), which is a limitation that only exists in browsers (for very good reasons). 

We have absolutely no control over this. You can control these restrictions by supporting appropriate OPTION requests on your server. See docs I linked above.

It doesn't exist in the Node version, because Node doesn't run untrusted code from multiple sources, like browsers do.

**Comment by delenius** [comment]
Hmm, as I understand it, my problem has nothing to do with CORS. I just want to return cookies that I get from previous server responses.

My Java server uses J2EE `@SessionScoped` bean classes. This is supposed to automatically instantiate one bean per "session". The sessions are handled by the server sending the client a cookie (this is done automatically by the J2EE app server), and the client returning the same cookie in subsequent requests.

So, how can I return cookies from Node.js?

**Comment by delenius** [comment]
It is the same as the problem discussed here: http://stackoverflow.com/questions/15485073/how-to-use-cdi-sessionscoped-without-a-http-session

**Comment by pornel** [comment]
I see. Well, then `withCredentials()` is certainly completely unrelated and won't help you at all.

To preserve cookies, you need to create an `agent`:

```js
const agent = request.agent();

agent.get('/url1').then(() => {
    agent.get('/url2').then(etc); 
});
```

The agent object will remember the cookies between requests.

**Comment by delenius** [comment]
Interesting. Does `Agent` have all the methods that `Request` does, like setting accept headers, `end()`, and so on?

**Comment by delenius** [comment]
I got this to work. In the browser, I still use withCredentials, since the browser version of superagent does not have a `.agent` field.

**Comment by evgenosiptsov** [comment]
I have solved it at another way. 

For ExpressJS we need to use **cookie-parser** midlleware
`const cookies = querystring.stringify(req.cookies, '; ', '=');`
variable cookies will contains value that we can pass into Superagent's setting header methods:
`return agent.get(`${BACKEND_URL}/reklama/api/advertisement/${advertisementId}`)
					.withCredentials()
					.set('Accept', 'application/json')
					.set('Cookie', cookies)
					.then((res) => { 
...
})`

Hope, it will be useful.
