### ISSUE TITLE
Content Type header is sent with semicolon

### ISSUE THREAD

**Issue by motymichaely** [visionmedia/superagent#1112]
Hey guys,

We are having a weird issue in which superagent requests content type are received with semicolon: `application/json;` which causes our RoR (Ruby on Rails) servers fail the request.

Is it a know issue?

Thanks!

**Comment by pornel** [comment]
Superagent doesn't add the semicolon. Maybe you have a proxy that does it?

Anyway, the semicolon is a valid part of the syntax, so if server can't parse it, then it's server's bug.
