### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by dciccale** [visionmedia/superagent#1117]
I am using supertest 2.0.1 for testing express server requests, but I get an error from superagent dependency (which has version 2.3.0) but also tested it with superagent@3.0.0

Following this piece of code

```js
...
    this.loginService.login(email, password)
      .then((user) => this.authService.signToken(user._id, user.role))
      .then((token) => ({token}))
      .then((json) => res.json(json))
...
```

It is sending a js object like this `{token: 'eyJhbGciOiJ..._VN735eFTAE'}`

But I get the following error:

```
SyntaxError: Unexpected end of JSON input
....node_modules/superagent/lib/node/parsers/json.js:8:35
```

So I went to that line of code, and the final chunk that is trying to JSON.parse is cut.

`'{"token":"eyJhbGciOiJ..._VN735eFTAE"'` and JSON.parse fails because of the missing last character `}`.

So I tried sending a shorter response (the one with the token is pretty long, the token alone has a length of 220 characters.

this works:

```js
...
      .then((token) => ({token: 'fake'}))
      .then((json) => res.json(json))
...
```

any suggestions? what I am missing? thanks in advance

**Comment by pornel** [comment]
Does it work without supertest? (i.e. if you make a real request over the network with superagent only).

**Comment by dciccale** [comment]
OK i found the problem, and has nothing to do with superagent feel free to close. However after explaining it here I know it won't make any sense such weird behavior.

There is a module which I export a plain object.
I was requiring this module and using an undefined key because of a typo. since I was passing this function (which is undefined because of the typo) to the `catch` promise chain of bluebird, there was no error at all anywhere, but somehow this was affecting receiving all the data in the request 'data' event (I logged every output of the chunk and it was coming cut by 1 char the last `}`). I do not have full understanding of the whole thing but I am 100% sure this was the problem because by just commenting this out I can reproduce the issue, just by commenting that one catch that looks like this

```
.catch(loginErrors.AuthenticationError, errorHandlers.sendUnauthorized(res))
```

where `loginErrors.AuthenticationError` is undefined.

just commenting that line makes it work. of course now I fixed the typo and no need to comment it.

thanks for driving me on a direction which allowed me to find this :)
ESLint basically have no way to know I was passing an undefined value into a catch promise chain which was not being called anyway.. but beneath the dungeons some check in bluebird would have thrown an error in the middle of the request, who knows ;)

**Comment by pornel** [comment]
Cool, thanks :)

BTW: all supported node versions have native promises now, and current node warns about unhandled rejections.

**Comment by dciccale** [comment]
I know, I'm using node7, but was not getting the unhandled rejection because the error may happened outside the promise chain which I guess it should have failed also in some way or another but yeah I have no clue of what exactly happened a part from my previous description. And apart from the error I stated there was no other.
