### ISSUE TITLE
Can't find variable btoa

### ISSUE THREAD

**Issue by manosim** [visionmedia/superagent#1122]
Hello and that's for making superagent! I am working on a react-native project and I am trying to make a request that has basic authentication. So my code is just:

```javascript
    return request
      .get(`${Constants.URL}/example`)
      .auth(Constants.USERNAME, Constants.PASSWORD) // <--------
      .end((err, res) => {
        if (err || !res.ok) {
          return dispatch({ type: FETCH_DATA.FAILURE });
        }
        return dispatch({ type: FETCH_DATA.SUCCESS, payload: res.body });
      });

```

As you can see in the screenshot below, the error I am getting is due to `.auth(..., ...)`.

<img width="1280" alt="screen shot 2016-12-06 at 16 30 23" src="https://cloud.githubusercontent.com/assets/6333409/20934414/f68e1c56-bbd2-11e6-9c23-ee6fd84d2d40.png">

So if I comment out `.auth(..., ...)` the it works but obviously the request is failing. After reading the source code, I can see that `btoa` is supposed to be set in the window and since this is a react-native app there is no `window`.

### A possible fix
I did find out that in the tests you are doing [this](https://github.com/visionmedia/superagent/blob/5e841d6dcad7ae3c2d13a31d00c9063ae7e56ee7/test/client/request.js#L143): `window.btoa = window.btoa || require('Base64').btoa;`

I can open a PR that has this change and also move the `Base64` dependency from `devDevependencies` to `dependencies` if you think this is the correct approach.

**Comment by pornel** [comment]
We deliberately don't do this, because it increases size of superagent.js (for all browsers, even those which have `btoa`).

In browsers it's needed only for IE9. React native is a new problem, but the solution is the same as we recommend for IE9: you should fix it yourself, in your code:

```js
window.btoa = require('Base64').btoa;
```

**Comment by manosim** [comment]
@pornel Agreed and thank you for your quick reply! For any future reference the way to fix this is:

Install `Base64` (note the capital **B**) from npm:

    npm install --save Base64

Then in your code before requiring `superagent` do:

    window.btoa = require('Base64').btoa;
