### ISSUE TITLE
SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by nshahpazov** [visionmedia/superagent#1127]
I'm trying to make a request to a express.js server sending an empty json object. What I get back is an error Unexpected end of JSON input.

It looks similar to this one:
https://github.com/visionmedia/supertest/issues/169

**Comment by pornel** [comment]
I think it's a bug in supertest only.

Can you reproduce the problem with superagent, *without* supertest?

**Comment by nshahpazov** [comment]
I'm not using supertest. This is what get as a stack.



(node:49885) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
  /api/organizations
{ SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/Users/nikolashahpazov/projects/volontime-api/node_modules/superagent/lib/node/parsers/json.js:8:35)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  rawResponse: '{"message":"Missing fields","errors":[{"message":"name cannot be null","path":"name"},{"message":"type cannot be null","path":"type"},{"message":"overview cannot be null","path":"overview"}]',
  statusCode: 400,
  response: undefined }
    ✓ should get validation errors

**Comment by nshahpazov** [comment]
I have tracked where the problem is. It seems to be in a dependency I'm using on the server - express-session which slices the length by 1.

https://github.com/expressjs/session/issues/395

Feel free to close the issue here :)

**Comment by pornel** [comment]
Thanks
