### ISSUE TITLE
Json parsing error is occurred when the pound symbol is contained in body request.

### ISSUE THREAD

**Issue by henrykapostel** [visionmedia/superagent#1131]
### Hello,

Please check my code and let me know how to solve this problem.

const API_URL = '...';
const KEY = '...';
const message = 'You sent £100 successfully';
export default function func1(tokens, message) {
  const promises = tokens.map((token) => {
    const body = {
     ...
      notification: {
        body        : message,
        ...
      },
      ...
    };
    const bodyStr = JSON.stringify(body);
    return request
      .post(API_URL)
      .set('Accept-Encoding', 'gzip,sdch')
      .set('Content-Type', 'application/json')
      .set('Content-Length', parseInt(bodyStr.length, 10))
      .set('Authorization', `key=${KEY}`)
      .send(bodyStr);
  });
  return Promise.all(promises)
  .then(() => console.info('success'))
  .catch(e => console.info(e));
}

### After running, the error occurred as following:
Error: Bad Request
    at Request.callback (/node_modules/superagent/lib/node/index.js:649:11)
    at Stream.<anonymous> (/node_modules/superagent/lib/node/index.js:846:18)
    at emitNone (events.js:86:13)
    at Stream.emit (events.js:185:7)
    at Unzip.<anonymous> (/node_modules/superagent/lib/node/unzip.js:63:12)
    at emitNone (events.js:91:20)
    at Unzip.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:973:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  status: 400,
  response: 
   Response {
     domain: null,
     _events: {},
     _eventsCount: 0,
     _maxListeners: undefined,
     res: 
      IncomingMessage {
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        socket: [Object],
        connection: [Object],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Object],
        trailers: {},
        rawTrailers: [],
        upgrade: false,
        url: '',
        method: null,
        statusCode: 400,
        statusMessage: 'Bad Request',
        client: [Object],
        _consuming: true,
        _dumped: false,
        req: [Object],
        setEncoding: [Function],
        on: [Function],
        _text: 'JSON_PARSING_ERROR: Unexpected token END OF FILE at position 316.\n',_
        read: [Function] },

**Comment by focusaurus** [comment]
It looks to me like the issue is probably with sending a compressed response body but manually setting the `Content-Length` header based on the uncompressed body size, thus resulting in there being less data than declared due to compression. In both your client and server code, it is usually best to let your libraries handle `Content-Length` automatically as they will calculate it correctly. I doubt this has anything to do with the actual content of the request body in terms of pound sign.

**Comment by henrykapostel** [comment]
Oh, I got it.
Thanks very much!! it works now
