### ISSUE TITLE
How to handle response `Content-Type: application/jwt`?

### ISSUE THREAD

**Issue by gargsms** [visionmedia/superagent#1135]
The Microsoft Translator API returns an auth token with `Content-Type: application/jwt` http://docs.microsofttranslator.com/oauth-token.html

The POST request succeeds with status code set to 200, but the response body is just an empty object, and the response text is undefined.
This is not the behaviour in case of [request](https://github.com/request/request) where the response is just the auth token.

Can superagent handle arbitrary response types? So far, `application/json`, `text/plain`, `text/html` has worked fine for me.

**Comment by focusaurus** [comment]
You can extend parsing with `request.parse['application/jwt'] = function (text) { return text }`. Similarly you could decode the JWT into a javascript object if that makes sense for your application.
