### ISSUE TITLE
Why is super agent inventing errors?

### ISSUE THREAD

**Issue by hepiyellow** [visionmedia/superagent#1139]
This code  (line 618) creates errors whenever the response status is not 200-300.
This makes it hard to do testing with packages like chaiHttp (which use super agent).

Can this be disabled with a configuration flag?

```
if (res && res.status >= 200 && res.status < 300) {
    return fn(err, res);
  }

  var msg = 'Unsuccessful HTTP response';
  if (res) {
    msg = http.STATUS_CODES[res.status] || msg;
  }
  var new_err = new Error(msg);
  new_err.original = err;
  new_err.response = res;
  new_err.status = (res) ? res.status : undefined;

  fn(err || new_err, res);

```

**Comment by pornel** [comment]
I wouldn't call it inventing. By default superagent treats status 2xx as success, and everything else as error. That's mostly in line with intentions of the http spec.

Note that in most cases there's `err.response` if you want to read content of error pages.

In the latest version there's `.ok()` function for customizing which responses are treated as errors.

**Comment by hepiyellow** [comment]
Great. 
The ok() function would work. 

Too bad though that chaiHttp uses superagent 2.x..x
