### ISSUE TITLE
Why does a crossDomainError attempt to pull the status from the Request prototype?

### ISSUE THREAD

**Issue by mmmeff** [visionmedia/superagent#1140]
See title

Happens here:
https://github.com/visionmedia/superagent/blob/master/lib/client.js#L613

I believe Chrome just recently started handling CORS requests a little differently and has started to enforce a stricter policy where the response headers must contain CORS headers for not just the OPTIONS but also the related req/res as well. I'm aware this is a spec requirement, but Chrome used to be forgiving on this and brought my API issues to light.

In attempting to debug what was going on, I noticed superagent was dropping the response code in errors due to this scenario and dug up the above line that is doing nothing as far as I can tell.

Is there a reason for this code that I'm missing?

**Comment by pornel** [comment]
That line of code is pointless indeed. In case of CORS error we don't get any status.
