### ISSUE TITLE
    TypeError: res.setEncoding is not a function

### ISSUE THREAD

**Issue by Slavrix** [visionmedia/superagent#1142]
Getting these error when trying to return a successful response

```
    Refused to set unsafe header "accept-encoding"
    Refused to set unsafe header "user-agent"
    Refused to set unsafe header "content-length"
    TypeError: res.setEncoding is not a function
    at parseJSON
```

**Comment by pornel** [comment]
It looks like you're using Node-only version of Superagent in a web browser. This won't work. In browser you can only use browser version of superagent.

The correct version is automatically picked by browserify and webpack (in webpack target:"browser"   (default) in config controls this).
