### ISSUE TITLE
Data not getting passed on PUT

### ISSUE THREAD

**Issue by nalumachurakesh** [visionmedia/superagent#1143]
I'm passing a integer in PUT request to update. But, that integer is not getting passed.

 return new Promise((resolve, reject) => {
                request
                    .put(url)
                    .send(2)
                    .end(function (error, result) {
                        error ? reject(error) : resolve(result.body);
                    })
            });

I have added the sample code which I use to update using PUT.

Thanks.

**Comment by pornel** [comment]
We do have [a test for PUT](https://github.com/visionmedia/superagent/blob/master/test/request.js#L164), so I think it works in general.

If you're sending from browser, make sure you implement CORS.

That `2` looks suspicious. Try `"2"` or `{id:2}`.
