### ISSUE TITLE
question - how does this lib find an available empheral port?

### ISSUE THREAD

**Issue by ORESoftware** [visionmedia/superagent#1144]
Been looking through the source and trying to figure out how this library discovers an available emphemeral port. Can't figure it out. I am hoping I can use this same code for another project I am working on.
Please advise, thanks!

**Comment by pornel** [comment]
This library doesn't handle this level of detail. Actual request and setting of ports is delegated to Node.js (or the browser in browser version), so the answer is "whatever Node.js usually does".

**Comment by ORESoftware** [comment]
Ok hmmm, but somehow this library tells Node.js to use an emphemeral port instead of a specific designated port. Or is it simply that if no port is given that Node.js will by default find an emphemeral port?

ok I think I figured it out, if you don't specify a port, Node.js will find an ephemeral port

```js
const net = require('net');
const server = net.createServer((c) => {
    // 'connection' listener
    console.log('client connected');
    c.on('end', () => {
        console.log('client disconnected');
    });
    c.write('hello\r\n');
    c.pipe(c);
});

server.on('error', (err) => {
    throw err;
});

server.listen((data) => {
    console.log('server bound ', data);
});

server.on('listening', function(data){
    console.log('server address => ', server.address())
});

```
thanks for the info!

**Comment by ORESoftware** [comment]
well, actually, I should have asked, in the "browser version", how does this work with emphemeral ports?

**Comment by pornel** [comment]
Since you're talking about the test suite, in browser version it's the same — test server is still runs in node.

**Comment by ORESoftware** [comment]
alright :) thanks
