### ISSUE TITLE
Socket hang up on GET request with Auth header JWT

### ISSUE THREAD

**Issue by ttbarnes** [visionmedia/superagent#1145]
Hey, i'm getting an error with a fairly simple GET request:

```
Error:  { Error: socket hang up
    at createHangUpError (_http_client.js:253:15)
    at Socket.socketOnEnd (_http_client.js:345:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9) code: 'ECONNRESET', response: undefined }
```
Any tips on how to resolve this? Do I need to config some socket things or something? I don't understand if this is an issue with my code or perhaps some dependancy conflict. Everything i've tried doesn't work :(

Here is the test:

```
import superagent from 'superagent';
var request = superagent;

...

const USER_JWT_VALID = 'JWT asdf.....';

it('should work', (done) => {
  request
    .get('http://localhost:3000/api/something/private')
    .set('Accept', 'application/json')
    .set('Authorization', 'Bearer ' + USER_JWT_VALID)
    .end((err, res) => {
      console.log('Error: ', err);
      if (err) done(err);
      expect(res.body).to.be.an('object');
    });
});
```

my related packages: 
```
"express": "^4.14.0",
"superagent": "^3.3.1",
"mocha": "^3.2.0",
```

node v7.3.0.

**Comment by pornel** [comment]
Socket hang up means the server closed the connection, which could be caused either by a hard crash of the server or a serious syntax error in the request. 

So you see any errors on server side? Is it possible that you have some non-ASCII characters or unexpected newlines in your headers?

Try running `nc -l 3000` instead of your server and see what superagent sends.

**Comment by ttbarnes** [comment]
Thanks @pornel ,  

The JWT used in the header is definitely valid. No syntax errors on the server side. 

This error only occurs in test environment. Other GET endpoints that do not require a Authorization header work fine.

I've tried using axios instead and I get exactly the same issue. Therefore this must be something to do with my setup. I suspect i'm missing something silly/obvious - still learning some node things. Any help would be great, i'll update here regardless.

I don't understand how simply adding an authorization header would cause the connection to close and not get any response.

I've enabled the server logs and it doesn't even seem to be sending a request, just instant 'socket hang up', with superagent and axios.

**Comment by focusaurus** [comment]
Your server is probably crashing due to an uncaught exception in your auth related code. Perhaps there's a `JSON.parse` call not wrapped in `try/catch`? But the problem is not in your superagent client code, it's in your express server.

**Comment by ttbarnes** [comment]
You're right @focusaurus  :) The auth check for this particular endpoint uses node passport. Within my tests using superagent, the endpoint is not getting past the passport check part:

The code:

```
router.route('/private')
  .get(
    passport.authenticate('jwt', { session: false }), (req, res, next) => {
      res.json({ allTheThings: true });
  })
```

Works fine in dev environment.  Still looking, will update.

**Comment by ttbarnes** [comment]
Sorry guys - this is nothing to do with superagent. This seems to be a bug with passport-jwt (auth GET requests are not getting past passport auth) Thanks all the same! :)
