### ISSUE TITLE
request body on error while using `await`

### ISSUE THREAD

**Issue by Kufert** [visionmedia/superagent#1148]
How can I get the request body in case the request failed (i.e. 422) while using `await`?

for example:

```
  let response
  try {
    response = await request.post(url)
    return response.body
  } catch (e){   
    console.log(response) #<---- undefined on error
  }
```

**Comment by Kufert** [comment]
to answer my own q - 

`e.response` #<-- response

**Comment by liesislukas** [comment]
it is undefined because `response = await request.post(url)` assigment never happens on error and in 1st line you have created `response` variable with value `undefined`.
