### ISSUE TITLE
Saucelabs Appium support is dead

### ISSUE THREAD

**Issue by kornelski** [visionmedia/superagent#1151]
The tests failed due to:

> Android@5.1: [init({"build":"1265","name":"superagent","tags":[],"browserName":"android","version":"5.1","platform":"Linux","appium-version":"1.6"})] The environment you requested was unavailable.: Appium 1.6.3 does not support Linux. Please check our platform configurator (https://saucelabs.com/docs/platforms)

I'm not sure if we need to specify something like "Android on Windows" (dunno how) or something else entirely. The linked page doesn't explain anything in detail.

For now I've removed Android from tests d7d2839437e74feb7a500fcb9b2a40b825c18725

**Comment by focusaurus** [comment]
I think the issue is the appium version. Using the saucelabs platform
configurator, it looks like if we want to test Android 5.1 that only works
on Appium 1.5 and 1.4.

**Comment by pornel** [comment]
Yeah, but staying on an old version of Appium doesn't seem like a proper (long-term) solution.

**Comment by kornelski** [comment]
Now Saucelabs fails with "Appium 1.7.2 does not support Mac 10.13. "
