### ISSUE TITLE
.send() encoding problem

### ISSUE THREAD

**Issue by Glutch** [visionmedia/superagent#1156]
i'm sending some text via .send(), the site uses charset ISO-8859-1.

I tried setting the charset with
```
const charset = require('superagent-charset')
charset(request)
.charset('ISO-8859-1')
```
Which has worked previously when **reading** the response. But when i'm sending, the text coming up on the site is encoded weirdly. å showing up as Ã¥ etc. Is there a specific method of setting the charset of .send()?

Thanks a lot

**Comment by pornel** [comment]
So, in general the Web platform supports only UTF-8 well, and the rest is legacy and broken.

I don't think it's possible to send a *string* via XHR and have it latin1-encoded.

It's definitely impossible to do that if you're sending files (using `.field()` and `.attach()`).

You could try:

- change encoding of your entire page to ISO-8859-1 encoding
- apply your own URL-encoding and use `request.post().type('form').send('text=%e5')`
- tell the recipient that UTF-8 is 25 years old and it's time to upgrade

**Comment by Glutch** [comment]
@pornel Havent managed to solve it yet :(

I'm sending a payload like this

```
const payload = `------WebKitFormBoundaryBkSiVoOiTVrsXXjp
Content-Disposition: form-data; name="something"

Hey!
------WebKitFormBoundaryBkSiVoOiTVrsXXjp
Content-Disposition: form-data; name="something else"

How you doin? ÅÄÖ
------WebKitFormBoundaryBkSiVoOiTVrsXXjp--`

user
    .post('http://url')
    .send(payload)
```

Any new ideas or tips would be greatly appreciated

**Comment by pornel** [comment]
I think `.send()` will always use UTF-8, or at least the same encoding as the page. I forgot how '90s encodings work...
