### ISSUE TITLE
RequestBase.prototype.catch call error "parse error" in old version webkit

### ISSUE THREAD

**Issue by lyykfi** [visionmedia/superagent#1158]
Solve problem - RequestBase.prototype["catch"]

**Comment by pornel** [comment]
That must be a *very* old WebKit.

**Comment by lyykfi** [comment]
Yes )
I am building smart TV project with webpack

**Comment by pornel** [comment]
Run `make test-browser-local` and open that URL on your TV to see if it's compatible.
