### ISSUE TITLE
Downloading binary data

### ISSUE THREAD

**Issue by a-ludi** [visionmedia/superagent#1161]
Could you please document somewhere the function at [https://github.com/visionmedia/superagent/blob/054782dfaa3f0fd360411be0cbd0f8319d8a75b9/lib/node/index.js#L346](https://github.com/visionmedia/superagent/blob/054782dfaa3f0fd360411be0cbd0f8319d8a75b9/lib/node/index.js#L346)? It is tremendously useful if you just want to download binary data. You can use it like this:

```javascript
var stream = fs.createWriteStream('path/to/my/file.zip');

request.get('http://example.com/file.zip').pipe(stream);
```

**Note:** IT does __NOT__ work if you use the `Reponse#pipe()` method. That method only produces garbage.

**Comment by pornel** [comment]
Could you help with it and make a PR?

**Comment by nwwells** [comment]
I would gladly help with a PR. Also, I'd like to suggest that using `pipe` on the response object from `end` should throw an error. Fail fast and all that.

**Comment by pornel** [comment]
cc #1188

**Comment by nwwells** [comment]
@pornel how do I build the docs?

**Comment by pornel** [comment]
```sh
make docs
```

**Comment by nwwells** [comment]
Should be closed by #1315

**Comment by sebastialonso** [comment]
Any ideas on how to check if the request failed before piping (say 401, or 404)?

**Comment by kornelski** [comment]
You can't directly. You have to call either `.pipe()` or `.then/.end()` first to make the request.

There's `response` event which lets you inspect the headers as soon as they arrive. Then you can unpipe?

Also with the pipe you should get `error` event on the pipe.

**Comment by sebastialonso** [comment]
Thanks for your reply @kornelski 
Yesterday I lost all my afternoon trying to trigger the error event on the pipe, forcing a 401 on my request, so I can say with a very high degree of confidence that the event it's either not being fired by the request error, or it's not working.

~~~javascript
return new Promise((resolve, reject) => {
    stream.on("finish", () => {
      console.log("File saved")
      resolve(stream.path);
    });
    stream.on("error", (err) => {
      console.log("error in request")
    })
  });
~~~
