### ISSUE TITLE
Question - What about adding a libhive badge for real code examples ?

### ISSUE THREAD

**Issue by libHive** [visionmedia/superagent#1162]
Libhive is a site that shows how packages are used by other packages.
There are currently around 3000 examples of how superagent is used.
We have a nice badge that can link to this -

[![libhive badge](https://www.libhive.com/providers/npm/packages/superagent/examples/badge.svg)](https://www.libhive.com/providers/npm/packages/superagent)

What do you think about adding this to the Readme ?
Thanks

**Comment by pornel** [comment]
Thanks for the suggestion. It's a cool idea.

Unfortunately in superagent's case the examples shown happen to be very basic 1-liners that don't tell much about the library.

**Comment by libHive** [comment]
:ok: 
We'll keep working on making the examples more useful - challenge accepted ;)
:tophat: Thanks for the awesome feedback !

**Comment by libHive** [comment]
Hi @pornel 
I revised the scoring algo so the examples are a bit more "lush".
Maybe you could reconsider ? :blush:  
Thanks

**Comment by pornel** [comment]
This is still showing usage in a misleading way that looks incorrect:

```
superagent = require('superagent')
agent.get('localhost:3000/multi')
agent.get('localhost:3000/raw?test=/api/countries')
agent.get('localhost:3000/multi?country=/api/countries')
agent.get('localhost:3000/multi?user=/api/customers/23&country=/api/countries')
agent.get('localhost:3000/multi?foo=/api/foo/&country=/api/bar')
agent.get('localhost:3000/multi?headers=/return-header')
```

It's not possible to have good 1-line example of superagent, becuase it has a fluent interface and at very least you must have a call to `.get()` and `.end()` or `.then()`. Limiting examples to just 1 function makes them invalid.

Instead of cutting examples down to one line/one function call, you should display at least one complete JS statement.

So this:

```js
        agent.get('localhost:3000/multi')
```
is invalid.

But the expanded version:
```
        agent.get('localhost:3000/multi').end(function(err, res) {
            assert.equal(res.statusCode, 200);
            // an empty object is returned if no parameters has been passed in
            assert.deepEqual(res.body, {});

            done();
        });
```

is OK-ish.

**Comment by pornel** [comment]
As for the ranking: the first result request-curator - request-curator-test.js is from a unit test, so it's a bit artificial. The second result farm-budgets-sdk - materials.js - is much nicer. It shows actual usage.

But it seems like half of the results are from unit tests, and even 3 in the row are indentical:

> ...
request = require('superagent')
request.get('http://localhost:1234/foo.js')
request.get('http://localhost:1234/bad.js')
request.get('http://localhost:1234/coffee.js')
request.get('http://localhost:1234/moobar.js')
...
browserify-dev-middleware - index.jsOpen full file
...
request = require('superagent')
request.get('http://localhost:1234/foo.js')
request.get('http://localhost:1234/bad.js')
request.get('http://localhost:1234/coffee.js')
request.get('http://localhost:1234/moobar.js')
...
koa-less-middleware - index.jsOpen full file
...
request = require('superagent')
request.get('http://localhost:1234/foo.js')
request.get('http://localhost:1234/bad.js')
request.get('http://localhost:1234/coffee.js')
request.get('http://localhost:1234/moobar.js')

**Comment by libHive** [comment]
Thanks ! This is some priceless feedback.
I'll keep working on it :hammer_and_wrench:
