### ISSUE TITLE
On using .then I get UnhandledPromiseRejectionWarning: Unhandled promise rejection

### ISSUE THREAD

**Issue by shraddha30** [visionmedia/superagent#1163]
How do I use .then and handle promise rejections using superagent?

**Comment by pornel** [comment]
Node wants you to add `.catch()` to the Promise. Using `.then(successCallback, errorCallback)` works too. 

You only need to catch errors on the last promise in a promise chain. If you're using superagent in a function that shouldn't be handling the error itself, then return the promise and let caller handle it.

BTW, I've found `node --trace-deprecation --trace-warnings` is helpful in finding where the warnings come from.
