### ISSUE TITLE
Sending POST body to GET request

### ISSUE THREAD

**Issue by jdmswong** [visionmedia/superagent#1165]
#534 Mentions the following line in the docs ( which I have been unable to find for myself )

> When issuing a GET request the res.send(obj) method will invoke res.query(obj)

I want to use an API which requires POST body params for its GET requests.  How can I achieve this with superagent?

**Comment by pornel** [comment]
In browsers it's not possible to send GET body. However, it works fine in Node version.

**Comment by jdmswong** [comment]
works:
```
const request = superagent['post'](url);
request.send({test: 'HELLO!'})
....
app.use(bodyParser.json());
app.post(url, (req, res) => { console.log(req.body) }
```

doesn't work:
```
const request = superagent['get'](url);
request.send({test: 'HELLO!'})
....
app.use(bodyParser.json());
app.get(url, (req, res) => { console.log(req.body) }
```

node v6.9.4
superagent@3.4.0

**Comment by jdmswong** [comment]
Also works when I call 
```
curl --header "Content-Type: application/json" -XGET <url> -d <json>
```
so the error is not on the receiving side, it's on the sending side

**Comment by pornel** [comment]
Does it work if you JSON.stringify() it first? 

I've added this test:
https://github.com/visionmedia/superagent/commit/aa8f1aef80a376b89c379957eb36951b910cdaf2

**Comment by sahil87** [comment]
I use body in GET queries frequently.
I was stuck with this issue for a long time (superagent not populating body in GET request) before stumbling here.

Why not let the library user decide whether they want to send a body or not?
According to [this](discussion), it allowed in HTTP specs too.

**Comment by niftylettuce** [comment]
Your "this" link was invalid, and pointed at a discussion?  You should never have a body in a GET request.
