### ISSUE TITLE
Using 'finally' on request

### ISSUE THREAD

**Issue by refaelos** [visionmedia/superagent#1170]
Hey, Great work on this plugin!

I understand that the promises support is not so great ... is that right?
I was just trying to call 'finally' on the request and got an error. Apparently only 'then' is supported...

Support in promises is always welcome.

**Comment by pornel** [comment]
AFAIK `finally` isn't in the standard yet. And superagent's `Request` is deliberately designed to be a *thenable* object, not an instance of the `Promise` class.

Promise methods only wait, they don't *start* any actions. So when you call `.then()` on superagent, you call our wrapper around `.end()`, not a method of a promise. 

If you need an actual `Promise` instance (e.g. because you've patched the prototype to add your own finally), then you'll need `Promise.resolve(request).finally(…)`.

**Comment by refaelos** [comment]
Oh... I didn't know that's possible.
Do you have a full example with request.get(...)... ?

**Comment by pornel** [comment]
```js
Promise.resolve(request.get('url')).finally(…).
```

but more realistic would be

```js
request.get('url').then(res => res.text).finally(…)
```

**Comment by IlyaSemenov** [comment]
Is there anything that prevents `finally` to be implemented?

On client side, this is a very common use case to prevent double submit:

```js
this.submitting = true
const { text } = await agent.get(url).finally(() => { this.submitting = false })
```

axios supports that, and having to type twice the code with superagent is frustrating.

**Comment by IlyaSemenov** [comment]
All right, I came up with the ad hoc plugin:

```js
const agent = superagent
  .agent()
  .use(function(request) {
    request.finally = function(fn) {
      return Promise.resolve(this).finally(fn)
    }
    return request
  })
```

Still I don't see any harm in landing this in the core.

**Comment by kornelski** [comment]
`.finally` is kind-of obsolete now:

```js
try {
   const res = await superagent.get(url);
} finally {
   finally_works();
}
```

**Comment by IlyaSemenov** [comment]
No, it's not. In your example, `res` is not accessible outside of the try block, and if the processing code goes inside `try` after `await`, then finally will be called too late.

Of course it can avoided by using `let res` outside of try/finally but then `res` becomes mutable for no reason.

There is no decent alternative to promise.finally for this scenario.

**Comment by kornelski** [comment]
That's logical, because in case of an error, there could be no `res`. And if you need a different behavior for success and error case, that's what try/catch are for.

**Comment by IlyaSemenov** [comment]
No, that's not logical, because the original example intentionally does NOT handle errors, therefore, `res` will always exist:

```js
this.submitting = true
const res = await agent.get(url).finally(() => { this.submitting = false })
// Further processing.
// res is guaranteed to exist and it is immutable!
```

Your supposed 'replacement' is invalid:

```js
try {
   const res = await superagent.get(url);
   // If processing goes here, finally will be called too late.
} finally {
   finally_works();
}
// If processing goes here, res is not be accessible.
```

replacing `const` with `let` makes the response it mutable:

```js
let res
try {
   res = await superagent.get(url);
} finally {
   finally_works();
}
// res is undesirably mutable. the developer may write:
// res = 'bazinga'
```

besides, the code becomes twice as long.

**Comment by IlyaSemenov** [comment]
In any case, the current implementation is plain wrong regarding its own type definitions. The return type is advertised to be `Promise<Response>`:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1e39558ee2231ad3df45859b81031da4d6425042/types/superagent/index.d.ts#L120

```ts
    interface Request extends Promise<Response> {
```

and Promises are officially supposed to have `then`, `catch`, and `finally`:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise#Methods_2

**Comment by kornelski** [comment]
Superagent doens't have its type definitions. Someone else wrote them incorrectly.

Superagent's request is a thenable, it only guarantees to have `.then`.
