### ISSUE TITLE
Browser Cache

### ISSUE THREAD

**Issue by refaelos** [visionmedia/superagent#1171]
How is it possible to use the browser cache for calls?

**Comment by pornel** [comment]
It's used by default. Use GET requests. On your server add "Cache-Control: max-age=999" (number of seconds) to make responses cacheable.

**Comment by focusaurus** [comment]
superagent (and all other browser HTTP client libraries) is ultimately built upon the functionality provided by `XMLHttpRequest` which does make use of the browser cache, but the specifics of how and when it is used are complex and may vary between browsers. You as a developer don't have any mechanism to explicitly opt in or out of the cache, other than using URLs with cachebust parameters in them.

**Comment by refaelos** [comment]
Thanks
