### ISSUE TITLE
fetch vs superagent with turned on withCredentials

### ISSUE THREAD

**Issue by indapublic** [visionmedia/superagent#1172]
Superagent code:

```
superagent
      .post(this.apiUrl + '/login')
      .send(data)
      .set('Accept', 'application/json')
      .set('Content-Type', 'application/json')
      .withCredentials()
      .end((err, result) => {
        console.log(err)
        console.log(result)
      })
```

Fetch code:

```
return fetch(this.apiUrl + '/login', {
      method: 'POST',
      headers: this.postJsonHeaders(),
      body: JSON.stringify(data),
      mode: 'cors',
      credentials: 'include'
    })
```

Response header contain `Set-Cookie:token=c06a3daba059e32529d2a25ab4be45bd; path=/; HttpOnly`

If I using fetch, I see cookies in Chrome console.
![screen shot 2017-02-08 at 12 46 21](https://cloud.githubusercontent.com/assets/856260/22721474/b14afdd8-edfc-11e6-8f4e-90781fe50f5d.png)

But if I using superagent, cookies is clear

![screen shot 2017-02-08 at 12 48 07](https://cloud.githubusercontent.com/assets/856260/22721504/dfc580c0-edfc-11e6-9ca3-e066d0c4c322.png)

**Comment by romanlex** [comment]
why topic is closed? I can confirm this. Cannot set cookie from server

**Comment by indapublic** [comment]
@romanlex I'm using **fetch** now

**Comment by catamphetamine** [comment]
I can also confirm this bug.

**Comment by catamphetamine** [comment]
Wow, just installed the fresh version `8.0.0` and seems like the bug has been fixed.
