### ISSUE TITLE
ERROR in Template execution failed: Error: Browser-only verison of superagent could not find XHR

### ISSUE THREAD

**Issue by khayalan-mathew** [visionmedia/superagent#1173]
Hello :)

Im having some trouble with this module atm...
At compiling with webpack i get the following error

```
ERROR in Template execution failed: Error: Browser-only verison of superagent could not find XHR

ERROR in   Error: Browser-only verison of superagent could not find XHR
```

I tried many other options to do http requests but all failed for some reason (in devbuild they work, just productionbuild not)

A link to my project is here, if necessary [>CLICK<](https://github.com/khayalan-mathew/gymdonapp/tree/feature/react-redux)
I searched in the internet but didnt found anything useful...

Thanks for the help in advance

**Comment by pornel** [comment]
Looks like you're bundling code using webpack or browserify that are configured to produce browser-only code, but you're not running this code in a real browser.

Either change your build system to build for nodejs, or change environment to be a real browser.

**Comment by khayalan-mathew** [comment]
Sorry if i misunderstood anything, but im building it with webpack and run the result in a browser (Chrome to be exact). Can it be that the cross-env package is the "fail"?

**Comment by khayalan-mathew** [comment]
Fixed it :) Deactivated ServerSide Rendering ^^ Thanks for the help

**Comment by foxpsd** [comment]
Hello :)
@pornel  want to ask how to configure webpack to produce a code for Node?
really confused~
Thanks for the help in advance

**Comment by pornel** [comment]
Add "target":"node" to your webpack config.
