### ISSUE TITLE
Require('emitter') in client.js not nesesary 

### ISSUE THREAD

**Issue by gerhardsletten** [visionmedia/superagent#1179]
Is there a reason that we cant require `component-emitter` instead of `emitter` [in lib/client.jsL15](https://github.com/visionmedia/superagent/blob/master/lib/client.js#L15) ?

Then this superagent will be compatible with more bundlers. Have an issue with FuseBox now..

In the package.json it is defined as the a replacement for emitter:

```json
"browser": {
  "./lib/node/index.js": "./lib/client.js",
  "emitter": "component-emitter",
  "./test/support/server.js": "./test/support/blank.js"
},
```

**Comment by pornel** [comment]
I guess it's not needed.

**Comment by gerhardsletten** [comment]
Have submitted a PR #1180
