### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by aruljagang** [visionmedia/superagent#1182]
I installed superagent using npm install superagent it successfully installed after that browserify my project which contain 1 js file, then i tried to execute, but am getting the following error

**Uncaught TypeError: Cannot read property 'prototype' of undefined
    at Object.84../test (index.js:16330)
    at s (index.js:1)
    at index.js:1
    at Object.83../lib/agent (index.js:16287)
    at s (index.js:1)
    at index.js:1
    at Object.88.chai (index.js:16798)
    at s (index.js:1)
    at e (index.js:1)
    at index.js:1**

Error Line: 
module.exports.agent = require('./lib/agent'); -< 16287
TestAgent.prototype.__proto__ = Agent.prototype; -<16330

Kindly help me out from this, thanks in advance

**Comment by pornel** [comment]
Looks like `TestAgent` doesn't have a prototype. That's not a type used in Superagent.
