### ISSUE TITLE
timeout fails to fire for MIME type of `application/javascript`

### ISSUE THREAD

**Issue by niftynei** [visionmedia/superagent#1186]
I traced this to a problem with the timeout in general -- any non-buffered request will fail to trigger a timeout.  Passing the same file with a MIME type of `application/json` works as expected, but fails to parse (so it throws an error).

Is this working as intended?

**Comment by niftynei** [comment]
buffering the response with `req.buffer(true)` seems to make the output unreachable.

**Comment by pornel** [comment]
Yes, for unbuffered request this works as intended, because superagent fires `end` event as soon as response arrives, and then it considers the response done, doesn't wait for the body to arrive.

**Comment by niftynei** [comment]
huh. that's in contradiction to the stated purpose of the deadline timeout.  better documentation around MIME-type buffering and the impact of buffering on other flags would be really helpful.

**Comment by pornel** [comment]
Unbuffered responses are unfortunately generally weird in superagent: #950

**Comment by niftynei** [comment]
closing this, as it's not really an issue.
