### ISSUE TITLE
Piping from response object

### ISSUE THREAD

**Issue by julien-f** [visionmedia/superagent#1187]
AFAIU, it's only possible to pipe from the request object but then it's a bit awkward to use the headers before consuming the stream:

```js
const req = req.get('<some download URL>')

// intermediate stream to trigger the request
const stream = req.pipe(new stream.PassThrough())

req.on('response', res => {
  stream.pipe(
    fs.createWriteStream(ers.headers['X-Filename'])
  )
})
```

It would be much nicer if the response could be use as a stream:

```js
req.get('<some download URL>').then(res => {
  res.pipe(
    fs.createWriteStream(res.headers['X-Filename'])
  )
})
```

**Comment by pornel** [comment]
`.then()` pipes the response to a parser, so at the point when *you* get tho see `res` it's already been finished and there is no data to pipe anywhere.

You can't use `.then()` or `.end()` anywhere at all if you want piping.

**Comment by julien-f** [comment]
And where is the data if I set `.buffer(false)?

**Comment by pornel** [comment]
It is in a weird place that only your parser sees. #950

**Comment by pornel** [comment]
cc #1188
