### ISSUE TITLE
headers are not preserved on redirect

### ISSUE THREAD

**Issue by jmarca** [visionmedia/superagent#119]
I've found that superagent drops headers when following redirects. 

I made a lame, non-passing test for the situation, and posted it here

[git://gist.github.com/3764079.git](https://gist.github.com/3764079)

## Use Case 

[CAS](www.jasig.org/cas) is retarded and throws an error if it doesn't recognize the user-agent, but works fine if I pass the header field:

     'User-Agent','Mozilla/5.0 (X11; Linux x86_64; rv:12.0) Gecko/20100101 Firefox/12.0'

I can log in to CAS with superagent, but then the redirect and authencate dance from other CAS-enabled servers fails.  This is because when checking authentication, the server redirects to CAS, but if superagent doesn't hang onto the headers.user-agent, then CAS throws an error and everything breaks.

By the way, this works fine using Mikeal's request library.  He has a headers copy step, but I can't seem to get the same sort of thing to work properly in superagent.  I tried a simple headers copy, but that didn't do the trick.

**Comment by defunctzombie** [comment]
I think this was fixed, if not open a new issue.
