### ISSUE TITLE
Aborted request invokes cross domain error (browser)

### ISSUE THREAD

**Issue by danielpgross** [visionmedia/superagent#1191]
I'm working with version 3.5.0 to do a file upload in Chrome. When calling `request.abort()` on an in-progress upload, a cross-domain error is triggered, even though the request was aborted manually. I've debugged the issue and it appears to be a bug.

The purpose of [this line](https://github.com/visionmedia/superagent/blob/v3.5.0/lib/client.js#L732) appears to be not to trigger an error in case the request timed out or was aborted. However, the value of `self._aborted` in that context comes from the value _saved in the closure_, not the current value. Therefore, it will be the value from when `end()` was originally called, which **will always be undefined/false.**

Example code to reproduce:
```
var req = request
        .post('/rest/upload')
        .attach('test', fileObj)
        .then(function() {});

// Wait for the upload to begin, then call:
req.abort();

// crossDomainError() will be invoked
```

**Comment by pornel** [comment]
The closure uses [reference to the `Request`](https://github.com/visionmedia/superagent/blob/616cbb3507a7c81cc168891860ea060f3a040fd7/lib/client.js#L710), which stays the same for lifetime of the request, so I don't see anything wrong with this code.

[We have a test](https://github.com/visionmedia/superagent/blob/a1a43aaa1b952bacfebf390df7e765176aefcd2b/test/basic.js#L513,L527) for the basic functionality, so it seems to work.

**Comment by danielpgross** [comment]
> The closure uses reference to the Request, which stays the same for lifetime of the request

This is exactly my point -- why check the value of `self._aborted` if it will always be undefined/false? That looks to me like a bug. It seems that the intent was to return in case `abort()` was called and therefore `request._aborted == true`, but this is not the actual behaviour.

Indeed the test validates the basic functionality, but it does not check whether `crossDomainError()` is invoked.

**Comment by pornel** [comment]
Sorry, I don't follow. 

It's not always undefined. `.abort()` sets `this._aborted = true;`

**Comment by danielpgross** [comment]
Never mind, I dove deeper into this and determined that it's actually being caused by my wrong usage. I am using it with React, storing the `Request` object in my component state. Between state changes, I was deep cloning the `Request` object. I was seeing this behaviour because `self` was referring to the original object (pre-cloning), while `._aborted = true` was being set on the new/cloned object.

Lesson learned, deep clones of the `Request` object will not work properly.

My attempted reproduction [here](http://plnkr.co/edit/2xnNeeijjJ2OBGEMNg0M?p=preview) confirmed that this was my bug, not superagent's bug.

Sorry for the confusion and thanks for your help.
