### ISSUE TITLE
CORS issue uploading a file to S3/Minio

### ISSUE THREAD

**Issue by pszabop** [visionmedia/superagent#1193]
I'm having a CORS issue uploading a file to S3/Minio from a browser.  The OPTIONS preflight returns back a 200/OK but superagent reports a CORS error.

I have three domains in my configuration:  javascript from the origin, an appserver, and an S3 clone (minio).  The javascript interacts with appServer using `.withCredentials()`, and the same superagent accesses the S3 minio server by using the URL for that server (but no credentials needed, that's what a presigned URL is for).

I've reproduced this on Firefox and Chrome.

I do not have this issue with XMLHttpRequest.   I followed the [example here ](https://github.com/harshavardhana/minio-js-browser-upload/blob/master/index-post.html )and it works.  I cannot tell any difference between the headers emitted by superagent or XMLHttpRequest.  Note that CORS is enabled by default on minio.

I also note that I have no issues doing this in nodejs, [example here.](https://github.com/pszabop/quickstart-minio/blob/master/test/started.js)

Here's the code that is failing with a CORS exception:

    const httpAgent = (typeof window === 'undefined') ? require('superagent').agent() : require('superagent');
    function uploadMultimediaResource(file, uploadTicket, onSuccess, onFailure)
    {
        console.info(`${objectName}.uploadMultimediaResource(uploadTicket = ${JSON.stringify(uploadTicket)})`);

        const uploadForm = JSON.parse(uploadTicket.uploadForm);
        const req        = httpAgent.post(uploadTicket.uploadLink);

        _.each(uploadForm, (value, key) => {
            req.field(key, value);
        });

        const formData = new FormData();
        formData.append(file.name, file);

        req
            .set('Content-Type', 'application/octet-stream')
            .send(formData)
            .then(res => {

**Comment by pornel** [comment]
Superagent doesn't have any control over CORS. It's 100% internal browser thing, so if you get a CORS error, the browser thinks that CORS headers are incorrect. Please check the headers using devtools.

There's never any CORS in Node, so it's normal that it's not affected.

**Comment by pornel** [comment]
BTW: your FormData isn't going to work. Please use `.field` and `.attach`, and not your own object. Superagent has its own copy of FormData and can't merge two of them, so half of your form will be dropped.

Also you probably shouldn't set Content-Type, unless you want to expose unparsed internals of HTTP request body.

**Comment by pszabop** [comment]
> Superagent doesn't have any control over CORS.

Yet it works with XMLHttpAgent...   I cross checked the headers using devtools and I cannot tell the difference between the two.  The set of fields present is the same.  The contents of the fields are trivially different.

> and .attach

`attach` works in a browser?

I see the mistake above but that should not have affected the OPTIONS request.  The mistake is in the body, which would have gotten to if the OPTIONS request had not failed...   Maybe the error is actually the mistake in the body and I'm getting an inappropriate error message?

**Comment by pornel** [comment]
Hm, it may be possible. On non-HTTP failure XHR reports status == 0, which we *guess* is a CORS error, since that's the most common cause.

**Comment by pszabop** [comment]
I have confirmed that generating headers or body that the browser doesn't like will generate the same error.  You can close this bug unless you can figure out a better error message.  This is a useful thread to keep around as a programming mistake could result in the same confusing message.

(example code above on how to generate a confusing error message :-)

The code below returns a 200/OK on the OPTIONS preflight.  Note I still get a 403 from minio on the POST but that's not a CORS issue, I probably still have a bug, and is unrelated to this issue.

    const uploadForm = JSON.parse(uploadTicket.uploadForm);
    const req        = httpAgent.post(uploadTicket.uploadLink);
    
    
    const formData = new FormData();
    _.each(uploadForm, (value, key) => {      formData.append(key, value);
    }); 
    formData.append(file.name, file);
     req
    .set('Content-Type', 'application/octet-stream')
    .send(formData)
    .then(res => {

**Comment by pszabop** [comment]
Working code.  I should add that this [link](https://blog.gaya.ninja/articles/uploading-files-superagent-in-browser/) here is providing outdated information and needs to be corrected.  I suggest reporting in your documentation that `.attach()` works in a browser now.

    const uploadForm = JSON.parse(uploadTicket.uploadForm);
    const req        = httpAgent.post(uploadTicket.uploadLink);
    
    _.each(uploadForm, (value, key) => {
      req.field(key, value);
    });
      
    req
    .attach('file', file)
    .then(res => {

**Comment by pornel** [comment]
#144 #1154
