### ISSUE TITLE
Error: Not Found

### ISSUE THREAD

**Issue by Wodki** [visionmedia/superagent#1196]
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
```js
Error: Not Found
    at Request.callback (../node_modules/superagent/lib/node/index.js:674:11)
    at ../node_modules/superagent/lib/node/index.js:881:18
    at IncomingMessage.<anonymous> (../node_modules/superagent/lib/node/parsers/json.js:16:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:122:9)
```

I sometimes get this error and I really dont know where it comes from
I am in the latest version 3.5.1

**Comment by pornel** [comment]
You're calling `request.get(…).then(…)`, and you need `request.get(…).then(…).catch(…)`.

**Comment by selenium-tester** [comment]
May I ask why this is the case? I'm still learning how to use this, and I guess maybe the promise docs aren't super clear because with supertest we can, for example:

``` 
await request
        .get(url)
        .set(headers)
        .then((response) =>
        {
            t.is(response.status, 404);
        })
```

I'm using Ava in my case for assertions within the `.then(...)`. I didn't realize this was a feature of supertest; I just switched to superagent since supertest dev seems to have stalled. Is it possible to use promises in this way directly with superagent?

**Comment by pornel** [comment]
Please note that `await` syntax is a different thing, and it's not related to the original question.

You don't need `.then()` if you're using async/await.

**Comment by takao-akiyoshi** [comment]
hi! I use superagent 3.8.3, and I have same error...
Please correct me if I'm wrong.

```
new Promise((resolve, reject) => {
    request
        .post(url)
        .set({'Content-Type': 'application/json', 'X-Authorization': key})
        .send({ k: v })
        .then(res => {
            resolve(res.body);
        })
        .catch(error => {
            reject(error);
        });
});
```

**Comment by kornelski** [comment]
The code is OK. It says not found, because the `url` in your case is not found on the server that the URL points to. That's not a bug in superagent.

**Comment by kornelski** [comment]
BTW: You **never** need to use `new Promise` when interacting with libraries that support promises (including superagent). `new Promise` is only for legacy callback-based libraries. This code is the same as your exaple:

```js
request
        .post(url)
        .set({'Content-Type': 'application/json', 'X-Authorization': key})
        .send({ k: v })
        .then(res => {
            return res.body;
        })
```
