### ISSUE TITLE
Upgrade to jqueryUI 1.12.1 in docs/tail.html

### ISSUE THREAD

**Issue by SethNute** [visionmedia/superagent#1197]
With the recent disclosure of an XSS security vulnerability in jqueryUI version 1.12.0 and lower, would it be possible for you guys to update the version in docs/tail.html? It's getting picked up in a few of my security code scans. I've just `rm`'d the file in my build process for now.

https://nodesecurity.io/advisories/127
https://bugzilla.redhat.com/show_bug.cgi?id=1360286

**Comment by pornel** [comment]
OK ef9af6c85b2b1a0cf5f350bece2f7e33d89b888a
