### ISSUE TITLE
Inconsistent documentation for .attach()

### ISSUE THREAD

**Issue by motet-a** [visionmedia/superagent#1198]
[This](https://github.com/visionmedia/superagent/blob/master/lib/node/index.js#L166) doesn't work in node:

```
.attach(new Buffer('<b>Hello world</b>'), 'hello.html')
```

As specified below, the first parameter of `.attach()` must be the field name. So this should be correct (at least it works for me):

```
.attach('someFieldName', new Buffer('<b>Hello world</b>'), 'hello.html')
```

Moreover, [`new Buffer(string)` is deprecated](https://nodejs.org/api/buffer.html#buffer_new_buffer_string_encoding) and should be replaced by `Buffer.from(string)`.

See also #762.

**Comment by pornel** [comment]
Right. Field name is always required.
