### ISSUE TITLE
Using an insecure version of the dependency, `qs`

### ISSUE THREAD

**Issue by fatman-** [visionmedia/superagent#1201]
More details here: https://snyk.io/vuln/npm:qs:20170213

On way to fix this, would be to update the dependency `qs` to version `6.4.0`

**Comment by pornel** [comment]
We define dependency as `^6.1.0`, which allows 6.4.0, so if you do `npm update`, you'll get the safe version.

**Comment by pea** [comment]
Another package I am using has specified version ~6.3.0 so superuser hasn't installed the latest version. This package shouldn't have done this, but it might be best to change the qs requirement from ^6.1.0 to ^6.5.0".
