### ISSUE TITLE
Multipart POST failing

### ISSUE THREAD

**Issue by dinkom** [visionmedia/superagent#1202]
I've tried building a multipart POST request as described here: http://visionmedia.github.io/superagent/#multipart-requests

This is my code: 
```
request
  .post(endpoint)
  .field('name', 'foo')
  .field('username', 'bar')
  .set('Authorization', api_key)
  .set('Accept', 'application/json')
  .set('Content-Type', 'multipart/form-data')
  .end(callback)
```

Server responds with a bad request - parameter `name` is missing. I know the endpoint works okay because the original is going through a Python app and get a good response, but now I have to reproduce it with superagent.

I also tried replacing ` .set('Content-Type', 'multipart/form-data')` with `.type('form')` and I tried getting rid of `.set('Accept', 'application/json')` which gave me a nice 500.

I doubt there's an issue with superagent, but I'm wondering if someone could tell me what am I doing wrong?

**Comment by pornel** [comment]
Never set Content-Type with multipart, as it erases the boundary argument that has to be set by the browser.

**Comment by dinkom** [comment]
@pornel When I try that, I get a 500.

**Comment by pornel** [comment]
Try adding `.attach('_wahtever_', new Blob([], {type:'blah/blah'});

The reason is we use browser's own `FormData` to build the form, but it doesn't give any control over the format. Adding a fake file may force it to use multipart format.

**Comment by dinkom** [comment]
Unfortunately, that didn't do it (tried both with content-type header and without it, getting same responses as without .attach(...)). There must be something missing in my request that is maybe related to the API itself. I'll investigate more today. In case you have other suggestion regarding what I can try with superagent, please share.

**Comment by dinkom** [comment]
Finally solved this, my clients had an API error they were not aware of... sorry for the trouble.
