### ISSUE TITLE
CrossDomainError with react native

### ISSUE THREAD

**Issue by demonhunterunderdarkness** [visionmedia/superagent#1203]
Superagent is a good job , it simplify much dev works.
Unfortunately,   I want to  build a app for ios platform with react native,but superagent always show CrossDomainError when the app send request to backend.
my dev info:
RN:0.42.3
superagent:3.5.2
PS:superagent worked fine on android app which made by rn too

**Comment by pornel** [comment]
Superagent doesn't know whether the problem is really caused by cross-domain communication. It can be any problem caused by the browser or the system.

Unfortunately I don't know specifics of RN, so I can't help.

**Comment by demonhunterunderdarkness** [comment]
@pornel   Thanks for your answer so quickly, i have figured out how made this.
Because ios security policy require  https  rather than http , so http will be prevented and this will cause superagent to show cross domain error.
Thanks anyway again
