### ISSUE TITLE
.agent() / cookie behaviour changes between 1.5.0 vs 1.6.0 & newer

### ISSUE THREAD

**Issue by mikemaccana** [visionmedia/superagent#1206]
I have a very simple scraper that works consistently on superagent 1.5.0, but fails on 1.6.0 and newer, including 3.x. The script simply GETs login a URL, finds a CSRF token, and POSTs a login. When run on 1.6.0 there's no response to the POST:

    var getLoggedInAgent = function(cb){
      var loginUrl = 'https://www.example.com/account/login.php'
      agent
      .get(loginUrl)
      .end(function(err, res){
        if ( err ) {
          return cb(err)
        }
        var $ = cheerio.load(res.text);

        var loginDetails = {}
        $('form input').each(function(index, element){
          loginDetails[element.attribs.name] = element.attribs.value
        });
        loginDetails.username = username
        loginDetails.password = password
        loginDetails['timezone-offset'] = '-1'
        loginDetails['timezone-abbr'] = ''
        loginDetails['button-clicked'] = 'login'

        log('Posting login')
        // NEVER COMES BACK ON SUPERAGENT 1.6

        agent
        .post(loginUrl)
        // Superagent uses JSON by default
        .type('form')
        .set('Referer', 'https://www.example.com/account/login.php')
        .send(loginDetails)
        .end(function(err, res){

          if ( err ) {
            return cb(err, null)
          }
          return cb(null, agent)
        })
      })
    }

I've checked and the `csrf-token` is still being sent when using superagent 1.6.0.

Looking through `history.md` I can see these two changes which seem to be relevant:

> retain cookies on redirect when hosts match (Tom Conroy)
> upgrade to latest cookiejar (Andy Burke)

If I install cookiejar 2.0.6 on superagent 1.5.0 it still works though, so the change seems to be in superagent itself. There seems to a be a big refactor between 1.5 and 1.6 though, so diffing the code is hard. 

 - Is there a good way to check out what cookies are set on the agent? 
 - Are you aware of any change in 1.6.0 that would make the login POST not respond?

I can reproduce the working / failing behaviour consistently between 1.5 and 1.6.

**Comment by pornel** [comment]
Is there a cross-domain redirect involved? (see `res.redirects`)

The offending commit is here: 68bc8c2e9615b5d577397f701f18c2ca7ab6f748

**Comment by mikemaccana** [comment]
Please close this. The issue seems to have been timing related! Thanks for your patience & help.
