### ISSUE TITLE
post() doesn't work when using send()

### ISSUE THREAD

**Issue by OmgImAlexis** [visionmedia/superagent#1209]
I'm using supertest with [ava](https://github.com/avajs/ava) for my tests.

The top test works perfectly yet the bottom never finishes instead it just timesout.
If you need me to add more of my test code I can but I thought I'd start off with a small sample incase I was doing something really wrong and hadn't noticed.

```js
await request.post('/user').then(users => console.log(users.body)).catch(err => console.log(err));
await request.post('/user').send({
    username: 'ava',
    password: 'rocks'
}).then(users => console.log(users.body)).catch(err => console.log(err));
```

**Comment by dodekeract** [comment]
Same here. Have you found any workaround/fix @OmgImAlexis?

**Comment by pornel** [comment]
Are you using superagent, or super**test** in your tests?

**Comment by OmgImAlexis** [comment]
Supertest but I get the same result with superagent so I'm assuming it's an underlying issues with superagent that's just showing because of the dependancy.

**Comment by dodekeract** [comment]
My issue was with superagent directly, but I suppose that doesn't matter anymore as it's arguably user-fault.

**Comment by qiangzi7723** [comment]
I have a same problem. I get a bug in my code and check for a long time. At last I found that superagent do not send my post body to the server. I don't know why and don't know how to solve it. I try to change to another library and it seems to be work. It is my code

```
agent.post(url)
    .send('encSecKey=xxx')
    .send('params=xxx')
    .end((err,res)=>{
        console.log(res);
    })
```

In the response, the body and text are all empty and I found that the request body did not send to the server.

**Comment by pornel** [comment]
You can't call `.send()` more than once. Use `.field` or `.send('foo=bar&baz=quz)`.

**Comment by qiangzi7723** [comment]
@pornel I am so sorry to tell you it doesn't work. The response body and text still null.
                    `.send('encSecKey=2af4ca51b906def2e80755a34450db64e8a34f038ffa7ee66ae4c50fbaacc785eddcc1a63222928af3814c355f20b7f8d4e4b05f26879087acd1f8a4da79adaa4a59e3efb54c135017d7f94f7514603e208b0178f547f436c9ca11a3f45e27876c81c3f0a5d3a82854b9d39fdee0ac1b16ecd23503908595fc48359e0811f6d6&params=DQU/eyfHyqpTa40dLoNsxkRxCEmEsIgzAgKEYce7d5o78+o4DrdquhuTE5/h5PWqI027kSWd4Y1c9/h6mQFX8J9KiGI0zhV7hb6F7JzXjmg2wtky3SXDoXDn2IYKQnoF4mSXfjGtJdL9kA0KmJvNow==')`

**Comment by pornel** [comment]
It looks like you're trying to build a form yourself. Are you sure you need this? To do this you'll also need to set the content type.
