### ISSUE TITLE
Is superagent producing a console.log for errors?

### ISSUE THREAD

**Issue by dinkom** [visionmedia/superagent#1210]
I am using superagent 3.5.1, installed via Yarn.

I am making a call to GitHub to create a webhook. If the webhook already exists, I get a 422 and that is fine. However, in that case, I have my own error handling and everything works. But, there is a console.log with the 422 that I'm not producing. It's confusing, seems like there's an error, although it is being handled.

Is this produced internally by superagent? If yes, is there a clean way for me to switch it off (without hacking console.log itself)?

**Comment by pornel** [comment]
Chrome developer tools is logging XHR failures automatically.

**Comment by dinkom** [comment]
Thanks!
#todayilearned
