### ISSUE TITLE
Superagent - React native

### ISSUE THREAD

**Issue by BenBenz** [visionmedia/superagent#1211]
This library is fully compatible with react-native ?

**Comment by pornel** [comment]
We've had some reports that React native packages wrong version of the library (we have two versions: one for the web platform only (web browsers) and one for Node.js only.)

**Comment by ramsestom** [comment]
react-native doesn't package superagent by default. As any other package, you have to install it with `npm -i superagent --save`. (so it would be the node.js version of superagent that would be installed). Now the real question is: is the node.js version of superagent compatible with react-native? And this question remains open as it seems that many people have issue making them work together.... (but maybe these issues have been fixed now)

**Comment by michaelroevievictoria** [comment]
any update with this ?

**Comment by kornelski** [comment]
I'm not using react-native, so I won't be able to answer this. Try it, and report bugs you find to either react-native or here.
