### ISSUE TITLE
post pfx has problem

### ISSUE THREAD

**Issue by runhwguo** [visionmedia/superagent#1213]
when i use superagent post,  .pfx(),  it always goes wrong

Error: error:0906D06C:PEM routines:PEM_read_bio:no start line

my code is here:
  // let response = await superagent
  //   .post(URL_REFUND)
  //   .send(formData)
  //   .pfx(PFX)
  //   .key(MCH_ID)
  //   .charset(config.common.char_set_utf8);

but when i use request library, it is ok!

**Comment by pornel** [comment]
Unfortunately I don't know why this is happening. We're just passing the argument straight to [Node's request](https://nodejs.org/api/https.html):

https://github.com/visionmedia/superagent/blob/8f1a90cbcc9aac066bfe58b4ad38ff2b3092bb46/lib/node/agent.js#L79

so if it works with Node, it should work with Superagent too.
