### ISSUE TITLE
Allow specifying content-type with attach()

### ISSUE THREAD

**Issue by danielfloyd** [visionmedia/superagent#1214]
It would be great if there was a way to specify the content-type of a file when uploading it with `attach()`.

My particular use case is while using `supertest` and wanting to override the inferred content-type of the uploaded file. I don't see any way to do that currently.

**Comment by pornel** [comment]
We use https://github.com/form-data/form-data so its `{contentType:…}` option should work in Node. In the browser you'll need `new Buffer([data], {type:…})`.

**Comment by danielfloyd** [comment]
That did it. Thanks!

That option that was not clear from the docs and I had supertest 2.x which pulled in superagent 2.x and so it wasn't actually an option. I upgraded to supertest 3.x and it worked.

Thanks again for the quick reply!
