### ISSUE TITLE
Node-WPAPI and React Native

### ISSUE THREAD

**Issue by enguerranws** [visionmedia/superagent#1217]
Hi,

I'm stuck on a issue I described on Node-WPAPI repo which is using superagent. 
The issue is here : https://github.com/WP-API/node-wpapi/issues/306

I'm using React Native to send an image using node-wpapi, which is just passing an URI, a File Object or a Buffer to superagent to handle this file upload. 

I tested this on client side, using a File Object, which is working fine. I tried the same thing in a React Native app, and there, it catches this error:

> TypeError: One of the sources for assign has an enumerable key on the prototype chain. Are you trying to assign a prototype property? We don't allow it, as this is an edge case that we do not support. This error is a performance optimization and not spec compliant.

I tried to log some stuff directly inside superagent, in lib/client.js, line 574:

```
Request.prototype.attach = function(field, file, options){
  console.log('file', file); // logs my file object
  console.log('field', field); // logs "file"
  console.log('options', options); // logs undefined
  if (file) {
    if (this._data) {
      throw Error("superagent can't mix .send() and .attach()");
    }

    this._getFormData().append(field, file, options || file.name);
  }
  return this;
};

```

I can't see what I missing there, but any help would be appreciated :)

**Comment by pornel** [comment]
I don't know what React-Native is complaining about. We don't use `Object.assign`. Is it about implementation of FormData.append()?

**Comment by enguerranws** [comment]
To be honest, I don't know :) If I can provide more information to debug this, let me know.

**Comment by pornel** [comment]
Yes, does it happen only when you call .attach()?

Does it happen when you use form-data package without superagent?

**Comment by enguerranws** [comment]
Hi,

I'm not sure what you expect from me here? Switching from superagent to from-data package in node-wpapi?

**Comment by pornel** [comment]
I'm trying to diagnose the problem. I need to know which line of code and when is misbehaving. Is it a problem with FormData or superagent?
