### ISSUE TITLE
Sync request

### ISSUE THREAD

**Issue by LuizSD** [visionmedia/superagent#1218]
Hi,

I need to make a sync request, how can i?

**Comment by pornel** [comment]
The old whole-browser-locking sync request is deprecated and won't be supported ever again.

You should give `async`/`await` syntax a try (you'll need Babel to compile for older browsers). It gives code as clear as sync code, but doesn't have the nasty side effects of the deprecated methods.

**Comment by LuizSD** [comment]
thx i will fix my callback.
