### ISSUE TITLE
Configuation Document Missing

### ISSUE THREAD

**Issue by brendonco** [visionmedia/superagent#1219]
<img width="1159" alt="screen shot 2017-05-04 at 10 28 57 am" src="https://cloud.githubusercontent.com/assets/6521691/25688808/bbc7acb6-30b4-11e7-9e38-67e0e4135c27.png">

[http://visionmedia.github.io/superagent/webpack.github.io/docs/configuration.html#target](url)

**Comment by pornel** [comment]
Fixed, thanks
