### ISSUE TITLE
when response redirects,the query() and send() can not work

### ISSUE THREAD

**Issue by meloseven** [visionmedia/superagent#1223]
when response redirects,the `query()`  and `send()` can not work.Then i found `_redirect` method in `Request`,`_data`  for post and  `qs` for get has been reset.So,how can i send data with request even if response redirect?

**Comment by pornel** [comment]
I don't quite understand your description. Can you post a minimal code sample that shows the problem?

**Comment by meloseven** [comment]
```javascript
 let req = agent.get('http:xxx/xxx');
 req.query(requestData);
 req.set('Cookie',cookie);
 req.end((err,res) => {
       res.setEncoding('utf8');
       response.writeHead(res.statusCode,res.statusMessage,res.headers);
       response.write(res.text);
       response.end();
});
```
when I send a request like this.The request will be redirected three times.The url of last time can not get the query string.Then I found  _data has been set null and qs has been set empty object in [_redirect](https://github.com/visionmedia/superagent/blob/master/lib/node/index.js#L395) .So how can the last url  receive the query params?

**Comment by pornel** [comment]
So you're sending request to `/foo?query=1`, which redirects to `/bar`, but you want `/bar?query=1`?

**Comment by meloseven** [comment]
Yes.

**Comment by pornel** [comment]
I'm afraid this won't work. The server should be adding query when redirecting (so the `/foo` server should be taught to forward the query). 

In HTTP there is no such thing as re-sending of the query string. There is re-sending of POST body in some cases, but it's mostly a legacy bug, so you shouldn't rely on it either.

In superagent you can set `.redirects(0)` and handle redirects yourself.

**Comment by meloseven** [comment]
Thank you.
