### ISSUE TITLE
A problem about superagent

### ISSUE THREAD

**Issue by jameslongyoung** [visionmedia/superagent#1233]
I do the web_parser together with the cheerio and i find a problem about the superagent , when I get the http://poj.org/problem?id=1002 use the superagent.get() method , I find the html of the page is not complete ,can you help me find this error?

**Comment by focusaurus** [comment]
I did `request.get('http://poj.org/problem?id=1002', function(error, res) {console.log(error, res && res.text)});` with the latest version of superagent from node v6.10.3 and I see HTML all the way to the close html tag so it looks complete to me. How are you determining the HTML is not complete?

**Comment by jameslongyoung** [comment]
Thank you for your helping and  maybe my npm and superagent version are not latest . After I update my npm and superagent version, I found the HTML of the page  is complete to me , Thank you very much!
