### ISSUE TITLE
Custom type of errors

### ISSUE THREAD

**Issue by kharandziuk** [visionmedia/superagent#1235]
I think it will be better if superagent throws errors of some custom type instead of Error type.

**Comment by focusaurus** [comment]
Can you elaborate specifically on "better"? Better how? What use cases would it enable?

**Comment by kharandziuk** [comment]
It will give me an ability to separate SuperAgent-level errors from all the other.  
```
    try {
        const a = await request.get('example.com/absent')
    } catch(e) {
        if(e instanceof SuperAgentError) {
            // do some specific handling for 404 or 500 and ? 
        } else {
            throw e // I don't want to handle e.g.:Error: getaddrinfo ENOTFOUND
        }
    }
```

Why is it better? With a typed error you don't need to figure out how to catch the only one specific type of the error.

**Comment by kharandziuk** [comment]
const request = require('superagent')

Promise.resolve(
    request
        .get('here.com/absent')
).catch(function(e) {
    console.log(e)
})
