### ISSUE TITLE
Upload progress inaccurate in various browsers/OS

### ISSUE THREAD

**Issue by mikecousins** [visionmedia/superagent#1236]
I'm seeing some weird behaviour with the progress event in various browsers. This what I'm seeing:

Windows/Chrome - The progress is way too fast. For instance a 160MB file shows 100% complete after about a second, while the actual transfer takes about 41s.
Windows/Firefox - Correct behaviour.
Windows/Edge - The progress event doesn't seem to fire ever???
Windows/IE11 - Fast progress like Windows/Chrome.

Mac/Chrome - Correct behaviour.
Mac/Firefox - Correct behaviour.
Mac/Safari - Very chunky progress.

Any idea what's going on?

**Comment by pornel** [comment]
Superagent doesn't track the upload progress, it only forwards events from the browser.

This is probably bufferbloat: https://en.wikipedia.org/wiki/Bufferbloat

**Comment by mikecousins** [comment]
I tried a plain XMLHttpRequest and tried Axios as well. All of them are identical.  Here is a gif that someone made to demonstrate it from: https://github.com/mzabriskie/axios/issues/593

https://camo.githubusercontent.com/630c4ee364add0232e2d04739d96a84dacd0fd8e/68747470733a2f2f67696679752e636f6d2f696d616765732f6178696f732d70726f67726573732e676966

**Comment by tkoenig89** [comment]
We are experiencing the same issue with XHR Progress. Just came here from google, searching for this issue.

From our observations this seems like an issue with Windows (independent of browser or framework). All browsers we tested so far (Chrome, Firefox, Edge, IE 11) are jumping from 0% to 100% in a few seconds on a Windows host. The final response - upload request completed - takes until the upload is done, and the server responds. Showing 100% for a few minutes...

On Linux Mint we get the progress events representing the real network speed. Tested with Chrome and Firefox on Linux.

A weird fact: The upload continues on windows, even if you close your browser. On Linux the upload stops as soon as the browser is closed.

This led us to conclude, that somehow Windows takes the files from the browser and handles the upload from there on. The browser thinks it has send the complete file, and waits for the response... (But we don't have any evidence for this conclusion at the moment).

**Comment by KerimG** [comment]
Hey @tkoenig89, 

we have encountered the same issue. Have you ever been able to find a fix for this issue?

**Comment by tkoenig89** [comment]
Hi @KerimG ,

actually we did not find a solution for this issue, as I recall. We later switched from a file upload to a download from an update server, as this did fit better with our emebeded system update scenario.

**Comment by KerimG** [comment]
@tkoenig89 

Unfortunate. Thank you very much for the additional information, though. Much appreciated 😃
