### ISSUE TITLE
Custom Header X-Auth-Token not sent with IE11

### ISSUE THREAD

**Issue by voiceofvega** [visionmedia/superagent#1239]
I create POST requests with a custom header field X-Auth-Token as follows:
```
const post = (url) => {
  return request
    .post(url)
    .set('Content-Type', 'application/json')
    .set('Accept', 'application/json')
    .set('X-Auth-Token', _token)
    .timeout(TIMEOUT);
};
```

With Firefox, Edge, Chrome, ... the X-Auth-Token header is included in the request:
```
POST myurl HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0
Accept: application/json
Content-Type: application/json
X-Auth-Token: 
[.....]
```

With IE11, the X-Auth-Token header is not included:
```
POST myurl HTTP/1.1
Content-Type: application/json
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; ASU2JS; rv:11.0) like Gecko
 ---- NO X-Auth-Token here
```

**Comment by pornel** [comment]
Try allowing that header with CORS: 

https://developer.mozilla.org/en/docs/Web/HTTP/Access_control_CORS#Access-Control-Allow-Headers

**Comment by voiceofvega** [comment]
This was not enough. I included Access-Control-Allow-Headers="*" or the value of Access-Control-Request-Headers + ",X-Auth-Token" but it failed:
- With "*", an error is shown in the console: content-type is not included in the response,
- With the other (as shown below), the custom X-Auth-Token is simply not included in the request.

`OPTIONS /myurl HTTP/1.1
Accept: */*
Origin: (myorigin)
Access-Control-Request-Method: POST
Access-Control-Request-Headers: content-type, accept
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; ASU2JS; rv:11.0) like Gecko
Host: (myhost)
Content-Length: 0
Connection: Keep-Alive
Cache-Control: no-cache

HTTP/1.1 200 OK
Date: Fri, 16 Jun 2017 17:14:30 GMT
Server: Apache
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: content-type, accept,X-Auth-Token
Allow: GET, HEAD, POST, PUT, DELETE, TRACE, OPTIONS, PATCH
Content-Length: 0
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive

POST /myurl HTTP/1.1
Content-Type: application/json
Accept: application/json
Referer: (myreferer)
Accept-Language: fr-FR
Origin: (myorigin)
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; ASU2JS; rv:11.0) like Gecko
Host: (myhost)
Content-Length: 48
Connection: Keep-Alive
Cache-Control: no-cache`

**Comment by voiceofvega** [comment]
Responding with a full set of CORS headers, including Access-Control-Allow-Credentials (as described in https://www.webdavsystem.com/ajax/programming/cross_origin_requests) worked better but was not correct for all navigators.
I stopped investigating this point, as I resorted to proxying the back-end requests (avoiding the CORS issue), so I close this issue.
