### ISSUE TITLE
Request headers getting added to files during upload PUT request from browser

### ISSUE THREAD

**Issue by oyeanuj** [visionmedia/superagent#1242]
Hi @pornel! Thank you for this excellent library. So, I was trying to upload files to S3, using PUT (to a pre-signed url) and ran into the following issue. I looked through StackOverflow and previous issues, and couldn't find anything which resolved this, hence this ticket.

The file I was uploading is getting corrupted. On investigation, it seems that is because the following headers are being appended to the file. 

I was unable to figure out - 
1. Why the headers are being added?
2. In the headers being added to the file, the `Content-Disposition` is different than that being set in the Request Header. Why is that?

Here are a couple of screenshots:
**Headers added in the payload**:
<img width="340" alt="screen shot 2017-06-29 at 9 51 25 pm" src="https://user-images.githubusercontent.com/9633371/27722249-3f56dd6c-5d1b-11e7-94f4-c90e4013325f.png">

**Superagent request object**
<img width="996" alt="screen shot 2017-06-29 at 10 29 44 pm" src="https://user-images.githubusercontent.com/9633371/27722267-53dc9970-5d1b-11e7-83f7-8a9e6d2975d4.png">

Following the docs, here is how I am making the request from my browser: 
```js
request.put(s3path)
  .set('Content-Type', 'image/jpeg')
  .set('Content-Disposition', 'inline')
  .attach(fileSlug, filename.jpg)
  .on('progress', updateCallback)
  .end(success, failure)
```

And if you think a doc clarification is needed, I'll be happy to PR!

Thank you!

**Comment by pornel** [comment]
Is that a superagent bug, or browser just doing its thing?

Do you get different headers when using XHR?

**Comment by focusaurus** [comment]
My initial thought is the browser is actually doing a multipart form upload which requires a corresponding `Content-Type`. See [https://msdn.microsoft.com/en-us/library/ms527355(v=exchg.10).aspx]() for more details. Try removing your js/superagent code that overrides the `Content-Type` header. I think that will allow the browser and server to process the content correctly.

**Comment by oyeanuj** [comment]
@pornel @focusaurus Thank you for taking a look! I found the root issue, and the solution (in case anyone else runs into this). 

The content boundary header added seems to be the default browser behavior whenever attaching files, or submitting a multi-part request (so, removing the content-headers above didn't matter).

It seems that typically webservers know how to strip that out when dealing with that upload, but not S3. S3 (and other object stores) requires the files to be uploaded as the main body/data. So, instead of the above method, the following works -

```js
request.put(s3path)
  .set('Content-Type', 'image/jpeg')
  .set('Content-Disposition', 'inline')
  .send(theFile)     // <--------------------------- THIS LINE instead of .attach()
  .on('progress', updateCallback)
  .end(success, failure)
```

At this point, the browser sends this as the main body of the request, rather than assuming it to be `multipart/form-data` request (which seems to be the default behavior).

Let me know if you guys think this sort of case needs to be mentioned in the main superagent homepage somewhere as an example!

**Comment by bcepuran** [comment]
thank you @oyeanuj ! using .send is what I was missing.

**Comment by marcocali** [comment]
Thanks @oyeanuj, 
I encountered the same issue using S3,  pre-signed urls and superagent with PUT. 
Your solutions works!
