### ISSUE TITLE
Change format of callback params in docs and README

### ISSUE THREAD

**Issue by kingscott** [visionmedia/superagent#1243]
In the README and docs, the callback params are as follows:

```javascript
...
.end(function(err, res) {
  ...
})
```

I'm on `3.5.2` and the structure is as follows:

```javascript
...
.end(function(res, err) {
 ... 
})
```

(with `res` before `err`). 

I can provide a PR for all changes, but I want to get confirmation from a contributor that this is how they are actually formatted. 

Thanks!

**Comment by focusaurus** [comment]
Ah no this looks very suspect to me and you are most likely confused. They are node style error first callbacks. What specifically makes you think differently?

**Comment by kingscott** [comment]
I was using this pattern:

```javascript
import request from 'superagent';

const foobar = () => {
   return request
      .get(`${URL}`)
      .set({ Accept: 'application/json' })
      .then((res, err) => {
         if (err || !res.ok) {
           return err;
         }
         return res.body.payload;
      });
};
```

That gives me the proper payload back. When I switched the params, I would get the entire request response back (from the `return err`).

**Comment by pornel** [comment]
The promse `.then(res => {})` callback has only one argument. It never has any error. For errors there's a second callback in `.then()` or `.catch(err => {})` callback.

**Comment by kingscott** [comment]
That'll do it. 

Thanks.
