### ISSUE TITLE
Feature request: Customize error from .ok() callback

### ISSUE THREAD

**Issue by jeremyruppel** [visionmedia/superagent#1247]
I have an API that responds to various failures with a HTTP 200 (long story), but responds with a field to key off of in the response body to determine the nature of the failure, something like:

``` json
{
  "stat": "fail",
  "code": 99,
  "message": "Something went wrong"
}
```

With superagent's `.ok()` callback, I can easily teach superagent what a failure response looks like:

``` js
.ok(res => res.ok && res.body.stat !== 'fail')
```

However, the error I get back from superagent in this case looks like `[Error: OK]` which is pretty confusing. I would like to be able to customize the error message returned to the caller, as well as maybe add additional helpful information such as the API's custom error code, etc.

I would totally be willing to provide a patch for this, but I first wanted to open this up to discussion on what the best implementation might be. Some ideas:

- Allow me to override the error message by setting `res.statusText` (or something) in the `.ok()` callback as soon as I decide to return falsy. [The client code would already allow this][1], but [the nodejs code does not][2]. node has [http.IncomingMessage#statusMessage][3] but then I have to set both properties in my `.ok()` callback (not quite ideal). Furthermore, this approach doesn't allow me to append any other properties to my error (like the above code, for example).
- Allow me to throw inside my `.ok()` callback, and if the surrounding code catches it use that error for `new_err` instead of creating one. This is a bit more of a significant change but it ultimately gives me complete control over the error if I want it.
- Provide a hook like `.ok()` that would allow me to customize how to create the error. I'm not sure this feature warrants a formal API, and given that the node and client implementations would have to be different anyways I'm not even sure this approach would work.

Thoughts?

[1]: https://github.com/visionmedia/superagent/blob/master/lib/client.js#L422
[2]: https://github.com/visionmedia/superagent/blob/master/lib/node/index.js#L682-L686
[3]: https://nodejs.org/api/http.html#http_message_statusmessage

**Comment by pornel** [comment]
You can do it already:

```js
.ok(() => {if (!res.ok) throw CustomError(); else {return true;}});
```

**Comment by jeremyruppel** [comment]
That snippet actually results in an uncaught error; what I want is to be able to catch the error and handle it just like any other non-ok response. Here's an example using the Flickr API:

``` js
var request = require('superagent');

request('GET', 'https://api.flickr.com/services/rest')
.query('method=flickr.test.echo')
.query('nojsoncallback=1')
.query('format=json')
.ok(function (res) {
  if (res.body.stat === 'fail') {
    throw new Error(res.body.message);
  }
  return true;
}).then(function (res) {
  console.log('never gets called');
}).catch(function (err) {
  console.log('i would expect this to be called with my error');
});
```

**Comment by pornel** [comment]
Oh, that's a bug. We should be catching this and passing it on.
