### ISSUE TITLE
Error: Cannot find module 'methods'

### ISSUE THREAD

**Issue by edencorbin** [visionmedia/superagent#1258]
I have in my package.json
```
    "superagent": "^3.5.2",
```
If I npm install (from fresh deleted node_modules folder) and execute code with superagent I get the following error:
```
Error: Cannot find module 'methods'
```
If I run a remove superagent, npm install fresh, then manually install superagent (npm install superagent) it then works fine. This seems more like a npm module management issue then superagent, but I'm wondering if there are any known issues, I would prefer this package install easily as we will be deploying many instances of it.

**Comment by pornel** [comment]
I haven't seen this particular problem. I have seen modules randomly missing with npm 5 before 5.3.0. Make sure you have the latest npm, or try yarn.

**Comment by edencorbin** [comment]
Good point, I want to say it did work on a different os/install without the extra install steps. I'll test a few more scenarios and post back when I figure out what is causing this.
