### ISSUE TITLE
Persist agent for the future use

### ISSUE THREAD

**Issue by quytang** [visionmedia/superagent#1261]
I want to persist `request.agent()` instance and re-initialized it for the future request.
I wonder if there are any ways to do that?

Thanks

**Comment by pornel** [comment]
Yes, you can keep `request.agent()`. You can store it in a global variable, or in an object that persists in your application — it depends on how you designed your program.

Keep in mind that you still need to create a new request object for every request (i.e. call `.get()`/`.post()` and set options each time). The requests are strictly one-time-use-only.

**Comment by quytang** [comment]
thanks @pornel
