### ISSUE TITLE
Load image from GFS

### ISSUE THREAD

**Issue by arn-the-long-beard** [visionmedia/superagent#1262]
Hello guys

I use superagent and I do like it. But despite the fact I spend the last days on the documentation, I am facing a problem that I do not succeed to resolve

I make a request to load an image inside react-dropzone
Here is my request inside a react component 

```javascript 

  loadImage(){
request.get('https://localhost:3000/' + 'api' +'/banner'+ this.props.path )
    .set({'Authorization': 'Bearer ' + Auth.getToken()})
      .then((res, err) => {
        if (err) {
          console.log(err)
        }
        console.log(res.status)
        if (res) {
          //  this.state.universities=

          console.log(res)

          var buf2 = new Buffer( res.text).toString('base64');
          console.log(buf2)
         var img = new Image();
          img.src = "data:image/png;base64," +  buf2 ;
          img.class='content';
          this.state.file=img
        }
  })}
```

I do a post when I drop a file and I succeed, but I do not understand how to get the image from my API. I did spend a lot of time taking my hairs out of my head.

Here is my rest API

```javascript

router.get('/banner/admin/university/:id', (req, res) => {
//TODO improve it
console.log('--------------get the banner --------------')

  University.findById(req.params.id, function (err, uni) {

    var readstream = gfs.createReadStream({_id: uni.banner});

    readstream.on("error", function(err){
      console.log(err)
      res.send("No image found with that title");
    });
    readstream.pipe(res);
  })



})
```

Is there something I am missing ?

I get the data inside the **res.text,** but it is not readable. How can I put it as a file ? If you consider this not as an issue but **as a newbie question,** where can I get the right help about it ?

Best regards,

Arn

**Comment by pornel** [comment]
The server is probably sending the response as text. It is essential that the server is configured to send the correct `Content-Type` header. Without this superagent doesn't know that you've wanted to load an image.

**Comment by arn-the-long-beard** [comment]
Hei.

Okay. I added  res.set('content-type','image/png') into the server side

´´´javascript

router.get('/banner/admin/university/:id', (req, res) => {
//TODO improve it
console.log('--------------get the banner --------------')

  University.findById(req.params.id, function (err, uni) {

    var readstream = gfs.createReadStream({_id: uni.banner});

    readstream.on("error", function(err){
      console.log(err)
      res.send("No image found with that title");
    });

    res.set('content-type', 'image/png')
    readstream.pipe(res);
  })



})
´´´

But I still get the data into the res.text. How should I write superagent request to get the image ?

Best regards,

Arn

**Comment by pornel** [comment]
Make sure it actually worked. Verify with `curl -I <url>`. 

You'll get `Buffer` or `Blob` in `res.body` if this content-type is set.

**Comment by arn-the-long-beard** [comment]
Hey :)

I read your answer after I succeed :

First : I use server side


´´´javascript
     readstream.on('close', function () {
                 const fbuf = Buffer.concat(bufs);
                 const base64 = fbuf.toString('base64');
                 console.log(base64);
                 return res.status(200).json({
                   message: 'You have got the image',
                   image: base64,
                   file: file
                 })
               //  ss(socket).emit('file-uploaded',     base64,file);
               });
´´´

Client side
´´´javascript
fixBinary (bin) {
    var length = bin.length;
    var buf = new ArrayBuffer(length);
    var arr = new Uint8Array(buf);
    for (var i = 0; i < length; i++) {
      arr[i] = bin.charCodeAt(i);
    }
    return buf;
  }
  loadImage(){
    //TODO make a single component for loading single image
    var file = null;
  request.get('https://localhost:3000/' + 'api' +'/banner'+ this.props.path )
    .set({'Authorization': 'Bearer ' + Auth.getToken()})
      .then((res, err) => {
        if (err) {
          console.log(err)
        }
        console.log(res.status)
        if (res) {
          var binary = this.fixBinary(atob(res.body.image));
          var blob = new Blob([binary], {type: res.body.file.contentType});
          var url = URL.createObjectURL(blob);
           file = res.body.file
          file.preview = url
          //  this.state.universities=
    console.log(res)
        //  this.state.file=res.body.file

          this.setState({
       file : res.body.file
          })
        }
  })
  }
´´´
It is working but think I can improve it a lot, can I ?

**Comment by pornel** [comment]
Eww, you should never need base64 here.

Please show me response headers from your server. I'm 99% sure that you just didn't set the content-type header properly (perhaps different endpoint needs it, perhaps it's proxied through something that breaks it).

In case your server can't be fixed, then use this:

```js
            .buffer(true)
            .parse(superagent.parse.image)
```

to force every response, even text or JSON, to be interpreted as an image.

**Comment by arn-the-long-beard** [comment]
ok

here is the response 
´´´json
headers
:
Object
content-length
:
"97541"
content-type
:
"application/json; charset=utf-8"
etag
:
"W/"17d05-99eV0mWYPfFRgmChfU8NAKdct0o""
status
:
"200"
x-powered-by
:
"Express"
´´´

**Comment by pornel** [comment]
Well, there you go: your server says it's sending JSON ("application/json; charset=utf-8"), not an image. If you fix that, then reading of images will work without a workaround.

**Comment by arn-the-long-beard** [comment]
Okay, I will try to fix this. I will keep you updated.

**Comment by arn-the-long-beard** [comment]
Hei.

Okay I tried this : 
```javascript
    .buffer(true)
        .set({'Content-type': this.props.university.banner.contentType})
        .parse(request.parse.image)
```
inside the superagent request.

I also tried in express 
  res.set({'Content-type': uni.banner.contentType})

**Comment by arn-the-long-beard** [comment]
Okay :
I did this .
```javascript
request.get('https://localhost:3000/public' + this.props.location.pathname+'/banner')
        .buffer(true)
        .set({'Content-Type': this.props.university.banner.contentType})
        .parse(request.parse.image)
        .then((res, err) => {
          if (err) {
            console.log(err)
          }
          console.log(res.status)
```


Here is the request result :
```json
eq
:
Request
header
:
Object
Content-Type
:
"image/jpeg"
__proto__
:
Object
method
:
"GET"
url
:
"https://localhost:3000/public/university/598ab55a694d261852bf6bab/banner"
xhr
:
XMLHttpRequest
```

Here is the Response header(s)
```javascript
header
:
Object
content-type
:
null
status
:
"200"
x-powered-by
:
"Express"
__proto__
:
Object
headers
:
Object
content-type
:
null
status
:
"200"
x-powered-by
:
"Express"
```

Here is the server side express code :  
```javascript
 var readstream = gfs.createReadStream({'_id': uni.banner})

    readstream.on('error', function (err) {
      console.log(err)
      res.send('No image found with that title')
    })
    readstream.pipe(res)
  })
```

I think you are right and something is breaking the headers. I am using 
const http2 = require('spdy') to run the server but I dont think it comes from this.

Best regards
Arn

**Comment by arn-the-long-beard** [comment]
Hello.

I added this on the server side 
```javascript
  const fbuf = Buffer.concat(bufs)
          res.setHeader("Content-Type", file.contentType);
          res.setHeader('Content-Length', file.chunkSize);
          res.setHeader('Content-Disposition', 'attachment; filename='+file.filename+'');
          res.write(fbuf,  'binary');
          res.end();

```
The headers is now 

```json
Object
content-disposition
:
"attachment; filename=moldeuniversity.jpg"
content-length
:
"261120"
content-type
:
"image/jpeg"
status
:
"200"
x-powered-by
:
"Express"
```
SO, how should I write the code with superagent to get the image as a file ?

**Comment by arn-the-long-beard** [comment]
Okay I solved everything. ( I wanted to do more complicated than necessary ... )

here is the explanation
Serverside :
```javascript
University.findById(req.params.id, function (err, uni) {
    if (err) {
      return res.status(409).json({
        success: false,
        message: 'error on getting the university'
      })
    }
    gfs.findOne({ _id: uni.banner}, function (err, file) {
      console.log(file)
      if (err) {
      }
      if (file) {
        const readstream = gfs.createReadStream({
          _id: uni.banner
        })

        const bufs = []
        readstream.on('data', function (chunk) {
          bufs.push(chunk)
        })
        readstream.on('error', function (err) {
          console.log(err)
          res.send('No image found with that title')
        })



        readstream.on('close', function () {
          /*
          const fbuf = Buffer.concat(bufs)
          const base64 = fbuf.toString('base64')
*/
          const fbuf = Buffer.concat(bufs)

          var img = new Buffer(fbuf, 'base64');

          res.writeHead(200, {
            'Content-Type': 'image/png',
            'Content-Length': img.length
          });
          res.end(img);

        })
        
      }
    })
```
Client side

```
```javascript
     file.url = 'https://localhost:3000/public' + this.props.location.pathname+'/banner'
```
I didnt need to use superagent to request the image. Just an Url. I do not know why I didnt think about this before.

Thank for helping me a lot with the header thing !

**Comment by focusaurus** [comment]
You should be able to simplify the server code even further with:

```js
res.type('image/png');
readstream.pipe(res);
```

You don't need `bufs` and the associated code. `.pipe()` will do that for
you.

**Comment by arn-the-long-beard** [comment]
Haa thank you.

it is working !! :+1:
