### ISSUE TITLE
Its more of a question , I want the request object as soon as a connection is opened with the server

### ISSUE THREAD

**Issue by deeparora29** [visionmedia/superagent#1264]
Its more of a question , I want the request object as soon as a connection is opened with the server. I am not sure which .on(' <event>' ) should I call??

**Comment by pornel** [comment]
`.on('response',…)` will let you peek the response before body arrives.

**Comment by deeparora29** [comment]
Thanks I am using this in conjunction with redux saga now. This can be closed
