### ISSUE TITLE
Using superagent with Artoo.js 

### ISSUE THREAD

**Issue by jasan-s** [visionmedia/superagent#1265]
I 'm using superagent along with[ artoo.js ](https://github.com/medialab/artoo)to scrape a site. however the site has images that load as you scroll down. Initially there are placeholder image urls.  Due to that all the scraped image urls are of the placeholder image not the actual images.  Would adding a delay to callback in reponse allow me to the grab the correct image urls.

**Comment by pornel** [comment]
Sorry, I can't help with this. This doesn't seem like problem caused by superagent.
