### ISSUE TITLE
Send multiple requests via superagent and perform an event when everyone completes

### ISSUE THREAD

**Issue by deeparora29** [visionmedia/superagent#1266]
I want to send multiple requests via superagent and perform an event when everyone completes. I am asking something similar to axios.all([Promise]).then(.....)

Is there something like this available in superagent?

**Comment by pornel** [comment]
Yes, superagent is a "thenable", so:

```js
const [foo, bar] = await Promise.all([
  superagent.get('foo'),
  superagent.get('bar'),
]);
```

will wait for both `foo` and `bar` requests to finish.
