### ISSUE TITLE
cannot send empty string value in multipart request

### ISSUE THREAD

**Issue by LoicUV** [visionmedia/superagent#1270]
`req.field('fieldName', '')` throws... I get that you wouldn't be able to send `undefined`, but any other falsy value should be supported. Use case is : patching with a file and input values that can be empty (to be reset for eg) or `null`.

EDIT : It was supported in an earlier version. I stumbled upon this after upgrading.

**Comment by pornel** [comment]
This was changed in #1066, because `FormData` doesn't allow empty values: #1065

I see this can be annoying, and we've had a few reports about this already. Perhaps we should redesign how we build FormData (i.e. not use it directly, but create a filtered version when you call `.end()`)

**Comment by LoicUV** [comment]
`FormData` does allow empty values, you mean that the dependency `form-data` doesn't, right ?

**Comment by kamilsmuga** [comment]
+1 more report - yes it is annoying :)

**Comment by niftylettuce** [comment]
PR welcome
