### ISSUE TITLE
add third parameter to .field method 

### ISSUE THREAD

**Issue by FoghostCn** [visionmedia/superagent#1271]
when I use .field method I can't set contentType to it, so is it possible to add a third parameter to .field method

**Comment by pornel** [comment]
We already support this: https://visionmedia.github.io/superagent/#attaching-files

**Comment by FoghostCn** [comment]
no no，I mean `.field` method, not `.attach` method

**Comment by pornel** [comment]
I see.  

For now, make it a `Buffer` or `Blob` and attach.

So far we haven't been paying attention to encoding of non-file fields. It probably be changed to default to `text/plain;charset=utf-8`.

I'm not sure if we should be adding options to `.field()`, as it would make it almost the same as `.attach()`.

**Comment by FoghostCn** [comment]
> For now, make it a Buffer or Blob and attach.

Yeah ,this is what I use now.
OK, thank you for your time
