### ISSUE TITLE
Problem with Request.prototype._isHost in client.js

### ISSUE THREAD

**Issue by lamyat2005** [visionmedia/superagent#1274]
Hi,
We observed that for some devices (e.g my LG G3 native browser), Object.prototype.toString.call(data) maybe return [object Array Iterator] instead of [object Object], making the data sent by xhr.send being invalid. We temporary solved the issue by changing client.js

`Request.prototype._isHost = function _isHost(obj) {
  // Native objects stringify to [object File], [object Blob], [object FormData], etc.
  return obj && 'object' === typeof obj && !Array.isArray(obj) && Object.prototype.toString.call(obj) !== '[object Object]'  && Object.prototype.toString.call(obj) !== '[object Array Iterator]';
}
`
Could you please have a look into this issue? Many thanks in advance.

**Comment by lamyat2005** [comment]
For your information, the data I have passed in is 

{access_token: null, action: "date:get_date", api_key: “key”, args: undefined}

However some devices toString it as [object Array Iterator] instead of [object Object]. Thanks.

**Comment by pornel** [comment]
It's not a bug. That's ES6 iterator. It looks like you're passing iterable instead of actual object. Use `Array.from(iter)` on it before passing it to superagent.

**Comment by lamyat2005** [comment]
Thanks!
