### ISSUE TITLE
This is not supported in browser version of superagent

### ISSUE THREAD

**Issue by walkertong** [visionmedia/superagent#1276]
I got this error when i use React Native with superagent to access https api, the code like is:

```
      Request
        .post('xxxx')
	.ca(HXYConst.CABuf)
        .send({ username:opt.username, password:opt.password})
        .set('Accept', 'application/json')
        .end(function(err, res){...}
```

any suggestion?

**Comment by pornel** [comment]
Like the message says, you're using web-browser-only version of superagent and you're trying to use `.ca()` feature which can only work in node.js environment.

Remove `.ca()` or run it in Node.js.

**Comment by niftylettuce** [comment]
v5.0.0 was released and should fix this issue
