### ISSUE TITLE
Calling .then() after .pipe() causes "write after end error"

### ISSUE THREAD

**Issue by jedwards1211** [visionmedia/superagent#1277]
I get that `.then()` is designed to send the request when not using `.pipe()`.

But how about making it so that after `.pipe()` is called, `.then()` just waits for the request to finish instead of trying to write again?

**Comment by pornel** [comment]
You can't use both. These are mutually exclusive features and can't work together.

**Comment by jedwards1211** [comment]
@pornel is there some technical reason that code like the following would be impossible?

```js
constructor() {
  this.once('pipe', () => this.isPiping = true)
}
then(resolve, reject) {
  if (this.isPiping) {
    this.once('response', resolve)
    this.once('error', reject)
    return
  }
  this.end(resolve, reject)
}
```

**Comment by jedwards1211** [comment]
@pornel it is indeed possible, I have made a PR complete with tests.

**Comment by jedwards1211** [comment]
@pornel in fact, if you ask me, it would be better if we could also call `.end` after `.pipe()` and it would merely register the callbacks instead of complaining that it was ended twice.  I don't see why the API for getting a response or error should be so different in the `.pipe()` case.

**Comment by pornel** [comment]
Ah, sorry, I assumed you've meant pipe for downloading the request.

 So this may work, although I have concerns:

- can there be race conditions? Is it guaranteed that pipe event is called immediately and sychronously? It'd be a nasty bug if piping started after call to `.then()`.

- people often try `req.get(url).pipe(output).end()` expecting this to work. I'm worried about creating confusion where `pipe() + end()` works in one way, but not the other. And I'm worried that supporting piping and buffering at the same time will be hard (it's already hairy with gzip and async parsers).

**Comment by jedwards1211** [comment]
@pornel 
> Is it guaranteed that pipe event is called immediately and sychronously?
I haven't found official documentation but it seems to?
```js
var PassThrough = require('stream').PassThrough

var a = new PassThrough()
var b = new PassThrough()
b.on('pipe', () => console.log('pipe'))

console.log('before')
a.pipe(b)
console.log('after')
```
```
$ node temp.js
before
pipe
after
```

I don't know much about how the buffering works.

**Comment by pornel** [comment]
I mean pipe client->server is OK, but pipe server->client is hard.

**Comment by jedwards1211** [comment]
@pornel I'm a bit confused what you mean, are you saying if we can await a request that has been piped to, you want to support awaiting a response we've piped to something as well?

**Comment by pornel** [comment]
Yes. There are two kinds of pipes in superagent, and supporting end/then with only one of them creates inconsistency. Currently superagent doesn't support combination of any pipe with end/then, which may not be very useful, but at least it's a simple rule and is consistent.

**Comment by jedwards1211** [comment]
@pornel I have noticed intermittent failures with waiting a request that I piped data into now...maybe the `pipe` event isn't synchronous.

**Comment by pornel** [comment]
The potential for race condition is worrying, so I'm going to close this.
