### ISSUE TITLE
More control over query string

### ISSUE THREAD

**Issue by dokipen** [visionmedia/superagent#128]
I'm using nodejs. I can't figure out how I can make a querystring like this:

    a=1&a=2&a=3

Even if I set the querystring manually in the request path, Request.prototype.end parses and edits it to make it like so:

    a[]=1&a[]=2&a[]=3

The docs mention that query() takes a string argument, but that causes an error since it's directly passed to qs.stringify(). Perhaps pluggable query string serialization, or even just not munging it when it's generated beforehand.

**Comment by cithukyaw** [comment]
I'm encountering the same problem. Is there any fix for this since 2012 when the issue was started?

**Comment by cithukyaw** [comment]
[Unirest](http://unirest.io/nodejs.html) works perfectly for this purpose:

        var unirest = require("unirest");
	unirest.get(/)
	.query({a: 1})
	.query({b: 2})
        .query({c: 3})
	.end(function(res) {
		console.log(res.body);
	});

**Comment by englercj** [comment]
It is also pretty strange that the browser version works differently than the node version currently:

node:

```js
qs.stringify({ a: ['b', 'c', 'd'] }, { indices: false })
// => 'a=b&a=c&a=d'
```

browser:

```js
serialize({ a: ['b', 'c', 'd'] });
// => 'a=b%2Cc%2Cd' which decodes as 'a=b,c,d'
```

I would expect them to work/act the same way. Can you not use qs with browserify in the browser version?

**Comment by defunctzombie** [comment]
Yea. I too find it strange that the behavior is different. One downside to using qs in the browser is that it increases the size of the lib (pretty substantially). Maybe I can use just the serialization part without the other parts.

**Comment by defunctzombie** [comment]
Will create a new issue to just use `qs` on client as well for consistency.

**Comment by bobgroves** [comment]
If a string is passed as a query, there is absolutely no legitimate reason why it should be parsed and serialized. It looks like something that was put in to make the code simpler(arguably). If the user passes in a string for a query, it should be used as is.

**Comment by defunctzombie** [comment]
Makes sense to me.

**Comment by dokipen** [comment]
Thanks! Can we get a release with this fix in it?

**Comment by cheryly279** [comment]
I see the commit above states that "Strings passed to request.query() will be used in the final querystring
unaltered," but is there a way to pass an option like we would in jQuery with {traditional : true}? So for instance we could pass something like:

request.query({a : [1,2]}, {traditional : true})

result in a url like ...?a=1&a=2...
