### ISSUE TITLE
set post data encoding 

### ISSUE THREAD

**Issue by CyrusLiu158** [visionmedia/superagent#1281]
I want to encode the posted data. but no effect. code:
 
request.post(url).set('Content-Type','application/json;charset=gbk').send({text: "some text"})

**Comment by pornel** [comment]
Unfortunately we only support UTF-8 for all text and JSON. You can't change it with any declaration.

The only way is to create a Buffer or Blob with appropriately encoded bytes, but superagent doesn't have any functionality to help with this.

You probably should switch the server to UTF-8 or use another library.
