### ISSUE TITLE
Large gzip Denial of Service

### ISSUE THREAD

**Issue by hckhanh** [visionmedia/superagent#1283]
There are some security issue with your module.
When I use NSP to check the securities issues, I receive this: https://nodesecurity.io/advisories/479

**Comment by walshie4** [comment]
possibly a dupe of https://github.com/visionmedia/superagent/issues/1259

**Comment by letsgolesco** [comment]
This is related to https://github.com/visionmedia/superagent/issues/1259

**Comment by pornel** [comment]
Fixed in v3.7.0
