### ISSUE TITLE
NSP Advisory on mime (dependency) < 2.0.3

### ISSUE THREAD

**Issue by timramsier** [visionmedia/superagent#1284]
I just want to bring to attention that NSP has reported a security advisory for any version of mime that is less than version 2.0.3.  Currently, 1.4.1 is a dependency for this package.  For anyone that is using NSP as part of their security scan process this will break your pipeline.

Here is the advisory:

https://nodesecurity.io/advisories/535

**Comment by pornel** [comment]
Fixed

**Comment by wooliet** [comment]
https://github.com/broofa/node-mime/releases

They might have a fix for the 1.x version. The 2.x version will break in node 0.12.

**Comment by pornel** [comment]
We've dropped support for Node 0.12 last year when it was EOL-ed and stopped getting any security updates. If you're still using Node 0.12 your first priority should be to upgrade to Node 6 ASAP.

See #1286
