### ISSUE TITLE
'Require' missing file extension 

### ISSUE THREAD

**Issue by dammo001** [visionmedia/superagent#1285]
After update, getting error `Cannot find module './types/standard' from 'index.js'` from superagent. The file is named `standard.json`. Adding the correct extension to the require seems to fix this issue.

**Comment by dammo001** [comment]
`superagent/node_modules/mime/index.js`

**Comment by evalphobia** [comment]
I got the same error when using jest and `supertest@3.0.0`.

```bash
    Cannot find module './types/standard' from 'index.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:191:17)
      at Object.<anonymous> (node_modules/superagent/node_modules/mime/index.js:4:27)
```

I removed that file and it worked.

```bash
$ rm node_modules/superagent/node_modules/mime/index.js
```

**Comment by jota** [comment]
I also use jest and could solve it by simply adding "json" as a possible extension in the jest config. For example:

```
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "json"
    ],
```

"json" is in that list by default so it should only be an issue if you overwrite that config parameter and are missing "json".
