### ISSUE TITLE
Mime dependency upgrade breaks ES5 support

### ISSUE THREAD

**Issue by com4** [visionmedia/superagent#1286]
Upgrading the mime dependency from version 1 to version 2 in superagent v3.6.1 breaks backward compatibility with ES5.

```
const Mime = require('./Mime');
^^^^^
SyntaxError: Use of const in strict mode.
```

I'd recommend upgrading the mime package to 1.4.1 instead of 2.0.3 to maintain backward compatibility for the minor version upgrade.

**Comment by pornel** [comment]
The browser version of mime doesn't seem to be affected. Our tests pass in IE, and we don't use any ES6 transpiler.

Superagent 3.x doesn't support Node 0.x. All ES5 versions of Node are officially dead since the end of 2016.

**Comment by silentroach** [comment]
mime upgraded in major, but you don't. why? it is a breaking change

**Comment by pornel** [comment]
It didn't change interface of superagent, and didn't change node versions we support, so I don't think it's a breaking change.

We don't support Node 0.x, so it absolutely doesn't matter what happens to it.

**Comment by silentroach** [comment]
You are wrong, your package works on node 0.10, but with upgrade to new mime it doesn't and *it is* a breaking change when *your package* is not compatible with old node any more.

**Comment by pornel** [comment]
Superagent 2.x works on Node 0.10.

Superagent 3.x was never meant to work on Node 0.10. We've intentionally bumped semver-major for this exact reason, and it's clearly documented. And yes, any Node module that uses Superagent 3.x requires Node 4 or later. 

It's entirely your problem that your big project failed to migrate away from dead version of Node, given years of advanced notice that this will happen.

**Comment by silentroach** [comment]
Didn't knew about 2->3 switch and its reason, my fault. Ok, thank you.

**Comment by com4** [comment]
> Superagent 2.x works on Node 0.10.
> Superagent 3.x was never meant to work on Node 0.10. 

@pornel For what it's worth I'm actually having trouble with the swagger-tools project. I'm just using swagger to document an API. I'm not a node developer so forgive any ignorance.

In the swagger-tools package.json it lists superagent as a dependency with ^2.0.0[1]. The NPM docs say that using a ^ prefix indicates "Compatible with version"[2]. 

Is it possible for you to mark superagent v3 as not compatible with v2 so other packages don't upgrade to this incompatible version? This should help maintain stability for other packages which haven't done the leg work to upgrade while still give you the freedom to make backward-incompatible changes.

1. https://github.com/apigee-127/swagger-tools/blob/master/package.json#L82
2. https://docs.npmjs.com/files/package.json#dependencies

**Comment by pornel** [comment]
^2.0.0 is not compatible with 3.x (it means 2.0.0 to 2.999…).

**Comment by com4** [comment]
Do you happen know why it would be pulling 3.0 versions?

**Comment by pornel** [comment]
`npm ls` will tell you why

**Comment by com4** [comment]
looks like it was a few dependencies deep (https://github.com/whitlockjc/path-loader/blob/master/package.json#L62) 

Thanks for your help.
