### ISSUE TITLE
Superagent Browser Version and pdf download

### ISSUE THREAD

**Issue by hellofantastic** [visionmedia/superagent#1287]
Hello there 

I have a reactjs app making a call to a Sailsjs api to run phantomjs and screen capture to a pdf
which works but I am having trouble getting that back to the browser as a download

Reactjs:
```javascript
printInfographicAPI = ()=>{
    request
      .get('api/frontEnd/generatePDF')
      .then((res) => { console.log('result',res); });
    }
```

and in the API i have  in callback from making the pdf
```javascript
       let stats = fs.statSync(tmpobj.name);

        res.writeHead(200, {
          'Content-Type': 'application/pdf',
          'Content-Disposition': 'filename="' + 'infographic' + '.pdf"',
          'Content-Length': stats["size"]
        });			
        
     
        let readStream = fs.createReadStream(tmpobj.name);
        readStream.pipe(res);	

```

When I fire the reactjs print function, from a button on page, the response res has a body:null but text what looks like the binary data for the pdf:

![screen shot 2017-09-29 at 2 14 20 pm](https://user-images.githubusercontent.com/6655746/31036347-9ee0532e-a520-11e7-935b-90793ab69edd.png)

I am hoping  I can get some insight on howto get the rest of the way to turning that into a pdf that downloads.  

Much appreciated

**Comment by pornel** [comment]
I guess we don't recognize that mime type by default. Try:

```js
const superagent = require('superagent');
superagent.parse['application/pdf'] = superagent.parse['application/octet-stream'];
```

**Comment by hellofantastic** [comment]
Before seeing this I figured out this , 
is it the same essentially? 
then pass it to a function to convert the blob and force it to the browser

```javascript
const self = this;
    this.setState({isLoading: true}, function() {   
        request
        .get('api/frontEnd/generatePDF')
        .on('request', function () {
            this.xhr.responseType = 'blob';
        })
        .then(function(res) {
            fileDownload(res.xhr.response, 'infographic.pdf');
            self.setState({isLoading: false});
        });
    });
```

**Comment by pornel** [comment]
Yes, it's a shortcut for responseType.
