### ISSUE TITLE
mime dependency update incompatible with use in node 4

### ISSUE THREAD

**Issue by pabigot** [visionmedia/superagent#1290]
Although `package.json` specifies superagent should work with node >= 4.0, commit 96f3df844d6db1eb3d updated the mime dependency from ^1.3.6 to ^2.0.3.  [mime 2.0 requires node 6.x or higher](https://www.npmjs.com/package/mime), resulting in warnings when installing in a system that still uses node 4:

    lilith[34]$ npm install superagent
    npm WARN engine mime@2.0.3: wanted: {"node":">=6.0.0"} (current: {"node":"4.5.0","npm":"2.15.9"})
    superagent@3.6.2 node_modules/superagent
    ├── cookiejar@2.1.1
    ├── component-emitter@1.2.1
    ├── methods@1.1.2
    ├── extend@3.0.1
    ├── formidable@1.1.1
    ├── mime@2.0.3
    ├── qs@6.5.1
    ├── debug@3.1.0 (ms@2.0.0)
    ├── readable-stream@2.3.3 (inherits@2.0.3, string_decoder@1.0.3, process-nextick-args@1.0.7, util-deprecate@1.0.2, core-util-is@1.0.2, safe-buffer@5.1.1, isarray@1.0.0)
    └── form-data@2.3.1 (asynckit@0.4.0, combined-stream@1.0.5, mime-types@2.1.17)

**Comment by pornel** [comment]
Fixed in 3.6.3
