### ISSUE TITLE
Superagent "pops" valid header from response.

### ISSUE THREAD

**Issue by nsf** [visionmedia/superagent#1295]
E.g. this code for me (chrome 61.0.3163.91)
```js
      const header = resp.xhr.getAllResponseHeaders();
      console.log(JSON.stringify(header));
      console.log(resp.header);
```
Prints this:
```
"content-type:\ttext/plain; charset=utf-8\nrange:\tbytes=0-524288"
{content-type: "text/plain; charset=utf-8"}
```

And this line of code suggests there should be a trailing `\r\n`:

https://github.com/visionmedia/superagent/blob/092e3d6d289f90af2551540a5fbcdf771ca9b7fe/lib/client.js#L223

Well, there is none as you can see in the snippets above. It just pops the actual header line...

**Comment by pornel** [comment]
Thanks. Can you help by making a pull request that only pops the line if it's empty?
