### ISSUE TITLE
should not retry on 500, 501

### ISSUE THREAD

**Issue by peebles** [visionmedia/superagent#1303]
The doc says "if they fail in a way that is transient or could be due to a flaky Internet connection".  A response of 500 or 501 is not transient or flaky ... the server is returning that response.  >= 502 should retry.

**Comment by pornel** [comment]
Since retries are opt-in, I'm going to leave configuring details of them up to #1178. 

Retrying of 501 does not make much sense, but 500 does IMO: you may have flaky app severs behind a load-balancer and hit a working app server on the next request.
