### ISSUE TITLE
abnormal when using with async in parallel

### ISSUE THREAD

**Issue by bi-kai** [visionmedia/superagent#1304]
I want to write a demo spider, quering pages with superagent and async, the code is below:
```javascript
var url = require("url"),
    superagent = require("superagent"),
    cheerio = require("cheerio"),
    async = require("async"),
    eventproxy = require('eventproxy');

var ep = new eventproxy();

var catchFirstUrl = 'http://www.cnblogs.com/', //入口页面
    deleteRepeat = {}, //去重哈希数组
    urlsArray = [], //存放爬取网址
    catchDate = [], //存放爬取数据
    pageUrls = [], //存放收集文章页面网站
    pageNum = 50, //要爬取文章的页数
    startDate = new Date(), //开始时间
    endDate = false; //结束时间

for (var i = 1; i <= pageNum; i++) {
    pageUrls.push('http://www.cnblogs.com/?CategoryId=808&CategoryType=%22SiteHome%22&\
ItemListActionName=%22PostList%22&PageIndex=' + i + '&ParentCategoryId=0');
}

// 轮询 所有文章列表页
// pageUrls.forEach(function(pageUrl) {});
var j = 0;
async.mapLimit(pageUrls, 3, getArticleList, function(err, results) {
    // results is now an array of stats for each file
    console.log("content: " + results.length + " " + urlsArray.length);
});

function getArticleList(pageUrl, cb) {

    superagent.get(pageUrl)
        .end(function(err, pres) {
            // 常规的错误处理
            if (err) {
                console.log(err);
                cb(err);
            }
            var $ = cheerio.load(pres.text);
            var curPageUrls = $('.titlelnk');
            for (var i = 0; i < curPageUrls.length; i++) {
                var articleUrl = curPageUrls.eq(i).attr('href');
                urlsArray.push(articleUrl);
                // 相当于一个计数器
                //ep.emit('BlogArticleHtml', articleUrl);
            }
            console.log((j++) + ' fetch ' + pageUrl + ' successful');
            setTimeout(function() {
                cb(null, "");
            }, 500);
        });

}
```
the code is offten blocked:
![2017-10-27_23-25-04](https://user-images.githubusercontent.com/15070379/32111975-ae18e3a0-bb01-11e7-80c3-fb93f95b27d8.png)
what is wrong with my code?

**Comment by bi-kai** [comment]
here is the testing result:
1 in parallel, setTimeout <1s, blocked.
1 in parallel, setTimeout 1.5s+, run finished(the results are not verified).
3 in parallel, setTimeout <3s , blocked.
1 in parallel, setTimeout 4s+, run finished(the results are not verified).

I donot really understand why this happened. Why they cannot run fluently in parallel?

**Comment by pornel** [comment]
If your code is getting mysteriously stuck, it may be because it fails to call a callback somewhere. I recommend using `Promise`-based async handling instead (ideally with `async`/`await` syntax), which eliminates these types of problems.

**Comment by bi-kai** [comment]
@pornel Hi, thanks for your reply. Isn't `async` module `Promise-based` inside or it's just a syntax sugar of callback? 

I'm not sure the difference between `async module` and `async` in `async/await`. I regard them as the same thing -_-!!! I want to use `async` for reliable result all the time. 

Is promise module like `bluebird` will be helpful? I'm not quite familiar with `async/await`.

**Comment by pornel** [comment]
If your code has `function(err, result)` and `if (err)` then it's callback-based, not promise-based. Library called "async" (`require('async')`) is an old callback-based one. It's the old world in Node, and it has manual error handling and continuation.

The new stuff is `async function()` and `await request()` which is `Promise`-based.

Bluebird and other libraries are from the era of Node 0.x, which didn't have promises built in. These days you don't need any library for promises, they are built into the language like `String`, `Array`, and `Object`.

**Comment by bi-kai** [comment]
@pornel Thx!
