### ISSUE TITLE
Documentation link is broken

### ISSUE THREAD

**Issue by pmbanugo** [visionmedia/superagent#1307]
I can't access the docs on http://visionmedia.github.io/superagent/

**Comment by pornel** [comment]
I can't reproduce it. Works for me. Try HTTPS link  https://visionmedia.github.io/superagent/

**Comment by pmbanugo** [comment]
I still get the same thing. Says the server is not responding both for http and https.

**Comment by pornel** [comment]
http://downforeveryoneorjustme.com/visionmedia.github.io
