### ISSUE TITLE
Superagent not storing cookies when 'Domain' is specified?

### ISSUE THREAD

**Issue by chrisveness** [visionmedia/superagent#1310]
It seems that superagent doesn't store a cookie when the `Domain` is specified?

I don't know how to separate this out from Koa for a standalone example, but this is a fairly minimal example using Koa:

    const Koa    = require('koa');
    const Router = require('koa-router');

    const app    = new Koa();
    const router = new Router();

    router.get('/set-implicit-domain', (ctx, next) => {
        const cookie = Date.now();
        console.log(ctx.url, cookie);
        ctx.cookies.set('test', cookie);
        ctx.set('X-Cookie-Val', cookie);
        ctx.body = cookie;
        ctx.status = 200;
    });

    router.get('/get-implicit-domain', (ctx, next) => {
        const cookie = ctx.cookies.get('test');
        console.log(ctx.url, cookie);
        ctx.body = cookie;
        ctx.status = 200;
    });

    router.get('/set-explicit-domain', (ctx, next) => {
        const cookie = Date.now();
        console.log(ctx.url, cookie);
        ctx.cookies.set('test', cookie, { domain: 'local.host' })
        ctx.set('X-Cookie-Val', cookie);
        ctx.body = cookie;
        ctx.status = 200;
    });

    router.get('/get-explicit-domain', (ctx, next) => {
        const cookie = ctx.cookies.get('test', { domain: 'local.host' });
        console.log(ctx.url, cookie);
        ctx.body = cookie;
        ctx.status = 200;
    });

    app.use(router.routes());

    app.listen(3000);

    module.exports = app;

This works fine in the browser (e.g. Chrome 61.0.3163.100). I am using `http://www.local.host` to avoid issues with localhost and/or number of dots in the domain. However it fails in a test script (`/get-explicit-domain` returns `undefined` for the cookie); my test is:

    const supertest = require('supertest');   // HTTP assertions made easy via superagent
    const expect    = require('chai').expect; // BDD / TDD assertion library

    const app = require('./app.js');

    const request = supertest.agent(app.listen());

    const headers = { Host: 'www.local.host:3000' }; // avoid using localhost (requires entry in /etc/hosts!)

    describe('cookie test', function() {
        let implicitCookie = null;
        let explicitCookie = null;

        it('sets cookie using implicit domain', async function() {
            const response = await request.get('/set-implicit-domain').set(headers);
            expect(response.status).to.equal(200);
            implicitCookie = response.headers['x-cookie-val'];
        });
        
        it('sees cookie using implicit domain', async function() {
            const response = await request.get('/get-implicit-domain').set(headers);
            expect(response.status).to.equal(200);
            expect(response.text).to.equal(implicitCookie);
        });

        it('sets cookie using explicit domain', async function() {
            const response = await request.get('/set-explicit-domain').set(headers);
            expect(response.status).to.equal(200);
            explicitCookie = response.headers['x-cookie-val'];
        });
        
        it('sees cookie using explicit domain', async function() {
            const response = await request.get('/get-explicit-domain').set(headers);
            expect(response.status).to.equal(200);
            expect(response.text).to.equal(explicitCookie);
        });
        
    });

...which fails on the fourth test.

Is this an issue with superagent, or am I doing something wrong?

If it helps, my package.json is:

    {
      "name": "superagent-cookie-domain-test",
      "version": "0.0.0",
      "main": "app.js",
      "scripts": {
        "start": "node app.js",
        "test": "mocha --exit test.js"
      },
      "dependencies": {
        "chai": "^4.1.2",
        "koa": "^2.4.1",
        "koa-router": "^7.2.1",
        "mocha": "^4.0.1",
        "supertest": "^3.0.0"
      }
    }

Thanks!

**Comment by pornel** [comment]
Can you reproduce it without supertest?

**Comment by chrisveness** [comment]
I've only used superagent through mocha/supertest, I'm afraid I'm not sure how to reproduce on its own – I'll see if I can work it out.

**Comment by chrisveness** [comment]
I don't know how to reproduce without supertest, but I think I've located the issue.

When superagent checks cookiejar's `CookieAccessInfo()` (`lib/node/agent.js:65`), for the 'domain to match', it passes `url.hostname` – apparently ignoring the `.set({ Host: 'www.local.host:3000' })` passed to `request.get()`.

This results in `CookieAccessInfo()` matching '127.0.0.1' against 'local.host' (and failing), instead of matching ''www.local.host' against 'local.host'.

**Comment by chrisveness** [comment]
Actually, I may be wrong, I can't really follow what's happening. For the 1st, 2nd, and 4th tests, `Cookie.collidesWith()` (`cookiejar.js:133`) gets invoked with a `CookieAccessInfo` as an argument, but on the 3rd test, it gets invoked with a `Cookie` as an argument. All a bit beyond me, sorry!

**Comment by chrisveness** [comment]
I've had a look through the code further – though I can't say I can follow it particularly well!

Where `Agent.prototype._attachCookies()` invokes `CookieAccessInfo()` (`lib/node/agent.js:65`), if I replace `url.hostname` with the (hardwired) *Host* header I specify with `request.get().set()`, then the host is matched successfully. 

However, at this point `req.url` is `http://127.0.0.1:<random-port>/<path>`, and it occurs before the `.set()` has been processed, which means the *Host* header specified in the `.set()` is not available.

I can't see any way around this, but I can't imagine I am the first to have encountered this issue. Is there something I am doing wrong?

**Comment by pornel** [comment]
That's a tough one. It looks like cookies have to be based on the URL and can't use the Host header.

To support the Host header cookie setting would have to be moved to the .end() callback, but then you wouldn't be able to read cookies from the request object and overriding agent's cookies would need special handling.

**Comment by pornel** [comment]
Related one is #938 for TLS/SNI hostname.

So maybe it'd require an alternative solution:

```js
supeagent.get('http://cookie-hostname').ip('127.0.0.1')
```

to override target IP explicitly this way.

**Comment by chrisveness** [comment]
Thanks for the reply.

I'd be happy with any workable solution, but I'm struggling to get to grips with superagent's innards.

I've been trying to pursue a superagent-only repro, and don't see why this node test passes:

    const setup = require("../support/setup");
    const base = 'http://www.local.host:5000';

    const request = require("../../");

    describe("request", () => {
      it("should retain cookies", done => {
        request
          .get(`${base}/header`)
          .set("Host", "www.local.host:5000")
          .set("Cookie", "foo=bar; Domain=local.host")
          .end((err, res) => {
            try {
              res.body.should.have.property("cookie", "foo=bar; Domain=local.host");
              done();
            } catch (err) {
              done(err);
            }
          });
      });
    });

`Agent.prototype._attachCookies()` doesn't even get invoked.

If you have any solution that would get my initial post to pass, I'd be super glad! Let me know if there's anything I could do to help.

**Comment by pornel** [comment]
That test passes, because it's a response. Client-side cookie handling only affects requests.

**Comment by chrisveness** [comment]
Of course, sorry – being slow!

To investigate further, I put together a test on the lines of SuperAgent's own 'node' tests (using Express) – which worked fine.

So looking into it, I think the culprit here is actually SuperTest: specifically, [supertest/lib/test.js:62](https://github.com/visionmedia/supertest/blob/199506d8dbfe0bb1434fc07c38cdcd1ab4c7c926/lib/test.js#L62) hardwires the 127.0.0.1 IP address.

I'll raise this over on the SuperTest side – sorry to have troubled you!

**Comment by chrisveness** [comment]
SuperTest [PR #297](https://github.com/visionmedia/supertest/pull/297) would fix this for me, but is SuperTest still active, or has it been abandoned?

**Comment by kswope** [comment]
Old issue but for anybody who find themselves here

using a plugin to prefix the URL will wipe out the cookie

The following 'plugin' kills cookie persistence
```
agent.use((req) => {
  req.url = `http://localhost:3000/${req.url}/`;
  return req;
});
```

In comparison, this does not
```
agent.use((req) => {
  return req;
});
```

I'd bet setting the domain, even if its the exact same, is enough to confuse the library.  This might

**Comment by ashersaupingomez** [comment]
@kswope Silly that the first plugin kills cookie persistence, but the 2nd one... You're not modifying the request at all. Is that a typo?

**Comment by kswope** [comment]
@ashersaupingomez I barely remember this but its obvious to me that I'm establishing that simply using the plugin mechanism doesn't break anything.  If you want you can ignore it.

**Comment by ashersaupingomez** [comment]
@kswope I'm just emphasising that it's strange that simply prefixing the request URL via a plugin, unfortunately, kills cookie persistence. I was also pointing out that the 2nd snippet you shared doesn't actually implement plugin behaviour, as the request object itself as an argument, must be modified.
