### ISSUE TITLE
How to add a query to every request

### ISSUE THREAD

**Issue by aharbis** [visionmedia/superagent#1313]
Say I have a basic request like this:

```js
var request = supertest(app)

request.post('/api/Note')
.query({
  token: token_val
})
.send(body)
.expect(200)
.end()
```

I'm struggling to find a good way to automatically apply the above `.query()` chain on all outgoing requests. I looked into using the `superagent-use` plugin, but I'm not quite sure if this would be the way to go, or how I would write `.query()` such that it could be used as a plugin.

Basically I'd like to set this somewhere once:

```js
agent.use(query({token: token_val}))
```

and let that query be chained on all requests. Is this possible? I've done a bit of searching around but have not found a solution. Thanks in advance for the help!

**Comment by pornel** [comment]
It's now possible with superagent (note that supertest is a separate codebase, so I'm not sure if has it yet):

```js
const myAgent = require('superagent').agent().use(req => req.query(etc));

myAgent.post(url).end(cb); // posts with the query
```
