### ISSUE TITLE
Any way to get 4xx response body w/o try...catch while using await?

### ISSUE THREAD

**Issue by liesislukas** [visionmedia/superagent#1316]
```
async function checkToken(token) {
  const result = await superagent
    .post(`${config.serviceUrl}/check_token`)
    .send({token});
  return result.body;
}
```
Default options if this call will return 401 throws an Exception, which is not what i expect. API i call is using HTTP status messages also as body to give information back and i just need the body part.

Response with http status 401 is 

```
{
    "data": null,
    "error": {
        "code": "INVALID_TOKEN",
        "message": "Token is not valid"
    }
}
```

And currently, to get this, I need to wrap all superagent calls with try...catch

```
async function checkToken(token) {
  let result = null;
  try {
    result = await superagent
      .post(`${config.serviceUrl}/check_token`)
      .send({token});
  } catch (e) {
    result = e.response;
  }
  return result.body;
}
```

Any way to have the 1st sample working and returning JSON w/o looking at HTTP status?

**Comment by pornel** [comment]
There's `.ok()` callback which lets you decide which responses are considered sucessful.

**Comment by Alexsey** [comment]
In case if anyone else would found this issue:

In [Jest](https://jestjs.io) you can
```javascript
const response = superAgent.get(url)
await expect(response).rejects.toMatchObject({
  status: 400,
  response: {
    text: '[expected error message]'
  }
})
```
Code for [Chai](https://www.chaijs.com/) or [Should.js](https://shouldjs.github.io/) would be very similar
