### ISSUE TITLE
[ Question ] Can add 'req.user' on the request

### ISSUE THREAD

**Issue by workfel** [visionmedia/superagent#1322]
Hi,

I came here because i want to know if is possible to add any attributes on request express object like this ` req.user = myObj `.

I need to do that, because i have a middleware who check the role identity of user connected. I know there is a way to make auth with superagent, but i want only check the role property on user object.
```js
req.user = { username : "...", roles : [ "role1", role2" ..] , ... } 
```

I want to make a thing like this.
```js
   it(`/POST insert users `, () => {
        return request(server)
            .post(`/users`)
            .auth(accessToken, { type: 'bearer' })
            .set({user : { roles: ["role1"] })
            .send({
                name: 'Toto',
                age: 2,
            })
            .expect(201);
    });

```

It's possible or not ?

Thx

**Comment by workfel** [comment]
Okey, thank you ! 
i will follow your guide and use `.auth`

**Comment by benjaminhera** [comment]
Any updates on this? I want to achieve the same thing, but had no luck finding anything related to modifying the request object directly... I don't want to set the headers nor the cookies, I want to access the request object before sending the request. (I'm actually trying to e2e test, but I can't mock my parameter decorator, so this would be very cool if I could do that).
