### ISSUE TITLE
Console always logging error

### ISSUE THREAD

**Issue by alaorneto** [visionmedia/superagent#1323]
It seems like everytime an error occur in a request, the error is logged in the console, even if I catch it somehow. How can I prevent this behavior?

```
const superagent = superagentPromise(_superagent, global.Promise);

const API_ROOT = 'http://localhost:3001/api';

//const encode = encodeURIComponent;

const handleErrors = err => {
  if (err && err.response && err.response.status === 401) {
    authStore.logout();
  }
  return err;
};

const responseBody = res => res.body;

const tokenPlugin = req => {
  if (commonStore.token) {
    req.set('Authorization', `${commonStore.token}`);
  }
};

const jsonPlugin = req => {
  req.set('Content-Type', 'application/json');
}

const requests = {
  post: (url, body) =>
    superagent
      .post(`${API_ROOT}${url}`, body)
      .use(jsonPlugin)
      .use(tokenPlugin)
      .end(handleErrors)
      .then(responseBody),
};
```
The code above, if I use the post function to try to log an user with the wrong credentials, will always print "POST http://localhost:3001/api/auth/ldap 401 (Unauthorized)" in the console, even if I catch the error.

**Comment by pornel** [comment]
The `superagentPromise` thing looks very suspicious. It's probably incompatible with superagent since version 2.x, which has promise support built-in.

**Comment by alaorneto** [comment]
I removed the superagentPromise but it still logs errors to the console. The line 772 of client.js is given as the source of the logged error:

`xhr.send(typeof data !== 'undefined' ? data : null);`

**Comment by alaorneto** [comment]
Well, I guess it's related to this question on stackoverflow:
https://stackoverflow.com/questions/14337351/can-i-prevent-the-chrome-developer-tools-console-from-logging-image-404-errors
Seems to be a issue with Chrome. Nevermind. I thank you for your attention.
