### ISSUE TITLE
Design flaw when using Promises + pipe

### ISSUE THREAD

**Issue by celicoo** [visionmedia/superagent#1327]
I'm using the superagent (awesome package BWT 👍) in a library that I'm developing to extract data from files and load it in a excel file. How the API works:

```javascript
00 const stream = fs.createWriteStream('result.xls')
01 garimpo.extract(paths, parsingRules)
02    .then(response => {
03      const { data, errors } = response.body
04      const request = garimpo.transformAndLoad(data, 'xls')
05      request.pipe(stream)
06      return request
07  })
08 .catch(console.error)
```

The problem happens in line 05 and 06, I need pipe the request of `garimpo.transformAndLoad` to a writable stream, but I still need to return the request, because if the method fails, the catch will capture the error, but if I leave like that, the superagent will complain it:

```
Warning: superagent request was sent twice, because both .end() and .then() were called. Never call .end() if you use promises
Warning: .end() was called twice. This is not supported in superagent
```

Resuming: If I use the `.pipe` method, my `.catch` won't catch any errors if my request fails because I'm not allowed to return the request.

Thank you in advance.

**Comment by pornel** [comment]
This is indeed a problem with "thenable" objects. The workaround is to return them wrapped in an object:

```js
return {request};
```

which will prevent promises/async from automatically calling `.then` on the returned value.

**Comment by celicoo** [comment]
Oh, thank you very much pornel! <3

I think it would be a good idea to add this to the docs.
