### ISSUE TITLE
Extension providing a declarative, uncurried API for Superagent

### ISSUE THREAD

**Issue by damoclark** [visionmedia/superagent#1332]
Hey @kornelski 

Not an issue, but just letting you know I have published a companion module for superagent called superagent-declare.  It provides a declarative, uncurried API for Superagent.  e.g.

```javascript
const superagent = require('superagent') ;
const request = require('superagent-declare') ;
request.use(superagent) ;
request({
	post: '/upload',
	field: [
		['user[name]', 'Tobi'],
		['user[email]', 'tobi@learnboost.com'],
		['friends[]', ['loki', 'jane'] ],
	],
	attach: ['image', 'path/to/tobi.png'],
	then: callback
}) ;
```

It is published on [npm](https://www.npmjs.com/package/superagent-declare) and [github](https://github.com/damoclark/superagent-declare).  

Raising this issue, just in case you wanted to make reference to it in Superagent's documentation.

Cheers,
Damien.

**Comment by kornelski** [comment]
Thanks. If you'd like, make a PR to add it to the list of plugins in the readme.

**Comment by damoclark** [comment]
No worries.  Happy to do that.

D.

**Comment by niftylettuce** [comment]
added to docs
