### ISSUE TITLE
[Doc Website Bug] Text overflowing the container

### ISSUE THREAD

**Issue by itaditya** [visionmedia/superagent#1336]
![image](https://user-images.githubusercontent.com/15871340/35371319-69986ba2-01b9-11e8-8505-2e3b314f4c57.png)

Hi I'm sorry if this is the wrong place to open the issue, but I couldn't find the doc hosting repo. As the screenshot shows, in http://visionmedia.github.io/superagent/#agents-for-global-state section *The complete list of methods*  part is overflowing,

**Comment by kornelski** [comment]
Fixed

**Comment by itaditya** [comment]
Nice
