### ISSUE TITLE
setting header in res when piping

### ISSUE THREAD

**Issue by lqzerogg** [visionmedia/superagent#1341]
how can I set response header when I use piping?  something like this
```
const req = request.get('/some.json');
req.pipe(res);
// I need a event handler to set res header
req.on('response', (_res) => { res.setHeaders(_res.headers) })
```

**Comment by kornelski** [comment]
I don't understand why do you set *response* headers. These headers are set by the server, and are supposed to be read-only for superagent. 

The event handler is not supposed to allow setting response headers either. You're just abusing Node API.

**Comment by louisbuchbinder** [comment]
I believe the OP is asking about proxying a request with superagent and setting the proxy response headers. Maybe something like:

```javascript

app.get('/', (req, res) => {
  const proxy = request.get('./some.json');

  proxy.on('error', err => {
    proxy.abort();
    res.end();
    ...
  });
  proxy.on('response', resp => {
    res.set(resp.headers);
    ...
  });

  proxy.pipe(res);
});



```

**Comment by Galienna** [comment]
Is this something possible now ? 
It's exactly my use case. I have a public fastify server called by a client to get some files. Within my fastify server, I use superagent to call a private server where the files are stored. I'm trying to stream superagent response to fastify "reply" object, and I need to edit some of the response headers sent by my storage server.
