### ISSUE TITLE
Help evaluating script tags in response text

### ISSUE THREAD

**Issue by NathanCH** [visionmedia/superagent#1343]
Hey guys,

I'm coming from jQuery.ajax(). When the 'dataType' is set to 'html', jQuery evaluates any script tags in the response text so they can be executed on document ready.

From jQuery.ajax() documentation on 'dataType'

> "html": Returns HTML as plain text; included script tags are evaluated when inserted in the DOM.

I've been trying to get this to work with superagent, but my script tags don't evaluate. Is this possible, or should it be done manually? I've dug deep into the source of jQuery and they don't call eval(), but some other magic occurs I'm assuming.

Request:
```
Request
.post('/cool/path')
.type('form')
.set('accept', 'text/html')
.send({ 'additionalFormData': true })
.then((res) => {
  document.getElementById('containerToPopulate').innerHTML = res.text;
})
.catch((e) => {
  console.log(e);
});
```

Post to view "/cool/path"
```
<!-- Html -->
<script>console.log('Hey');</script>
```

**Comment by NathanCH** [comment]
Here is the solution I came up with, but I can already see a number of issues with it such as the scripts appending multiple times.

```
.then((res) => {

  // Populate container with response.
  const body = document.getElementById('containerToPopulate');
  body.innerHTML = res.text;

  // Extract and evaluate scripts.
  const scripts = body.getElementsByTagName('script');
  for (let i = 0; i < scripts.length; i++) {
    const scriptText = scripts[i].text;
    const scriptTag = document.createElement('script');
    scriptTag.text = scriptText;
    const head = document.getElementsByTagName('head')[0];
    head.appendChild(scriptTag);
  }
})
```

All I'm doing here is looping through the response text (after it has been mounted to the DOM), and recreating the scripts to apply to the header. From what I can see, this is how jQuery does it too, but probably much better.

**Comment by kornelski** [comment]
If you already have jQuery, then you can use `jQuery.html()` (if I recall correctly) to take advantage of its script magic.

**Comment by NathanCH** [comment]
Hey thanks for your response, unfortunately we didn't want to use jQuery in this project. But you're 100% correct. 

Upon further looking, jQuery does pretty much exactly what I'm doing here.

**Comment by NathanCH** [comment]
Whoops didn't mean to close the issue! But yes you are 100% right, sticking with jQuery would solve this problem. It sounds like you're saying the jQuery.html() method may be responsible for the script magic. 

That's a good point, I'll take a look. And if that's the case, this issue should be closed as it's not the responsibility of superagent to mount.
