### ISSUE TITLE
Always throw an error when the request is aborted

### ISSUE THREAD

**Issue by kornelski** [visionmedia/superagent#1344]
Currently on `.abort()` we emit an `abort` event, cancel the request, and any further callbacks are not guaranteed. Error event/callback might happen if the underlying implementation throws an error, but it may not. 

This is annoying, since it adds another failure case to handle beyond the usual `.end()` callback, and it's especially awful when it creates a never-resolving stuck `Promise`.

We should simplify things by treating abort the same as all request failures, so it should emit an `error` event, call end callback and reject promises.

#1342

**Comment by christian-dinh** [comment]
Perhaps this is the wrong place to ask this question (if so I apologize), but I'm working on an application in which we keep a count of in-flight superagent requests. When a request is created we increment the counter, and when a request resolves or rejects we decrement the counter in the promise then/catch. It is possible for a request to be aborted, in which case we have an `abort` event listener that decrements the counter.

As mentioned in https://github.com/visionmedia/superagent/pull/1342, the in-flight promise will still sometimes resolve and we'll end up decrementing the counter an extra time. It seems what you're proposing here would solve our problem (we could drop the `abort` listener and rely on the promise rejection instead), but in the meantime is there a workaround for this issue in the current implementation of superagent?

**Comment by kornelski** [comment]
In the current version:

```js
const req = request.get(…);
return new Promise((resolve, reject) => {
  req.on('abort', reject);
  req.then(resolve, reject);
});
```

Promises always resolve only once.

**Comment by christian-dinh** [comment]
Clever, thank you!

**Comment by kornelski** [comment]
Done in v4
