### ISSUE TITLE
[IE11] Javascript-breaking error in 3.8.0

### ISSUE THREAD

**Issue by RiccardoMargiotta** [visionmedia/superagent#1345]
Hi,
We're importing Superagent into a React component, and serving it through a Webpack compiled bundle.

After upgrading to 3.8.0, we see an error in IE11 in the production build, which stops all other Javascript functioning on the page. This doesn't happen with the development build, so potentially an issue with the code being uglified?

Error in IE11 dev tools:

![image](https://user-images.githubusercontent.com/7202952/36031653-650e6a00-0da3-11e8-8f2d-4dfce485b8d2.png)

Since the error directs me to production minified code, it's quite hard to diagnose. Here's a snippet from around where the tools send me, specifically the error is pointing me to the end of the word 'arguments' in `push({fn:e,arguments})`:

```js
{function n(){this._defaults=[]}["use","on","once","set","query","type","accept","auth","withCredentials","sortQuery","retry","ok","redirects","timeout","buffer","serialize","parse","ca","key","pfx","cert"].forEach(function(e){n.prototype[e]=function(){return this._defaults.push({fn:e,arguments}),this}})
```

The error doesn't occur after rolling back to 3.7.0.

**Comment by kornelski** [comment]
Yup, that's ES6 sneaking in.

**Comment by kornelski** [comment]
Our code is

```js
this._defaults.push({fn:fn, arguments:arguments});
```

so probably your minfier is not IE-compatible.

**Comment by RiccardoMargiotta** [comment]
Thanks for the update. I'll see if there's anything weird going on in our Webpack setup. 👍

**Comment by RiccardoMargiotta** [comment]
For future reference, it looks like Webpacker changed the default Uglifier settings to target `ecma: 8`, which led to the issue I was seeing. https://github.com/rails/webpacker/issues/1235
