### ISSUE TITLE
Response body is an empty object when response has Content-Type: text/plain; charset=utf-8

### ISSUE THREAD

**Issue by jedwards1211** [visionmedia/superagent#1350]
I want to detect if superagent parsed the response in a verbose error plugin I'm writing, so I was hoping that `response.body` would not be present (or at least not be an object) for any `text/plain; charset=utf-8` response.  Is this a bug?

**Comment by kornelski** [comment]
It's a quirk. We have `response.body = {}` as the default value.

**Comment by jedwards1211** [comment]
okay.  is there any way to determine if superagent parsed the response without building a big list of content types?

**Comment by kornelski** [comment]
I'm not sure. It's different between Node and browser version as well -- that's a bit of tech debt that we have.
