### ISSUE TITLE
DNS defunct for localtunnel at .focusaurus.com

### ISSUE THREAD

**Issue by kornelski** [visionmedia/superagent#1352]
The saucelabs builds are failing.

@focusaurus can you check your localtunnel/DNS?

**Comment by focusaurus** [comment]
I'm investigating. I switched DNS from namecheap to digitalocean but things should have kept working.

**Comment by focusaurus** [comment]
I think it's working now. I think the issue was I didn't have a wildcard DNS A record for `*.focusaurus.com` configured, but while troubleshooting I also updated to the latest `defunctzombie/localtunnel-server:latest` docker image as well. Can you confirm?

**Comment by kornelski** [comment]
Works. Thanks.
