### ISSUE TITLE
How do I get the contents of a response (image file) piped into a stream?

### ISSUE THREAD

**Issue by biot023** [visionmedia/superagent#1353]
Hi -- I'm returning image data in a request being made by superagent (with supertest).
I'm getting timeout errors and all sorts of issues -- I'm obviously missing some fairly key information on how to access streamed information from a request!
Could someone advise me on how to pipe the data from a request into a stream, wait for it to finish, and then access that data?
My current best effort (sadly) is this:

    test('returns the adjusted image', (done) => {
      request(app).get(`/${ imgId }/640x`).then(res => {
        const img = sharp();
        res.pipe(img);
        img.metadata().then(metadata => {
          expect(metadata.width).toEqual(640);
          done();
        });
      });
    });

The error I'm getting with this is:

> Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.

Any and all help would be *greatly* appreciated, thank you!
   Doug.

**Comment by kornelski** [comment]
Piping and promises are mutually exclusive. .then() waits for all piping to be permanently finished.

You either only pipe or only use then/end callbacks, never both.

**Comment by biot023** [comment]
Ah, that makes sense, I'll give something along those lines a try...
...
... and that did it. Thank you so much, @kornelski !

**Comment by justinmchase** [comment]
Where is the documentation on how to pipe with superagent?
