### ISSUE TITLE
Unset default application/json content-type header

### ISSUE THREAD

**Issue by Exomnius** [visionmedia/superagent#1362]
I'm using superagent to perform various request to custom API's for my project. I also want to use it to call the geocode API from google maps. This API only accepts requests without the content-type header due to CORS.

Is it possible to remove (unset) the default application/json type/header? (request-base.js - line 593)

**Comment by kornelski** [comment]
That's a good use case. We have `unset()`, which currently only unsets headers you've `set()` yourself, but it would make sense to keep note which headers have been unset and avoid setting default ones.

**Comment by kornelski** [comment]
Could you try implementing it? I think it could go like this:

- in `unset` save all header names that have been unset, something like `this._unsetHeaders[name] = true (keep in mind case-insensitivity, so lowercase names)
- in places where we set our own headers (lots in `end()` and friends) check for `_unsetHeaders` headers and don't set defauts if the name is set
- write a test for it.
- I'm not sure what should happen for `.unset(foo).set(foo)` combo. maybe it doesn't need special handling?

**Comment by Exomnius** [comment]
Will do!

**Comment by niftylettuce** [comment]
v5.3.0 published to npm and GitHub releases page with changelog
