### ISSUE TITLE
how to create a package that depends on superagent, and let it work both in browser and node? 

### ISSUE THREAD

**Issue by videni** [visionmedia/superagent#1365]
hi,  I have a package that depends on superagent , I wanna my package can be used both in browser and node enviroment, how can I do this ?  just like [wpcom-xhr-request](https://github.com/Automattic/wpcom-xhr-request) , I also post a question in stackoverflow,   [/how-to-build-npm-package-for-node-and-web](https://stackoverflow.com/questions/49718934/how-to-build-npm-package-for-node-and-web/49719814#49719814)

**Comment by kornelski** [comment]
If you use browserify or webpack, it just works. You don't have to do anything.

**Comment by videni** [comment]
@kornelski, it supposed to work , I have configured web and node for webpack , but none of them work, I don't know why , so I stop writing my own configurations , I use n8-make and the makefile from ` wpcom-xhr-request ,`, it works.

**Comment by niftylettuce** [comment]
similar issue but I'm using common-shakeify and it's erroring #1418
