### ISSUE TITLE
Error In Documentation Example

### ISSUE THREAD

**Issue by dustinws** [visionmedia/superagent#1366]
I noticed this error yesterday when looking through the documentation. The error is in the timeout example - notice how the `err` variable used in the `.then` block is never defined. Perhaps the `.timeout` property is on the response, or perhaps a `.catch` is required instead.

[A link to the documentation](https://visionmedia.github.io/superagent/#timeouts)

And a screenshot for quick reference.
<img width="480" alt="screen shot 2018-04-13 at 9 09 22 am" src="https://user-images.githubusercontent.com/10288625/38736571-73d3fc7a-3efa-11e8-8114-0bf713fdc1d9.png">

**Comment by kornelski** [comment]
Thanks
