### ISSUE TITLE
HPE_UNEXPECTED_CONTENT_LENGTH Error

### ISSUE THREAD

**Issue by GTKSKY2014** [visionmedia/superagent#1373]
Response is using transfer-encoding chunked, but includes a content-length header, the worst part is that I cannot modify any server configuration. 
request:
```
detailQueryRsp = await agent.get(url.queryDetailInfo)
                                          .responseType('text/html')
                                          .set('Content-Type', 'application/x-www-form-urlencoded')
```
response header:
Content-Encoding: gzip
Content-Length: 24530
Content-Type: text/html; charset=utf-8
Date: Mon, 14 May 2018 03:32:19 GMT
Transfer-Encoding: chunked

exception:
nodejs.HPE_UNEXPECTED_CONTENT_LENGTHError: Parse Error
    at TLSSocket.socketOnData (_http_client.js:439:20)
    at TLSSocket.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at TLSSocket.Readable.push (_stream_readable.js:213:10)
    at TLSWrap.onread (net.js:599:20)
bytesParsed: 189
code: 'HPE_UNEXPECTED_CONTENT_LENGTH'
response: undefined
name: 'HPE_UNEXPECTED_CONTENT_LENGTHError'

help me  guys

**Comment by vasergen** [comment]
+1
