### ISSUE TITLE
.attach file removes Content of File during Post

### ISSUE THREAD

**Issue by ForGuru** [visionmedia/superagent#1378]
<img width="948" alt="screen shot 2018-05-20 at 10 35 45 pm" src="https://user-images.githubusercontent.com/14887664/40281814-54122400-5c7f-11e8-9ca6-dfccc1ff46a0.png">

`	Request.post(URL_FILE_UPLOAD)
			.attach('uploadedfile', acceptedFiles[0], acceptedFiles[0].name)
			.on('progress', event => {
				console.log('Progress', event.percent);
			})
			.then((response)=>{
				console.log('reaponse',response);
			}
			);
`

**Comment by kornelski** [comment]
Have you verified it using other sources? I think devtools just don't display the content.

**Comment by niftylettuce** [comment]
PR welcome with failing test if still an issue
