### ISSUE TITLE
res.type is available for HEAD but not for GET.

### ISSUE THREAD

**Issue by Redsandro** [visionmedia/superagent#1379]
On a HEAD request, the response has a `res.type` set as `res.headers['content-type']`.

On a GET request however, `res.type` is not available but `res.headers['content-type']` is.

I think for intuitive re-use of functions that can work with the response of either a HEAD or a GET request, both response objects should be similar where possible. I.e. the `type` attribute should be available on both responses. (Or neither).

Using superagent 2.3.0.

**Comment by kornelski** [comment]
Please test with 4.0.0

```sh
npm i superagent@next
```

**Comment by niftylettuce** [comment]
PR welcome with failing test if still an issue
