### ISSUE TITLE
why request.agent  will drop prev cookies while set another new cookie by server

### ISSUE THREAD

**Issue by DragonCat1** [visionmedia/superagent#1384]
`const header = {Cookie: 'a=1;b=2'}`;
`const agent = Request.agent().set(header)`
`agent.get(path1) //server set-cookies:b=3` 
then
`agent.get(path2) //req header only left cookie b=3`

this not happen under version 3.8.2 but 3.8.3

**Comment by DragonCat1** [comment]
@kornelski 
```javascript
import Express from 'express'
import Superagent from 'superagent'

const app = Express()
let i = 99
app.use('/', (req, res) => {
  res.cookie(String.fromCharCode(i++), i).send(req.headers.cookie)
})

app.listen(8080, () => {
  const header = { Cookie: 'a=1;b=2' }
  const agent = Superagent.agent().set(header)
  agent.get('http://localhost:8080/').then((data) => {
    console.log(data.text)
    return agent.get('http://localhost:8080/')
  }).then((data) => {
    console.log(data.text)
    return agent.get('http://localhost:8080/')
  }).then((data) => {
    console.log(data.text)
  })
})
```
run this script,the result is
```
a=1;b=2
c=100
c=100;d=101
```
the initialized cookies has been droped

https://github.com/DragonCat1/superagent_cookie_issue

**Comment by kornelski** [comment]
Hi. Thanks for your response. I've been travelling and only now I've had a chance to have a look at it.

I don't quite understand why there's stringFromCharCode. Is there a problem only if certain non-printable character is used?

Could you do the test the format that can be used in https://github.com/visionmedia/superagent/tree/master/test/node ? Having it checked automatically in the test suite will help writing a fix _and_ ensuring it won't be broken again in the next release.

**Comment by ashersaupingomez** [comment]
Hi guys, any progress on this issue? I'm having the same issue.

**Comment by niftylettuce** [comment]
PR welcome
