### ISSUE TITLE
How can I prevent superagent from following redirects?

### ISSUE THREAD

**Issue by d11wtq** [visionmedia/superagent#1385]
I'm trying to call a backend service via `superagent` and expecting a response object with a 302 status and a location header. I need to process the response on the client, rather than having superagent assume I want the result of the GET from the location header. Is this supported?

I've tried setting `superagent.post('/my-service').redirects(0).send( ... );`, `superagent.post('/my-service').redirects(-1).send( ... );` and `superagent.post('/my-service').redirects(false).send( ... );` - none of these seem to stop superagent from following the redirect and incorrectly giving me a 200 OK when the actual response I need is the 302.

I can see the redirect being followed from my server logs.

**Comment by kornelski** [comment]
In node it should work. In the browser it's just not possible at all.

**Comment by d11wtq** [comment]
Oh, is that a limitation of XMLHttpRequest itself?

**Comment by d11wtq** [comment]
Just checked. Yeah it's a limitation of XMLHttpRequest. That's a shame. Seems like a pretty odd design choice but it is what it is. Will work around it, thanks.
