### ISSUE TITLE
Is there a way we can disable body parsing?

### ISSUE THREAD

**Issue by anasanzari** [visionmedia/superagent#1386]

**Comment by kornelski** [comment]
It depends if you need it in Node or browser:

https://visionmedia.github.io/superagent/#parsing-response-bodies
https://visionmedia.github.io/superagent/#binary

**Comment by anasanzari** [comment]
This looks like application wide change. What if i only want to disable
specific requests.

**Comment by kornelski** [comment]
`.parser()` and `.responseType()` are per request.

**Comment by anasanzari** [comment]
I guess this needs to be documented

**Comment by kornelski** [comment]
It is in the section I've linked to:

> You can set a custom parser (that takes precedence over built-in parsers) with the .buffer(true).parse(fn) method.

**Comment by anasanzari** [comment]
Does this work for browser?

**Comment by kornelski** [comment]
No, that's node specific. For browser there's responseType
