### ISSUE TITLE
Prevent default Content-Type header (Reddit API)

### ISSUE THREAD

**Issue by alexcroox** [visionmedia/superagent#1387]
I'm trying to connect to the Reddit API using superagent. However the Reddit API does not allow Content-Type in the headers. I am only setting `Authorization` but superagent seems to be setting it's own default headers which I can't seem to unset. 

```
request.post('https://www.reddit.com/api/v1/access_token')
  .send(data)
  .set('Authorization', `Basic ${authCode}`)
  .then(res => {
    console.log(res.body)
  })
  .catch(error => {
    console.error(error)
  })
```

`Failed to load https://www.reddit.com/api/v1/access_token: Request header field Content-Type is not allowed by Access-Control-Allow-Headers in preflight response.`

Reddit allows:

access-control-allow-credentials: false
access-control-allow-headers: **Authorization**
access-control-allow-methods: POST
access-control-allow-origin: *

**Comment by kornelski** [comment]
We're aware of the problem. Maybe you could help with this issue? #1362

**Comment by niftylettuce** [comment]
dup of #1362
