### ISSUE TITLE
CORS problem

### ISSUE THREAD

**Issue by srdjanRakic** [visionmedia/superagent#1388]
I can not make post call, I get this error all the time: 

> Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

This is my code: 

`       superagent
            .post(url, body)
            .use(tokenPlugin)
            .withCredentials()
            .then(responseBody),`

I have CORS enabled on my ASP.NET Core Web API: 
`        app.UseCors(x => x
                .AllowAnyOrigin()
                .AllowAnyMethod()
                .AllowAnyHeader()
                .AllowCredentials());`

**Comment by kornelski** [comment]
This looks like a message from your browser, and if the browser says CORS is not sent by the server correctly, then it's not sent by the server correctly. Inspect the headers.

**Comment by trunggb** [comment]
I have this problem too, can u show me how to solve it ? Thank
