### ISSUE TITLE
superagent not working as expected with CHROME

### ISSUE THREAD

**Issue by palakdesai7** [visionmedia/superagent#1390]
I am trying to print response from a API. very simple. Works fine when I run below script with Firefox.

code is something like this:
 
```
it('Verify "First Name" from api and profile page are same', function() {
     //Do initial login
       request
        .post("api url)
        .send({email:"test@test.com", password:"tester"})
        .set('Accept', 'application/json')
        .end(function(err,res){
          console.log(res.body); 
        });
        
    });
```

Any one facing issues with chrome and superagent.

Thanks

**Comment by kornelski** [comment]
The code looks like from a test, not from actual superagent use. As it stands, this test is meaingless — it has no assertion, and doesn't even wait for the result.

Also you haven't provided any specific information about how chrome fails, what was expected and acutal result, and relevant information such as http headers from the client and the server.

**Comment by palakdesai7** [comment]
@kornelski This test is an example. And as mentioned, I don't want to assert or do anything. Just want to print response. Test passes with no errors when browser is chrome. And superagent can be use in multiple ways. So here I want to use it to print response from api mentioned in `post`.  Plus end function will wait till console.log is executed so no additional waiting is required.

Thanks

**Comment by kornelski** [comment]
So for purpose of printing the code looks fine. I can't help you without specific description of what doesn't work, what should work, and what HTTP header superagent has sent and received (from Chrome's network inspector or tcp dump).

**Comment by jonathansamines** [comment]
@palakdesai7 From your test seems like it is not waiting for the response (super agent is completely async). If your are using mocha, you can return the whole expression as mocha is promise-aware and superagent returns promises.

**Comment by palakdesai7** [comment]
@jonathansamines Thanks I will try that.

**Comment by niftylettuce** [comment]
v5.0.0 was just released to NPM and an updated README is now available here on GitHub (see <https://github.com/visionmedia/superagent#superagent>).

## What's new

* Browser version is now only 19KB (that's 60% in file size savings from v4.x which was 48KB)!
* Codebase refactored using `xo`, `prettier`, `remark`, and more
* Browser compatibility linting via `eslint-plugin-compat`
* Browserslist integration (current targets are `> 1%, last 2 versions, ie 9`)

## How to install

```sh
npm install superagent@latest
```

> Or if you're using yarn:

```sh
yarn add superagent@latest
```

## Polyfills

Please see the [Required Browser Features](https://github.com/visionmedia/superagent#required-browser-features) section in the README if you plan to support IE 9 and/or IE 10 and use `superagent`.
