### ISSUE TITLE
.send({ __proto__: {} }) actually sends an empty object

### ISSUE THREAD

**Issue by EvanHahn** [visionmedia/superagent#1392]
These two lines are equivalent but I think they shouldn't be:

```javascript
superagent.post('https://example.com')
  .send({})
  .end()

superagent.post('https://example.com')
  .send({ __proto__: {} })
  .end()
```

This likely happens because `JSON.stringify({ __proto__: {} }) === '{}'`.

Happy to submit a pull request if we think this is valuable.

**Comment by kornelski** [comment]
`__proto__` is a non-standard hack. While it has some uses, I don't see why would it be useful for sending JSON. Behavior of `JSON.stringify` seems sensible here.

So I think current behavior is fine, and I'd rather pretend `__proto__` doesn't exist and not support any objects hacked that way.

**Comment by EvanHahn** [comment]
Makes sense.

I was using Supertest to figure out whether my API server did anything weird with `__proto__`. For anyone else doing exactly what I was, I wrote a request like this to accomplish this:

```javascript
supertest(app)
  .post('/my-route')
  .set('Content-Type', 'application/json')
  .send('{"__proto__": {}}')
  .end(/* ... */)
```
