### ISSUE TITLE
How to close http connection？

### ISSUE THREAD

**Issue by icewitch** [visionmedia/superagent#1394]
After the request is sent, http connection is not closed by the client? How to close http connection in the superAgent? The server is messed up with 150 http rest connections... 

request   
	   .get(url)
	   .auth(test.username,test.password)	   
	   .type('application/json')
	   .end(function(err, result){	   		
	   		if ( err == null ) {	   					
			    console.log("[getLibid] statusCode=="+result.statusCode);					
					body=result.body							
					var len=body.libraries.length
					var libid=''
					for (var i=0;i<len;i++) {
						lib=body.libraries[i]						
						if (lib.name==test.library) {
							libid=lib.id
							console.log("[getLibid] library name="+lib.name+" id="+libid)
							break
						} 
					}
					if (libid=='') {
						console.log("Cann't find the library name="+test.library)
						return
					}					
					control.libid=libid					
					control.retrieveTSidFromSession()					
	      } else {
	      	//console.log(err)	      	
	      	console.log("[getLibid] "+result.body.reason)
	      	return
	      }
	    })

**Comment by kornelski** [comment]
It's best if the server decides what to do, not the client. Make the server send `Connection: close` and most frameworks will handle that for you.
