### ISSUE TITLE
Superagent calls ctx.body = data in.then to return 404

### ISSUE THREAD

**Issue by yewenxiang23** [visionmedia/superagent#1396]
Sorry, my English is not good. It's translated

```js
const Koa = require('koa')
const superagent = require('superagent')
const cheerio = require('cheerio')
const url = require('url')
const async = require('async')
const cnodeUrl = 'https://cnodejs.org'
const topicUrls = [];
const app = new Koa()

let test = new Promise((resolve, reject) => {
  resolve('success')
})
function getData(ctx) {
  test.then(res=> ctx.body = res)
}
const main = async ctx => {
  getData(ctx)
};
app.use(main);
app.listen(3000);
```
Accessing localhost:3000 is a success,But if you do that, you'll return 404。Why is that? I'm a beginner. Thank you for your advice

```js
function getData(ctx) {
 superagent.get('https://blog.csdn.net/yewenxiang?viewmode=contents')
 .then(res => {
   const $ = cheerio.load(res.text)
   let result = []
    $('.article-item-box').each((index, item) => {
      result.push({
        title: $(item).find('.text-truncate a').text().replace(/[原|转]/,'').trim()
      })
    })
    console.log(result)
    ctx.body = []
 })
 .catch(err=>{
   console.log(err)
 })
}
const main = async ctx => {
  // ctx.response.type = 'josn'
  // ctx.response.body =  await getData()
  getData(ctx)
};
```

**Comment by kornelski** [comment]
You get 404, because your path on localhost:3000 doesn't exist. Probably you need to add routes to the server or ensure your URL is correct.

**Comment by yewenxiang23** [comment]
@kornelski 
![image](https://user-images.githubusercontent.com/20874994/42940275-7143e2d0-8b8b-11e8-9774-ce94bbf6d088.png)
![image](https://user-images.githubusercontent.com/20874994/42940424-fa757eb0-8b8b-11e8-9bbb-436b04d323f8.png)

**Comment by yewenxiang23** [comment]
![image](https://user-images.githubusercontent.com/20874994/42940453-16b3a8cc-8b8c-11e8-9727-e39110e554ab.png)

**Comment by kornelski** [comment]
Your problem has nothing to do with superagent. Delete all superagent-related code and it will be 100% the same. You haven't defined routes for your server.
