### ISSUE TITLE
Status is undefined in case of 413 error

### ISSUE THREAD

**Issue by vyemialyanchyk** [visionmedia/superagent#1397]
```
Request.prototype.callback = function(err, res){
  if (this._shouldRetry(err, res)) {
    return this._retry();
  }

  var fn = this._callback;
  this.clearTimeout();

  if (err) {
    if (this._maxRetries) err.retries = this._retries - 1;
    this.emit('error', err); <==== break point is here
  }

  fn(err, res);
};

```

```
err: Error: Request has been terminated Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc. at Request.crossDomainError (webpack:///../node_modules/superagent/lib/client.js?:621:13) at XMLHttpRequest.xhr.onreadystatechange (webpack:///../node_modules/superagent/lib/client.js?:703:19)
crossDomain
:
true
method
:
"POST"
status
:
undefined
```

so on error callback I can't detect status..

**Comment by kornelski** [comment]
This cannot be fixed in superagent. The browser refuses to expose information about this error.

**Comment by rhae** [comment]
I have the same situation.
Trying to look what is really happening I wrote a little plain javascript and armed the XHR callbacks (see below).
I tested Chrome beta,FF 52.6, FF 61.0.2, IE 11.0.9600.18537. They show the true xhr.status.

I have also tried to debug superagent. However I have no clue, why the xhr.status is 0 here. Maybe you have some more insight. This would be helpful.

Here are the files and the output. Somehow it didn't work to upload files.

HTML
-------8<---------8<-----------------------
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="X-UA-Compatible" content="IE=Edge, chrome=1"/>
<script>
"use strict";
function submitForm(oFormElement)
{
  var xhr = new XMLHttpRequest();
  var formData = new FormData();

  formData.append( 'action', 'upload' );
  formData.append( 'type', 'DOC' );
  formData.append( 'name', oFormElement.children[0].files[0].name );
  formData.append( 'file', oFormElement.children[0].files[0], oFormElement.children[0].files[0].name );

  xhr.onload = function(){
    console.log( "onload " + xhr.responseText);
  } // success case
  xhr.onerror = function(){
    console.log( "onerror " + xhr.responseText);
  } // failure case
  xhr.onabort = function(){
    console.log( "onabort" + xhr.responseText);
  } // failure case
  xhr.onreadystatechange = function(){
    console.log( "onreadystatechange readyState/state " + xhr.readyState + "/" + xhr.status);
    if ( xhr.readyState == 4 ) {
      console.log( "complete" );
    }
  }
  xhr.open (oFormElement.method, oFormElement.action, true);
  // xhr.setRequestHeader("Content-type", "multipart/form-data");
  try {
  xhr.send ( formData );
  } catch (e) {
    console.log( "XX " + e );
  }
  return false;
}
</script>
</head>

<body>
<form method="post" action="http://192.168.2.253/cfg" onsubmit="return submitForm(this);">
  <input type="file" accept="*.pdf" />
  <input type="submit" value="post request"/>
</form>
</body>
</html>
------->8--------->8-----------------------

Output
-------8<---------8<-----------------------
upload.html:27          onreadystatechange readyState/state 1/0
upload.html:35          POST http://localhost:3002/cfg 413 (Payload Too Large)
submitForm @ upload.html:35
onsubmit @ upload.html:45
upload.html:27          onreadystatechange readyState/state 2/413
upload.html:27          onreadystatechange readyState/state 3/413
upload.html:27          onreadystatechange readyState/state 4/413
upload.html:29          complete
upload.html:18          onload Not enough file space.
------->8--------->8-----------------------

**Comment by rhae** [comment]
When trying to collect the HTTP request headers I tried some other constellation.
1) My plain script with a nodejs express server and
2) my complete app that is using superagent with the nodejs express server.

In this environment I was getting the true xhr.status in Request.prototype.end from client.js.
So it seems the nodejs server is doing something different than my normal server. Need to see what is different between the two.

Besides. Using my normal server the plain javascript is not working either.
Don't know if I get enough time to work on this...

**Comment by rhae** [comment]
Hello

my normal server is sending another HTTP/1.1 at the end of the answer. This seems to cause the behaviour.

```
HTTP/1.1 413 Request Entity Too Large
Connection: Close
Server: Micro-Web
Content-Type: text/plain; charset=utf-8
Cache-Control: no-cache
Content-Length: 28

413 Request Entity Too LargeHTTP/1.1 501 Command not implemented
```

**Comment by niftylettuce** [comment]
PR welcome
