### ISSUE TITLE
Official way to determine superagent error

### ISSUE THREAD

**Issue by AlexeiGontarCyber** [visionmedia/superagent#1401]
To describe problem I would like to provide following code:

```js
const superagent = require('superagent');

const NOT_EXISTING_URL = 'https://github.com/fewfewf';

async function main() {
  const response = await superagent.get(NOT_EXISTING_URL);
}

main().catch((e) => {
  if (/*some way to determine that e is superagent error*/){
    // custom logic in case of request error
    return;
  }
  console.log('Panic: ', e);
  process.exit(42);
});
```
The main idea is that error handler is dedicated from the source code itself.

**Do we have any way to determine that error is request error?**

Real world use case:
We want to reduce amount of logs and send better error message in response to user.

**Comment by kornelski** [comment]
If the server has responded, there will be `e.response`. 

Please note that in many cases, especially cross-origin errors, browsers *deliberately* hide all details of errors and intentionally make it impossible to learn what happened, as network errors are a privacy leak.

**Comment by AlexeiGontarCyber** [comment]
@kornelski Thank you for your comment. Few points:
1. Is there any strong reason to avoid creation of custom error?
2. I think in case when this is strong policy to rely on duck-typing. I think that it makes sense to expose function like `isSuperagentError` to make smooth migration to new versions of library(at some point error could be changed). And have well tested function which will detect library generated errors.

Personally I think that custom error class will be better because allows to use simple `instanceOf` check.
