### ISSUE TITLE
How to disable forced redirection when response status code is 302?

### ISSUE THREAD

**Issue by noah-goodrich** [visionmedia/superagent#1402]
I am working with an external api where the api designer returns a 302 status code from a request for an authorization token. I am aware of the fact that is not standard behavior, but its what I have to deal with. 

What's the simplest path to overriding the default behavior in superagent so that it doesn't try to redirect on this status code?

**Comment by kornelski** [comment]
In Node `.redirects(0)`. In browser — not supported at all.

**Comment by noah-goodrich** [comment]
This still throws an error because _isResponeOK asserts that the status code has to be less than 300. 

Its a hack, but for those coming after, I catch the error with this:

```
if(err.message === 'Found') {
    return JSON.parse(err.response.res.text)
} else {
    throw err
}
```

**Comment by kornelski** [comment]
There's `.ok()` callback that decides which status is an error.

**Comment by noah-goodrich** [comment]
@kornelski Example?

**Comment by kornelski** [comment]
https://visionmedia.github.io/superagent/#error-handling

**Comment by tractorcow** [comment]
Why do you treat 30x as an error?

**Comment by kornelski** [comment]
Because it's not success (2xx). Bodies of 30x responses tend to be garbage.

You usually don't see 30x, because we follow redirects.  If there are too many redirects and we stop following them, then you get 30x. That's probably not what you expected, so we default to erring.

**Comment by tractorcow** [comment]
Thanks for the explanation. :)
