### ISSUE TITLE
SSO in non-browser context

### ISSUE THREAD

**Issue by erik-stephens** [visionmedia/superagent#1403]
My setup is single sign-on to an auth service under the same domain (eg sso.example.com) as the service I'm trying to authenticate to (eg portal.example.com).  Even though they share a domain, the [auth & cookie headers get cleared](https://github.com/visionmedia/superagent/blob/ec987f6f154de764435da2f5cbd88a3a85d1fb7f/lib/utils.js#L54) because [the domains do not match exactly](https://github.com/visionmedia/superagent/blob/13ff9b3a1bec34020c7d5dfcf88bbb26d67b9ee1/lib/node/index.js#L474).

Ideas on how I can do this the "right" way instead of a hack like the following?

https://github.com/erik-stephens/superagent/commit/b4fa2da5288638f08954023e0baa33d44288e03c

**Comment by kornelski** [comment]
Unfortunately, we don't have a good solution here.

Do you know if the cookiejar library has support for matching cookies by domain? I'm not sure if we're using the library properly.

**Comment by erik-stephens** [comment]
For my case, it's working as I expect: my diy/artisinal SSO service issues a `Set-Cookie` with a JWT for `domain=example.com` and the target service (foo.example.com) sees that cookie.

I assumed there would be some standard like CORS to help guide this, but not being in a browser changes the game considerably?  I've been out of the web dev game for a while and feel a bit out of touch - wondering if there's a best practice to follow.  My "let clients declare their level of trust" seems sound but I'm a bit biased, especially since I'm not worrying about browser clients.

Feel free to close if doesn't seem worth any more consideration.  I expect my use case to be outside the norm.

**Comment by niftylettuce** [comment]
PR welcome
