### ISSUE TITLE
interface Response is missing redirects property

### ISSUE THREAD

**Issue by dotnetCarpenter** [visionmedia/superagent#1405]
### Steps to reproduce:

Using [vscode](https://code.visualstudio.com/) copy the following snippet into a new file:

```js
// @ts-check
import request from 'superagent'

async function missingRequestsProp () {
  const result = await request.get('http://skovbar.dk')
  return result.redirects
}
```
_make sure you have installed superagent (`npm i superagent`)_

Gives error:
> [ts] Property 'redirects' does not exist on type 'Response'. Did you mean 'redirect'?
index.d.ts(109, 9): 'redirect' is declared here.

### Fix

Add `redirects: string[];` to  [`interface Response`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/superagent/index.d.ts#L92).

The fix works locally but a real fix should probably be a PR to the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/) project.

**Comment by kornelski** [comment]
We don't maintain TS interface. Please report it to DefinitelyTyped or author of the ts file.

**Comment by dotnetCarpenter** [comment]
@kornelski just letting you know. I fixed it on my end and probably won't use superagent for anything but tests. But I thought you might wanted to know, so you could take action. Sorry but I won't do anything further.
