### ISSUE TITLE
superagent.agent.post returns typeError

### ISSUE THREAD

**Issue by kaas115** [visionmedia/superagent#1411]
Hi, I'm trying to write a POST request but it returns a error. Tried a couple things and I seriously doubt my code is the issue.
`async function login(schoolname, lastname, password) {
    let href;
    let loginForm;
    let formData;
    let agent = request.agent();

    await agent
        .get(`https://${schoolname}.cupweb6.nl/`)
        .buffer(true)

        .then(res => {
            let $ = cheerio.load(res.text);
            loginForm = $("#mainForm")
            href = res.redirects[0]
            

        }).catch(console.log);

    formData = new FormData(loginForm);

    formData.append("_zoekButton", "Zoek");
    formData.append("_VIEWSTATEGENERATOR", "CA0B0334");
    formData.append("_VIEWSTATE", "/wEPDwUKLTk2NDIyODYxM2RkNj6hnwARkPCtsC5Hn5E0sJYMF3r7CqyU82Yc9l35WB4=");
    formData.append("_EVENTVALIDATION", "/wEdAARL/XX41Z4RzAnSTMXRQeQZxurWqYfDAQvTZnFnK0U7Kk0GaO9VtQt7Jxe2Y2ezNCURReF+wxp4uxWtRwwZ1rXEJURSRH7Wm0RDHB8h6l72LHMLuHiuQGCyqQLXJs4tjUI=");
    formData.append("numberOfLettersField", "3");

    await agent
        .post(href)   //<== the code that returns the error
        .send(formData)

        .then(res => {

            console.log(res);

        }).catch(console.log);

}`

Error: 
`TypeError: "string" must be a string, Buffer, or ArrayBuffer
    at Function.byteLength (buffer.js:481:11)
    at Request._end (C:\magistertests\node_modules\superagent\lib\node\index.js:804:84)
    at Request.end (C:\magistertests\node_modules\superagent\lib\node\index.js:777:15)
    at C:\magistertests\node_modules\superagent\lib\request-base.js:238:12
    at new Promise (<anonymous>)
    at Request.then (C:\magistertests\node_modules\superagent\lib\request-base.js:237:31)
    at login (C:\magistertests\projects\cupweb6\cupweb6auth.js:39:10)
    at <anonymous>
    at process._tickCallback `(internal/process/next_tick.js:188:7)`

**Comment by kaas115** [comment]
Thanks for the swift response.

**Comment by perki** [comment]
In the documentation 
http://visionmedia.github.io/superagent/#multipart-requests

It's quoted that superagent does support FormData 

"Sending a FormData object is also supported. The following example will POST the content of the HTML form identified by id="myForm":"

Is it a "browser only" feature ?
