### ISSUE TITLE
Response promise rejected when JSON is invalid

### ISSUE THREAD

**Issue by iDroid27** [visionmedia/superagent#1412]
**Reproducable code:**
```js
const superAgent = require('superagent');
superAgent
  .get('http://tt.chadsoft.co.uk/index.json')
  .then(res => console.log(res.rawResponse));
```

The JSON returned by the given website is **broken**, however `superagent` rejects the promise when `JSON.parse` returns an error. That could be seen as something good for those who really want a JSON response but let's say your website returns that piece of text and you want to handle it yourself, you need to do that in the `catch` callback which can be annoying (it's not really its purpose).  
  
I don't **think** that's an expected behaviour, it should just ignore the error and resolve the promise since it's not really a request error.  
  
That's more a "discussion" issue to talk about this rather than an actual suggestion (even if that could become one if people kinda agree with me).

**Comment by y21** [comment]
I contacted the website administrator of that website and he told me the first character that causes the JSON.parse error stands for the [Byte order mark](https://en.wikipedia.org/wiki/Byte_order_mark).

**Comment by kornelski** [comment]
There's no BOM in UTF-8. That's a made-up hack for Windows Notepad. The JSON spec explicitly forbids use of the BOM in UTF-8, so superagent's behavior is correct.

Superagent only tries to parse response as JSON when the server tells it to parse it as JSON by setting `application/json` Content-Type. If the Content-Type was something else, like `text/plain`, then it wouldn't be parsed, and the non-JSON data would be allowed.

**Comment by iDroid27** [comment]
Right, I understand 😄
**Closed** :lock:

**Comment by kornelski** [comment]
BTW, we support overriding of parsers. The API is a bit tricky, but you could try copying code of our existing JSON parser, set it as parser for the request, and make it skip over the problematic character.
