### ISSUE TITLE
Question: Require Superagent ES5 Module

### ISSUE THREAD

**Issue by djizco** [visionmedia/superagent#1416]
Version: 4.0.0-beta.2

Would it make sense to rename or move the ES5 module of superagent into a separate folder.  Maybe I am not requiring it the best way but it is currently at node_modules/superagent/superagent.js.  I am requiring it like such:

```
const request = require('superagent/superagent');
```
To me it doesn't make sense and looks confusing or wrong. Should there be a /es5 or /src directory?

**Comment by kornelski** [comment]
It's not a module. It's a stand alone copy to include in web browsers like it's 1999.
