### ISSUE TITLE
How abort request when using async/await?

### ISSUE THREAD

**Issue by jazoom** [visionmedia/superagent#1417]
I feel like I'm missing something basic here. When using something like the below, how do you get a reference to the `req` object to call `abort()`?

```
const res = await request.post('someurl').attach('thing', thingFile);
```

I'm in the process of updating dependencies and I note you've now deprecated returning `req` from calls to `end()`. One instance of old code that I wrote before promises were a thing in JavaScript uses this to abort. I can't see how to update it to use the async/await syntax, which is what I use for all my promises nowadays.

I should note that I see in your documentation an example using `yield` to handle the promise. That is a keyword I avoid to keep all code consistent using async/await.

**Comment by jazoom** [comment]
Ah right. So `req` is a promise and you can call `abort` directly on the promise? Interesting.

**Comment by kornelski** [comment]
Req isn't a promise. It's "thenable", which means it's converted to a promise when needed.

**Comment by jazoom** [comment]
Gotcha. That makes more sense. Thanks.
