### ISSUE TITLE
Promise is not supported in Opera Mini all, IE Mobile 11, IE 11

### ISSUE THREAD

**Issue by niftylettuce** [visionmedia/superagent#1419]
We don't have a note anywhere in README that Promise is used in `superagent.js` and a polyfill is needed such as `es6-promise`.

**Comment by kornelski** [comment]
I think we're not using promises at the core yet, so if you use end() callback it should work without promise polyfill.

**Comment by linzhaoken** [comment]
It happened to me as well.
![image](https://user-images.githubusercontent.com/4997989/50833726-1b6ac300-134a-11e9-82b0-a448cba2f32e.png)

**Comment by kornelski** [comment]
Did you call `.then()`? That one case requires promises, but non-promise interface shouldn't.

**Comment by kornelski** [comment]
Requirement is documented here:

https://visionmedia.github.io/superagent/#promise-and-generator-support

and here

https://github.com/visionmedia/superagent#upgrading-from-previous-versions

**Comment by niftylettuce** [comment]
v5.0.0 is released and fixes this issue
