### ISSUE TITLE
thoughts for src folder and new setup with babel? (example link included)

### ISSUE THREAD

**Issue by niftylettuce** [visionmedia/superagent#1421]
@kornelski @juliangruber curious your thoughts and if you'd be open to a PR that would add a `src` folder which would be similar to the setup I have here <https://github.com/cabinjs/cabin> where we have src which compiles to lib, and a dist folder for browserified builds with unpkg.com support.  if so I would gladly add this

**Comment by niftylettuce** [comment]
the main benefits to this is that we can use `@babel/preset-env` to target node versions we want to support, and take advantage of a `.browserslistrc` file for both babel targeting and eslint (with added support for `eslint-plugin-compat` which uses caniuse database for linting).

**Comment by kornelski** [comment]
I suspect it may be tricky, because we share files between Node and browser. For browsers compiling/copying is a necessary evil, but we only support ES6-capable Node versions, so it's desirable to serve ES6 files directly to Node.

**Comment by niftylettuce** [comment]
once Lass has babel support I could tackle this <https://github.com/lassjs/lass/issues/40>

**Comment by niftylettuce** [comment]
@kornelski I've submitted PR #1423 to fix this.  Please accept/test 👍 !

**Comment by niftylettuce** [comment]
v5.0.0 is released and fixes this issue
