### ISSUE TITLE
lib/client.js not ES5 compatible :'(

### ISSUE THREAD

**Issue by leefsmp** [visionmedia/superagent#1424]
pretty much sum it up in the title, code like [this](https://github.com/visionmedia/superagent/blob/master/lib/client.js#L51)  makes IE11 angry ... I know, I know, screw that due. Superagent is THE only module in my 100,000,000 deps I need to include in the transpiling step.

**Comment by kornelski** [comment]
Indeed, in superagent v4 we've dropped support for ES5. If you need ES5 compatibility, you have to either stay with superagent v3 or transpile.
