### ISSUE TITLE
http range functionality?

### ISSUE THREAD

**Issue by contra** [visionmedia/superagent#1425]
Right now you have to do this all by hand, which can lead to mistakes:

```js
// simple range
req.set('Range', 'bytes=0-1023')

// multipart ranges
req.set('Range', 'bytes=0-50, 100-150')

// conditional range requests
req.set('If-Range', 'Wed, 21 Oct 2015 07:28:00 GMT')
```

Would be great if superagent made this nicer, sample API of what that could be:

```js
// simple
req.range([ 0, 1023 ])

// multipart
req.range([ [ 0, 50 ], [ 100, 150 ] ])

// with conditional
req.range([ 0, 1023 ], {
  if: new Date() // any date object
})
```

Will send PR if interested.

**Comment by kornelski** [comment]
Thanks for the suggestion. I'm not sure if that change is appropriate. It's an indirection, but not abstraction.

Users would still need to understand mapping between `.range()` microsyntax and HTTP semantics. If header syntax errors are an issue, superagent could handle the problem directly by checking the syntax of the header.

Proper support would need more changes. For example, response with multiple ranges should probably have `body` as an array of `Buffer`s, and we should be smart enough not to try to parse fragments using parsers designed for parsing a full response (e.g. fragments of JSON are not parsable as JSON). But I'm not sure if ranges are used often enough to justify all the changes to have *good* range support, and just a minimal one doesn't seem that interesting.

**Comment by contra** [comment]
@kornelski Yep, the code in the issue is just a starting point to the discussion around putting better support for ranges in superagent.

Concretely I need to use this for downloading files in a resilient way - right now superagent is not suited to do that. If you're downloading a 16GB file to disk and the network hiccups somewhere you have to start over from the beginning. I'll probably end up making a plugin to handle this case really well, but it's worth having a conversation about how much of this should go into core (I think downloading a file is a pretty common case IMO).

My dream API (figured this was probably too much) would be:

```js
// will detect range support, and in the event of any connection issue
// it will continue the request where it left off
request.get('largefile')
  .resilient()
  .pipe(transform)
```

> not sure if ranges are used often enough to justify all the changes to have good range support

Servers support range headers - I can't think of any that doesn't. Usually request libraries is where the gap is, so they probably aren't being used as much as they should be.

**Comment by kornelski** [comment]
Resilient downloads sound cool, but we're always keeping the result in memory, which limits how large the large file can be. So it may be better left to a higher-level downloader that also manages on-disk storage.

**Comment by contra** [comment]
@kornelski 	That's already the case, I don't follow how adding the `resilient` functionality would make the problem any worse?

**Comment by niftylettuce** [comment]
PR welcome
