### ISSUE TITLE
There is a puzzling error, which is threw by "formidable" package

### ISSUE THREAD

**Issue by IveHD** [visionmedia/superagent#1428]
![image](https://user-images.githubusercontent.com/17447867/47643138-814a0a00-dba5-11e8-9926-d6f2fd3865aa.png)

According to the console shows, the global.GENTLY is undefined, but "require" is changed to undefined. So when "require" is called, error threw.

**Comment by colbyhub** [comment]
I'm also having this issue, any luck with this?
