### ISSUE TITLE
Cookie not preserved for further requests if secure option is set to true 

### ISSUE THREAD

**Issue by WangHansen** [visionmedia/superagent#1429]
When use `secure: true` when setting the cookie, the `request.agent(app)` calls don't pass the cookie. Not sure if this is superagent issue because they seem to have this [fixed](https://github.com/visionmedia/superagent/issues/130) a long time ago. If I remove the secure option, everything works fine.

**Comment by niftylettuce** [comment]
Is this still an issue?  If so, a PR welcome with a failing test is welcome.
