### ISSUE TITLE
getting 415 issue when sending file attachment using attach method

### ISSUE THREAD

**Issue by sred36** [visionmedia/superagent#1431]
superagent
        .post(`${url}/image`)
        .use(tokenPlugin)
        .attach('file', file.target.value)
        .then((response, err) => {
            // tslint:disable-next-line:no-console
            console.log('err', err);
        });
![image](https://user-images.githubusercontent.com/35680138/47798949-484d9900-dd4f-11e8-8b26-990c7f8ac4a4.png)

**Comment by kornelski** [comment]
It looks like your server is paying attention to MIME type of the attached file, but the browser doesn't know/can't know what the right value is expected.
