### ISSUE TITLE
version 3.x or 4.x

### ISSUE THREAD

**Issue by csantanapr** [visionmedia/superagent#1433]
I see that the version of 4.x is marked `-beta` 

What's the major change, or braking change between 3.x vs. 4.x?

I'm building runtimes for serverless and only using nodejs 8+

Is the only difference that it drops support for nodejs 4.x?

Is it a safe bet on picking up 4.x even if it's marked beta?

thank you for your patience and for this project.

**Comment by kornelski** [comment]
The major breaking change is used of ES6 in the source code.

https://github.com/visionmedia/superagent/releases

**Comment by csantanapr** [comment]
Super that sounds easy then for me :-)
