### ISSUE TITLE
Async plugin

### ISSUE THREAD

**Issue by ashersaupingomez** [visionmedia/superagent#1434]
I've tried creating and using an asynchronous plugin in my code. When I do this, the request is called before the promise is resolved.

So I guess asynchronous plugins aren't supported. Does anyone else have this same problem or am I missing a particular method of achieving this behaviour besides resolving values before calling the request?

**Comment by kornelski** [comment]
Indeed, there is no support for async plugins. You have to wrap superagent in your own async funciont.

**Comment by ashersaupingomez** [comment]
I think async plugins could make for great functionality. For example, I know of a few instances where async work needs to be done before the first request in order to authenticate a user.

I'd be happy to work on this if you agree.

**Comment by kornelski** [comment]
I totally agree it'd be useful. Go for it!

**Comment by ashersaupingomez** [comment]
Hm... After looking at the code, I don't know of a way that this can be done while preserving the ability to chain methods. If the plugin itself was asynchronous, for example, the use method would have to be as well.

**Comment by ashersaupingomez** [comment]
The exact functionality I'd love to see is being able to call some sort of authentication request before each request, build that into an agent using the `use` method, then exporting that agent, ready for use.

**Comment by niftylettuce** [comment]
PR welcome
