### ISSUE TITLE
Precompiling node_modules troublesome, include browser ready version in npm?

### ISSUE THREAD

**Issue by suprMax** [visionmedia/superagent#1437]
It appears that every other project (React, React-Router, Redux, ...) tend to precompile ES6+ code on the publish step. Targeting superagent during build or including all `node_modules` in the babelify step is problematic.

Are you opposed to an idea of also precompiling your ES6+ code down to IE9 compatibility level? I'm currently stuck unable to update to v4 because of this.

**Comment by suprMax** [comment]
I've decided to switch to axios: https://github.com/axios/axios

**Comment by niftylettuce** [comment]
@suprMax I am releasing superagent@5.0.0 soon with support for this.  You can see my PR is already done here https://github.com/visionmedia/superagent/pull/1423, now I am a maintainer/contributor to this package and will have this released soon!

You can use [@ladjs/superagent](https://www.npmjs.com/package/@ladjs/superagent) in the meanwhile until `superagent@5.0.0` is released.
