### ISSUE TITLE
Cannot use Electron's net module as https protocol

### ISSUE THREAD

**Issue by NilSet** [visionmedia/superagent#1439]
When attempting to replace the `https` module in `request.protocols` with the `net` module from Electron, inside electron's node environment, the ostensibly compatible module returns a response which has arrays for the values of response headers instead of strings (see electron/electron#8117)

superagent quite reasonably assumes that the response object has string headers and throws a type error when trying to look up the content-type of the response.

The use case here is to use electron's proxy aware https transport from the nodejs half of electron.

**Comment by kornelski** [comment]
I don't use Electron, and it's not a supported platform for superagent, so I'd rather not maintain workarounds for it. It's a bug they should fix.

**Comment by NilSet** [comment]
Would you accept a PR making header access go through `this` to allow implementing a workaround as a plugin?

**Comment by NilSet** [comment]
I do agree that electron ought to fix this but there has been no movement on it for three years...

**Comment by Gloridea** [comment]
The Issue ([electron/electron#8117](https://github.com/electron/electron/issues/8117)) is resolved and merged in [Electron 6.0.0-beta.1](https://github.com/electron/electron/releases/tag/v6.0.0-beta.1).

**Comment by NilSet** [comment]
excellent!

**Comment by Gloridea** [comment]
But it still doesn't work.

**Comment by NilSet** [comment]
Not as excellent!
