### ISSUE TITLE
Send & Attach Are Incompatible.

### ISSUE THREAD

**Issue by jvanalst** [visionmedia/superagent#144]
I was able to get around this by using the low level part() API, but...

When you send form data and have one or more attachments superagent explodes with an obscure "Argument Must be String" error. This is because the content-type gets set to multipart, and there is no multipart formatter to convert it to string, it tries to do a Byte Length operation on the raw JSON to set the content-length.

In fact if you skip that error condition it will send the attachment correctly, but ignore the form-data.

``` coffeescript
describe '/worms', () ->
  describe 'POST', () ->
    it 'should respond with JSON', (done) ->
      worm = _.first fixtures.worms()
      delete worm.image_url
      delete worm.location
      console.dir 
      supertest(app)
        .post('/worms')
        .attach('image', wormImage)
        .send(worm)
        .expect(400)
        .set('accept', 'application/json')
        .expect('content-type', 'application/json')
        .end (err, res) ->
          throw err if err
          console.dir res.body
          done()
```

>  ✖ 1 of 1 test failed:
> 
>  1) /worms POST should respond with JSON:
>     TypeError: Argument must be a string
>      at Test.Request.end (/Users/vanalsti/Projects/citizen-science-api/node_modules/supertest/node_modules/superagent/lib/node/index.js:607:43)
>      at Test.end (/Users/vanalsti/Projects/citizen-science-api/node_modules/supertest/lib/test.js:121:7)
>      at Context.<anonymous> (/Users/vanalsti/Projects/citizen-science-api/tests/server.coffee:29:173)
>      at Test.Runnable.run (/Users/vanalsti/nvm/v0.8.14/lib/node_modules/mocha/lib/runnable.js:187:15)
>      at Runner.runTest (/Users/vanalsti/nvm/v0.8.14/lib/node_modules/mocha/lib/runner.js:307:10)
>      at Runner.runTests.next (/Users/vanalsti/nvm/v0.8.14/lib/node_modules/mocha/lib/runner.js:353:12)
>      at next (/Users/vanalsti/nvm/v0.8.14/lib/node_modules/mocha/lib/runner.js:235:14)
>      at Runner.hooks (/Users/vanalsti/nvm/v0.8.14/lib/node_modules/mocha/lib/runner.js:244:7)
>      at next (/Users/vanalsti/nvm/v0.8.14/lib/node_modules/mocha/lib/runner.js:192:23)
>      at Runner.hook (/Users/vanalsti/nvm/v0.8.14/lib/node_modules/mocha/lib/runner.js:212:5)
>      at process.startup.processNextTick.process._tickCallback (node.js:244:9)

A less obscure error would be nice. Even nicer would be if send and attach could be compatible.

**Comment by skskumbharkar** [comment]
I want to access 'extra_info' data (based on above example) in my expressJS app.
How to access it?

**Comment by yadirhb** [comment]
> but it would be nice to have `.fields(object)` or something similar that invokes .field() a bunch

I tested this and is working....

`
const superagent = require("superagent");
`
!superagent.Request.prototype.fields &&  Object.defineProperty(superagent.Request.prototype, "fields", 
{
    value: function(items) {

      if (items && typeof items === "object") {

        for (let key in items) {

          if (items.hasOwnProperty(key)) {

            let item = items[key];

            if (typeof item === "function") continue;
            else if (typeof item === "object") {
              item = JSON.stringify(item);
            }

            this.field(key, item);
          }
        }
      }

      return this;
    }
  });
`
