### ISSUE TITLE
Feature: reusable requests that automatically manage the state of previous request

### ISSUE THREAD

**Issue by kremit** [visionmedia/superagent#1442]
I'm new to SuperAgent and have spent a few hours reading through the docs and code. Any chance there could be (or already is) a way to re-use requests and chain them together? Two use cases for this are:
- autosuggest text fields: after debounce time, cancel any requests in-flight and re-execute search API request with updated field text
- web map data layers: I have an app that requests real-time data based on the current map bounds, and this is updated each time the map stops panning/zooming.

In older web frameworks, this was possible. The easiest was actually in MooTools-Request, which had a simple flag `link: 'cancel'` which automatically cancelled any previous in-flight requests, skipped the callback, and issued a new GET request using (optionally) new query parameters. This avoided any issue where a slow-arriving response would do funny things in the UI like going back in time.

MooTools [Request](https://mootools.net/core/docs/1.6.0/Request/Request):

```
this.requestTasks.jsonRequestObs = new Request.JSON({
	url: '/api/feed',
	link: 'cancel',
	timeout: 30,
	onSuccess: function(obj) {
		this.liveUpdateMarkers(obj);
	}.bind(this)
});
this.requestTasks.jsonRequestObs.get({type: 'obs', bounds: map.getBounds().toBBoxString()})
// Update previous request
this.requestTasks.jsonRequestObs.get({type: 'obs', bounds: 'somewhere else'})
```

jQuery, but pretty ugly:

```
this.requestTasksXHR = {};
this.requestTasks = {};
this.requestTasks.resultsMap = function(query) {
	if(this.requestTasksXHR.resultsMap && this.requestTasksXHR.resultsMap.readyState < 4) {
		console.log('aborting resultsMap');
		this.requestTasksXHR.resultsMap.abort();
	}
	this.requestTasksXHR.resultsMap = null;
	this.requestTasksXHR.resultsMap = $.ajax({
		url: '/feed/obs',
		timeout: 30000,
		data: query,
		dataType: 'json'
	})
	.done(function(data) {
		liveUpdateMarkers(data);
	});
}.bind(this)
```

I'm happy to work on this soon and make a pull request. It looks like this would be quite similar to `BaseRequest._retry` but maybe you could point me in the right direction, or maybe it's complicated without cancelable Promises?

**Comment by kornelski** [comment]
Mutable state is already quite problematic for superagent, so I'd rather not add anything more in that direction.

You can build the features you want as a higher level on top of superagent. Building of request objects isn't expensive, so it's perfectly fine to make new request object every time you want to send a new request.

**Comment by kremit** [comment]
Good to know, thanks! I'll see about wrapping the requests with a simple manager that checks the progress of the connection and aborts if still running when another request for the same task comes in.
