### ISSUE TITLE
.attach didn't upload file

### ISSUE THREAD

**Issue by sidhijakpat** [visionmedia/superagent#1444]
We try to use superagent to upload file to our server by following this guide, https://visionmedia.github.io/superagent/#multipart-requests, on React Native project 

here is our implementation code 

      superagent.post(full_url)
        .field('type', 'image_type')
        .attach('file', file.uri, {contentType: 'image/png'})
        .then(response => {
          console.log(`response ${JSON.stringify(response.body)}`)
          callback(response.body)
        })
        .catch(error => {
          console.log(`error body json stringify ${JSON.stringify(error)}`)
          errorCallback(error)
        })

`file.uri` here is image that we got from react-native-camera

the field `type` was received by server, but the `file` was not there
response from server is, more or less
```
{
  "status": false,
  "data": "Required request part 'file' is not present"
}
```

we try to change the `attach` parameter to 
`        .attach('file', file.base64, {contentType: 'image/png'})`

and 
`        .attach('file', RNFetchBlob.wrap(file.uri), {contentType: 'image/png'})`

and also
`        .attach('file', RNFetchBlob.wrap(file.base64), {contentType: 'image/png'})`

with no luck

we try to log the form data on `attach` function, 
```
{
  "_parts": [
    [
      "type",
      "image_type"
    ],
    [
      "file",
      "path/to/file"
    ]
  ]
}
```

it clearly show that the `file` is there

calling the same api from `Postman` is success without a problem

what did we do wrong here?
any feedback is welcome

thank you

Superagent: v4.0.0
React Native: v0.57.5
React: v16.6.3
rn-fetch-blob: v0.10.13

**Comment by sidhijakpat** [comment]
We try to load the file using `react-native-fs` before sending the file, like this:

      rnfs.readFile(file.uri, 'base64').then(result => {
        superagent.post(full_url)
          .field('type', 'image_type')
          .attach('file', result, {contentType: 'image/png'})
          .then(response => {
            console.log(`response ${JSON.stringify(response.body)}`)
            callback(response.body)
          })
          .catch(error => {
            console.log(`error body json stringify ${JSON.stringify(error)}`)
            errorCallback(error)
          })
      })

still got the same error

**Comment by sidhijakpat** [comment]
I got it, so the `file` must be in JSON object in the following format to make it work:

    const file = {
      fileUri,
      name: 'image_name.png',
      type: `image/png`
    }

Thank you

**Comment by sidhijakpat** [comment]
Sorry, the issue still exist, 

the server did find `file` key, but the uploaded file is empty

still need help 😄

**Comment by sidhijakpat** [comment]
Once again, it was our mistake, the JSON Object should be:

```
const file = {
  uri: fileUri,
  name: 'image_name.png',
  type: `image/png`
}
```

Thank you again

**Comment by hichamon306** [comment]
Hello @sidhijakpat ,
I'm facing the same problem, i have to upload image with superagent, I try attach with multiple paramters, but still have the issue, with postman it works, can you explain please what you did to get it work ?

Thanks

**Comment by sidhijakpat** [comment]
When I call it here

```
const file = {
  fileUri,
  name: 'image_name.png',
  type: `image/png`
}
```

you see that the `fileUri` didn't have a key? 
because it didn't have a key, the JS will automatically transform it into

```
const file = {
  fileUri: fileUri,
  name: 'image_name.png',
  type: `image/png`
}
```
that where it wrong, 

the file uri of the request should be `uri`, 

so we need to change it into 

```
const file = {
  uri: fileUri,
  name: 'image_name.png',
  type: `image/png`
}
```

where the `fileUri` key is `uri`

**Comment by hichamon306** [comment]
You mean i should do this  ? 
`const file = {
  uri: fileUri,
  name: 'image_name.png',
  type: `image/png`
}
request.post(`${API_URL}/reports`)
..field('files.gallery',file);
`
i try it but it dosen't work

**Comment by sidhijakpat** [comment]
here is my full code

```
  const fileJson = {
    uri: fileUri,
    name: 'image_name.png',
    type: `image/png`
  }

  superagent.post(full_url)
    .field('type', 'image_type')
    .attach('file', fileJson, {contentType: 'image/png'})
    .then(response => {
      console.log(`response ${JSON.stringify(response.body)}`)
      callback(response.body)
    })
    .catch(error => {
      console.log(`error body json stringify ${JSON.stringify(error)}`)
      errorCallback(error)
    })
```

and looking at your code, what is `files.gallery` on `attach`?
could it be the problem?

**Comment by hichamon306** [comment]
Thank you very much for your help, the problem comes from react native debugger with network inspect enabled, since i disable it, the file upload work like a charm.

Thanks again @sidhijakpat

**Comment by sidhijakpat** [comment]
your welcome @hichamon306

**Comment by RodolfoGS** [comment]
> Once again, it was our mistake, the JSON Object should be:
> 
> ```
> const file = {
>   uri: fileUri,
>   name: 'image_name.png',
>   type: `image/png`
> }
> ```
> 
> Thank you again

Thank you, that works!

**Comment by kuangyanit** [comment]
from the doc about attach, the params are name, file(**either string with file path or Blob/Buffer object.**)  and options. I'm confused. Are there multi styles invoke attach method?

**Comment by RodolfoGS** [comment]
> from the doc about attach, the params are name, file(**either string with file path or Blob/Buffer object.**) and options. I'm confused. Are there multi styles invoke attach method?

I think that the doc is wrong. I tried with string to the file path and didn't work.

That object worked great for me.
```
.attach('image', {
  uri: '/path/to/image.jpg',
  name: 'filename.jpg',
  type: `image/jpg`,
})
```

**Comment by sidhijakpat** [comment]
> > Once again, it was our mistake, the JSON Object should be:
> > ```
> > const file = {
> >   uri: fileUri,
> >   name: 'image_name.png',
> >   type: `image/png`
> > }
> > ```
> > 
> > 
> > Thank you again
> 
> Thank you, that works!

Glad I can help

**Comment by kuangyanit** [comment]
can you tell me version number you used? @RodolfoGS

**Comment by RodolfoGS** [comment]
> can you tell me version number you used? @RodolfoGS

Sure, I'm using `superagent: 5.2.2` (the latest right now)

**Comment by kuangyanit** [comment]
there a error like "source.on is not a function" in my project with your way, my code seems like following:
````js
request
        .post(elimeiServiceUrl)
        .set('Connection', 'Keep-Alive')
        .set('Charset', 'UTF-8')
        .attach("1", { uri: uris[0], name: filenames[0], type: 'image/jpg' }, {contentType: 'jpg'})
````

**Comment by sidhijakpat** [comment]
> �there a error like "source.on is not a function" in my project with your way, my code seems like following:
> 
> ```js
> request
>         .post(url)
>         .set('Connection', 'Keep-Alive')
>         .set('Charset', 'UTF-8')
>         .attach("1", { uri: uris[0], name: filenames[0], type: 'image/jpg' }, {contentType: 'jpg'})
> ```

If I'm not mistaken, post and attach are not mean to be used together, 
let me search for that

**Comment by RodolfoGS** [comment]
> > �there a error like "source.on is not a function" in my project with your way, my code seems like following:
> > ```js
> > request
> >         .post(url)
> >         .set('Connection', 'Keep-Alive')
> >         .set('Charset', 'UTF-8')
> >         .attach("1", { uri: uris[0], name: filenames[0], type: 'image/jpg' }, {contentType: 'jpg'})
> > ```
> 
> If I'm not mistaken, post and attach are not mean to be used together,
> let me search for that

Yes, you can use .post and .attach together.
BUT, you can't use .send and .attach together.

> When you use .field() or .attach() you can't use .send() and you must not set Content-Type (the correct type will be set for you).

https://visionmedia.github.io/superagent/#multipart-requests

**Comment by kuangyanit** [comment]
Is it means there is a another problem in my projcet?

**Comment by AhmedRazaVerge** [comment]
![Capture](https://user-images.githubusercontent.com/64129958/89782704-3b1e2a80-db2f-11ea-8f26-e898c6f4f4c4.PNG)

i am getting this while trying to upload file i have full network access, i test uri it correct. does any one know is what is problem
