### ISSUE TITLE
Leaving for rustier pastures!

### ISSUE THREAD

**Issue by kornelski** [visionmedia/superagent#1450]
These days I'm programming mostly in [Rust](https://www.rust-lang.org/), and I'm migrating away from Node.mjs. I won't be using superagent any more, so it doesn't make sense for me to continue maintaining it.

Superagent is pretty stable and in an OK shape, so that's not end of the world for superagent. If you're a superagent user I recommend:

* keep it, if it works for you,
* or move to `fetch()`.

I'll be around to merge pull requests and make new releases once in a while, so contributions are still welcome. There's always some tech debt or quirk to remove, never-ending number of cookie edge cases to patch, etc. If you want to help, please do!

**Comment by niftylettuce** [comment]
Can you please add me as collaborator/NPM? cc @kornelski @tj

**Comment by kornelski** [comment]
I don't have admin rights, so @defunctzombie needs to do that.

**Comment by defunctzombie** [comment]
@niftylettuce What is your npm username?

**Comment by niftylettuce** [comment]
@defunctzombie it's "niftylettuce", thank you

**Comment by defunctzombie** [comment]
@niftylettuce I've added you as an owner on npm.

**Comment by kibertoad** [comment]
@kornelski @niftylettuce Do you still need additional collaborators or there's enough for now?

**Comment by sbusch** [comment]
Thanks, @kornelski
