### ISSUE TITLE
Release includes test code

### ISSUE THREAD

**Issue by smulesoft** [visionmedia/superagent#1455]
Hello @kornelski I wanted to ask you if it's possible to remove the test sources from your releases? Honestly it looks like an unnecessary clog that could easily be removed.

**Comment by kornelski** [comment]
Sure, make a PR.

**Comment by smulesoft** [comment]
My bad you are already doing that. I had a problem with transitive dependencies. Thanks for your answer anyway!

**Comment by niftylettuce** [comment]
@smulesoft I've added to `.npmignore` the `test` folder.  This will go out in the 5.0.0 major release soon.

**Comment by smulesoft** [comment]
Awesome, thanks for letting me know @niftylettuce
