### ISSUE TITLE
When API's response is a pure text, it will cause an error,Could you please help?

### ISSUE THREAD

**Issue by dylanzhang123456** [visionmedia/superagent#1457]
![image](https://user-images.githubusercontent.com/25168679/52056597-a2a00500-259d-11e9-9e34-3ed620ef80ca.png)

**Comment by dylanzhang123456** [comment]
I try to fix this issue for ./lib/node/parsers/json.js:
'use strict';

module.exports = function parseJSON(res, fn) {
    res.text = '';
    res.setEncoding('utf8');
    res.on('data', chunk => {
        res.text += chunk;
    });
    res.on('end', () => {
        try {
            var body
            try {
                body = res.text && JSON.parse(res.text);
            } catch (e) {
                body = res.text;
            }
        } catch (e) {
            var err = e;
            // issue #675: return the raw response if the response parsing fails
            err.rawResponse = res.text || null;
            // issue #876: return the http status code if the response parsing fails
            err.statusCode = res.statusCode;
        } finally {
            fn(err, body);
        }
    });
};

it works in my local test cases, but it's not ok in the your test, is it ok for my change? If so, Could you please help update your test?If not, Could you please help find another way?Thank you so much!
Here is the test result in your test:

https://travis-ci.org/visionmedia/superagent/builds/487220999?utm_source=github_status&utm_medium=notification

![image](https://user-images.githubusercontent.com/25168679/52096376-9b124780-2601-11e9-99f8-bbef074d6eea.png)

**Comment by niftylettuce** [comment]
PR welcome
