### ISSUE TITLE
cannot build via webpack with node target

### ISSUE THREAD

**Issue by iblis17** [visionmedia/superagent#1469]
Hi, I followed the wiki about webpack (https://github.com/visionmedia/superagent/wiki/Superagent-for-Webpack)
but it don't work.

Here is a MWE.
```javascript
% cat package.json 
{
  "name": "demo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "superagent": "^4.1.0"
  },
  "devDependencies": {
    "webpack": "^4.29.6"
  }
}
```
```javascript
% cat webpack.config.js 
const webpack = require('webpack');

module.exports = {
  target: 'node',
  entry: __dirname + '/index.js',
  output: {
    path: __dirname + '/build',
    filename: 'demo-node.js'
  },
}
```
```javascript
% cat index.js 
import superagent from 'superagent'
```

I got this failure:
```javascript
% node --version
v11.9.0
% node
> require('./build/demo-node')
Thrown:
TypeError: n is not a function
    at Object.<anonymous> (/usr/home/iblis/tmp/demo/demo/build/demo-node.js:7:9158)
    at i (/usr/home/iblis/tmp/demo/demo/build/demo-node.js:1:172)
    at Object.<anonymous> (/usr/home/iblis/tmp/demo/demo/build/demo-node.js:7:9041)
    at i (/usr/home/iblis/tmp/demo/demo/build/demo-node.js:1:172)
    at Object.<anonymous> (/usr/home/iblis/tmp/demo/demo/build/demo-node.js:1:4629)
    at i (/usr/home/iblis/tmp/demo/demo/build/demo-node.js:1:172)
    at Module.<anonymous> (/usr/home/iblis/tmp/demo/demo/build/demo-node.js:7:3119)
    at i (/usr/home/iblis/tmp/demo/demo/build/demo-node.js:1:172)
    at /usr/home/iblis/tmp/demo/demo/build/demo-node.js:1:964
> 
```

**Comment by niftylettuce** [comment]
Hello @iblis17 &ndash; v5.0.0 was just released to NPM and an updated README is now available here on GitHub (see <https://github.com/visionmedia/superagent#superagent>).

## What's new

* Browser version is now only 19KB (that's 60% in file size savings from v4.x which was 48KB)!
* Codebase refactored using `xo`, `prettier`, `remark`, and more
* Browser compatibility linting via `eslint-plugin-compat`
* Browserslist integration (current targets are `> 1%, last 2 versions, ie 9`)

## How to install

```sh
npm install superagent@latest
```

> Or if you're using yarn:

```sh
yarn add superagent@latest
```

## Polyfills

Please see the [Required Browser Features](https://github.com/visionmedia/superagent#required-browser-features) section in the README if you plan to support IE 9 and/or IE 10 and use `superagent`.
