### ISSUE TITLE
Why is the documentation so simplistic?

### ISSUE THREAD

**Issue by jackwener** [visionmedia/superagent#1472]
Setting header fields doc is useless

Are you sure this description is useful?

```
Setting header fields is simple, invoke .set() with a field name and value:

 request
   .get('/search')
   .set('API-Key', 'foobar')
   .set('Accept', 'application/json')
   .then(callback);
You may also pass an object to set several fields in a single call:

 request
   .get('/search')
   .set({ 'API-Key': 'foobar', Accept: 'application/json' })
   .then(callback);
```

**Comment by niftylettuce** [comment]
Hello @jackwener &ndash; v5.0.0 was just released to NPM and an updated README is now available here on GitHub (see <https://github.com/visionmedia/superagent#superagent>).

## What's new

* Browser version is now only 19KB (that's 60% in file size savings from v4.x which was 48KB)!
* Codebase refactored using `xo`, `prettier`, `remark`, and more
* Browser compatibility linting via `eslint-plugin-compat`
* Browserslist integration (current targets are `> 1%, last 2 versions, ie 9`)

## How to install

```sh
npm install superagent@latest
```

> Or if you're using yarn:

```sh
yarn add superagent@latest
```

## Polyfills

Please see the [Required Browser Features](https://github.com/visionmedia/superagent#required-browser-features) section in the README if you plan to support IE 9 and/or IE 10 and use `superagent`.
