### ISSUE TITLE
http2 module not found

### ISSUE THREAD

**Issue by AndreiEnache** [visionmedia/superagent#1474]
After updating from superagent@4.1.0 to 5.0.0 in create-react-app with typescript I'm running into an error:
```
./node_modules/superagent/lib/node/http2wrapper.js
Module not found: Can't resolve 'http2' in '{redacted}\node_modules\superagent\lib\node'
```

Downgrading back to 4.1.0 solves this problem

**Comment by rux** [comment]
I have seen exactly the same thing.  My preliminary research looks like it has something to do with create-react-app interfering with the http2 module, though it's a bit beyond my comprehension the reasons for doing this.  https://github.com/facebook/create-react-app/pull/5686 seems to reference the problem.

**Comment by fmal** [comment]
@AndreiEnache @rux @niftylettuce  i guess with 5.0.0 it's required to make alias in webpack config such as:

```js
resolve: {
  alias: {
    superagent: 'node_modules/superagent/lib/client' // or node_modules/superagent/dist/superagent.js
  }
}
```

i was hoping that there will would something like `dist/es` folder where sources transpiled by Babel  would be kept (as ES modules) and `package.json` could use `module` field to point to that folder, so it will be automatically picked by webpack. That's what you usually expect when bundling package from NPM.

**Comment by AndreiEnache** [comment]
You can't modify the webpack config unless you eject the CRA which I'd rather not do

**Comment by fmal** [comment]
@AndreiEnache maybe you could try `import superagent from 'superagent/dist/superagent` then? 😃

**Comment by AndreiEnache** [comment]
> @AndreiEnache maybe you could try `import superagent from 'superagent/dist/superagent` then? 😃

CRA handles linking correctly - I did try it just in case and it's still no go.

> I have seen exactly the same thing. My preliminary research looks like it has something to do with create-react-app interfering with the http2 module, though it's a bit beyond my comprehension the reasons for doing this. [facebook/create-react-app#5686](https://github.com/facebook/create-react-app/pull/5686) seems to reference the problem.

This seems to be it and it's unrelated to superagent so I'm guessing the issue can be closed.
Thank you

**Comment by AndreiEnache** [comment]
I managed to get a way with only a warning by surrounding the http2 require in a try-catch in `http2wrapper.js`
```
let http2 = {};
try {
  http2 = require('http2');
} catch (e) {
  console.log(e);
}
```
and by commenting
`if (global.GENTLY) require = GENTLY.hijack(require);`
from `formidable` in `incoming_form.js`, `file.js`, `querystring_parser.js` and `json_parser.js`
but I'm guessing a cleaner way is needed

**Comment by niftylettuce** [comment]
Your Node version needs to be at least v8.4.0, we recommend using at least v8.8.1.

The 'http2' is not supported until Node.js 8.4.0.

**Comment by AndreiEnache** [comment]
As I said in the OP, I'm running this in the browser (it's a react app bootstrapped by create-react-app)

**Comment by niftylettuce** [comment]
v5.0.1 is released and it has fixed this issue.  This package also works again without throwing this error in Node versions v6.4.0 to v8.x.

```sh
npm install superagent@latest
```

or with yarn:

```sh
yarn add superagent@latest
```

let me know if any further issues.  you should not need any workarounds.

**Comment by AndreiEnache** [comment]
Sadly v5.0.1 doesn't fix this issue as it is not related to node. To prove a point, I updated to 5.0.1 and I'm not getting the `This version of node is not supported` but rather keep getting `Module not found: Can't resolve 'http2' in ...`
Just to make sure that we're on the same page - I'm trying to run superagent in a browser, not on a server.
You should be able to see that it errors out here as well (albeit with no readable error message).
https://ww8xjq0qw7.codesandbox.io/
(5.0.1 isn't indexed yet by codesandbox but you can update the version easily by clicking the Dependencies -> Refresh icon near superagent)

**Comment by niftylettuce** [comment]
@AndreiEnache please try v5.0.2 (just released!) and get back to me - thank you for reporting.

We were missing a line in browser config in `package.json` that would have instructed webpack (in your case) to require the client-side version `./lib/client.js` as opposed to `./lib/node/index.js`.

See <https://github.com/visionmedia/superagent/commit/ccc7f564f6db79f150f029d850a01452bc07f7e3>

**Comment by niftylettuce** [comment]
I have also just unpublished v5.0.0 and v5.0.1 from NPM to prevent further headache.

**Comment by AndreiEnache** [comment]
It's fixed.

Thank you!
