### ISSUE TITLE
React Native - Unable to resolve module

### ISSUE THREAD

**Issue by igorkovalchuk** [visionmedia/superagent#1475]
I am trying to use the 'superagent' in the React Native (0.59.1) project, but it shows a number of similar errors 'Unable to resolve module'.

Modules are: url, stream, https. At least these modules.

I've tried to add 'url' and 'stream' manually with 'yarn add', but seems this is an incorrect way. 
Should it add dependencies automatically?
What am I doing wrong?

error: bundling failed: Error: Unable to resolve module `stream` from `AwesomeProject/node_modules/superagent/lib/node/index.js`: Module `stream` does not exist in the Haste module map

error: bundling failed: Error: Unable to resolve module `https` from `AwesomeProject/node_modules/superagent/lib/node/index.js`: Module `https` does not exist in the Haste module map

**Comment by niftylettuce** [comment]
Please use v5.0.2, I have fixed the issue already

**Comment by niftylettuce** [comment]
I have also just unpublished v5.0.0 and v5.0.1 from NPM to prevent further headache.

**Comment by igorkovalchuk** [comment]
Thank you! Now it installs v5.0.2 automatically and works!
