### ISSUE TITLE
how to avoid sending user-agent header?

### ISSUE THREAD

**Issue by oprogramador** [visionmedia/superagent#1479]
In [unirest](https://github.com/Kong/unirest-nodejs), when I don't specify `user-agent` header, it's just not sent. However `superagent` sends `node-superagent/5.0.2`.

`.set('user-agent', undefined)` fails with `TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "user-agent"`

`.set('user-agent', '')` sends `{ 'user-agent': '' }`

`.set('user-agent', null)` sends `{ 'user-agent': 'null' }`

**Comment by apoorv-mishra** [comment]
@niftylettuce Not familiar with codebase much, but after digging a bit, it seems like `user-agent` is set [here](https://github.com/visionmedia/superagent/blob/974ac02b6a79492e7a27e989aaa98e76af41364b/src/node/index.js#L161) and [here](https://github.com/visionmedia/superagent/blob/974ac02b6a79492e7a27e989aaa98e76af41364b/src/node/index.js#L542)(for redirects). Do you suggest we remove those calls to resolve this issue?

**Comment by niftylettuce** [comment]
Yes, I am completely OK with removing the user-agent added altogether.

Please submit a PR

**Comment by falkenhawk** [comment]
`.unset('User-Agent')` would have worked

**Comment by natanavra** [comment]
This should be in the docs so users know they must explicitly set a User Agent as some CDNs block requests without it
