### ISSUE TITLE
Node retries not compatible with timeouts

### ISSUE THREAD

**Issue by petergphillips** [visionmedia/superagent#1487]
I'm looking at integrating superagent to make a server side call to a flaky backend API.  The API either responds quickly or doesn't respond at all and needs to therefore be retried.

I'm therefore using `retry(3)` in combination with `timeout({ deadline: 3000 })`.  However the timeout is overruling the retry and throwing an `Aborted` error which returns a 500 error to the client. From what I can tell the following is happening when the request takes too long:

1. Superagent makes a get request to backend API
1. `GET` request times out so emits an `abort`
1. `abort` handler then `reject`s the request
1. Retry logic kicks in and decides that we should retry
1. `Aborted` error then causes 500 error to client
1. Backend API is then retried
1. If API call fails then is retried twice more otherwise finishes

Looking at the code the retry logic attempts to reset the `_aborted` and `timedout` properties, but it looks like by then it is too late as `reject` is called.

Is there a way I can therefore retry when the API call times out?

**Comment by petergphillips** [comment]
I've investigated a bit further and it turns out that the timeout functionality is not compatible with using the promise version of superagent i.e. using `then`.  When using `end` and wrapping the superagent call in a manual promise instead then it all works as expected and the request is retried after it times out.

**Comment by pushplay** [comment]
I found the same problem in version 5.0.5.  Using `.timeout()` with `.retry()` worked in version 3.8.3.

**Comment by djmitche** [comment]
The issue here is that when a timeout occurs, superagent calls `req.abort()`, which emits an `aborted` message, which is handled by rejecting the promise with `err.code == ABORTED`.  Only then does it try to reject with a timeout error -- but the promise has already rejected so that second error is silently ignored.

**Comment by djmitche** [comment]
To reproduce:

```js
const request = require('superagent');

const main = async () => {
  const req = request('http://localhost:8000');
  req.timeout(1000);
  await req.catch(err => {
    if (err.timeout) {
      console.log('got timeout');
    }
    throw err;
  });
};

main().then(console.log, console.log);
```
and in another terminal, run a server that will not reply.  Netcat will do:
```shell
nc -klp 8000
```

**Comment by niftylettuce** [comment]
v5.3.0 published to npm and GitHub releases page with changelog
