### ISSUE TITLE
Documention on Query

### ISSUE THREAD

**Issue by ZehuaZhang** [visionmedia/superagent#1489]
I've read the documentation, could I get clearer understanding on query strings, maybe should we update the documentation to a more certainty?

I was looking at _JSON / Urlencoded_ in documentation below
https://visionmedia.github.io/superagent/#response-properties

```
request
   .get(url)
   .query(input1)
   .query(input2)
```
```
input1: 
{  
 menu: "[1, 2 ,3]" // string
}
```

input2:
```
{
  meun: [1 , 2 ,3] // array
}
```

input3:
```
{
  menu: "1,2,3" // string
}
```

What would be the query string output appended on GET request url, for each input listed above?

**Comment by niftylettuce** [comment]
PR welcome

**Comment by ZehuaZhang** [comment]
Could you clear the doubt above whether those three produce the same query string to append in request url?
