### ISSUE TITLE
(0 , _typeof4.default) is not a function

### ISSUE THREAD

**Issue by markusramsak** [visionmedia/superagent#1494]
Version: 5.0.7 (5.0.6 works fine)

I get the error (0 , _typeof4.default) is not a function
when calling
`superagent.get('/any-url').type('json');`

If I skip the method call type('json') no error occurs.

**Comment by niftylettuce** [comment]
I see what the issue is, and I unpublished v5.0.7.

**Comment by niftylettuce** [comment]
v5.0.8 is released and should resolve this issue
