### ISSUE TITLE
Please update HISTORY for version 5!

### ISSUE THREAD

**Issue by mikemaccana** [visionmedia/superagent#1498]
https://github.com/visionmedia/superagent/blob/master/HISTORY.md goes up to 4.x and stops. Would love to see what's changed!

**Comment by niftylettuce** [comment]
I am now using Releases tab of GitHub

https://github.com/visionmedia/superagent/releases

**Comment by niftylettuce** [comment]
I was hoping to get admin by @tj on this repo so I can fix the GH-pages

**Comment by mikemaccana** [comment]
Fair enough. Can you merge the PR above?

**Comment by niftylettuce** [comment]
done!! thank you again!!!!!!
