### ISSUE TITLE
How to specify port?

### ISSUE THREAD

**Issue by Jeff-Tian** [visionmedia/superagent#1519]
Hello, if I need to specify a port during testing, how can I make it? I didn't see it on document.

something like the following:
```
request.get('/xxx/yyy', {
  port: 7001
})
```

I checked https://github.com/visionmedia/superagent/issues/1144, learned that superagent didn't handle how to choose a available port. But is it possible to let superagent use a port that manually set?

Thanks

**Comment by keverw** [comment]
You should be able to if you use it with a hostname. So for example localhost would use: `localhost:7001/xxx/yyy `

**Comment by Jeff-Tian** [comment]
> You should be able to if you use it with a hostname. So for example localhost would use: `localhost:7001/xxx/yyy `

@keverw , Thanks for replying. Will try it next time I come to this case.
