### ISSUE TITLE
json parser buffer pipe requests

### ISSUE THREAD

**Issue by danzajdband** [visionmedia/superagent#152]
I'm using superagent for https://github.com/danzajdband/Tuiter

When using a stream method (like tuiter#sample) I'm using the superagent pipe method. Because the response content-type is json (I think that's the reason) the request object is buffering the stream inside res.text.

This is critical for my lib because this buffer is increasing apps memory usage in ~ 1.5MB / sec.

Do you think that's the reason? Is a Superagent issue or am I doing something wrong?

**Comment by defunctzombie** [comment]
Closing this old issue. If something similar comes up we can revisit. The pipe logic is less than ideal at the moment anyway.
