### ISSUE TITLE
The combination of retry () and timeout () is invalid

### ISSUE THREAD

**Issue by izhouteng** [visionmedia/superagent#1541]
![code](https://user-images.githubusercontent.com/32240838/75437453-2b4fc700-5991-11ea-93f5-285ae1a9e4d3.png)

After the first request timed out, although 5 retries were set, it will actually only be retried once.

And I found that there is no timeout () restriction when retrying.

Because timeout () is invalid during retry, although the result is obtained after retrying, catch () is still called, and the prompt triggers a double callback BUG.

My mother tongue is not English, here is the original:

第一次请求超时后，尽管设置了5次重试，实际上只会重试一次。

并且我发现，重试时不受timeout()限制。

由于重试时timeout()无效，尽管重试得到了结果，但还是调用了catch()，并且提示触发了双重回调BUG。

**Comment by niftylettuce** [comment]
v5.3.0 published to npm and GitHub releases page with changelog
