### ISSUE TITLE
Content-type  case sensitivity

### ISSUE THREAD

**Issue by lijjhaha** [visionmedia/superagent#1572]
Some website resonding with the "content-type" which is not normalized, such as "Text/HTML"。

As expected, the text content should be parsed by the "text parser"，but "Text"  can't be recognized, so，none of parser is called.

Should add a line of code, as below( node/index.js) :
    var max = _this4._maxRedirects;
    var mime = utils.type(res.headers['content-type'] || '') || 'text/plain';
    var type = mime.split('/')[0];
    **if (type) type = type.toLowerCase();**

**Comment by niftylettuce** [comment]
This will go out in the v6.0.0 release later today.
