### ISSUE TITLE
this._unset is undefined in the browser

### ISSUE THREAD

**Issue by don-smith** [visionmedia/superagent#1573]
I haven't chased this down completely, but I don't think https://github.com/visionmedia/superagent/blob/master/src/node/index.js#L134 is being invoked in the browser, such as in a webpack bundle. Which means `_unset` is not defined before https://github.com/visionmedia/superagent/blob/master/src/request-base.js#L367 is called, which is where I'm seeing this error happen. This line was added a couple of hours ago as part of version `5.3.0`.

**Comment by don-smith** [comment]
@dobesv and @niftylettuce I think this is going to affect anyone setting headers in the browser.

**Comment by niftylettuce** [comment]
I deprecated v5.3.0 in the interim.  Let me rollback that commit and publish new.

**Comment by niftylettuce** [comment]
v5.3.1 published with the fix, in the interim I deprecated v5.3.0 in npm and also commented on #1560 about this

https://github.com/visionmedia/superagent/releases/tag/v5.3.1
