### ISSUE TITLE
.attach() sends nothing in node 14

### ISSUE THREAD

**Issue by puzrin** [visionmedia/superagent#1577]
```js
    let res = await superagent
      .post('/')
      .field('url', 'http://example.com')
      .attach('config', path.join(__dirname, 'fixtures', 'config_custom.json'))
      .set('Accept', 'application/json');
```

This code works in node 10 & 12 as expected, but sends request without atachment in node 14.

Could you fix or suggest workaround?

**Comment by puzrin** [comment]
Ref https://github.com/form-data/form-data/issues/476

Seems problem in `form-data`.

**Comment by niftylettuce** [comment]
There's also this TODO https://github.com/visionmedia/superagent/blob/44fadf94e0b0a84276faeacc956eca7eb4d40abf/src/node/index.js#L1226 that is somewhat related.

**Comment by puzrin** [comment]
Not sure. That mode is when size can not be detected an not actually needed too much.

IMO problem is caused by multiple breaking changes in stream api. Reading "History" notes under headers shows many interesting things. For example, `autoDestroy` => `true`, `emitClose` => `true`.

https://github.com/pillarjs/multiparty/commit/6afaf7aa02121d7542cc1d9f7b42a563d215e521#diff-168726dbe96b3ce427e7fedce31bb0bcR53 multiparty fixed bug with node v14, but i can't understand why this helps.

**Comment by puzrin** [comment]
Seems node 14 fixed at some moment. Not a problem anymore.
