### ISSUE TITLE
How to make superagent receive cookies from the server?

### ISSUE THREAD

**Issue by nspeedzy** [visionmedia/superagent#1579]
Hello! So I want to know how to receive cookies from the server using superagent. Here is how the code on my server looks like:
```js
var router = require('express').Router();
// Please note: I am using express
router.post('/', function(req, res) {
    res.cookie('uname', req.body.key).send("Cookies are set!");
});
//
module.exports = router;
```
And here is how the code looks on the client-side:
```js
superagent.post('http://localhost:5000/')
   .send({ key: "fragile", cat: "billy" })
   .set('accept', 'json')
   .end(function(err, res) {
        if (err) { console.error(err); }
        else { console.log(res); }
   });
```
I know that whenever a cookie gets set, a `set-cookie` header pops up. I even tried cross-referencing [this stackoverflow question](https://stackoverflow.com/questions/11919737/how-can-you-use-cookies-with-superagent) and #597 but it didn't help. Is there any way to make superagent receive cookies?

**Comment by nspeedzy** [comment]
Looks like no one wants to respond!

**Comment by sannajammeh** [comment]
Cookies are already set for you when you make the request, as long as you on the server set the cookie on the response object.

To retrieve the cookie you can simply use js-cookie or any other library.
Js-cookie implementation.

```javascript
   import Cookies from "js-cookie";

  // .... other code

  // Make request
  const response = await superagent.get(url).withCredentials();
  //
  console.log(Cookies.get("COOKIE_ID"));
```
