### ISSUE TITLE
Documentation is broken

### ISSUE THREAD

**Issue by adam-arold** [visionmedia/superagent#1587]
I'm looking at [this page](https://visionmedia.github.io/superagent/#preserving-cookies) and I can't find what to import in order to get the `request` object that is often used in the code examples.

I figured that I can do this: `import { superagent as request } from "superagent";` but the `agent()` method is missing. In its current from one can't determine from the documentation how to use the `agent()` in order to enable cookies.

**Comment by niftylettuce** [comment]
You figure it out I take it?

**Comment by adam-arold** [comment]
It would be great if the docs would include the imports, but I figured out that I was importing the wrong object.

**Comment by niftylettuce** [comment]
PR welcome

**Comment by adam-arold** [comment]
I don't really have the time now, sadly.

**Comment by niftylettuce** [comment]
okay.
