### ISSUE TITLE
formidable warnings when used with webpack

### ISSUE THREAD

**Issue by byungjuJin** [visionmedia/superagent#1609]
in dependencies, superagent use "formidable": "^1.2.2"
And this have a issue with webpack.
For fix it, update need to formidable V2.
It still on canary version but owner recommend use it.
Please check below issue.

[https://github.com/node-formidable/formidable/issues/337](https://github.com/node-formidable/formidable/issues/337)

Warning: ./node_modules/superagent/node_modules/formidable/lib/incoming_form.js 1:43-50
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
    at CommonJsRequireContextDependency.getWarnings ()
 @ ./node_modules/superagent/node_modules/formidable/lib/index.js
 @ ./node_modules/superagent/lib/node/index.js

**Comment by mccart** [comment]
formidable v1 now depreciated and v2 supposed to be backward compatible to v1

**Comment by vicb** [comment]
Hey @niftylettuce is this fixed in 7.0.1 ? I see that formidable is now at v2.

If not is there anything I can help with ?

**Comment by niftylettuce** [comment]
Yeah it's fixed, thank you!
