### ISSUE TITLE
Invalid description URL

### ISSUE THREAD

**Issue by dgmike** [visionmedia/superagent#1647]
Above the "About" area in github exists a link to superagent documentation/website. But it is an old github pages address.

![image](https://user-images.githubusercontent.com/94767/139477263-3bd97160-66a0-4c0d-88c7-586e81b6462e.png)

The right link must be https://visionmedia.github.io/superagent/

**Comment by adiatma85** [comment]
I hope they fix it soon. It's really minor, but some of us really bugged for that
Another same issue at:
- #1624 
- #1622 
- #1632

**Comment by slaveofcode** [comment]
any update on this? today got the wrong URL too
but since I am aware of the domain, this could be ridiculous for a new guy
