### ISSUE TITLE
add opt-in global error-handling (by default)

### ISSUE THREAD

**Issue by tj** [visionmedia/superagent#165]
this gets redundant on the client:

``` js
  request
  .get('/querystring')
  .query('search=Manny')
  .query({ order: 'desc', range: '1..5' })
  .end(function(res){
    if (res.error) return something(res.error)
  });
```

ideally you opt in with something similar to:

``` js
request.on('error', function(err){

});
```

though this would be a bit of a hack since we have no `.error(fn)` to opt-into http errors in the first place. Arguably global handling is an anti-pattern but worth thinking about

**Comment by Arsenalist** [comment]
This really needs to be part of the library.  It satisfies too many use cases not to.

**Comment by jacamat** [comment]
Agreed.

**Comment by liubko** [comment]
Could someone share a workaround?

**Comment by xpepermint** [comment]
Status?

**Comment by syropian** [comment]
Anyone have a solution for this?

**Comment by mikestopcontinues** [comment]
Important.

**Comment by apsavin** [comment]
Example of quick and dirty workaround:

```js
const end = superagent.Request.prototype.end;
superagent.Request.prototype.end = function (callback) {
  return end.call(this, (error, response) => {
    if (response.unauthorized) {
      // handle the error here, for example:
      // window.location = '/login'
    } else {
      callback(error, response);
    }
  });
};
```

**Comment by focusaurus** [comment]
Can anyone interested confirm whether or not https://github.com/camshaft/superagent-defaults allows a default `.end` callback and whether that facilitates any of these use cases? I think in general we are pointing to superagent-default for global stuff, but will still consider things here if a compelling case can be made.

@apsavin thank you for the workaround snippet.

**Comment by boucher** [comment]
I believe `.end` is not supported by superagent-defaults.
