### ISSUE TITLE
Formidable@1 is deprecated

### ISSUE THREAD

**Issue by wopian** [visionmedia/superagent#1650]
Looks like v1 of formidable was marked as deprecated by the owner a few weeks ago, with the following message logged during install/upgrades:

> npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau

Changelog: https://github.com/node-formidable/formidable/blob/master/CHANGELOG.md

Checking the changelog, v2 deprecated `new formidable.IncomingForm()`, being replaced by `new Formidable()`

Upgrading to v2 or v3 will also fix the static analysis warnings from Webpack and similar tools as in #1609

**Comment by niftylettuce** [comment]
Pr welcome 🙏
