### ISSUE TITLE
npm package formidable is deprecated. Need to upgrade

### ISSUE THREAD

**Issue by rosenfl** [visionmedia/superagent#1655]
This is the warning I got.

npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau

From package-lock.json:

    "superagent": {
      "version": "6.1.0",
      "dev": true,
      "requires": {
        "component-emitter": "^1.3.0",
        "cookiejar": "^2.1.2",
        "debug": "^4.1.1",
        "fast-safe-stringify": "^2.0.7",
        "form-data": "^3.0.0",
        **"formidable": "^1.2.2",**
        "methods": "^1.1.2",
        "mime": "^2.4.6",
        "qs": "^6.9.4",
        "readable-stream": "^3.6.0",
        "semver": "^7.3.2"
      },

**Comment by WikiRik** [comment]
superagent was updated to formidable@v2 in https://github.com/visionmedia/superagent/pull/1651 but due to a broken test no new release is made yet.

**Comment by niftylettuce** [comment]
Fixed

**Comment by niftylettuce** [comment]
v7.0.1+
