### ISSUE TITLE
Engine syntax incorrect

### ISSUE THREAD

**Issue by ungrim97** [visionmedia/superagent#1660]
I cannot install the latest v7 on node 16 at the moment. NPM is complaining about incompatible version:

```
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: superagent@7.0.0
npm ERR! notsup Not compatible with your version of node/npm: superagent@7.0.0
npm ERR! notsup Required: {"node":">=6.4.0 <13|>=14"}
npm ERR! notsup Actual:   {"npm":"8.3.0","node":"v16.13.0"}
```

I believe the issue is the syntax used in the engines block in the package.json

I think instead of:
```
  "engines": {
    "node": ">=6.4.0 <13|>=14"
  },
```
it should be:
```
  "engines": {
    "node": ">=6.4.0 <13||>=14"
  },
``` (double pipe instead of single)

**Comment by ungrim97** [comment]
[#1661 ](https://github.com/visionmedia/superagent/pull/1661)

**Comment by niftylettuce** [comment]
v7.0.1 released https://github.com/visionmedia/superagent/releases/tag/v7.0.1

**Comment by nbezzala** [comment]
This is still an issue. 

$ npm install superagent
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'superagent@7.0.1',
npm WARN EBADENGINE   required: { node: '>=6.4.0 !13' },
npm WARN EBADENGINE   current: { node: 'v17.3.0', npm: '8.3.0' }
npm WARN EBADENGINE }

up to date, audited 38 packages in 2s

9 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by niftylettuce** [comment]
What might be a valid fix? Not too experienced with engines property.

**Comment by ungrim97** [comment]
Looking at the Semver spec I don't think there actually is a `not equals` operator available.

It looks like the correct solution is the one I original gave or the symantically equivelent PR by @nbezzala above. Both of which might cause you Eslint issues.

On the plus side it looks like the reported error is a warning only and it is still installing the module

**Comment by ungrim97** [comment]
Also running Eslint seems to suggest that the earliest supported node that will work is `v10.10.0` (Catch binding and http2 support).

Removing the catch binding would lower the supported Nodejs to v8.13.0 as http2 was backported

**Comment by textbook** [comment]
You want e.g. `>=6.4.0 <13 || >=14`, you can try these out on https://semver.npmjs.com/

**Comment by jcurlier** [comment]
+1

**Comment by niftylettuce** [comment]
v7.0.2 released https://github.com/visionmedia/superagent/releases/tag/v7.0.2

I had to publish with `np --no-tests` because of `yarn test` lint errors with `eslint` not parsing `engines` properly per <https://github.com/mysticatea/eslint-plugin-node/issues/315>.
