### ISSUE TITLE
Unable to install 7.0.1 version on 16.12.0 Node

### ISSUE THREAD

**Issue by brainroma** [visionmedia/superagent#1665]
Still getting the error when trying to install 7.0.1 version on v16 Node

npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: superagent@7.0.1
npm ERR! notsup Not compatible with your version of node/npm: superagent@7.0.1
npm ERR! notsup Required: {"node":">=6.4.0 !13"}
npm ERR! notsup Actual:   {"npm":"8.3.0","node":"v16.12.0"}

**Comment by korbav** [comment]
https://github.com/visionmedia/supertest/issues/752#issuecomment-1009854158

Please replace `>=6.4.0 !13` by `6.4.0 - 12 || >= 14`

**Comment by SergioSuarezDev** [comment]
same here

`
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: superagent@7.0.1
npm ERR! notsup Not compatible with your version of node/npm: superagent@7.0.1
npm ERR! notsup Required: {"node":">=6.4.0 !13"}
npm ERR! notsup Actual:   {"npm":"8.3.0","node":"v14.18.1"}
`

My node v: v14.18.1
My npm  v: 8.3.0

**Comment by visoft** [comment]
No error, but a warning

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'superagent@7.0.1',
npm WARN EBADENGINE   required: { node: '>=6.4.0 !13' },
npm WARN EBADENGINE   current: { node: 'v16.13.1', npm: '8.1.2' }
npm WARN EBADENGINE }
```

**Comment by ekmobile** [comment]
For me it's an error:

npm i --save-dev supertest

npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for superagent@7.0.1: wanted: {"node":">=6.4.0 !13"} (current: {"node":"14.18.2","npm":"6.14.15"})
npm ERR! notsup Not compatible with your version of node/npm: superagent@7.0.1
npm ERR! notsup Not compatible with your version of node/npm: superagent@7.0.1
npm ERR! notsup Required: {"node":">=6.4.0 !13"}
npm ERR! notsup Actual:   {"npm":"6.14.15","node":"14.18.2"}

**Comment by SergioSuarezDev** [comment]
In my case the error comes from the **nestjs** framework that uses superset 
https://github.com/nestjs/nest/blob/master/package.json

**Comment by glasser** [comment]
I've filed https://github.com/visionmedia/superagent/pull/1666 to fix this issue.  (It is more correct than #1663 which fails to exclude v13.)

**Comment by niftylettuce** [comment]
v7.0.2 released https://github.com/visionmedia/superagent/releases/tag/v7.0.2

I had to publish with `np --no-tests` because of `yarn test` lint errors with `eslint` not parsing `engines` properly per <https://github.com/mysticatea/eslint-plugin-node/issues/315>.
