### ISSUE TITLE
timeouts

### ISSUE THREAD

**Issue by tj** [visionmedia/superagent#17]

**Comment by OlgaKozlova** [comment]
And what is default timeout for requesr? Can't find this info!

**Comment by jazoom** [comment]
I also can't find it. I want to create a longer timeout for a particular request.

**Comment by pornel** [comment]
By default there is no timeout (superagent will wait for the response forever). You set timeout with `.timeout` method, e.g. to wait up to 5 seconds: `request.post('/foo').timeout(5000).end()`;

**Comment by jazoom** [comment]
Okay, thanks. That's good to know.
