### ISSUE TITLE
Is superagent deprecated?

### ISSUE THREAD

**Issue by beenotung** [visionmedia/superagent#1719]
It is no longer searchable on npmjs.com, and it shows deprecated message:
> Deprecated due to bug in CI build https://github.com/visionmedia/superagent/pull/1677\#issuecomment-1081361876

Is the deprecated message auto generated accidentally, or is it really deprecated?

**Comment by tsdamas** [comment]
I am also interested to know if it deprecated. 

Following this thread.

**Comment by titanism** [comment]
No, just that one version was deprecated.

v7.1.3 released https://github.com/visionmedia/superagent/releases/tag/v7.1.3

Should fix the deprecation warnings

Any issues please ping
