### ISSUE TITLE
Notice regarding the move from @visionmedia org to @ladjs org

### ISSUE THREAD

**Issue by titanism** [visionmedia/superagent#1755]
👋 Hello as maintainers of superagent for the past few years - we have moved the repo from @visionmedia org to @ladjs org so that our team can maintain it.  We of course are retaining original authorship, license, and commit history.  This was mainly done after we unexpectedly had integrations removed by someone else with access to the @visionmedia organization that did not contribute to superagent.  For security reasons as well, we want to make sure we have as few single points of failure as possible.  Thanks!

**Comment by MR4online** [comment]
I was looking for the (old) docs page, which isnt working anymore.
As a work a round I use web-archive:
[https://web.archive.org/web/20220614150754/https://visionmedia.github.io/superagent/](url)

**Comment by ltxhhz** [comment]
Does anyone know what happened to @niftylettuce? He's one of the contributors to this library, but it's been a long time since I've seen him active on GitHub.
