### ISSUE TITLE
Follow redirections when piping

### ISSUE THREAD

**Issue by buschtoens** [visionmedia/superagent#178]
```javascript
var request = require('superagent')
  , fs = require('fs');

var stream = fs.createWriteStream('/apparently/not/the/redirected.file');
var req = request.get('/I/will/redirect');
req.pipe(stream);
```

When the requested resource performs a redirect, the response stream (`req.pipe`) is empty and nothing is written to `stream`.

**Comment by rase-** [comment]
Looks like it was addressed recently: https://github.com/visionmedia/superagent/pull/558

cc @defunctzombie

**Comment by thanpolas** [comment]
mmm indeed, this looks promising
