### ISSUE TITLE
pass (err) for {4,5}xx

### ISSUE THREAD

**Issue by tj** [visionmedia/superagent#180]
need to think on this a little but we should be fine to pass an Error _and_ the response. This will allow you to differentiate between network errors and request errors as desired, pretty much the same functionality as before but a bit less redundancy for handling some use-cases

**Comment by defunctzombie** [comment]
Yes, I will be doing this in the new error handling refactoring. I have already removed arity, this is the next piece. Basically, anything that is not 2xx will be an error and response object will also be provided.
