### ISSUE TITLE
headers missing on firefox

### ISSUE THREAD

**Issue by andrewrk** [visionmedia/superagent#181]
This causes `resp.body` to be `null` for json responses which is pretty catastrophic.

I've tried every version down to 0.9.8 and they all have the same issue. 0.9.8 actually throws an error instead of having a response which is incorrect because the status is 200 and the text is valid json.

**Comment by alinz** [comment]
OK, it seems this bug returns when I use it with `react-native` 0.6 and above. What I found that `xhr.getResponseHeader('content-type')` starts to return null which isn't right. 

Calling to `this.xhr.getAllResponseHeaders()` returns the correct sets of headers which also includes `content-type`. 

So here's my humble solution:

```js
var tryAnotherContentType = this.xhr.getResponseHeader('content-type');
if (tryAnotherContentType && tryAnotherContentType.length > 0) {
    this.header['content-type'] = tryAnotherContentType;
}
```
