### ISSUE TITLE
http cache support

### ISSUE THREAD

**Issue by tj** [visionmedia/superagent#184]
for node client

**Comment by jpodwys** [comment]
I know this is old, but I recently published a superagent extension that adds transparent caching. You can see it here: https://github.com/jpodwys/superagent-cache.

**Comment by martnst** [comment]
https://github.com/jpodwys/superagent-cache does not care about HTTP Caching but caches by it's own rules.

**Comment by jpodwys** [comment]
That's true. I'm happy to look into opening up a plug-in architecture so others can add that functionality without forcing it upon everyone. There is also a fork of superagent-cache-plugin that adds http cache support. You can find the fork here: https://github.com/finanzcheck/superagent-cache-plugin/tree/feature/CORE-440-respect_response_cache_headers

**Comment by martnst** [comment]
@jpodwys thanks a lot for sharing this 👍

**Comment by igorsantos07** [comment]
I just wanted to let it written somewhere on the Internet how there's a lot of custom caching solutions for JS HTTP requests out there, instead of following actual standards like... HTTP Caching headers. I'm using Axios and found nothing that could reliably and simply respond to the ETag standard. Checked "rival tech" and all I find is a fork of another custom-cache...

Any sense of reinventing this wheel?

**Comment by jpodwys** [comment]
HI @igorsantos07! I'm the author of one of the two libraries you mentioned.

[`superagent-cache-plugin`](https://github.com/jpodwys/superagent-cache-plugin) V3 (currently available as a [beta release](https://github.com/jpodwys/superagent-cache-plugin/releases/tag/3.0.0-beta.1)) uses the excellent [`http-cache-semantics`](https://github.com/kornelski/http-cache-semantics) written by @kornelski who is a `superagent` maintainer.

You might have a look at the the V3 release and see if it meets your needs.

**Comment by jpodwys** [comment]
@igorsantos07 I, too, think first-party HTTP cache support would be great! However, I'm curious if you're putting too much emphasis on how many stars a repo has. I think it's more meaningful to look at how many times a library is being downloaded. You can see `superagent-cache-plugin`'s download history [here](https://npm-stat.com/charts.html?package=superagent-cache-plugin). 

Another interesting thing to consider is who is using a library. You can find that info [here](https://github.com/jpodwys/superagent-cache-plugin/network/dependents?package_id=UGFja2FnZS0xNDg2OTc3NA%3D%3D).
