### ISSUE TITLE
No way to set rejectUnauthorized option of underlying node https request

### ISSUE THREAD

**Issue by georgesnelling** [visionmedia/superagent#205]
TJ, for https requests, node core changed the default value of the https.request option rejectUnauthorized from false to true. 

8.22:  http://nodejs.org/docs/v0.8.22/api/https.html#https_https_request_options_callback

10.4:  http://nodejs.org/docs/v0.10.4/api/https.html#https_https_request_options_callback

This means that if a node 0.8.x client sends an https request to a server with a self-signed certificate it will succeed.  A  node 0.10.x client sending the same request to the same server will fail with Error: DEPTH_ZERO_SELF_SIGNED_CERT.  

While I agree with the change in default, we need to be able to set this bit, (similar to curl's --insecure option) in our request lib in order for our tests to hit https servers using self-signed certs.  Mikeal's request lib exposes a strictSSL option which maps to the underlying node option, but I can't find a way to twiddle that bit from superagent.   

I hate to clutter superagent's clean api, but perhaps an .options({}) method, passed through to node's request constructor, could give those who cared full access to all the underlying knobs.  There's probably a cleaner way... 

Thanks.

**Comment by devangpaliwal** [comment]
process.env.NODE_TLS_REJECT_UNAUTHORIZED = 0; Worked!!

**Comment by mikemaccana** [comment]
Is it currently possible to pass `rejectUnauthorized` in options? Reading some of the linked comments suggests it is, but there's nothing mentioned in the documentation and it doesn't seem to work when I try.
For my own use case  `process.env.NODE_TLS_REJECT_UNAUTHORIZED = 0;` is dangerous.

**Comment by pornel** [comment]
We don't have a solution to this yet. 

* The general idea is to have `.tls()` method with TLS-related options, but the current pull requests simply allow setting of *any* agent option, and I'm not comfortable with having an "anything goes" unlimited API.

* `rejectUnauthorized` is not scary enough. It should be `THIS_IS_TOTALLY_INSECURE_AND_WILL_EAT_BABIES = true` or such.

**Comment by mikemaccana** [comment]
Thanks for the quick answer. Good point, node itself doesn't name the option very well, I've asked what people think about renaming it: https://github.com/nodejs/node/issues/5258  

In my case (I want to check an existing TLS setup so I can recommend how to fix it) I ended up just checking for `err.code === 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'` which was sufficient for my needs.

**Comment by harshithjv** [comment]
@devangpaliwal @mikemaccana 

I am not able to make make it work by setting `process.env.NODE_TLS_REJECT_UNAUTHORIZED = 0;`. Where should I set it?

**Comment by pornel** [comment]
Please never use `NODE_TLS_REJECT_UNAUTHORIZED` for anything, ever. It's a dangerous option that ruins security of all requests made by node.

Please either get a free certificate from Letsencrypt, or create your own certificate and CA.

**Comment by andig** [comment]
I'm back with this problem. I've got self-signed certificates working when doing `GET` requests. I'm stuck however with `POST` requests. All available options have already been set:

**request**

    { url: 'https://.../data.lua',
      rejectUnauthorized: false,
      strictSSL: false,
      method: 'POST',
      form:
       { sid: 'xxx',
         xhr: 1,
         no_sidrenew: '',
         device: '17',
         oldpage: '/net/home_auto_hkr_edit.lua',
         back_to_page: '/net/network.lua' } }

**process.env**

    { ...
      NODE_TLS_REJECT_UNAUTHORIZED: '0' }

Any idea what might be wrong here?
