### ISSUE TITLE
OPTIONS always sent

### ISSUE THREAD

**Issue by contra** [visionmedia/superagent#210]
I'm having some weird behavior. When I use an XMLHTTPRequest against the soundcloud API all works fine. When I use superagent, it sends an OPTIONS (the XMLHTTPRequest doesn't do this) to the API which responds with nothing causing the request to fail.

Very very strange. I've tested this using jQuery's ajax stuff and it works fine there too.

**Comment by rase-** [comment]
Perhaps related to https://github.com/visionmedia/superagent/pull/567

@contra could you try with latest master and see if that helps?

**Comment by jnak** [comment]
FYI, I still get weird behavior with the soundcloud api. The same request will sometimes fail for no reason. I don't think it does send an OPTIONS request though (at least request.method is 'GET'). 

@contra did you find what the issue was? Though I realize it was a long time ago ;)

**Comment by pornel** [comment]
The issue fixed previously was that `progress` event handler forces options request.

Browsers will also force options request if you set custom headers.

**Comment by jnak** [comment]
This is happening when running in node 4.2.1

**Comment by pornel** [comment]
That is very surprising. Can you share code to reproduce this problem?
