### ISSUE TITLE
expose xml as res.body

### ISSUE THREAD

**Issue by tj** [visionmedia/superagent#215]
never thought I'd say this, but for amazon shit it's necessary

**Comment by stephy** [comment]
I was able to use the solution from @laurilarjo, so Thanks!
For those who want to use that solution as well, there's a little typo in his code. Don't forget the error comes first in the callback function on end.
```
var request = superagent.get(url);
request.buffer();
request.type('xml');
request.end(function(err, res) {    
    console.log(res.text);
});
```

or better yet,
```
const request = superagent.get(url)
 .buffer()
 .type('xml')
 .end((err, res) => {    
    console.log(res.text);
});
```

**Comment by susumuasaga** [comment]
I also was able to use solution from @laurilarjo, thx!
The key point is enable buffering with .buffer(), the .type() refers to the request body and useless if you are only interested on the response body:
`
superagent.get(url).buffer().end((err, res) => console.log(res.text);
`

**Comment by AdamT213** [comment]
@susumuasaga, your solution worked for me!
