### ISSUE TITLE
window.btoa not available in older browsers

### ISSUE THREAD

**Issue by btknorr** [visionmedia/superagent#220]
Currently in the client when you call auth it uses btoa which is a global window function, and I assume this would be something the component framework would frown upon.  Maybe we should refactor this to use an independent base64 encoding component instead.

**Comment by rexxars** [comment]
@defunctzombie Since you added IE9 to the test matrix, tests have been failing because (among others) this issue. Any ideas on how you want to proceed? Don't support IE9? Use a base64-module to support it? I'd be happy to contribute with a PR if you have any feedback on how you want it solved.

**Comment by defunctzombie** [comment]
@rexxars is this the only thing blocking IE9 use? I am wondering if it is even worth the trouble for IE9.

**Comment by defunctzombie** [comment]
https://github.com/visionmedia/superagent/blob/8d1c04e3aa29aa6d7da122de584593214f9242f4/lib/client.js#L656-L660

**Comment by rase-** [comment]
Auth works fine with a polyfill according to the test suite: https://github.com/visionmedia/superagent/blob/master/test/client/request.js#L565

I'm wondering if we should just document it somewhere (like in the README after the plugins section?) that IE9 use requires a polyfill for auth instead baking it into superagent. Thoughts?

cc @defunctzombie

**Comment by defunctzombie** [comment]
We should document that you need the polyfill for btoa for auth to work. I do not think native support for old IE warrants including such a large polyfill by default for everyone.

We should have a `supported browsers` section in the readme that covers these topics.

**Comment by rase-** [comment]
If we're just going to document the need for a polyfill, I think this can be closed after merging in #564.

cc @defunctzombie
