### ISSUE TITLE
Set Content-Length header on DELETE, PUT when no entity body

### ISSUE THREAD

**Issue by damianb** [visionmedia/superagent#236]
Similar to https://github.com/mikeal/request/pull/41 - I'm seeing issues with an nginx server handling an API where DELETE operations to it are now returning HTTP 411 - there's a transfer-encoding header being injected somewhere along the way (not by superagent, likely nodejs itself because there's no content-length header) and it is causing severe problems with http requests.

**Comment by defunctzombie** [comment]
@damianb Can you provide a simple example to show the problem please.

**Comment by jdesboeufs** [comment]
Any DELETE request through nginx without body :(
Hopefully it's easy to fix with `req.set('content-length', 0)`.

curl seems to do this by default.

**Comment by soyuka** [comment]
@defunctzombie `DELETE` requires a content-length, at least with nginx (seems I had no issues with apache). If I try to `curl DELETE` it will send a [`411 Length Required`](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.12) status. 
Solution here is to set a `Content-length` header:

```
    if(this.method == 'DELETE') {
      this.set('Content-length', 0)
    }
```

atm I have a hack [like this one](https://raw.githubusercontent.com/LearnBoost/superagent-oauth/master/superagent-oauth.js) to override the `Request.prototype.request` method.

**Comment by defunctzombie** [comment]
@soyuka can you make a PR with appropriate tests for this?

**Comment by soyuka** [comment]
@defunctzombie are there specific instructions to run tests? I did `make test` or `make test-node` but a lot is failing. Thanks.

**Comment by defunctzombie** [comment]
@soyuka `make test-node` should would. For browser tests you will need to setup [zuul](https://github.com/defunctzombie/zuul/wiki/Cloud-testing) for cloud testing. Just steps 1 & 2 should be enough.

**Comment by soyuka** [comment]
@defunctzombie sorry made a lot of mistakes in my first commit it's late here ^^.

**Comment by pornel** [comment]
As mentioned in #236 the HTTP RFC the DELETE request doesn't require Content-Length, so I think nginx is being too picky here.

Has anybody reported the issue to nginx? If the bug can be fixed in nginx I'd rather avoid adding a workaround superagent.

**Comment by damianb** [comment]
a client workaround will still likely be necessary due to propagation of that patch/update across the web.  even if nginx patches it today, it wouldn't land anytime soon in rhel, deb, ubuntu, so handling nginx's edge case would be necessary in the meantime.

**Comment by soyuka** [comment]
@damianb  I see no client workaround here. How can you set the `Content-Length` header from the client (aka web browser)? See [in the list of forbidden header name](https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name).

@pornel agreed, but it then say in `OPTIONS` that a request with an empty body MUST provide a `Content-Length` of 0. I'll search on the nginx side if there are mention of this particular issue.

**Comment by soyuka** [comment]
Continuing the discusison from the #711 PR here:

OPTIONS:
> A server MUST generate a Content-Length field with a value of "0" if no payload body is to be sent in the response.

DELETE:
> A payload within a DELETE request message has no defined semantics;
sending a payload body on a DELETE request might cause some existing
implementations to reject the request.

-------

Yes indeed, I read both, but the OPTIONS paragraph was a more logical explanation to why does nginx sends 411 when DELETE happens without Content-Length.
If you mix both parts, you could deduce that DELETE should not have any body, and so, should set the Content-Length to `0`, like OPTIONS expects.

I can't find any relevent issues on the nginx Trac, I'll try to dig deeper.
