### ISSUE TITLE
Unhandled error if destination is unreachable even with time out

### ISSUE THREAD

**Issue by suparngp** [visionmedia/superagent#238]
I am using superagent to check s user session from a REST services based backend server. While testing the node for errors, I have come across a weird situation.
I am running node in a restricted network to simulate office like network (people usually don't have access to different ports). This ensures that my backend server can't be pinged because my network wont allow me. At this point, I should get a timeout error from my agent when it tries to contact the backend since it cannot reach the server. However, it throws an unhandled exception 'connect ETIMEDOUT'.

I traced back and found that lower level net api's throw this error (I might be wrong). The only way I am able to catch this error is to have a process.on('unhandledException', handler) event handler. Here is the sample code:

> agent.get('path')
         .set('token', session)
         .set('Content-Type', 'application/json')
         .set('Accepts', 'application/json')
         .timeout(5000)
         .end(function(err,response){
             if(err){
                 console.log(err); //log the error ***
                 console.log("Log: error in check user session response from backend");
                 req.sessionExists = false;
                 callback(req, res);
             }
             else{//do something else}
     }

Here is the output:
> { [Error: timeout of 5000ms exceeded] timeout: 5000 }

    events.js:72
    throw er; // Unhandled 'error' event
          ^
    Error: socket hang up
        at createHangUpError (http.js:1445:15)
        at CleartextStream.socketCloseListener (http.js:1495:23)
        at CleartextStream.EventEmitter.emit (events.js:95:17)
        at tls.js:623:10
        at process._tickCallback (node.js:415:13)

Also, if I remove all the callbacks in if(err){ //} and remove timeout block and simply return, it throws a different error,

> throw er; // Unhandled 'error' event
              ^
Error: connect ETIMEDOUT
    at errnoException (net.js:884:11)
    at Object.afterConnect [as oncomplete]

I am not sure why the err object not handling the code properly.

**Comment by gebrits** [comment]
@suparngp is this still your go-to solution? I'm experiencing the same thing
