### ISSUE TITLE
res.body set too late

### ISSUE THREAD

**Issue by ARAtlas** [visionmedia/superagent#244]
I recently upgraded superagent from 0.14.7 to 0.15.4 and a bug appeared when getting large amounts of JSON data (a couple megabytes worth at least).

In this test, an array of 2000 JSON objects is downloaded:

agent.get(url).end(function(err, res) {
  should.not.exist(err);
  res.body.should.have.length(2000); // Usually fails because res.body is not defined
});

With superagent 0.15.4, it fails about 70% of the time because res.body is undefined, even though I can see form the server logs that the data was returned.  However, if I stick in some time-wasting operation, such as:

agent.get(url).end(function(err, res) {
  should.not.exist(err);
  console.log(res.body); // Problem is mysteriously fixed by this
  res.body.should.have.length(2000); // Succeeds
});

Then the problem goes away.  But in 0.14.7 it works even without the time-wasting line stuck in.

**Comment by mindjuice** [comment]
Not sure if I am seeing the same issue, but it seems similar.

The res.body field is never set for my GET request when running superagent in a node app.  My res.text is very small (about 120 characters), and the content-type is set as shown:

    "content-type": "application/json; charset=utf-8",

I am running the same code in the browser to send requests to my REST API and it sets res.body properly in that environment, but running under node, res.body is never set.

**Comment by defunctzombie** [comment]
Going to close this due to age.
