### ISSUE TITLE
.type('form') doesn't prepare Javascript arrays correctly

### ISSUE THREAD

**Issue by chrisabrams** [visionmedia/superagent#250]
Please let me know if I am doing something wrong, but if I say something like:

```
var data = {
    interests: [300, 400]
}

request('/foo')
    .type('form')
    .send(data)
    .end()
```

The form data is sent as

```
interests: 300, 400
```

when it should be

```
interests[]: 300
interests[]: 400
```

I am able to get it to work if I do:

```
request('/foo')
    .type('form')
    .send($.param(data))
    .end()
```

but the reason I'm using superagent is so this will also work on Node and I'd rather not require in Node jQuery just for this.

With that said, is there a setting I'm missing that is not preparing the params correctly?

**Comment by davis** [comment]
this is important!!

**Comment by vs4vijay** [comment]
How can I send post data as Array?
I am using `.type('form')`

**Comment by tjdavenport** [comment]
I just stumbled into this problem today. Going to try to get a PR up sometime this week

**Comment by badunk** [comment]
> when it should be
>    ```
>    interests[]: 300
>    interests[]: 400
> ````

I'm trying to find the spec that backs up this claim - why should it be that way?  I'm also running into the same issue.  Closest thing I've found is:

> RFC 2388                  multipart/form-data                August 1998
> 5.5 Ordered fields and duplicated field names

>    The relationship of the ordering of fields within a form and the
>    ordering of returned values within "multipart/form-data" is not
>    defined by this specification, nor is the handling of the case where
>    a form has multiple fields with the same name. While HTML-based forms
>    may send back results in the order received, and intermediaries
>    should not reorder the results, there are some systems which might
>    not define a natural order for form fields.

Which implies there's no specification for a duplicate `interests[]` field

**Comment by badunk** [comment]
Small update, I tested a bit with express's multer and it does in fact parse multipart as @chrisabrams suggests, regardless of the spec.

In fact, despite superagent's refusal to parse these more complex multipart requests, you can build up a much more complicated structure where for example `attach("interests[name]", "myname")` gets parsed into the interests object `{name: "myname"}` and `attach("interests[0][name]", "myname")` serializes into `[{name: "myname"}]`

**Comment by davis** [comment]
wasn't this fixed in https://github.com/visionmedia/superagent/releases/tag/v1.5.0?

**Comment by J-F-Liu** [comment]
Please note that jQuery.param() also has special treatment for object data.

**Comment by pornel** [comment]
This is intentional and IMHO correct. 

The brackets `[]` are only an informal convention used by some frameworks/servers, but not all environments use it. There are web servers that expect repeated keys **without** brackets:

     http://example.com/service?value=1&value=2&value=3

If superagent always added `[]` to arrays, then it would not be able to create a URL like the one above.

The current implementation supports both cases. If you'd like an array with `[]` in the name, then put `[]` in the name explicitly:

```js
request.get('/').query({'interests[]': [300, 400]});
```
