### ISSUE TITLE
econnreset

### ISSUE THREAD

**Issue by babsonmatt** [visionmedia/superagent#266]
Getting the following with some requests:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: read ECONNRESET
  at errnoException (net.js:901:11)
  at TCP.onread (net.js:556:19)

Edit: I'm doing something along the lines of req.pipe(stream), is there anyway to catch connection errors piping to stream?

Anything I can do to try to catch the error to prevent it from killing the process?
Thanks!

**Comment by mustapha-wang** [comment]
我调用某些特殊的REST服务，也是遇到这个问题。
restify模组是通过设置agent:false来解决的。
superagent模组不知道设置哪个参数。
