### ISSUE TITLE
Listen for "upgrade" event

### ISSUE THREAD

**Issue by bminer** [visionmedia/superagent#296]
Superagent should probably allow `req.on("upgrade", ...)`.

```
Emitted each time a server responds to a request with an upgrade.
If this event isn't being listened for, clients receiving an upgrade header
will have their connections closed.
```

Implementing this sugar in Superagent might be a bit tricky since if you aren't listening for the event, clients receiving an upgrade header should have their connections closed.

At the very least, it would be nice if the workaround was documented, which is something like:

```javascript
var req = require("superagent").post("/websocket")
var rawReq = req.request();
rawReq.on("upgrade", ...);
req.end(...);
```

**Comment by defunctzombie** [comment]
Probably outside of the scope of superagent.

**Comment by elimisteve** [comment]
@defunctzombie No plans for superagent to support WebSockets?

**Comment by pornel** [comment]
WebSockets are a completely different protocol (the HTTP-like handshake is just a decoy). Handling WebSockets well, with logic that handles reconnections, stalled connections, bufferbloat, etc. requires amount of effort enough for a library on its own.

I don't plan to add support for WebSockets (not even Server-Sent events which would be technically more compatible with HTTP).
