### ISSUE TITLE
Agent executes "end()" callback before setting cookies

### ISSUE THREAD

**Issue by vsuhanov** [visionmedia/superagent#314]
when using agent to keep persistent cookies it executes end callback before agent saves cookies and the next request might not have these cookies set. 

here is an example of test that fails when it should not. 
https://gist.github.com/vsuhanov/8599800

possible solution: 

1. try to insert event handler, that saves cookies, in the beginning of the event handleк list — unfortunately default eventEmitter of node doesn't support it and it might be not such a great idea to rearrange the list.

2. change the way(the place where) the callback is executed. Right now request class attaches an on('response') listeneу when it is created if I move it to Request.prototype.end method all tests pass but they yield "double callback!" so I assume it's wrong.

**Comment by Dynasty9** [comment]
I've lost days to this.

**Comment by ilanbiala** [comment]
Has this been merged in and released?

**Comment by defunctzombie** [comment]
I don't think it has.

**Comment by alexanderlperez** [comment]
+1

**Comment by alexhung** [comment]
Just lost like 4 hours on this. +1 on merging and release soon.

**Comment by defunctzombie** [comment]
The PR needs to be reworked. I think we need a cleaner way to do it than the way the PR is doing it.

**Comment by elbuo8** [comment]
:+1: to this.

**Comment by livin** [comment]
How it's possible that such an import bug is not yet fixed. Why this testing library is needed if it can't handle cookies at all. Struggled with it for enough time. Now thinking about replacing controller testing with something else. Perhaps e2e testing instead.

**Comment by defunctzombie** [comment]
Fixed by 04a04e2
