### ISSUE TITLE
Redirects cause exception if no location header is present

### ISSUE THREAD

**Issue by ashaffer** [visionmedia/superagent#321]
Amazon S3 301 redirects sometimes do not contain a location header (if, for instance, you create a bucket in a non-standard region, and then attempt to access it at the non-region-specific subdomain, though probably in other cases as well).  This seems like strange behavior on S3's part, but superagent probably shouldn't throw an exception when this happens.

**Comment by defunctzombie** [comment]
Will give an error now: https://github.com/visionmedia/superagent/commit/ecd32cb0d15d291c4262852c369c318ff30a9bf9

You can't redirect with no header
