### ISSUE TITLE
Using querystring lib with .query

### ISSUE THREAD

**Issue by hallas** [visionmedia/superagent#338]
Any objections to this? Currently when posting an array, the keys are enumerated but not when using the native node lib querystring. Maybe someone could explain why?

SuperAgent:
`?key[0]=value1&key[1]=value2`

Querystring:
`?key=value1&key=value2`

**Comment by gjohnson** [comment]
My apps requirements have changed these days, I need this feature now. :stuck_out_tongue_closed_eyes:

**Comment by travisjeffery** [comment]
***go*** figure :stuck_out_tongue_winking_eye:

**Comment by travisjeffery** [comment]
https://github.com/visionmedia/superagent/pull/539

**Comment by vs4vijay** [comment]
How to make this work?
