### ISSUE TITLE
res.body is empty

### ISSUE THREAD

**Issue by math-nao** [visionmedia/superagent#347]
When superagent is called in a superagent callback, it returns empty "res.body".

The fix is to call superagent callback in the next tick of the event loop.

Tested on version 0.17.0

Example: https://gist.github.com/math-nao/320441b6cc9ec601b195

**Comment by mindjuice** [comment]
I tried putting your patch into superagent 0.21.0, but my res.body is still undefined even though my res.text is set and content-type is "application/json; charset=utf-8".

**Comment by defunctzombie** [comment]
@mindjuice please open a new issue with a failing example so we can take a closer look.
