### ISSUE TITLE
Timeout error reports "timeout of 0ms exceeded" for non-zero timeouts

### ISSUE THREAD

**Issue by gasi** [visionmedia/superagent#376]
Timeout causes [`Request.abort`](https://github.com/visionmedia/superagent/blob/7fbdf9730d60cf2415cab15c1050e279e61514ff/lib/client.js#L868) which leads to [`Request.clearTimeout`](https://github.com/visionmedia/superagent/blob/7fbdf9730d60cf2415cab15c1050e279e61514ff/lib/client.js#L495) which sets [`this._timeout = 0`](https://github.com/visionmedia/superagent/blob/7fbdf9730d60cf2415cab15c1050e279e61514ff/lib/client.js#L495) that is then reported in [`timeoutError`](https://github.com/visionmedia/superagent/blob/7fbdf9730d60cf2415cab15c1050e279e61514ff/lib/client.js#L851).

**Comment by ianwalter** [comment]
:+1:

**Comment by defunctzombie** [comment]
What is the issue here?

**Comment by gasi** [comment]
It’s been a while, but I believe `abort`ing a request results in timeout error, although it shouldn’t.

**Comment by defunctzombie** [comment]
What should it do? No error? Should it emit the `abort` event?

**Comment by defunctzombie** [comment]
Also, is this an issue with server side lib or client side lib?

**Comment by gasi** [comment]
Frankly, it’s been too long to remember all the details but I have the following. This issue occurred in the client-side library and I have this comment in this snippet:

```javascript
// TODO: `err.timeout` is incorrectly reported:
// https://github.com/visionmedia/superagent/issues/376
if (err.timeout != null) {
  error = new Error('Settings change event timed out.');
  error.code = 'Timeout';
  return callback(error);
} else {
  return callback(err);
}
```

**Comment by ianwalter** [comment]
Yea if you're intentionally aborting a request there shouldn't be an error.

**Comment by gasi** [comment]
:+1:
