### ISSUE TITLE
.redirects() not working from the browser

### ISSUE THREAD

**Issue by gpbl** [visionmedia/superagent#380]
I am trying to limit the redirects for a get request but the `redirects()` method does not exist:

```javascript
  var superagent = require('superagent');
  var request = superagent.get('/');
  request.redirects(1); // Uncaught TypeError: undefined is not a function 
```

This seems related to #326 by @ddo. 

I use Webpack as module loader, and I'm requiring [superagent.js](https://github.com/visionmedia/superagent/blob/master/superagent.js), which actually does not have a `redirects()` method. Is redirects() supposed to work on a browser?

**Comment by defunctzombie** [comment]
The browser handles redirects for you.
