### ISSUE TITLE
Attachment specifying file as String overrides custom filename argument

### ISSUE THREAD

**Issue by nuarhu** [visionmedia/superagent#397]
Using the method `request.attach(field, file, filename)` where `file` argument is of type String has the result that the `filename` argument is ignored. This happens because `filename` is overridden if `file` while the stream is created:

``` javascript
Request.prototype.attach = function(field, file, filename){
  if (!this._formData) this._formData = new FormData();
  if ('string' == typeof file) {
    filename = file; // custom filename is lost here
    debug('creating `fs.ReadStream` instance for file: %s', filename);
    file = fs.createReadStream(filename);
  }
  this._formData.append(field, file, filename);
  return this;
};
```
(https://github.com/visionmedia/superagent/blob/24cf589ad6ad5348b874a4474a3f7c8af7fab31e/lib/node/index.js)

Unfortunately, even when providing a ReadStream object as `file`, the filename doesn't make it into my request object on the server. But that is a different matter. I've just spotted this during debugging and thought I'd notify you. If it is intentional some hint in the documentation would help.

Setting the custom filename is also discussed in #381 .

**Comment by defunctzombie** [comment]
I believe fixed in master.
