### ISSUE TITLE
browserify incompatibility

### ISSUE THREAD

**Issue by barroudjo** [visionmedia/superagent#398]
I use superAgent in a browser side project, using browserify, and the buffer() method does not exist.

Example:
```
var query = request.get(url);
query = query.buffer();
```

Is that a known issue ?

**Comment by bryancallahan** [comment]
@barroudjo I'm using https://www.npmjs.com/package/superagent-browserify (v0.0.2) and it's working great w/ superage v0.11.0.

**Comment by adam-lynch** [comment]
@bryancallahan FYI the version of superagent that superagent-browserify installs looks out of date

**Comment by defunctzombie** [comment]
Buffer is not available on the client right now. Should I make it a no-op? What behavior would help here?

**Comment by mjhasbach** [comment]
@defunctzombie You could perhaps leverage [bops](https://github.com/chrisdickinson/bops) to add ```buffer``` support to the client.

**Comment by defunctzombie** [comment]
Not worth the bloat in the final code bundle.

**Comment by mjhasbach** [comment]
Perhaps [ArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer), then.

**Comment by defunctzombie** [comment]
I am going to close this. Browser side just doesn't support `.buffer()`. If someone submits a PR I will review but this is not a feature that is blocking usage or something high on my priority list.
