### ISSUE TITLE
Getting binary data (octet-stream)

### ISSUE THREAD

**Issue by katcipis** [visionmedia/superagent#402]
I have an service that provides binary data (octet-stream). How do i receive binary data using superagent ? I checked the docs:

http://visionmedia.github.io/superagent/

But it seems to cover only formats that superagent knows and can parse, or text (the *text* and *body* fields of the response).

On my case *body* is empty and *text* is undefined when my server responds with a 'application/octet-stream'.

**Comment by cedx** [comment]
This worked for me using a stream:

```javascript
var fs = require('fs');
var request = require('superagent');

var output = fs.createWriteStream('path/to/file.zip');
request.get('http://domain.com/path/to/file.zip').pipe(output);

// "output" contains the raw data.
```

Use a module like `memorystream` if you don't want to store the output on the file system.
