### ISSUE TITLE
Multi-part attachment doesn't set filename correctly

### ISSUE THREAD

**Issue by programble** [visionmedia/superagent#403]
https://github.com/visionmedia/superagent/blob/master/lib/node/index.js#L200

The filename is passed to form-data as the last argument to `append`, but the last argument should be an `options` object.

https://github.com/felixge/node-form-data/blob/master/lib/form_data.js#L111

`attach` should either pass the filename wrapped in an object, or accept an `options` argument itself and pass it along to form-data, which allows setting a custom `Content-Type`.

**Comment by defunctzombie** [comment]
I think this is fixed in master.
