### ISSUE TITLE
Is there a way to get call timings?

### ISSUE THREAD

**Issue by ptrwllrt** [visionmedia/superagent#405]
I'm wondering if superagent provides a way to know how long a call needed to be answered. Don't want to wrap every call into a timer. :-/

**Comment by szarouski** [comment]
Is there a reason why it was closed? Adding timing information would be great - https://blog.risingstack.com/measuring-http-timings-node-js/

**Comment by pornel** [comment]
That seems like a good idea for a plugin. I don't think it needs to be in core superagent.

**Comment by szarouski** [comment]
Got it, thank you.
