### ISSUE TITLE
Support cross domain requests on IE 8 and 9

### ISSUE THREAD

**Issue by trevorreeves** [visionmedia/superagent#409]
Surprise surprise, CORS requests don't work quite the same way in IE 8 & 9 as they do in other browsers, and they come with some extra restrictions. This is a nice page describing some of the finer details: http://blogs.msdn.com/b/ieinternals/archive/2010/05/13/xdomainrequest-restrictions-limitations-and-workarounds.aspx.

In a nutshell, CORS is implemented with its own XDomainRequest object, seperate from XMLHTTPRequest. As a bonus, it doesn't support sending cookies, at all, or custom headers, or any verbs other than GET and POST, and requests must be made to the same scheme as the current page.

I've attempted a plugin for my current project, which achieves support for this (https://github.com/trevorreeves/superagent-legacyIESupport), however I'm no JS god, and the my solution required some code duplication from the main library.

The IE 8 & 9 restrictions provide some nice discrepancies between other browsers that I imagine would require some more abstractions in Superagent.

Well anyway, up to you guys if you think its appropriate for the main library to support cross domain requests on IE 8 & 9.

**Comment by defunctzombie** [comment]
I think your approach with the plugin is the right one. I view IE 8 and 9 and legacy and not worth core lib support :/ At least I don't have the cycles to deal with the pains right now.

**Comment by trevorreeves** [comment]
Sounds good to me.  Hopefully people like me on projects like mine will soon enough not be given requirements to support IE 8 and 9 - they're slowly but surely dying.
