### ISSUE TITLE
Unpossible to handle the error from zlib

### ISSUE THREAD

**Issue by kof** [visionmedia/superagent#410]
The error I get from zlib

Error: unknown compression method
    at Zlib._binding.onerror (zlib.js:361:17)
{ errno: -3, code: 'Z_DATA_ERROR' }

But the real problem is that I can't handle it.

utils.unzip overrides res.on method to attach handlers on zlib stream, however in combination with streaming interface, utils.unzip(req, res) is called before 'response' event is triggered to the user instance, so I get the access to the res object after the error is already triggered.

Does this need a reproducible example?

**Comment by defunctzombie** [comment]
If you have a reproducible example I can take a look. Going to close due to age of issue.
