### ISSUE TITLE
end event never fired

### ISSUE THREAD

**Issue by kof** [visionmedia/superagent#413]
When trying to send a get request to this site

http://www.channellock.com/blog/post/feed/2010/06/09/A-message-from-President-and-CEO-William-S-DeArment.aspx?format=ATOM

**Comment by rase-** [comment]
Is this still an issue?

A piece of sample code could be useful.

**Comment by defunctzombie** [comment]
Closing due to age.

**Comment by knownasilya** [comment]
Still an issue, see https://travis-ci.org/Strider-CD/strider-github/jobs/104789778#L299
