### ISSUE TITLE
Error: Hostname/IP doesn't match certificate's altnames

### ISSUE THREAD

**Issue by igorescobar** [visionmedia/superagent#414]
I'm getting the erro:
```Error: Hostname/IP doesn't match certificate's altnames``` 

Does anybody knows how to workaround this problem?

**Comment by Redsandro** [comment]
@igorescobar did you ever figure out what the problem was? I am running into the same.

**Comment by igorescobar** [comment]
@Redsandro sorry bro but it's been awhile since I got this error... I don't remember what I did to solve it. But it was probrably something in my local network or my machine. This is not a superagent bug.

**Comment by Redsandro** [comment]
@igorescobar you are right. I figured right about now that I was doing a request on a proxy, but the SSL certificate was for the end server.

This is about mismatching SSL certificates. In node (`0.12`) you can opt to ignore the certificate, but I don't think SuperAgent uses this.

Thank you for getting back so soon.

**Comment by igorescobar** [comment]
@Redsandro I'm glad to hear good news from you! I'm under a authenticated proxy too, maybe this is what we have in common :+1:
