### ISSUE TITLE
Compability with bluebird

### ISSUE THREAD

**Issue by markuplab** [visionmedia/superagent#418]
https://github.com/petkaantonov/bluebird

```
var Promise = require('bluebird');
var request = require('superagent');

Promise.all([
    request.get('http://example.com'),
    request.get('http://example.biz')
]).then(function(){
    // Never pass here :'(
});
```

Bluebird have special methods for Promisifying:
https://github.com/petkaantonov/bluebird/blob/master/API.md#promisification

**Comment by lapo-luchini** [comment]
Just for the records, I noticed it [**has been** added in the meantime](http://visionmedia.github.io/superagent/#promise-and-generator-support) and the opening post example is now perfectly working as is.
