### ISSUE TITLE
streaming is broke

### ISSUE THREAD

**Issue by gjohnson** [visionmedia/superagent#420]
With large responses that are gzipped, it just skips over the response and emits a body of undefined. 0_o

**Comment by defunctzombie** [comment]
Who wrote the streams code for this module?

**Comment by rase-** [comment]
What qualifies as "large" here?

**Comment by defunctzombie** [comment]
Closing for no response. If streaming is still broken we need a failing example. Age of bug might indicate things have been fixed up in other ways.
