### ISSUE TITLE
Triggering OPTIONS preflight in firefox

### ISSUE THREAD

**Issue by rralian** [visionmedia/superagent#442]
We're using CORS to fetch a cross-domain JSON file with superagent via GET request, and we noticed that a simple CORS request that should not trigger a preflight OPTIONS check was still doing so in firefox. It seems to come from the progress check for uploads https://github.com/visionmedia/superagent/blob/master/lib/client.js#L908-L913

**Comment by mdawaffe** [comment]
See also #548.
