### ISSUE TITLE
pass the original error message to the catched error

### ISSUE THREAD

**Issue by timaschew** [visionmedia/superagent#450]
superagent is catching all errors: https://github.com/visionmedia/superagent/blob/f106c7226758a22f633d0cf1607b5bb6a3ce264e/lib/client.js#L458

so if you make a request and get a runtime error in the response callback it's totally annoying, because you only get a __Parser is unable to parse the response__ and you need to debug it to get the origin error message, which has nothing to do with parsing the response.

**Comment by dcousens** [comment]
+1

**Comment by constantx** [comment]
:+1:

**Comment by defunctzombie** [comment]
This has been fixed in master. The callback is not in the try/catch anymore.

**Comment by dcousens** [comment]
Any word on a publish?

**Comment by defunctzombie** [comment]
Yea, I am trying to blow through the issue backlog today and tomorrow and want to try to get an RC out tomorrow but can't promise anything.

If you want to use master today you can certainly just reference git commits directly.
