### ISSUE TITLE
Connecting to non-listening socket for OPTIONS gives incorrect Access-Control-Allow-Origin err

### ISSUE THREAD

**Issue by mikemaccana** [visionmedia/superagent#451]
I have a web API, located on port 3000. 

The API is accessed from clients including a web app that runs on port 8000.

**I am deliberately turning off the API server to make sure the client handles this condition correctly.**

Using superagent, the OPTIONS request to the API is refused. 

    OPTIONS http://localhost:3000/login net::ERR_CONNECTION_REFUSED 
    superagent.js:1297

This makes sense: the API server is down. However logging the error gives:

    Error {
        crossDomain: true, 
        stack: (...), 
        message: "Origin is not allowed by Access-Control-Allow-Origin"}

I get that the API server is indeed cross domain, but the `message` field seems incorrect: my `Access-Control-Allow-Origin` headers on the API allow the client to access the API, the problem is before that: there's nothing listening on the socket.

**Should superagent produce a different/better error message if the OPTIONS request is refused?**

Thanks.

**Comment by defunctzombie** [comment]
Related:
http://stackoverflow.com/questions/19325314/how-to-detect-cross-origin-cors-error-vs-other-types-of-errors-for-xmlhttpreq

**Comment by defunctzombie** [comment]
Closing in favor of: https://github.com/visionmedia/superagent/issues/484
