### ISSUE TITLE
How to add custom mime type parsers?

### ISSUE THREAD

**Issue by redonkulus** [visionmedia/superagent#458]
The doc mentions "Super Agent will parse known response-body data for you, currently supporting application/x-www-form-urlencoded, application/json, and multipart/form-data.", how do I add my own? 

I found the [parsers/index.js](https://github.com/visionmedia/superagent/blob/717ce9b738a4ff12e0bee0e209b8fb9e013024ba/lib/node/parsers/index.js) file but when adding my own, the response body was still not parsed. Been trying to read through the /lib/node/index.js to see if there are other places that need to be updated.

Any help or guidance would be appreciated.

**Comment by gechols** [comment]
I found this thread when I was trying to do the same thing. I found that setting superagent.buffer(true) and then using the response.text worked.
Of course, in my case the content was actually JSON by another name so it was safe to treat it as a string. This may not be the case for binary data.

**Comment by mikemaccana** [comment]
👍 Thanks @gechols, using `.bufffer(true)` and using `response.text` worked for me too. I suspect a whole bunch of users will end up here from bad API vendors who just use JSON but have horrible unnecessary custom mime types like `application/vnd.somecompany.rest-v1+json`. 💩
