### ISSUE TITLE
Is there a way to determine if there are active requests?

### ISSUE THREAD

**Issue by sporto** [visionmedia/superagent#465]
In our test we have to wait for AJAX request to be finished before asserting things.
When using jQuery we use `$.active` to find if there are active requests.

Is there a way to do this in superagent?

**Comment by defunctzombie** [comment]
No. You can only know in each request callback if they are done. Use a module like `after` or `async` to wait on multiple things. There are no globals for this for good reason.

**Comment by sporto** [comment]
@defunctzombie is not about waiting for several things in the application itself, this can be done with callbacks or async as you say.

It is about writing end to end test that depend on an ajax response to be finished. For example:

- I write end to end test using a tool like https://github.com/jnicklas/capybara (which uses Selinium or PhantomJS)
- capybara clicks on things that triggers ajax request
- then I want to assert that something is shown for example, but I need to wait for all ajax request to be finished first

The capybara has no way to ask superagent if there are ajax request going on.

**Comment by defunctzombie** [comment]
I think the best bet here is to create a plugin that will populate whatever
global you want.
