### ISSUE TITLE
Piping a request to a wrong url, throws an uncatchable error

### ISSUE THREAD

**Issue by brugnara** [visionmedia/superagent#470]
```js
request.get(url).pipe(feed);
```

If url is something like: `http://fake123.12341ksd.cjjais.asdada.dadada.dada.ada/feed.xml`, the application crashes with:

```js
NODE uncaughtException: Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
Program node example exited with code 1
```

I have tried with no luck, this:

```js
try {
  request.get(url).pipe(feed);
} catch(e) {
  return false;
}
```

Any hint will be appreciated, many thanks.

**Comment by rase-** [comment]
Indeed I think this can be closed.

In future versions there is no arity checks for the end cb, so the error will always be passed there.

cc @defunctzombie
