### ISSUE TITLE
isHost seems too strict: ArrayObject is converted to string when sent

### ISSUE THREAD

**Issue by Ezku** [visionmedia/superagent#479]
Hi, I recently had a problem with file uploads not going through superagent. Calling .send on superagent would convert the ArrayObject I was holding to '[object ArrayObject]' instead of passing it directly on to XMLHttpRequest's send.

Eventually I managed to track the problem down to isHost(obj) in client.js, which checks for whether an object should be passed through directly. The list comprises File, Blob and FormData, but ArrayObject is missing. Comparing against this list, the observed behaviour seems too strict: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest

I was able to circumvent this problem by passing in File instead, but others may not be as lucky. Hope this helps!

**Comment by defunctzombie** [comment]
I don't see ArrayObject in that list.
