### ISSUE TITLE
res not returned when superagent fails JSON parsing

### ISSUE THREAD

**Issue by DonutEspresso** [visionmedia/superagent#487]
In the JSON parser:

``` javascript
  res.on('end', function(){
    try {
      fn(null, JSON.parse(res.text));
    } catch (err) {
      fn(err);
    }
  });
```

The res object is not returned on a failed parse - I cannot inspect headers or anything else on the res that might be of interest or can give me a way to handle failed parsing.

**Comment by badeball** [comment]
I am also having this issue. Personally, I absolutely consider it to be a bug. Even if a requests returns a response that doesn't conform to the standard, I still want to be able to see the status code.

**Comment by hilkeheremans** [comment]
I agree. No one can really guarantee all server APIs they communicate with behave as they "should". Superagent should be robust enough to handle these cases.

**Comment by adriaanbalt** [comment]
+1

**Comment by dcurletti** [comment]
+1

**Comment by castrolem** [comment]
+!

**Comment by pornel** [comment]
Unparseable input is now returned as a property of the error.
