### ISSUE TITLE
retry logic

### ISSUE THREAD

**Issue by tj** [visionmedia/superagent#50]
on econnrefused etc, exponential falloff or similar

**Comment by firstdoit** [comment]
Apparently `superagent-retry` is not actively maintained and still depends on `"superagent": "~0.20.0"`.

**Comment by szarouski** [comment]
If anyone else will look at this issue - retry is already a part of superagent: http://visionmedia.github.io/superagent/#retrying-requests. If you're looking for more details: https://github.com/visionmedia/superagent/pull/1155
