### ISSUE TITLE
OPTIONS sent before POST in the browser for CORS request

### ISSUE THREAD

**Issue by kkartunov** [visionmedia/superagent#501]
Hi,
great `superagent`!

I use the lib to make requests to HP's IDOL API. Works great in nodejs but in the browser(build with browserify) it sends an OPTIONS request first before the POST request the app is actually making. This sadly breaks everything because the API throws some error and can't handle OPTIONS request at all.

the endpoint in question is:
`https://api.idolondemand.com/1/job`
anyway send an OPTIONS request and one see the Error.

**The questions:**
1. Can sending OPTIONS before POST (in browser env) be disabled in `superagent` somehow?
2. Is this related to CORS, I mean if the request was not CORS would the browser send OPTIONS before POST at all?

Looks like this "issue" is related to #451 because after the failing OPTIONS request the error is the same.

**Comment by fiatjaf** [comment]
For anyone with this problem, here's a fork that does not add `application/json` unless you ask for it: https://github.com/fiatjaf/superagent-cors
