### ISSUE TITLE
Support for HTTP Digest Authentication

### ISSUE THREAD

**Issue by c4milo** [visionmedia/superagent#51]

**Comment by dbellavista** [comment]
Was it closed because it's now supported or because it's unimplementable?

**Comment by defunctzombie** [comment]
It was closed because there is no issue description saying what behavior is desired or why. I can't act on something that has no example use case even.

**Comment by dbellavista** [comment]
Ok, I will expand the original issue.

I have some express API protected by HTTP Digest Access Authentication (using [passportjs](http://passportjs.org/guide/basic-digest/), for instance) and I'd like to test them using supertest, without spawning a server.

```
var app = express();
// ... express setup and protection using Digest Access Authentication
supertest(app)
.digestAuthentication('user', 'secretkey') // Desiderata
.get('/my/protected/api')
.expect(200)
.end()
```

I didn't try `superagent.auth(user,pass)`, because the [documentation](http://visionmedia.github.io/superagent/#basic-authentication) states that `Basic authentication` is supported, but there's no mention to digest.

**Comment by defunctzombie** [comment]
This is the superagent library not the supertest library.

**Comment by dbellavista** [comment]
Uh... right (sorry)!
Still, it would be a useful feature to have in superagent and libraries such as supertest will get the benefits too.

```
request
.get('/my/protected/api')
.digestAuthentication('user', 'secretkey') // Desiderata
.end(callback)
```

**Comment by taylordowns2000** [comment]
Been using Superagent for about 6 months now and absolutely love it. Thanks to all involved. Are there any plans to implement a digest auth feature?

**Comment by focusaurus** [comment]
I don't think it's on any of the maintainers' roadmaps to proactively code this. If someone submit's a pull request with solid code, tests, and docs, I don't think we'd hesitate to merge it though.

**Comment by taylordowns2000** [comment]
OK, thanks for the swift response, @focusaurus ! At the moment I may try to get the job at hand done with ["request"](https://github.com/request/request) but when I can pick my head up I'll do my best to take a look. By the way, I really appreciate what you've built here. It's been a big part of our open-source "adaptors" at [www.openfn.org](https://www.openfn.org). Thanks again.

**Comment by pornel** [comment]
I've updated the docs. We do have Digest in browsers that support it http://visionmedia.github.io/superagent/#authentication

It's missing in Node though.
