### ISSUE TITLE
Content-type application/json-patch leads to TypeError

### ISSUE THREAD

**Issue by mitchallen** [visionmedia/superagent#510]
This was discovered by way of using supertest to test using patch:

.set( 'Content-Type', 'application/json-patch' )

Results in the error: 

 Uncaught TypeError: Argument must be a string
      at Test.Request.end (.../node_modules/supertest/node_modules/superagent/lib/node/index.js:806:41)

Example:

	request( testHost )
		.patch( patchUrl )
		.send( 
				[
						{"replace": "/status", "value": "UPDATE PATCH" }
				] )
		// Uncaught TypeError: Argument must be a string 
		.set( 'Content-Type', 'application/json-patch' )
		// .set( 'Content-Type', 'application/json' )
		.expect( 200 )	
		.end( function(err, res ) {
			should.not.exist(err);
			done();
		 })

**Comment by defunctzombie** [comment]
Sounds like your server is sending a content type that the parser can't handle. I don't think `application/json-patch` is a thing that is automatically handled if you are sending that as the response. Just use json?

**Comment by nilgradisnik** [comment]
Why was this issue closed?

I'm having the same problem trying to use patch and setting headers similar to `'Content-Type: application/json-patch'`. I should be allowed to set any custom headers and superagent should not result in error.

**Comment by sescobb27** [comment]
I have the same issue but with `application/vnd.api+json` which is the content type for JSON API http://jsonapi.org/format/#conventions

**Comment by nodu** [comment]
I was having a similiar issue with `content-type: application/json` and a lowercase `patch`, uppercase `PATCH` has fixed the issue.  Go figure.
