### ISSUE TITLE
Add progress event on node

### ISSUE THREAD

**Issue by mauricesvay** [visionmedia/superagent#516]
The `progress` is only triggered on the browser version of the lib. It would be nice to have it on the node side too.

**Comment by olalonde** [comment]
+1. Has this been implemented yet?

**Comment by olalonde** [comment]
I started implementing this but got stuck here because writable streams don't have a 'data' event:

```javascript
  // See http://dev.w3.org/2006/webapi/progress/Progress.html
  req.on('data', function () {
    var length = req.getHeader('Content-Length');
    var lengthComputable = !!length;
    var loaded = 0;
    var total = lengthComputable ? length : 0;
    return function (data) {
      loaded += data.length;
      self.emit('progress', {
        lengthComputable: lengthComputable,
        loaded: loaded,
        total: total
      });
    };
  }());
```

I tried googling around but couldn't find any helpful info on tracking upload progress with nodejs' http module.

**Comment by olalonde** [comment]
Ok, so I implemented this on `form-data` uploads only (e.g. when using .attach() or .field()).

**Comment by shishirx34** [comment]
This is exactly what I was looking for, @olalonde is there an ETA on when #771 PR would be merged?

**Comment by pornel** [comment]
I have concerns about the PR in the current state, and I'm waiting for a response from @olalonde, but in general I agree that's a good thing to implement.

**Comment by olalonde** [comment]
PR merged though it would still be nice to have 

1) progress events on the incoming side (when downloading). (and a way to distinguish them)

2) currently, the progress event only works when using the `attach()` or `field()` APIs (anything that uses form data). It would be nice to also have it on regular requests or requests that are piped to from a readable stream.

**Comment by pornel** [comment]
Agreed.
