### ISSUE TITLE
attach(field, buffer) should throw an error if filename is missing

### ISSUE THREAD

**Issue by SystemParadox** [visionmedia/superagent#521]
`.attach(field, buffer)` should probably throw an error if the filename argument is not specified, since this will not work.

From what I can work out from RFC2388, a part must have a `filename=` parameter, or use `content-disposition: file` in order for it to be identified as a file.

With multiparty at least, such a request results in the file data appearing in the fields map, rather than the files map.

For anyone having issues with trying to attach buffers even when specifying the filename, see #403.

Thanks.

**Comment by SystemParadox** [comment]
Yes, `.attach(field, buffer, {filename: 'need a filename'})` does work, but that is to do with #403 (it shouldn't need an object wrapper).

This issue is about what happens when you don't provide a third argument at all. Superagent should either make this work correctly, or throw a useful error message.

**Comment by defunctzombie** [comment]
I think this is now fixed in master.
