### ISSUE TITLE
Posting JSON to PHP again

### ISSUE THREAD

**Issue by lborgman** [visionmedia/superagent#522]
I use to do something like this to POST a stringified JSON:

        rq.open("POST", url, true);
        rq.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
        rq.send(jsonTxt);

Then I get this as a JSON string in PHP input:

       $entityBody = file_get_contents('php://input');

When I try to do something like it with SuperAgent I get $entityBody == NULL:

       superagent.post("http://localhost:1234/myphp.php")
              .send('{"a":"b"}')
              .type("application/x-www-form-urlencoded")
              .end(function(e,s){console.log("e", e, "s", s)})

How can I send jsonTxt with SuperAgent so I can catch it with PHP as above?

**Comment by lborgman** [comment]
Seems to be something with the format of the onprogress function. Switching to the supported addEventListener instead makes things work as I expected.

**Comment by defunctzombie** [comment]
Closing this since it seems you resolved your own issue.

**Comment by lborgman** [comment]
Thanks @defunctzombie, but that is a misunderstanding. I changed the code in Superagent to make it work. Maybe this could work in all browsers, I am not sure:

// progress
/// Fix for Chrome
if (xhr.addEventListener) {
    xhr.addEventListener("progress", function(e){
        e.percent = e.loaded / e.total * 100;
        self.emit('progress', e);
    });
} else if (xhr.upload) {
    xhr.upload.xonprogress = function(e){
        e.percent = e.loaded / e.total * 100;
        self.emit('progress', e);
    };
}

**Comment by defunctzombie** [comment]
Please format the issue so we can read it. Also a PR or failing test would help explain more what is wrong here and what we should be doing. I can't tell from the code snipped what actually changed.

**Comment by lborgman** [comment]
Sorry, I added the markdown to format the code.

**Comment by lborgman** [comment]
I took a look again. I works with my patch (`$entityBody` in PHP above contains what I expect), but not without it (`$entityBody` is NULL).

When I look at the event it looks ok in addEventlistener, but in onprogress e.total == 0 and e.lengthComputable == false.

So it might be considered kind of a bug in Chrome, but does onprogress exist in the standards?

**Comment by lborgman** [comment]
And please reopen this, of course. ;-)

**Comment by lborgman** [comment]
Here is my test case, on browser side:

```javascript
    superagent.post("http://localhost:7000/test.php")
        .type("application/x-www-form-urlencoded")
        .send('{"a":"b"}').end()
```

On the PHP side it is just the one line code I mentioned above, test.php:

```php
    <?php
     function writeStdErr($msg) { $fh = fopen('php://stderr','a'); fwrite($fh, $msg); fclose($fh); }
     $entityBody = file_get_contents('php://input');
     writeStdErr("entityBody:\n".$entityBody."\n\n");
```

Just run it with `php -S localhost:7000`

**Comment by defunctzombie** [comment]
Not sure what this is suppose to show but sending `x-www-form-urlencoded` content type but actually sending `json` can't be too good. I bet php is refusing to decode invalid content type most likely. I would make sure you are sending valid requests first.

**Comment by lborgman** [comment]
This was a really hard one. It looks like a PHP bug so far, but I am not quite sure. The problem occurs when I POST from PHP to another URL (this is a proxy server), but I have a hard time to understand how.

The missing input is fetched at the beginning of the PHP file and the offending code comes much later in the PHP file.

And it is working code. Except for the problem I see here. I looks like the PHP code (in HTTP/Request2.php) is doing some quess-work in a first parsing pass and tries to help me. A very bad idea if that is the case.

**Comment by lborgman** [comment]
I am beginning to understand what is happening. The request is sent two times when it is POST.

So there is no PHP bug. However the problem I saw above in Superagent exists, but is a bit hard to nail down. It seems to show up when `application/json` is used and `500` is sent back.

But at least this should be fixed, I think:
* Check the `e.lengthComputable` value. If it is not true, then just do `return` in `onprogress`.

And maybe replace `onprogress`. But that one is harder to show. 

For anyone wanting to test more, here is my PHP testing script. Run it with `php -S localhost:7000` for example:

```php
<?php

require_once 'HTTP/Request2.php';
header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Headers: Content-Type");

ini_set('display_errors', 1); 
error_reporting(E_ALL);

ini_set('default_charset', "UTF-8"); 

function writeStdErr($msg) { $fh = fopen('php://stderr','a'); fwrite($fh, $msg); fclose($fh); }
writeStdErr("\n=====================================\n");

foreach (getallheaders() as $name => $value) { writeStdErr("IN: $name: $value\n"); }

writeStdErr("GET:\n".var_export($_GET, true) . "\n");
writeStdErr("POST:\n".var_export($_POST, true) . "\n");
$entityBody = file_get_contents('php://input');

writeStdErr("entityBody:\n".$entityBody."\n");

$postedJson = json_decode($entityBody, true);
writeStdErr("POSTed json:\n".var_export($postedJson, true) . "\n");

$status = "500";
if (array_key_exists("status", $_GET)) { $status = htmlspecialchars($_GET["status"]); }

header("HTTP/1.0 ".$status." Just testing, look at status value here");
writeStdErr("Sent back ".$status."\n");
echo "Sent back ".$status."\n";
```

And test it with something like the below in the web browser console. Test status 200 and 500 (default).

```javascript
superagent.post("http://localhost:7000/test.php?status=200").send('{"a":"b"}').end()
```

**Comment by lborgman** [comment]
I getting a bit closer to understand what is going on. The PHP code is somehow getting run 2 times when `application/json` is used, but not when `applicaiton/x-www-form-urlencode` is used.

Please take a look here:

http://stackoverflow.com/questions/27924902/why-do-an-ajax-application-json-run-php-code-twice

**Comment by defunctzombie** [comment]
Is your request being preflighted? You should look into CORS preflight and
handle that in your php code if that is the case.

**Comment by lborgman** [comment]
It could perhaps be something with CORS preflight, but why should that be different with the two headers?

**Comment by defunctzombie** [comment]
If you read the preflight rules it talks about certain content types being
preflighted and others not.

**Comment by lborgman** [comment]
Ah, you are right. Thanks. :-)

I have no idea why the rules looks like that, though. It looks to me that due to this it might be better to send JSON with `application/x-www-form-urlencoded`.

Since that would make it one round-trip less, I mean. Or am I missing something else?

**Comment by lborgman** [comment]
I posted an answer based on your advice to my own question on StackOverflow (linked above).

**Comment by doesnotexist** [comment]
I have the same issue, when sending a post request to a webservice (that I do not control) which does not implement a handler for the preflight OPTIONS request.  So the OPTIONS preflights always fail.   However, the preflight can be avoided in the latest versions of chrome as long as xhr.upload.onprogress is not directly bound.  

So the code provided in the [comment above](https://github.com/visionmedia/superagent/issues/522#issuecomment-68897297)  as a patch to superagent fixes the issue for me by avoiding the preflight.  It appears that chrome is ok with code that addsEventListners to the xhr but requires a preflight if any javascript code touches the xhr.upload object.  

It should be noted that jquery.ajax does not have this issue as they always use addEventListener and never touch xhr.upload

**Comment by doesnotexist** [comment]
from the chrome source code 
" // The presence of upload event listeners forces us to use preflighting because POSTing to an URL that does not // permit cross origin requests should look exactly like POSTing to an URL that does not respond at all."

**Comment by lborgman** [comment]
Thanks for finding the explanation, @doesnotexist! So in principle other browsers should do this too.

All I can say now is that I really wonder how the CORS rules got through the standard committees.

**Comment by doesnotexist** [comment]
@sonicsnes is really to thank.  He helped me track this down as I was porting my app from using jquery ajax to superagent.
