### ISSUE TITLE
Adding a prefix to all requests

### ISSUE THREAD

**Issue by tbo** [visionmedia/superagent#525]
I'm searching for a way to add a prefix to all requests. I tried using the superagent-prefix, but it didn't work as documented. If I execute the code as listed on the frontpage, I get an error. For example:
``` 
var request = require('superagent');
var prefix = require('superagent-prefix')('http://127.0.0.1');

prefix(request);

request.get('/api/entity').end([...]);
```
Leads to 
```
TypeError: Cannot read property '0' of undefined
[...] 
```
It turned out, that superagent-prefix can only be applied to a single(!) request:
```
var request = require('superagent');
var prefix = require('superagent-prefix')('http://127.0.0.1');

prefix(request.get('/api/entity')).end([...]);
```

Is there a way to configure superagent to apply a prefix for all requests without monkey patching every REST-method (get, post, ...)?

**Comment by defunctzombie** [comment]
sounds like a bug with the `superagent-prefix` module. I would try there first.

**Comment by tbo** [comment]
1. superagent-prefix never claimed to offer this functionality. Only the superagent documentation is stating this: "Prefixes *all* requests"
2. superagent-prefix doesn't seem to be maintained anymore
3. I don't think that this a superagent-prefix bug. It consists of only 9 lines of code and seems to do exactly, what it is supposed to do: Add a prefix to a *single* request:
```
module.exports = function (prefix) {
    return function (request) {
        if (request.url[0] === '/') {
            request.url = prefix + request.url;
        }

        return request;
    };
}
```

This is why I am asking, how this could be achieved just by using vanilla superagent.

**Comment by morlay** [comment]
@tbo recently I use superagent to do the same thing.  

Fortune, I use https://www.npmjs.com/package/superagent-defaults to solve my problem.

    var superagent = require('superagent-defaults')();
    superagent.on('request', function (request) {
      if (request.url[0] === '/') {
        request.url = 'http://127.0.0.1:3001' + request.url;
      }
    });

Goodluck

**Comment by BenLorantfy** [comment]
Even if there's a plugin that addresses this issue, isn't this a common use case and a good feature to have in the core library?
