### ISSUE TITLE
Superagent call when javascript is Off on the browser

### ISSUE THREAD

**Issue by hverma11** [visionmedia/superagent#527]
Hi Team,

   I am working on the isomorphic application and want to post the request using superagent. It is working fine when javascript is ON. When I made Javascript OFF , post request is not getting triggered.

Snippet :

In XClient.js
 addX:function(award){
        request
            .post('http://localhost:8080/xx')
            .send(award)
            .set('Accept', 'application/json')
            .end(function(res){
                if (res.ok) {
                    alert('yay got ' + JSON.stringify(res.body));
                } else {
                    alert('Oh no! error ' + res.text);
                }
            });
    }

This method is called from input button under Render event from React Component.
Techonogy Used : ReactJs,NodeJS,Superagent

Please suggest , if I have to use some mixin or need to additional handling  to make it work at server side.

**Comment by defunctzombie** [comment]
javascript is required
