### ISSUE TITLE
Redirect with relative location fails

### ISSUE THREAD

**Issue by sixmen** [visionmedia/superagent#542]
http://www.unizzang.com returns 302 with 'location: shop/index.php'
and
http://www.unizzang.com/shop/index.php returns 302 with 'location: main/index.php'

Final url must be 'http://www.unizzang.com/shop/main/index.php',
but superagent tries 'http://www.unizzang.comshop/index.php' and 'http://www.unizzang.commain/index.php'.

I think Request.prototype.redirect should use url.resolve to make final url.

**Comment by defunctzombie** [comment]
Sounds like a bug to me. Can you look into making a fix with failing tests?
