### ISSUE TITLE
OPTIONS support

### ISSUE THREAD

**Issue by jcristovao** [visionmedia/superagent#544]
In my preliminary testing, and with the server I'm using, a modified GET using the string `OPTIONS` instead seems to do the trick. Am I missing something, or is this enough and should I send a pull request?

```
request.options = function(url, data, fn){
  var req = request('OPTIONS', url);
  if ('function' == typeof data) fn = data, data = null;
  if (data) req.query(data);
  if (fn) req.end(fn);
  return req;
};
```

Thanks!

**Comment by defunctzombie** [comment]
I don't understand this issue.

**Comment by jcristovao** [comment]
Does superagent support the [OPTIONS](http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.2) HTTP Method?

It seems to not support it, but perhaps I'm missing something...

**Comment by defunctzombie** [comment]
I don't see it supported in the current codebase. Would review a PR that adds support on the client and server as well as tests.

**Comment by fletchowns** [comment]
This would be great for use with [Django Rest Framework|http://www.django-rest-framework.org/api-guide/metadata/].

**Comment by lgdexter** [comment]
Hate to necro, but is this supported yet? `request.options` doesn't seem to be working.

**Comment by pornel** [comment]
Options requests are fully supported as far as superagent is concerned.

Note however that *browsers* have a lot of restrictions regarding HTTP features, and may not permit you to make OPTIONS request unless you make your server explicitly permit it in [preflight request](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Access-Control-Allow-Methods).
