### ISSUE TITLE
multipart support is very broken

### ISSUE THREAD

**Issue by asadovsky** [visionmedia/superagent#546]
- The example on the webpage doesn't work (part() is deprecated, and Part.set() throws): http://visionmedia.github.io/superagent/#multipart-requests
- Nearly all the tests are commented out: https://github.com/visionmedia/superagent/blob/master/test/node/multipart.js

This does not inspire confidence...

**Comment by seriousben** [comment]
I've had lots of socker hangup recently while using multipart requests... I wish there would be good alternatives..

**Comment by defunctzombie** [comment]
I think this is actually fixed in master, but there hasn't been a release in a while. I will try to cut a 1.0.0 RC for folks to try out.

**Comment by asadovsky** [comment]
The tests are still all commented out, so I don't understand why this issue was closed.
Has anyone verified that this actually is fixed in master?

**Comment by formula1** [comment]
Multipart has not been working for me either. However my situation may be unique(ish) https://github.com/felixge/node-form-data/issues/90

https://gist.github.com/formula1/582b2acb8c1e6513fe1a
