### ISSUE TITLE
Parsing vendor response types: application/vnd.github.repo.v1+json

### ISSUE THREAD

**Issue by jphastings** [visionmedia/superagent#550]
It'd be sweet if super agent could parse responses which declare themselves as being a custom data type that conforms to JSON: `Content-Type: application/vnd.github.repo.v1+json` can be assumed to be JSON parseable.

**Comment by nw** [comment]
It does! I believe this change hasn't been published on npm yet.

**Comment by defunctzombie** [comment]
`request.parse` is what you want

```
request.parse['application/vnd.github.repo.v1+json'] = JSON.parse
```

**Comment by jphastings** [comment]
Ha! Awesome - thanks so much :)
