### ISSUE TITLE
Superagent fails to parse responses without a body

### ISSUE THREAD

**Issue by gabrielecirulli** [visionmedia/superagent#551]
I'm performing an ordinary POST request to an API endpoint which, when successful, returns an empty response body and the 201 status code. At the moment, superagent fails by trying to parse it as JSON, which causes `SyntaxError: Unexpected end of input` to be thrown. This in turn makes superagent assume that the entire request has failed, which is wrong.

Since it is not out of the ordinary to have APIs respond with empty bodies when transactions are performed, I wanted to ask if superagent is aware of this and/or it's something that needs to be fixed.

**Comment by defunctzombie** [comment]
It should be fixed but I think a 201 should be sending back something. A 204 is the one that can send back no body.

**Comment by defunctzombie** [comment]
Is this a browser or client issue?

**Comment by gabrielecirulli** [comment]
Browser, sorry. So not all responses can contain empty bodies?

**Comment by defunctzombie** [comment]
What content type is being sent in the response? Likely we could handle no body a bit better. If you can make a failing example or test case that would help.

**Comment by kingedward** [comment]
I've got the same problem... I my world, the response of for example an delete-request, is perfectly fine without an body (just 200OK as response code).

**Comment by rodsouto** [comment]
Same issue here, sending a DELETE request that returns 204 I get "Uncaught SyntaxError: Unexpected end of input"

**Comment by defunctzombie** [comment]
I checked the test suite and we have tests for 204 no content responses. For those hitting this error, please provide a failing example, otherwise there may be other things going on with your request/response that is not clear here.
