### ISSUE TITLE
Investigate impact of using `qs` module on client

### ISSUE THREAD

**Issue by defunctzombie** [visionmedia/superagent#552]
Right now the client code uses a half-baked serialization format for query strings.

https://github.com/visionmedia/superagent/issues/128

**Comment by rps** [comment]
```npm install superagent``` gives a dependency of ```"qs": "1.2.0"``` which has some issues

**Comment by jeffreywescott** [comment]
Now it gives "qs:" : "^3.1.0" ... should be okay, right? Consistent behavior across the node and client versions seems essential to me ... (see again #128)

**Comment by PedroEsperanca** [comment]
still 1.2.0 ..

**Comment by wavded** [comment]
Just got bitten by this in an isomorphic React app.  Used `Qs.stringify` on the browser side as well to get around it but would love to see it fixed.  To recap, browser-side was producing the grievous `a=1,2,3` and server was producing the proper `a[1]=1&a[2]=2&a[3]=3`

**Comment by DylanPiercey** [comment]
What about just using the native node [querystring](https://github.com/Gozala/querystring)?

**Comment by pornel** [comment]
`qs` almost doubles size of superagent.js, so it's not so good for the browser version. Currently we still use our own thing in the browser, but since v1.5 it's closer to what Node does.
