### ISSUE TITLE
Support for Tokens

### ISSUE THREAD

**Issue by emiidee** [visionmedia/superagent#562]
Tokens should be automatically saved and sent the way cookies are

To avoid having to do this for every authenticated route:
```
authenticatedAgent
  .get(url)
  .set('authorization', 'Bearer ' + token)
  .end(function(err, res) {
    // do stuff
  });
```

**Comment by defunctzombie** [comment]
We don't support cookies currently (that I am aware of) and this this feature is left to the user.
