### ISSUE TITLE
Optional filename is not properly used with .attach() function

### ISSUE THREAD

**Issue by Noxalus** [visionmedia/superagent#568]
Hello everyone,

I already searched the solution to this problem here, and I found some related issues like this one: https://github.com/visionmedia/superagent/issues/381

I have the exact same problem, except that I must provide some additional fields. I tried the "secret sauce" suggested by *gollygeewizard* but I always get a 400 HTTP error.

This following code upload a file properly on my service, but the filename is wrong, **superagent** uses _name_ field filled by **multer** (what I use to handle  multipart/form-data):

```js
superagent
    .post(url)
    .set('Authorization', token)
    .attach('file', file.path, filename)
    .field('field1', value1)
    .field('field2', value2)
    .end();
```

What I tried to do is something like that:

```js
let fs = require('fs');
let data = fs.readFileSync(file.path);

superagent
    .post(url)
    .set('Authorization', 'Token ' + req.token)
    .set('Content-Type', file.mimetype)
    .set('Content-Disposition', 'attachment; filename=' + filename)
    .set('Content-Length', data.length)
    .send(data)
    .field('field1', value1)
    .field('field2', value2)
    .end()
```

I've tried to change functions call order (field before attach, etc...), but doing that still result to a 400 error.

Do you know why filename is ignore in the attach function?

**Comment by Noxalus** [comment]
This issue has been fixed on master, I used the last version available on npm (https://www.npmjs.com/package/superagent) without the changes from the last 4 months.

**Comment by misaunde** [comment]
I was following this tutorial: https://developer.atlassian.com/blog/2015/11/scripting-with-node/#packaging-shell-commands 
and experienced the same results (was ignoring filename).

Neither this:
`.attach('file', file, 'my-title')`
or this:
`.attach('file', file, {filename: 'my-title'})`
worked for me...

Using "superagent": "^3.6.3" in my package.json...

**Comment by pornel** [comment]
@misaunde The filename is sent as part of `content-disposition` header inside multipart body. Whether it's used on the server depends entirely on the library you use to parse multipart requests.
