### ISSUE TITLE
interface for response status message

### ISSUE THREAD

**Issue by Jxck** [visionmedia/superagent#570]
current implementation gives res.status or res.status for browser and server.
but I wanna get status message like 'Not Found' for 404.

I could get that from..
server: `res.res.statusMessage`
browser: `res.xhr.statusText`

but adding interface for `res.statusMessage` seems fine.
If you guys agree with me, ofcourse I can send you a PR for that :)

thanks.

**Comment by rase-** [comment]
Seems like a good idea to me. Thoughts @defunctzombie?

**Comment by defunctzombie** [comment]
yep, seems pretty reasonable to expose that out.

Does the browser generate the statusText for us? or is that something the library is populating and we just want to expose it better?

**Comment by defunctzombie** [comment]
added `res.statusMessage` in commit 77aa6c0 for error handling revamp.
