### ISSUE TITLE
Middleware for end()

### ISSUE THREAD

**Issue by codesuki** [visionmedia/superagent#571]
I ran into the situation that I have to check for several errors in each request which is kind of annoying to check in every end() callback. With this I can just provide a Request object that has the needed Middleware and use instead.
Maybe I misunderstood the Superagent API and it is actually very easy to do that somehow, if so, please let me know!

https://github.com/codesuki/superagent-intercept

**Comment by defunctzombie** [comment]
Seems like your module handles exactly what you want. If that is not the case, please describe more specifically what you are looking for.

**Comment by codesuki** [comment]
Sorry, I just wondered if there is a more official way. I didn't make that clear above.

**Comment by defunctzombie** [comment]
Not to my knowledge. I think plugins are the way to go for that stuff.

**Comment by codesuki** [comment]
Ok thanks!

**Comment by dncrews** [comment]
A friend of mine wrote https://github.com/camshaft/superagent-defaults. It allows you to set defaults for all of your calls, e.g.
1. If on __every request__ you set the same accept headers;
2. If on __every request__ you check for the same errors (using `.on('response', fn`)
3. If on __every request__ you do the same authentication
4. Or if you need to define your own request methods

It's more DRY than using a .use for every superagent call. Might be more like what you're looking for...

**Comment by defunctzombie** [comment]
We should start throwing these up on the wiki or even the docs pages.
