### ISSUE TITLE
Breaking API change (1.0.0): error on status 400

### ISSUE THREAD

**Issue by kmalakoff** [visionmedia/superagent#580]
I just wanted to make sure this wasn't a mistake because it is breaking all of our uses of superagent with a callback like `(err, res)` so we are locking to 0.x.

Is this change to both send an error and the response the desired behaviour: https://github.com/visionmedia/superagent/blob/master/lib/node/index.js#L771

With standard node callbacks, we are used to getting an error or the response (not both) and all of our client code has been written assuming this, e.g. errors are only for things like parsing errors, not expected HTTP response codes.

**Comment by defunctzombie** [comment]
This is indeed an expected breaking API changed that was discussed in an issue as well as this PR

https://github.com/visionmedia/superagent/pull/554

The thinking, to summarize, is that any non success http response is an error. If you want to know if it is a network error or something else, you can use `err.status` or see if there is a response object as well as an error.

This is documented in the changelog and the reason for the 1.x release to indicate API change was breaking.

**Comment by kmalakoff** [comment]
Wow! This is not a good API change.

Down-vote. We'll stick with 0.x.

**Comment by defunctzombie** [comment]
Why do you feel like that is not a good API change?

/cc @gjohnson

**Comment by kmalakoff** [comment]
I've added a comment on https://github.com/visionmedia/superagent/pull/554

**Comment by kmalakoff** [comment]
@defunctzombie has chosen to stay the course on this change despite:

1) that the change breaks the Node callback conventions
2) is against the original design philosophy of superagent 

Forked: https://github.com/kmalakoff/superagent-ls and https://www.npmjs.com/package/superagent-ls. I'll aim for a first release the weekend.

I'm happy to accept for issues and pull requests for this fork. 

Please star [the superagent-ls repo]( https://github.com/kmalakoff/superagent-ls ) to show your support for reverting the 1.x API would be great, too  :smirk:

**Comment by kmalakoff** [comment]
superagent-ls has been released on npm: https://www.npmjs.com/package/superagent-ls and component.io

Please star and use [the superagent-ls repo]( https://github.com/kmalakoff/superagent-ls ) to show your support for reverting the 1.x API  :smirk:
