### ISSUE TITLE
Repeated query string keys are transformed into bracket notation

### ISSUE THREAD

**Issue by RamIdeas** [visionmedia/superagent#581]
I'm dealing with an API which requires me to add the same querystring key multiple times, where the order is significant.

``` js
var sa = require('superagent')
sa.get('http://my-api.com/user?sort=lastName&sort=firstName').end(...);
```

But the request is sent to `'http://my-api.com/user?sort[0]=lastName&sort[1]=firstName'`. However, the API does not accept this format.

The issue is caused by passing a hard-coded `true` to `url = parse(url, true);` in `Request.prototype.request` where parse is defined: `var parse = require('url').parse;`.

Is it a viable solution to surface this boolean option?

**Comment by defunctzombie** [comment]
Which version of superagent?

**Comment by RamIdeas** [comment]
Sorry, I somehow had 0.21.0 installed. Only started this project last week, so not sure how/why npm did that.

I've got 1.1.0 now and it works just fine :)
