### ISSUE TITLE
List of breaking changes

### ISSUE THREAD

**Issue by menelaos** [visionmedia/superagent#583]
Hey, 
would it be possible to extend the changelog as to what are the breaking changes in 1.0? 
Today I was bitten by the removal of arity checking in `.end()` callbacks and it took me a little bit too long to find out why. This could save other people some time.

Also, the last example in http://visionmedia.github.io/superagent/#request-basics will need to be changed accordingly. 

Thanks for your work!

**Comment by mferraco** [comment]
Can you give an example here as to what has changed and how to fix it?  I am having issues as well.

**Comment by menelaos** [comment]
The issue I am referring to is that previously superagent checked the number of arguments of the callback passed to `.end()` and took actions accordingly. Now (as discussed in #283), it expects a `function (err, res) {}`. 
Thus
```javascript
request('/search', function(res){

 });
```
will need to be changed to
```javascript
request('/search', function(err, res){

 });
```
While I support this change, I think it should be mentioned somewhere that this can break existing code. Currently, it is not clear to me which of the changes in history.md are breaking changes.

**Comment by insin** [comment]
An upgrade guide `.md` would be useful. I'd be willing to contribute to it, but I'm still trying to divine the correct way to deal with 1.0.0 changes from commit notes and issue discussions.

**Comment by basti1302** [comment]
FWIW, there is already an upgrade guide. It's just not linked to or advertised anywhere, so nobody will see it.

https://github.com/visionmedia/superagent/wiki/Migrating-0.x-to-1.x

**Comment by insin** [comment]
Sweet, thanks!

**Comment by vinayakkulkarni** [comment]
Is there a migration guide for let's say v5.x to v7.x ?
