### ISSUE TITLE
.withCredentials() fails in node context

### ISSUE THREAD

**Issue by dennishall1** [visionmedia/superagent#586]
The node version of superagent does not create a `withCredentials` method.  Code that is shared with node and the browser (in my case, an api-connection helper) will fail in the node context if it invokes `withCredentials`.

**Comment by Keepcase** [comment]
+1 Running into the same issue.

**Comment by Keepcase** [comment]
+1

I'm running into the same issue as well.

**Comment by arielschiavoni** [comment]
+1

**Comment by Lucas-Gluchowski** [comment]
+1

**Comment by alex94puchades** [comment]
Related to #690

**Comment by scags9876** [comment]
+1

**Comment by focusaurus** [comment]
Do we just need a no-op function on the node side or some particular behavior?

**Comment by markdalgleish** [comment]
Not sure why this issue has so many +1s when it was a 5 minute fix. I've just issued a PR with a fix for this, including a test case, so hopefully it's satisfactory :)
