### ISSUE TITLE
All 1.0.0 releases miss the pre-build superagent.js

### ISSUE THREAD

**Issue by basti1302** [visionmedia/superagent#587]
The file superagent.js is missing from the 1.0.0 releases on bower, component and npm. Is this intentional? I see that is has been removed from the git repo (probably to keep diffs clean) which makes sense. But I think the releases should still have the pre-build browser build for people that just want to include superagent with a script tag and not use browserify.

**Comment by novabyte** [comment]
I agree with @basti1302 it'd be nice to continue to easily grab a pre-built browser build of `superagent.js` from Bower.

**Comment by defunctzombie** [comment]
I specifically removed it from the repo because it isn't something I want to keep building and storing in version control. If anyone knows of a CDN that will accept files we can look into that.

Bower is not a package manager we support.

**Comment by lattmann** [comment]
@defunctzombie: I completely agree with you on not checking the built artifacts into the git repository. We do the same in our projects.

Is it possible that you would still pre-build superagent.js for browsers as part of the `npm prepublish` script? At least people using npm will get it and you will not need to check it into the repository.
https://docs.npmjs.com/misc/scripts

Thanks.

**Comment by defunctzombie** [comment]
People using npm can use browserify. There is also a browserify CDN (I
forget the link) but I should add that to the readme and it can provide the
prebuilt file.

**Comment by lattmann** [comment]
Understood, thanks.

**Comment by defunctzombie** [comment]
For reference:
https://wzrd.in/standalone/superagent@latest or https://wzrd.in/standalone/superagent@1.1.0

via https://github.com/jfhbrook/browserify-cdn Which you can use for any npm module that can build via browserify.

**Comment by pmeijer** [comment]
From the current readme "npm (for browser standalone) When we publish versions to npm, we run make superagent.js which generates the standalone superagent.js file via browserify, and this file is included in the package published to npm..."

So this issue is implemented from npm, correct?

**Comment by pornel** [comment]
npm version contains a pre-compiled superagent.js file.

We don't have a package for bower, so bower only gets link to the repository, which does not have any precompiled files by design.
