### ISSUE TITLE
[discuss] allow creation of separate instances of superagent

### ISSUE THREAD

**Issue by kmalakoff** [visionmedia/superagent#591]
We have been struggling with a problem with parsers being global as we use superagent as a basis for internal libraries. 

The problem is that one developer may register a parser for XML as being xml2js and another one just wants to use the XML text, but if both libraries are included, one stomps on the other depending on require ordering.

I saw in a previous issue: https://github.com/camshaft/superagent-defaults where they provide a way to create and set defaults for instances of superagent. 

I was wondering what people thought about making the instance creation a first class implementation in superagent (perhaps with reduced or different functionality than superagent-defaults) and extending it to include parsers and serializers.

Global use (as it is now)

```
request = require 'superagent'
request.parser['application/xml'] = request.parser.text # (server only). Now we could have stomped on a dependent library's 'application/xml' parser

request.get('/url.xml').end (err, res) ->
request.get('/url2.xml').end (err, res) ->
```

Instance use (new solution)

```
request = (require 'superagent')() # create instance
request.parser['application/xml'] = request.parser.text # (server only). 'application/xml' parser only used on all requests in this module

request.get('/url.xml').end (err, res) ->
request.get('/url2.xml').end (err, res) ->
```

We have encountered this problem internally and switched to doing the parsing in the end function to make the selection of the parser reliable. It think this has a potential to be a problem as more libraries use superagent.

What do other people think?

Maybe another approach would be to make deprecate globals and instead introduce async middleware for processing responses (like express) in addition to the current middleware for modifying requests.

**Comment by defunctzombie** [comment]
Overall I am +1 on the idea. The global parsers are one of the places where the lines between module and global ajax like library are blurred.

I will say that I think that the instances should have some sane defaults as they do today with the option to override those defaults.

**Comment by kmalakoff** [comment]
There is the middleware approach that also might work:

```
request.post('/url')
  .use(parser)
  .end (err, res) ->
```

Or even specialized functions:

```
request.post('/url')
  .parser('application/xml', xmlParser)
  .end (err, res) ->
```

In either case, by default superagent could first register the defaults and then overrides or new parsers could be added by the caller.

I think the question comes down to whether having globals for superagent makes sense in a world where it it used inside libraries who cannot control what others set.

Finally, we have created what we call a superagent factory which abstracts out the get, post, put, head, del functions (plus default signature variants) so that we can derive and create defaults from request.Request. This could be a way to allow library writers to define their own base Request class with their own defaults.

Lot's of ideas...it would be great to agree a direction for library writers. Personally, I avoid globals so I would even support a proposal that went as far as deprecating them.

**Comment by defunctzombie** [comment]
Can't this middleware approach be implemented today with no changes to the codebase?

**Comment by kmalakoff** [comment]
Sure, with monkey patching, keeping the global settings problems unaddressed, etc.

I'd like to see what people think is the best API for safe usage of superagent across libraries and modules. 

We have created a superagent factory for subclassing Requests which could be part of one approach if they get their own configuration settings. Maybe exposing the parsers and serializers on the Request with chaining helper methods could be another approach. I think either of these are preferable to using middleware to monkey patch superagent..

**Comment by defunctzombie** [comment]
Agreed on pre/post flight not being hook-able currently. Maybe `use` could be extended to accept `options` or a `when` value that would hook the used function into various predefined locations in the lifecycle.

**Comment by matthewmueller** [comment]
+1 to this change as well. 

I thought `post` was hookable via `.parse(fn)`. I guess `pre` could be hooked in via `.use(fn)`, maybe. Maybe I'm misunderstanding what you mean though.

**Comment by pornel** [comment]
In #1302 `request.agent()` creates a reusable copy of superagent and sets default settings.
