### ISSUE TITLE
Documentation: https://visionmedia.github.io/superagent/#error-handling still shows pre-1.0 error handling

### ISSUE THREAD

**Issue by yourcelf** [visionmedia/superagent#595]
The documentation at https://visionmedia.github.io/superagent/#error-handling describes error handling in the pre-1.0 fashion, where non-2xx responses don't always have a non-null error argument.

Unless the discussion in #283 results in this change being reverted, the documentation should be updated to reflect current behavior.

**Comment by defunctzombie** [comment]
fixed
