### ISSUE TITLE
How to get cookie from responce?

### ISSUE THREAD

**Issue by leedut** [visionmedia/superagent#597]
I used superagent & cheerio to get something from my college's homepage.
The website needs log in and it uses Asp.Net.Session .
I need to post email&psw to get the SessionID, and then send a get-request with the SessionID.

But I don't find cookie from the post-request's responce.
So how to get cookie from responce?Thank you~

Here is my superagent code:
superagent.post('http://XXX.com/Default.aspx').set('Content-Type','application/x-www-form-urlencoded').set('Access-Control-Allow-Origin','*').accept('application/json').send({//some data}).end(function(err,result){
      //result.text?result.header?
});

**Comment by defunctzombie** [comment]
look at `result.headers` and then pull out the cookie header. You will need a cookie module to parse it I believe.

**Comment by leedut** [comment]
I've got it.
The homepage will jump into another page when it receives email&psw.
So <code>result.headers</code> i got is the header of next page. Second page doesn't include the cookies infor.
I use <code>redirects(0)</code>  and it works~  
THX~

**Comment by nspeedzy** [comment]
the `result.headers` says undefined for me. Any ideas?
