### ISSUE TITLE
all headers not found in response

### ISSUE THREAD

**Issue by Agrosis** [visionmedia/superagent#598]
I have a vagrant machine set up with an nginx frontend reverse proxying a service. Whenever i use superagent (from my host machine) to make a GET or POST request (through the nginx frontend), in the headers field I only see a Content-Type header. I cURLed the same URL and I get all the headers that I'm expecting.

Specifically, I'm trying to be able to set a cookie from the service, but I can't since the headers aren't coming through all the way. Any reason for this?

**Comment by defunctzombie** [comment]
Without a failing example it could really be anything or nothing.

**Comment by Agrosis** [comment]
I wasn't really sure if pasting code or config would work, there was a lot of space where it could've been. But I just figured out that apparently cookies and those additional headers won't come in if I'm on a localhost domain, so there has to be at least 2 levels, a custom dns name like www.localhost or 127.0.0.1 will have to be used.

Thanks!
