### ISSUE TITLE
How can I get superagent.js ?

### ISSUE THREAD

**Issue by drypot** [visionmedia/superagent#600]
/superagent.js is gone.
bower is not supported.
What is the easist way to get superagent.js ?

**Comment by defunctzombie** [comment]
Build it using browserify

**Comment by ilyaigpetrov** [comment]
`echo "window.superagent = require('superagent')" | browserify - > superagent.js`, but I wish I could get a prebilt bundle from `visionmedia/superagent/dist/superagent.js`.

**Comment by stephanebachelier** [comment]
@ilyaigpetrov Since this is an issue since 0.21.0, I've published superagent-dist on bower, that just bundle and release the new version with the same semver.
