### ISSUE TITLE
Calling POST method to send array to php backend.

### ISSUE THREAD

**Issue by sunglee** [visionmedia/superagent#602]
In jQuery, I am able to call POST method with array like this:
```
var ary = [1, 2, 3];
   $.post(
   '/api/path/',
   {ids: ary},
   callback_func,
   'text'
);
```
Is it possible with superagent?
I tried
```
var ary = [1,2,3];
request
   .post('/api/path/')
   .send({ids: ary})
   .end(function(err, res) {
   ...
   }
```
It seems res.ok is true, but my php backend didn't recognize:
```
<?php
   is_array($args['ids'] //is false
?>
```

**Comment by defunctzombie** [comment]
Not sure what the issue is, but we would need a failing test showing the POST failing. It is likely your php code is not processing the POST params correctly (I don't know PHP). Try stackoverflow.
