### ISSUE TITLE
Issues sending certain mimeTypes with formdata

### ISSUE THREAD

**Issue by James1x0** [visionmedia/superagent#604]
This is most likely a superagent issue, not a chai-http issue, so I will post it here.
Original issue: chaijs/chai-http#36

I have a test that attaches a csv/xls/xlsx (all in separate tests) to send to a busboy route. Busboy interprets the csv as a file, but the xls/xlsx as a field (form field). I have also seen the same behavior with png files, but works with jpg. **Sending from the browser works fine**, which is why I think this is a superagent issue.

Since chai-http acts as a wrapper to superagent issues, all of these hooks should just proxy to superagent.

``` javascript
// Works and interprets as file so I can pipe the data into a writeStream
chai.request(app)
  .post('/my-busboy-endpoint')
  .attach(fs.readFileSync('mycsvfile.csv'), 'mycsvfile.csv');

// Does not work and busboy interprets as a field
chai.request(app)
  .post('/my-busboy-endpoint')
  .attach(fs.readFileSync('myexcelfile.xls'), 'myexcelfile.xls');
```

Debugging the request I do get the -webkit boundary data the same both requests. Would it be possible to add a test case?

**Comment by James1x0** [comment]
Bump

**Comment by pornel** [comment]
That's an old issue. It's probably been fixed (we have mapping of extensions to mime types, plus we now support options object for attach).
