### ISSUE TITLE
request.get(...).send(...) not populating querystring

### ISSUE THREAD

**Issue by yourcelf** [visionmedia/superagent#606]
The [documentation](https://visionmedia.github.io/superagent/#query-strings) indicates that a call to ``request.get(...).send(...)`` should invoke ``.query(...)``, so that the data given to ``send`` populates the querystring rather than a POST body.

This doesn't seem to be working; the querystrings from a request build with ``.send`` are empty.  I'll include a PR with failing test case shortly.

**Comment by focusaurus** [comment]
Docs updated to no longer indicate this API. Thanks for finding this issue!

**Comment by vmasto** [comment]
Greetings, this also appears on the README of the repo (under installation)

https://github.com/visionmedia/superagent#installation

**Comment by focusaurus** [comment]
The only instance of `.send()` I see in the README is for a `POST` request, which defines the request body to be sent as always. This particular issue pertains specifically to GET requests.

**Comment by vmasto** [comment]
Ahh, my apologies, I naively assumed it was an all-in-one like jQuery's `data` property.
