### ISSUE TITLE
Auto-parsing image type - suggestion to revert PR 300

### ISSUE THREAD

**Issue by kmalakoff** [visionmedia/superagent#611]
Ever since 0.18.1, we have been unable to pipe image data using superagent. 

We've chased it down to the following pull request: https://github.com/visionmedia/superagent/pull/300 and specifically: https://github.com/nebulade/superagent/commit/c65b7758bced00c656bf6ae6734cc39c3e7007a0#diff-c24ce7e3da4c0e4ff811a2b6a76f8bd9R728

There's not much of an explanation on why this is desired default behaviour especially when it breaks streaming. 

What would people think to reverting this change as it really belongs in the application logic layer not a network transport layer?

**Comment by defunctzombie** [comment]
I would be down for reverting it. This seems a bit too assuming especially if we have streaming.

As an aside, can we detect streaming and support both?

**Comment by kmalakoff** [comment]
Great!

Not sure if streaming can be detected because we pipe the stream in the end function after the parsers have been applied and status codes have been checked.

Disabling parsers or forcing streaming (server only) could be selected via an option or chained function, but this brings back to the question of whether there should be global parsers or isolated instances of superagent with their own settings as alternative API changes.

**Comment by kmalakoff** [comment]
OK. I've reviewed the code and wanted to run a few ideas by you...

1) should the image parser still be bundled with superagent? For example, I could move it into a module like superagent-parser-image. I think the parser is quite simple so this might be overkill, but depending on 2), it might still be best to keep superagent lean.

2) it looks like there is some custom type checking logic (https://github.com/nebulade/superagent/commit/c65b7758bced00c656bf6ae6734cc39c3e7007a0#diff-c24ce7e3da4c0e4ff811a2b6a76f8bd9R728) which if it is moved to a library, will need a way to be hooked up. The logic is basically extracting the major type (image) before the slash and using that as the check. A few options:

a) allow parsers to be registered by major type, eg. image. Of course, it doesn't make a lot of sense for 'application/*' lookups. This would be quick and dirty, but probably handle most cases.

b) expand and generalize the "type to parser key" lookup API. Unfortunately, this would require people to know that they may need to register in two places (one for the parser name and another for the parser itself). For example, isText and isImage would register custom typeToParserKey functions and the parser key would end up being a name for the parser instead of a mix of types and keys.

c) move away from the object/key lookup and add API that either takes a function or key, and the parser (stored in an array). It could work both at the global level and the Request instance level:

Global API
```
request = require 'superagent'
request.parser(isImage, parseImage) # only this format would be supported for non-string keys
request.parser('application/xml, parseXML) # or request.parser({'application/xml: parseXML})
```

and/or

Local API
```
request = require 'superagent'

request.get('/images/1234')
  .parser(isImage, parseImage)
  .end (err, res) ->


request.get('/xmls/1234')
  .parser('application/xml', parseXML)
  .end (err, res) ->
```

I kind of think 2 is the worst API, but either 1 or 3 could be acceptable.

Thoughts? I'm happy to implement this, but if 2 or 3 is chosen, it could bump superagent's major release number.

**Comment by pornel** [comment]
That's an old issue. Parsing has been refactored again. It's still a bit wonky, but there's `.buffer(false)` and `req.pipe()`.
