### ISSUE TITLE
when pipe, what about `headers`?

### ISSUE THREAD

**Issue by alsotang** [visionmedia/superagent#614]
I am using superagent to build a web resource proxy api. And the source of the api is some image resources.
there are `cache-control` header in these resources, but when I pipe them with superagent. All headers lost. And then the clients request the api every time they access my site.

I try `request`(https://github.com/request/request/) and it works. request would preserve original headers.

And I dive into source code of both. It's true that superagent do not do anything about original headers.

**Comment by alsotang** [comment]
I wanna fix this issue myself. but I think all things about protocol is accurate work. Though I can solve problem about mine, I dont know the right solution.

**Comment by defunctzombie** [comment]
If request works I would use request. I believe the pipe in this module is for data only.
