### ISSUE TITLE
find it's hard to use superagent to do reverse proxying

### ISSUE THREAD

**Issue by undoZen** [visionmedia/superagent#622]
I can't do things like

```js
req.pipe(superagent(req.method, endpoint + req.url)).pipe(res);
```

cause `pipe()` called `end()` and it will break piped data from `req`

**Comment by defunctzombie** [comment]
Superagent is not designed for reverse proxying. You can do it, but it isn't ideal IMO. Maybe you need `{ end: false}` on the first pipe.
