### ISSUE TITLE
Cloning a request

### ISSUE THREAD

**Issue by prayerslayer** [visionmedia/superagent#623]
Hello there!

I’d like to have a plugin for superagent that abstracts the OAuth2 Implicit Grant flow away from me. I’d just define some configuration (e.g. where is the authentication endpoint, what’s my client id…) and off we go. This API is what I want to achieve:

    superagent
    .get('http://some.ser.ver/whatever/resource/id')
    .oauth(myOAuthProviderObj) // see below
    .exec() // promisified end()
    .then(....) // business logic

What `.oauth()` would do:

1. Check if I have an access token somewhere
2. If I do, send the request
3. If it fails with `401`, check if I have a refresh token
4. If I do, use it to get a new access token
5. Go to 1.

Actually I’m almost finished. One problem that I have though: I might have to call the original request twice (at step 2). I can’t just call `end` again, since this test fails.

~~~
it('should send a request twice', done => {
  let req = superagent('localhost');
  req.end(err => {
    req.end(err2 => {
      done();
    });
  });
});
~~~

The other solution is to clone the original request, so that when I encounter step 2 the second time, I’ll send not the same request but a perfect copy. This is nasty though because `Object.create` doesn’t do the initialization of a new request. I ended up doing this:

~~~
function clone() {
  let doppelganger = new superagent.Request();
  doppelganger.method = this.method;
  doppelganger.url = this.url;
  doppelganger._query = this._query;
  return doppelganger;
}
~~~

Obviously this is both incomplete (what about form data or the request body when POSTing?) and implementation-specific. What I’d rather have is something along the lines of `request.clone()`.

What do you think? Do you happen to have any other solutions maybe? It’s late already :)

**Comment by prayerslayer** [comment]
Bumpy!

It’s been two weeks and I’ll need this in production probably as soon as next week. Depending on a forked superagent is nothing that excites me though, so would you mind sharing your opinion on whether this is a desirable functionality (=> you would accept the PR) in the first place? If not I’d be very interested in an alternate solution where I don’t need to patch superagent.

Reasons putting `clone` into superagent:

* From the outside I don’t know whether I’m using the Node or Browser request and as a library user I don’t care, actually.
* State needed for cloning might not be available from the outside.

Thanks for your time and consideration!

**Comment by defunctzombie** [comment]
Commented in the PR.

**Comment by agrohs** [comment]
> Hello there!
> 
> I’d like to have a plugin for superagent that abstracts the OAuth2 Implicit Grant flow away from me. I’d just define some configuration (e.g. where is the authentication endpoint, what’s my client id…) and off we go. This API is what I want to achieve:
> 
> ```
> superagent
> .get('http://some.ser.ver/whatever/resource/id')
> .oauth(myOAuthProviderObj) // see below
> .exec() // promisified end()
> .then(....) // business logic
> ```
> 
> What `.oauth()` would do:
> 
> 1. Check if I have an access token somewhere
> 2. If I do, send the request
> 3. If it fails with `401`, check if I have a refresh token
> 4. If I do, use it to get a new access token
> 5. Go to 1.
> 
> Actually I’m almost finished. One problem that I have though: I might have to call the original request twice (at step 2). I can’t just call `end` again, since this test fails.
> 
> ```
> it('should send a request twice', done => {
>   let req = superagent('localhost');
>   req.end(err => {
>     req.end(err2 => {
>       done();
>     });
>   });
> });
> ```
> 
> The other solution is to clone the original request, so that when I encounter step 2 the second time, I’ll send not the same request but a perfect copy. This is nasty though because `Object.create` doesn’t do the initialization of a new request. I ended up doing this:
> 
> ```
> function clone() {
>   let doppelganger = new superagent.Request();
>   doppelganger.method = this.method;
>   doppelganger.url = this.url;
>   doppelganger._query = this._query;
>   return doppelganger;
> }
> ```
> 
> Obviously this is both incomplete (what about form data or the request body when POSTing?) and implementation-specific. What I’d rather have is something along the lines of `request.clone()`.
> 
> What do you think? Do you happen to have any other solutions maybe? It’s late already :)

I have the exact same usecase @prayerslayer, where did you ever land on this/what solution did you use? I'd gladly swap out superagent in general but Im looking to add oauth as a PR into an existing library that is already using superagent
