### ISSUE TITLE
Progress event not fired unless added before `end` is called.

### ISSUE THREAD

**Issue by tmathews** [visionmedia/superagent#624]
You should still be able to register events after end is called to the request object after the end method is called. [Here](https://github.com/visionmedia/superagent/blob/8486ffe551eb1a9771eb6602f1f7c144bc44d065/lib/client.js#L925) you can see that it only registers the `progress` event if it has been preregistered. This should be fixed.

**Comment by kornelski** [comment]
No, end is the end.

**Comment by tmathews** [comment]
Ripadipdip :skull:
