### ISSUE TITLE
Multiple-value parameter

### ISSUE THREAD

**Issue by asarr** [visionmedia/superagent#631]
Hi there,

I've been facing issue passing multiple value parameter using chai-request which merely make use of superagent for http requests:

request("myUrl").get("/v1/skus?id=123&id=456")...

this request got encoded and the server receives id[0]=123&id[1]=456 which is totally different than the expected format by the server.

Otherwise - using .query({id: "123", id: "456"}) or 
.query({id: "123"})
.query({id: "456"})
override the initial value so only one param is getting sent.

Is there any reason the query param list get encoded ? What I want to achieve is this:

/skus?id=1&id=2&id=3.....

I might be doing it wrong - in this case could you please advice how to pass multiple param values ?

Cheers

**Comment by jtwebman** [comment]
I am having this same issue using the supertest which uses this library!

I am writing a test where I want to pass multiple values into the same query string item to make it an array. I am using the connects library that likes me add [] to the end and makes sure it is an array on the server side. If I pass just one like this:

```javascript
request(app)
    .get('/balance_records/?types[]=BalanceCredit')
```
Supertest does the correct thing and doesn't add anything to the url:

/api/v1/accounts/1-VzLqGc7vJK/balance_records/?types%5B%5D=BalanceCredit

But if I pass mutiple like this:

```javascript
request(app)
    .get('/balance_records/?types[]=BalanceCredit&types[]=BalanceDebit')

//or
request(app)
    .get('/balance_records/')
    .query({ 'types[]': ['BalanceCredit', 'BalanceDebit'] })
```

Supertest injects array elements like so:

/api/v1/accounts/1-VzLqGc7vJK/balance_records/?types%5B%5D[0]=BalanceCredit&types%5B%5D[1]=BalanceDebit

What I need is:
/api/v1/accounts/1-VzLqGc7vJK/balance_records/?types%5B%5D=BalanceCredit&types%5B%5D=BalanceDebit

Is there a way to turn this off or remove it. At least adding an option to override the default and allow for this way of handling arrays would be nice.

**Comment by xogeny** [comment]
I have also run into this.  Was there any resolution to this?

**Comment by jtwebman** [comment]
I just did like below and it seem to work.

```javascript
request(app)
.get('/balance_records/')
.query({ types: ['FlashDisplayCreative', 'ImageDisplayCreative'] })
```

**Comment by xogeny** [comment]
What query string did it generate?  Does it produce:

```
?types[0]=FlashDisplayCreative&types[1]=ImageDisplayCreative
```

or

```
?types=FlashDisplayCreative&types=ImageDisplayCreative
```

I'm using the version bundled with `traverson` right now (which is, presumably, an older version).

**Comment by Kinjeiro** [comment]
Any updates? This problem is now urgent

**Comment by pornel** [comment]
It does the latter.

BTW: you can use whatever serialization you want using your own code/library, and then set the query as a string.

**Comment by whistlerbrk** [comment]
I'm still running into this and I can't seem to just pass a string....
