### ISSUE TITLE
An empty body with PUT on ie11 sends undefined down the wire.

### ISSUE THREAD

**Issue by 4lt4i** [visionmedia/superagent#632]
The following code sends content-length: 0 and no body on FF and Chrome, but on IE11 the browser sends "undefined" with content-length: 9.

```
superagent('PUT', 'example.com').set('API-Key', 'foobar').end(function(err, res){
   // handle response
});
```

I used superagent 1.2.0, IE11 via modern.ie and tcpdump to verify this. The request was a CORS request with an initial OPTIONS call identical to Chrome and FF.

Can anyone reproduce the error?

**Comment by tux4** [comment]
I can reproduce this issue on IE 11 on Windows 8 too. My request is:

```js
superagent
  .post('example.com')
  .end(/* ... */)
```

Same as you, the request body for IE11 is 'undefined' with Content-Length: 9.

**Comment by amarnus** [comment]
Workaround:

```javascript
request.post('/foo')
.send(null)
.end()
```

Useful at least until the pull request above gets accepted.
