### ISSUE TITLE
why is superagent not A+ compliant?

### ISSUE THREAD

**Issue by davis** [visionmedia/superagent#647]
it seems like there are some libraries that add .then() to superagent's request, but I was just wondering the reasoning behind why it hasn't been included directly in the library

**Comment by defunctzombie** [comment]
Because this library doesn't use promises for the API.

**Comment by bbirand** [comment]
It is clear that you are very keen on not having anything to do with Promises, seeing as you locked a previous conversation over a pull request, and answered this one in a very blunt and uninformative fashion.

At 4000+ stars, you certainly do have the luxury of not caring at all what other members of the community think, and I appreciate that. But perhaps showing a bit more humility and providing an explanation (justification?) as to this derision against promises would be a grander goal? Like it or not, Promises are a very prevalent part of JS...

**Comment by undoZen** [comment]
@davis have a look at [promisingagent](https://github.com/undoZen/promisingagent)

**Comment by ScreenDriver** [comment]
+1 for supporting Promises
