### ISSUE TITLE
I wish your documentation made it clear multipart is broken

### ISSUE THREAD

**Issue by dukedougal** [visionmedia/superagent#650]
I spent alot of time trying to follow your docs and construct a multipart file upload using the low level API.

As far as I can tell it doesn't work at all.

It would have been helpful if the docs had conveyed this - would have saved me alot of time.

thanks

**Comment by SwiftOne** [comment]
As a specific item, the docs say:
 "Multipart requests
Super Agent is also great for building multipart requests for which it provides methods .attach() and .field()."

What isn't stated is that it appears to only support multipart/form-data, not multipart/mixed.  Saying as much would have saved me a day and seems pretty simple.  Unless I'm wrong? (he says with great hope and anticipation)

**Comment by defunctzombie** [comment]
PR for docs update is most welcome. I don't know much about the current multipart support or the limitations. Nothing is perfect so this is an oversight likely in docs or regression.
