### ISSUE TITLE
HTML5 File upload

### ISSUE THREAD

**Issue by olalonde** [visionmedia/superagent#652]
Does superagent support `req.post('/').attach(file)` where file is an HTML5 File object?

**Comment by olalonde** [comment]
Yep.

**Comment by tnrich** [comment]
This isn't working for me. Anyone else having this issue?

**Comment by focusaurus** [comment]
@tnrich could you provide your browser version details and what specifically happens when it doesn't work?

**Comment by tnrich** [comment]
Sorry this was an issue with express not handling file uploads by default.
I used the `multer` package to get them to come in. Thanks for the response
:)
