### ISSUE TITLE
Part method for multipart requests is not defined

### ISSUE THREAD

**Issue by dprentis** [visionmedia/superagent#662]
Trying to send a multpart request according to the docs, using the low-level api: http://visionmedia.github.io/superagent/#multipart-requests

It seems the part method is not defined (tried with versions 1.1.0 and 1.2.0)

**Comment by fraczak** [comment]
I hit the same problem. Any news of that one?

**Comment by sean-madhavan** [comment]
me too have same problem with 1.2.0

**Comment by Donaira** [comment]
Same here with 1.2.0:
"request.part is not a function"

**Comment by dgellow** [comment]
I have the same problem.
Request#part seems deprecated since Apr 29, 2014, cf commit https://github.com/visionmedia/superagent/commit/9afb6dfe703d6efe2155be98b2f9fb32a6ee7629

So, the documentation is out of date ?

**Comment by sean-madhavan** [comment]
I had to use `field` function instead and that worked.

**Comment by dprentis** [comment]
yes, field works fine
```
request.field(key, data);
```
