### ISSUE TITLE
laravel not detecting superagent call as ajax

### ISSUE THREAD

**Issue by mouhsinelonly** [visionmedia/superagent#663]
i'm using superagent with laravel framework 5 and laravel wont detect the call is an ajax call .

**Comment by subdesign** [comment]
Partly true. Request::ajax() for some reason doesn't work, but except that SuperAgent works, example:
```
<script src="js/vendor/superagent.js"></script>
<script>
$(function(){
	var request = window.superagent;
	request
		.post('/testapi')
		.send({ name: 'Tom', '_token': $('meta[name="_token"]').attr('content') })
		.end(function(err, response) {				
			console.log(response.body.greeting);				
		});
});
</script>
```
in routes.php:
```
Route::post('testapi', function(){
	$name = \Input::get('name');
	return Response::json(array('greeting' => 'Hello, '.$name));
});
```
only thing, you have to pass the csrf token with the request, but that's all.

**Comment by jmp909** [comment]
(note: csrf does not get processed on GET routes)

there are some functions in Laravel that use eg
` if ($request->ajax() || $request->wantsJson()) {`

that first function checks headers for `X-Requested-With = 'XMLHttpRequest'`
the second function checks header for `Accept = 'application/json'`

as far as superagent is concerned I have to set one of these 2 to pass that initial test:

`.set('X-Requested-With', 'XMLHttpRequest')`
`.set('Accept', 'application/json')`

to answer the original queston then, it appears superagent is not setting the `X-Requested-With` value in order for laravel to see it as Ajax?

regards
J
