### ISSUE TITLE
Custom Request Header Not Set Properly

### ISSUE THREAD

**Issue by mtando** [visionmedia/superagent#666]
This is my first javascript code using superagent js:

request.get('http://localhost:8080/api/products/')
.set('auth_token', authToken)
.end(function (err, res) {
  if (res.ok) {
    alert('yay got ' + JSON.stringify(res.body));
  } else {
    alert('Oh no! error ' + res.text);
  }
});
I'm calling the API that's hosted on another remote server, so this is a cross origin http request (CORS). My API server is configured to return response with CORS headers as follows:

Access-Control-Allow-Headers:auth_token
Access-Control-Allow-Methods:OPTIONS, POST, GET, PUT, DELETE
Access-Control-Allow-Origin:*
Access-Control-Max-Age:3600
Content-Type:application/json;charset=UTF-8
Date:Sat, 30 May 2015 05:16:37 GMT
Server:Apache-Coyote/1.1
Transfer-Encoding:chunked

However, my GET request that gets generated does not have the auth_token header with the expected token values:

Accept:*/*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8,id;q=0.6,fr;q=0.4
Access-Control-Request-Headers:auth_token
Access-Control-Request-Method:GET
Connection:keep-alive
Host:localhost:8080
Origin:http://localhost:8100
Referer:http://localhost:8100/
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/53

I can see auth_token being set as value of 'Access-Control-Request-Headers' but i what i want to see is my custom header 'auth_token' with some token values...

Please let me know how to use set a custom header properly... super thanks!

**Comment by schmittyjd** [comment]
@mtando how did you solve this?

**Comment by 91ranjan** [comment]
Was anyone able to solve this problem?

**Comment by 91ranjan** [comment]
@schmittyjd Where you able to solve this?

**Comment by bmf-san** [comment]
I want to know about this solution.

**Comment by shadidchowdhury** [comment]
I also have this problem, and after searching a lot it seems this more of a CORS issue rather than a superagent issue. So as I understood to be able to send a custom header the server response needs to send back the header `Access-Control-Request-Headers` with custom headers in it on the pre-flight request.  

Otherwise, you can only send the simple headers as defined here https://www.w3.org/TR/cors/#terminology.
