### ISSUE TITLE
5000ms delay when fetching from 127.0.0.1 via hosts mapping

### ISSUE THREAD

**Issue by kaivi** [visionmedia/superagent#667]
On serverside, when doing any type of HTTP request to 127.0.0.1, mapped as something else that localhost, there is a 5000ms delay before the request is actually sent. In this example, `http://dev.local:8081/me` is only hit with a request on the 5th second. Here is a string from my `hosts` file on OS X:

`dev.local        127.0.0.1`

And the code I am using:

```javascript
console.time('fetch user info');
request
  .get('http://dev.local:8081/me')
  .end(function(api_err, api_resp){
    console.timeEnd('fetch user info');
    // fetch user info: 5026ms
});
```

It returns in ~6ms when using `localhost` instead of another alias. I'm on Node v0.12.4. Also, there is no delay with the same code in browser.

**Comment by defunctzombie** [comment]
Does using node's builtin http library also incur such a delay? I am tempted to think this is either an issue on your system or something with node's dns lookup. I highly doubt it is anything to do with this library.
