### ISSUE TITLE
should head requests follow redirect?

### ISSUE THREAD

**Issue by wenzowski** [visionmedia/superagent#669]
Not sure if bug or by design: http GET requests follow correctly formed redirects but http HEAD requests do not appear to.

```javascript
var request = require('superagent');
request.get('https://google.com').redirects(1).end(function(err, res){console.log(res.status)});
// 200
request.head('https://google.com').redirects(1).end(function(err, res){console.log(res.status)});
// 302
```

**Comment by jonhester** [comment]
Just ran into this issue. I think that this is a bug.

**Comment by juanmaia** [comment]
+1

**Comment by pornel** [comment]
I think they should. Right now it's a coded as it was a feature, but probably not a good one.

**Comment by wenzowski** [comment]
Superb, thanks @pornel
