### ISSUE TITLE
arrays in query parameter are handled differently in node vs browser libraries

### ISSUE THREAD

**Issue by davis** [visionmedia/superagent#670]
`.query({ hello: ['a', 'b', 'c'] })`

returns different things
node:
`?hello=a&hello=b&hello=c` (correct)

browser:
`?hello=a,b,c` (incorrect)

**Comment by davis** [comment]
can be merged with #629

**Comment by aalpern** [comment]
:+1: 

I just ran into this problem as well, in a REST API client I wrote that's intended for both node.js and browser usage. It means avoiding superagent's built-in query string encoding altogether, which really defeats the purpose of having it at all.

**Comment by defunctzombie** [comment]
Can you make a PR if there isn't one already? Also please add tests.

**Comment by aalpern** [comment]
I'll see what I can do. Although I'm currently getting 35 test failures under node.js (in node 0.12.2 and 0.12.5) from a fresh clone of `master`, so that doesn't give me a lot of confidence in testing my own changes.

**Comment by aalpern** [comment]
Digging in, it looks like the bug is actually in the `qs` module, which handles all query string formatting: https://github.com/visionmedia/superagent/blob/master/lib/node/index.js#L823 , which has had 6 releases since the one in user here. 

Ah, there's an array format option in qs 2.4.0 that does the trick (and there's already a test for this case in the node.js tests, just not one in the browser). PR incoming shortly.

**Comment by aalpern** [comment]
Just submitted a PR - if it could be package in a 1.2.1 release that would be :sparkles: :guitar: :tada:

**Comment by ianks** [comment]
Why was this syntax (`?hello=a&hello=b&hello=c)` decided on over:

`?hello[]=a&hello[]=b&hello[]=c`

It seems to me that the latter is the most common syntax for representing arrays in a query string.

**Comment by pornel** [comment]
1. If you need to, you can achieve a `hello[]` keys by using exactly that name in the input, but it wouldn't work the other way — if superagent always added `[]` then it wouldn't be compatible with servers that require `[]`-less arguments.

2. Node already does it this way, and superagent aims to be identical in browser and node.
