### ISSUE TITLE
dude put promise support in

### ISSUE THREAD

**Issue by ronnieoverby** [visionmedia/superagent#674]
it's a no brainer

**Comment by kmalakoff** [comment]
It looks like from https://github.com/visionmedia/superagent/issues/647 that there is already a [module](https://github.com/undoZen/promisingagent) to add promises.

What is the best way to give superagent users choice?

**Comment by defunctzombie** [comment]
I am not increasing the size of the library for everyone just because someone wants a function with a different name. If you want promises, just use what is available.

**Comment by defunctzombie** [comment]
I will accept a PR for the readme to point to any relevant module/use for promises if you want to show users how that can be accomplished.
