### ISSUE TITLE
"superagent.agent is not a function" in browser

### ISSUE THREAD

**Issue by aommm** [visionmedia/superagent#677]
I get an error when I try to access the 'agent()' function when using superagent from a browser:
```javascript
var superagent = require('superagent');
var agent = superagent.agent();
```
This yields the error "superagent.agent is not a function".

After some debugging, I found that the superagent version found in lib/client.js does not export the 'agent()' function. This is different from the node version found in lib/node/index.js, which does export the function.

Ought not the two versions be identical in functionality?

**Comment by defunctzombie** [comment]
No, agent is only available in the nodejs version.

**Comment by GantMan** [comment]
So this doesn't work in React Native either :(

**Comment by rinchenlama0075** [comment]
Hey, is there a way to work around this in react? I'm trying to use the mitsuku-api-gold but I get this error.
