### ISSUE TITLE
Getting error "Origin is not allowed by Access-Control-Allow-Origin" in browser when no internet connection

### ISSUE THREAD

**Issue by scottnonnenberg** [visionmedia/superagent#679]
I'm getting a "Origin is not allowed by Access-Control-Allow-Origin" error from superagent in Chrome 43 on OSX when I attempt to hit a service that does not respond, or when the internet connection has been turned off entirely.

Seems that [`Request.prototype.crossDomainError`](https://github.com/visionmedia/superagent/blob/94afa3ae189267a8d352d72b20edb9900148959e/lib/client.js#L847) is called too often? Maybe some more checks should be added in [`Request.prototype.end`](https://github.com/visionmedia/superagent/blob/94afa3ae189267a8d352d72b20edb9900148959e/lib/client.js#L913) before falling through to `crossDomainError()`?

**Comment by xcatliu** [comment]
+1

**Comment by nalwayaabhishek** [comment]
+1 I am getting the same error when no internet connection

**Comment by scsper** [comment]
+1

**Comment by crcn** [comment]
+1

**Comment by benjdezi** [comment]
+1

**Comment by WenXuanYuan** [comment]
The same error occured with me !

**Comment by scsper** [comment]
@defunctzombie Any guidance on what to do?  I'm willing to open the pull request, but I'd like some community support before putting in the work.

**Comment by pornel** [comment]
Agreed this is a problem. Duplicate of  #484

**Comment by askucher** [comment]
+1
