### ISSUE TITLE
Consuming streams from SSE endpoint

### ISSUE THREAD

**Issue by Snorlock** [visionmedia/superagent#680]
Im trying to consume a http get with accept: text/event-stream and response is content-Type:text/event-stream

npm request has this:
```request.on('data', function(data){..})```
which provides a buffer for me to parse.

Does superagent support this kind of behaviour?

**Comment by pornel** [comment]
No, superagent is not best suited for this. Most of the functionality it adds is based on assumption that resources have a finite size.
