### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by crypti** [visionmedia/superagent#687]
I have problem with supertest. Supertest using superagent. I run api tests. Sometimes some random tests send me this error.

    Uncaught TypeError: undefined is not a function
     at Socket.socketOnEnd [as onend] (http.js:1572:9)
     at _stream_readable.js:943:16
Example of one test:

```javascript
  it(test + '. We attempt to upVote same delegate SEVERAL TIMES from random account. We expect error',function(done){
           var votedDelegate = '"+' + node.Eaccount.publicKey + '","+' + node.Eaccount.publicKey + '"';
           setTimeout(function(){
               node.api.put('/accounts/delegates')
                   .set('Accept', 'application/json')
                   .send({
                       secret: Raccount.password,
                       delegates: [votedDelegate]
                   })
                   .expect('Content-Type', /json/)
                   .expect(200)
                   .end(function (err, res) {
                       console.log(res.body);
                       node.expect(res.body).to.have.property("success").to.be.false;
                       node.expect(res.body).to.have.property("error");
                       done();
                   });
           }, 1000);
       });
```
Then all other tests run good. Is it possible that it's some issue of superagent? Maybe too much http calls?

**Comment by defunctzombie** [comment]
Please make a self contained test that we can actually run. How do you expect reproduction of your error if the steps to reproduce are not provided. What debugging have you done to try and identify the error? This about if I came to you with the error report you just posted above (and no other information), are you able to fix the problem based on that info?

**Comment by crypti** [comment]
I can't catch it. It's crash in different places all time, i can try to debug it again and maybe make pull request.
