### ISSUE TITLE
Different behaviour between browser and node library

### ISSUE THREAD

**Issue by ianmurrays** [visionmedia/superagent#690]
Hi, not sure this is a bug, but I've noticed that there is at least one difference between [lib/client.js](https://github.com/visionmedia/superagent/blob/master/lib/client.js) and [lib/node/index.js](https://github.com/visionmedia/superagent/blob/master/lib/node/index.js). For example, checking a response's `statusCode` attribute works in node but does not work in the browser, since client.js doesn't even mention this attribute.

If this is by design, please disregard this. Thanks! :smile:

**Comment by alex94puchades** [comment]
It appears so (see #729). The long-term goal will be to eventually diminish the differences (PR welcome!)

**Comment by pornel** [comment]
We've fixed a lot of these. We do have `statusCode` now, too. Please file bugs if you find more undocumented differences.
