### ISSUE TITLE
superagent always send data by OPTIONS method

### ISSUE THREAD

**Issue by eeskov** [visionmedia/superagent#692]
```
request
    .get(url)
    .end(function (err, res) {
        if (err) {
            console.log(url);
            console.log(err);
        } else {
            var data = res.body;
            callback(data, ctx);
        }
    });
```

I always get this response

Request Method:OPTIONS
Status Code:405 METHOD NOT ALLOWED

**Comment by fertrig** [comment]
Getting the same issue.

**Comment by tonyalaribe** [comment]
same here. CORS issue

**Comment by alex94puchades** [comment]
Yep, that seems like a CORS issue, not related to Superagent. @eeskov could you please provide with full request/response headers so we can help? Are you using [express-cors](https://www.npmjs.com/package/cors) on the server?

**Comment by neekey** [comment]
@alex94puchades  I think actually superagent always send `Content-Type: 'application/json` caused the problem

Anyway to disable this behavior?

**Comment by pornel** [comment]
For simple data, you could submit it as `.type('form')` instead of JSON.

**Comment by neekey** [comment]
sorry, I doubled checked, not an issue with superagent, just the browser's CORS strategy.
