### ISSUE TITLE
A lot of web developers don't use Node

### ISSUE THREAD

**Issue by jugimaster** [visionmedia/superagent#694]
For example, I've never used Node for a project.

The problem here is that there's no plain JavaScript "distribution" of Superagent - a file I could download and set up in my browser to start using it.

I figured Superagent looked like a decent library, so I even tried this "Browserify" thing, which seems like something meant for this specific situation. Apparently this is a widespread problem.

Anyway, after looking at the Issue list here, I'm left feeling vaguely uncomfortable with using Superagent, or just about any other non-jQuery ajax library out there.

**Comment by twincle** [comment]
maybe you're looking for this: https://github.com/twincle/superagent/tree/master/client
hope this could help you.
have fun~

**Comment by jugimaster** [comment]
Thanks, that is roughly what I was looking for!

Well, it's easier for me to fire off a couple of comments here than to set up a local repo and scrape together a pull request, so.. here goes.

You might want to adjust the ```isObject``` method a bit though, because the current version returns true for ```Arrays``` too. 

Instead, you could do something like: 
```javascript
function isObject(obj) {
  return obj === Object(obj) && !(obj instanceof Array) && !(obj instanceof Node);
}
```

You could also start using strict equality comparisons: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness

**Comment by defunctzombie** [comment]
Browserify is a simple tool you can use to build the bundle. It does not require you to "use node".

Alternatively, you can download a pre-built version from this awesome site:
https://wzrd.in/standalone/superagent@latest

All it does is run the module through browserify for you and give you a standalone you can use.

Powered by:
https://github.com/jfhbrook/browserify-cdn

**Comment by jugimaster** [comment]
Thanks for the tip :) 

I'm using Babel now, and reasonably happy so far.
