### ISSUE TITLE
Different realization of query method on server and client

### ISSUE THREAD

**Issue by MaxSvargal** [visionmedia/superagent#701]
Request.prototype.query method on client and server has a different behavior if passed e.g. null or undefined.

In browser (ES6):
request.get(url).query({somequery});
ES5:
request.get(url).query(function(){return r?{somequery:r}:null}.call());
Will return no params in request (i think it's ok).

On server (iojs 2.2.1)
request.get(url).query({somequery});
Will return query parameter key string with no value: '?somequery='

**Comment by alex94puchades** [comment]
Hi @MaxSvargal, sorry for the late response. Could you please write about your issue in #690? We'd want to join all efforts into addressing this important issue in the best way possible. Thanks for your understanding
