### ISSUE TITLE
Data cleared after a 302

### ISSUE THREAD

**Issue by warrenseine** [visionmedia/superagent#702]
Hi,

SuperAgent clears any data set with the `send()` function when the server responds with a 302. The [code](https://github.com/visionmedia/superagent/blob/master/lib/node/index.js#L618) seems to confirm that.

In my case, the server automatically redirects HTTP to HTTPS, so I need SuperAgent to do the exact same requests with the new location. Unfortunately, the server answers the second request with a 400, because it's not seeing the data parameters. No problem when making the same request in Chrome.

This looks like a major issue. Can you confirm I'm not the only one seeing this behavior?

Regards,
Warren.

**Comment by alex94puchades** [comment]
The behaviour seems not easy to implement in a standard-compliant way (see [here](http://stackoverflow.com/a/304654)). However, you could make a plugin: the superagent plugin api is quite flexible and easy to work with!

**Comment by warrenseine** [comment]
I've moved to the native HTTP module for that specific case anyway.
