### ISSUE TITLE
examples/simple-get.js url endpoint invalid

### ISSUE THREAD

**Issue by oleersoy** [visionmedia/superagent#705]
$:~/Lab/superagent$ node examples/simple-get.js 

/examples/simple-get.js:11
  if (err) throw err;
                 ^
Error: Not Found
    at Request.callback (/superagent/lib/node/index.js:792:17)
    at IncomingMessage.<anonymous> (/superagent/lib/node/index.js:990:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:929:16
    at process._tickCallback (node.js:419:13)

**Comment by reinaldo13** [comment]
Fixed and awaiting approval for PR https://github.com/visionmedia/superagent/pull/723

**Comment by natarajanmca11** [comment]
I am getting the same error in post request. Details are given below.

`"superagent": "^1.8.3",`

![image](https://cloud.githubusercontent.com/assets/9244766/15352263/7426d058-1d37-11e6-9513-da73d45c9f13.png)

**Comment by pornel** [comment]
This bug is about running `examples/simple-get.js`, not post requests, and not Redis.

"Not Found" error is very generic and can correctly happen in lots of situations. You should check whether you're calling correct URL and whether your server allows POST for that url.
