### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by simoneb** [visionmedia/superagent#706]
What is the suggested way to handle specific response errors, say, 403 status?

```
.end(function(err, res) {
  // if status is 403 do something custom
  // if response status is not 200 do something else custom
  // if there is any other kind of error just invoke a callback function with such error
});
```

I'm trying:

```
.end(function(err, res) {
  if(res.forbidden) return handleForbidden();
  if(!res.ok) return handleNon200Response();
  if(err) return handleGenericError(err);
});
```

But:

1. does `res` always exist? (i.e. request error)
2. if it does exist, will `res.ok` be falsy also for request errors? (rather than response errors?)

So I'm not sure this pattern (which I would like to use) really works as I would like it to work, I'm curious to know how others are handling errors and what is a suggested pattern, without compromising readibility.

**Comment by defunctzombie** [comment]
`err.status` (or err.statusCode I forget) will have the specific status.

Alternatively, you can check for `if (res)` before checking the status on res.

```js
.end(function(err, res) {
    if (err) {
       if (err.status === 403) {
       }
    }

    // non error code
});

**Comment by simoneb** [comment]
Doesn't this make `res.forbidden` and the like (which would be quite handy) basically useless?

**Comment by defunctzombie** [comment]
You can still use those of you check that red exists first. The new error
handling is based around the idea that it is better to have non success
status codes be errors and force you to deal with them.

**Comment by simoneb** [comment]
Which means I should write this:

```
.end(function(err, res) {
  if(res) {
    if(res.forbidden) return handleForbidden();
    if(!res.ok) return handleNon200Response();
  }
  if(err) return handleGenericError(err);
});
```

It's certainly not a big deal but not very readable either in my opinion. Why are non 2xx/3xx status codes errors in the first place? Probably too late to change this, but I think it would be much more consistent with other node APIs if the first line in a callback was always:

```
if(err) return callback(err);
```

which it is in all other libraries that I commonly use.

**Comment by defunctzombie** [comment]
Discussion already had in other issues :)

You can write the if statements however you want :)

**Comment by simoneb** [comment]
I looked up those issues and PR and understand why you're not willing to discuss this further. I strongly disagree with this decision though, as [others](https://github.com/kmalakoff/superagent-ls) did already, very counter-intuitive.
