### ISSUE TITLE
Ability to upload videos

### ISSUE THREAD

**Issue by eltoob** [visionmedia/superagent#707]
I just tried to upload a video

    var url = "some_local_path"
    request.put("https://mybucket.s3.amazonaws.com/test.mp4")
           .type("video/mp4")
           .set('Content-Type', 'video/mp4')
           .set('X-Amz-Signature', 'somesig')
           .set('X-Amz-Credential', 'somecred')
           .set('Date', 'Thu, 23 Jul 2015')
           .set('X-Amz-Algorithm', 'AWS4-HMAC-SHA256')
           .set('X-Amz-Acl', 'public-read')
           .end(function(err,res){debugger;})

And my mp4 is uploaded but just contains a few lines of text

    --zWGdmuxl4sxXXXXXXXXXXXXXXXxQjaHYwaodP7.FWOAa_-s7
    content-disposition: form-data; name="test.mp4"

    file:///myPath
    --zXXdmuxl4sxqXSTnilUXXXXXXXXXXXXwaodP7.FWOAa_-s7--

Any Idea?

**Comment by defunctzombie** [comment]
No idea without a failing example script with file.
