### ISSUE TITLE
How to ignore Response's content-type?

### ISSUE THREAD

**Issue by oleynikd** [visionmedia/superagent#720]
Both `res.body` and `res.text` are 'empty' if `content-type` is for example something like `audio/x-mpegurl`. How do I ignore it? How to read such responses?

Thanks.

**Comment by ptz0n** [comment]
Browser or Node/IO? Please provide example request.

**Comment by h1bomb** [comment]
maybe you can do like this
``` javascript
request
    .get('http://someaudio')
    .parse(request.parse.image) //I think audio parse like image
    .end(function function_name(err, res) {
        if (err) throw err;
        console.log(res.body);
    });
```

but body is `{}`，I don't known why?

**Comment by oleynikd** [comment]
I used it in node! I could'n figure out hot fix this so I switched to https://github.com/request/request
