### ISSUE TITLE
Can't use with phonegap

### ISSUE THREAD

**Issue by ccapndave** [visionmedia/superagent#733]
When trying to request a local file compiled into a phonegap/cordova application, superagent throws a `Origin is not allowed by Access-Control-Allow-Origin` error.

This can be seen with code as simple as:

```
request.get('mylocalfile.json').end((err, res) => {
    console.log(err);
});
```

Doing the same thing with vanilla JS works fine:

```
function listener() { console.log(this);}

var url = "mylocalfile.json";
var req = new XMLHttpRequest();
req.addEventListener('load', reqListener);
req.addEventListener('error', reqListener);
req.open("get", url, true);
req.send()
```

**Comment by ccapndave** [comment]
P.S. looking at the network panel shows that the file *is* getting loaded, even though superagent reports an error.

**Comment by ccapndave** [comment]
The cause of this seems to be that phonegap/cordova webviews sometimes return 0 instead of 200 for the status.  http://simonmacdonald.blogspot.ch/2011/12/on-third-day-of-phonegapping-getting.html

**Comment by stephanebachelier** [comment]
@ccapndave it seems related to #484
