### ISSUE TITLE
Cannot set correct Content-Type header for JSON API

### ISSUE THREAD

**Issue by digitalsadhu** [visionmedia/superagent#753]
The following works fine:
```
request.set('Content-Type', 'application/json')
```
whereas using the JSON API header as follows:
```
request.set('Content-Type', 'application/vnd.api+json')
```
results in the following error:
```
TypeError: first argument must be a string or Buffer
      at ClientRequest.OutgoingMessage.end (_http_outgoing.js:517:11)
      at Test.Request.end (node_modules/supertest/node_modules/superagent/lib/node/index.js:1020:9)
      at Test.end (node_modules/supertest/lib/test.js:121:7)
      at Context.<anonymous> (test/create.test.js:39:10)
```

Bypassing superagent and using CURL works fine:
```
curl -X POST -H "Content-Type: application/vnd.api+json" --data  '{"data": { "type": "posts", "attributes": { "title": "test", "content": "test content" } }}' http://127.0.0.1:3000/api/posts
```

**Comment by sescobb27** [comment]
I have the same issue but with application/vnd.api+json which is the content type for JSON API http://jsonapi.org/format/#conventions, but it only happens with PATCH request, not with POST or GET

**Comment by sescobb27** [comment]
Test are failing due to lack of support of PATCH request in BROWSER mode. any hint on this?

**Comment by digitalsadhu** [comment]
@sescobb27 so your fix works on the server but not on the browser?

**Comment by sescobb27** [comment]
@digitalsadhu basically yes :disappointed: due to lack of support for PATCH request in some of them

**Comment by digitalsadhu** [comment]
@sescobb27 I ended up setting my tests Content-Type to application/json to avoid the issue and then added a single test using nodes http module to verify that setting Content-Type to application/vnd.api+json to verify that it works. Would be nice to be able to just stick with superagent/supertest but works for now.

**Comment by sescobb27** [comment]
@digitalsadhu I made something similar
```js
return request
  .post('/customers')
  .send(this.data)
  .expect(201)
  .expect('Content-Type', /application\/(vnd\.api\+)?json/) // match application/vnd.api+json or application/json)
```

**Comment by trbmcginnis** [comment]
This is still an issue for me on 5.0.0-0. I had to use @digitalsadhu's workaround by setting the content-type as `application/json`:

```
      return request(server)
        .patch('/dispositions/472fc5a1-9844-e811-813d-1458d04d0698')
        .type('application/json')
        .set('Cookie', token)
        .send({
          data: {
            type: 'dispositions',
            id: '472fc5a1-9844-e811-813d-1458d04d0698',
            attributes: {
              dcp_publichearinglocation: "test test",
            },
          },
        })
        .expect(200)
```

Any thoughts? I'm using this with NestJS so maybe it's in the NestJS related layer.
