### ISSUE TITLE
form-data 0.2.0 has bug, form-data lasted version fixed it.

### ISSUE THREAD

**Issue by byhgj** [visionmedia/superagent#754]
form-data 0.2.0 has bug, form-data lasted version fixed it.

when attach file, adodb.stream report error.

0.2.0
FormData.prototype._lastBoundary = function() {
  return '--' + this.getBoundary() + '--';
};

lasted
FormData.prototype._lastBoundary = function() {
  return '--' + this.getBoundary() + '--' + FormData.LINE_BREAK;
};

**Comment by defunctzombie** [comment]
What is the bug? Can you make a PR and tests for this please?

**Comment by pornel** [comment]
We use new form-data now

**Comment by tarjei** [comment]
@pornel when was this bug fixed?

**Comment by pornel** [comment]
In 2.0.0. It uses form-data 1.0.0-rc4
