### ISSUE TITLE
Support for tvOS 

### ISSUE THREAD

**Issue by narirou** [visionmedia/superagent#757]
We currently use this module in AppleTV development using browserify, but some errors occurred.
Is there a support plan of tvJS?

```
TypeError: xhr.open is not a function. (In 'xhr.open(this.method, this.url, true)', 'xhr.open' is undefined)
```

This error because tvJS does not have global `window` object.

https://developer.apple.com/library/prerelease/tvos/documentation/TVMLJS/Reference/TVJSXMLHttpRequest_Ref/index.html#//apple_ref/javascript/cl/XMLHttpRequest

Thanks.

**Comment by hc2p** [comment]
i had the same issue while using webpack instead of browserify. I solved it by using the imports-loader to inject a fake window object: `superagent = require('imports?window=>{XMLHttpRequest:XMLHttpRequest}!superagent')`

**Comment by pornel** [comment]
If reading XHR from global rather than `window` is all that's needed then I don't mind supporting tvOS. If it's more involved then we'd need to figure out how to test it.

**Comment by CezaryDanielNowak** [comment]
I had similar issue, when using webpack code on server side.
The solution was:

Front-end:
```
// HACK: Allow to user different versions of superagent in browser and in node
if (global.superagent) {
  // node superagent
  superagent = global.superagent;
} else {
  superagent = require('superagent');
}
```

Back-end:
```
global.superagent = require('superagent');
```
