### ISSUE TITLE
Improve error message

### ISSUE THREAD

**Issue by matthewmueller** [visionmedia/superagent#765]
What do you guys think of adding to the error message? 

```
app: TypeError: fn is not a function +2m
    app:     at Request.callback (/Users/matt/Projects/finbox.com/app/node_modules/superagent/lib/node/index.js:781:12)
    app:     at ClientRequest.<anonymous> (/Users/matt/Projects/finbox.com/app/node_modules/superagent/lib/node/index.js:736:10)
    app:     at emitOne (events.js:77:13)
    app:     at ClientRequest.emit (events.js:169:7)
    app:     at Socket.socketOnEnd (_http_client.js:288:9)
    app:     at emitNone (events.js:72:20)
    app:     at Socket.emit (events.js:166:7)
    app:     at endReadableNT (_stream_readable.js:893:12)
    app:     at doNTCallback2 (node.js:429:9)
    app:     at process._tickCallback (node.js:343:17)
```

This doesn't really tell me anything about:

1) The API call I made
2) The location in the code this call was made

---

I'm not sure if it's a good idea to inject addition information into the stack, but at the very least the API call that triggered this would be helpful

**Comment by pornel** [comment]
Agreed we shouldn't be causing any TypeErrors. Some callback-related bugs were fixed recently. Can you re-test with the latest version?
