### ISSUE TITLE
How can I set the User-Agent header using the node module?

### ISSUE THREAD

**Issue by osherx** [visionmedia/superagent#768]
Im trying to test that my system idenfifies user-agents correctly

using mocha, in my test code, before function - I have:

```
        before(function(done) { 
              //...some actions
              //...some actions
               superagent.post('http://localhost:8080/api/v1/path1')
                    .send(body)
                    .set('Referrer', 'http://dummy.domain.com/somepage.html')
                    .set('User-Agent', "some spoofed agent")
                    .end(function (e, r) {
                        res = r;
                        _done();
                    });
       })
```

however,the server gets

```
'node-superagent/1.3.0'
```

Help?

**Comment by focusaurus** [comment]
I tried to reproduce your issue with superagent v1.4.0 but was able to set a custom User-Agent header without any issue. Can you try to create a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) on the latest superagent release and post your results?

**Comment by olalonde** [comment]
FWIW, if you are running your tests in a browser, setting the user-agent header won't work because web browsers don't allow overriding the user-agent header.

**Comment by pornel** [comment]
I'm assuming this was due to browsers not allowing it. Please re-open if it affects node.

**Comment by ixtli** [comment]
I'm also having this issue when doing ```javascript
			request
				.get(url)
				.set('User-Agent', uaString)
				.expect(200)
				.end((err, resp) => {
					console.log(resp.body);
					done();
				});```
with node 6.2.1. 

I think it's clear that OP was not trying to override this request from a browser, otherwise it would not have identified itself as `node-superagent/1.3.0`.

**Comment by ixtli** [comment]
Ok so apparently I had failed at isolating the code and I now believe that it's actually some interaction i don't understand with https://github.com/visionmedia/supertest because when i require `superagent` directly and make a `get` request with the full URL it passes the user-agent correctly.

For what it's worth, what I'm doing with supertest is
```javascript
const supertest = require('supertest');
const request = supertest(config.serverAddress());
request
     .get(url + '&platform=WEB&type=start')
     .set('User-Agent', macUAString)
     .end((err, resp) => {
	console.log(resp.body.data);
	done();
});
```

**Comment by pornel** [comment]
Ah, ok. Supertest is a separate codebase. Can you report it in that project?

**Comment by habiba-abbasi** [comment]
I got this issue when installing the latest ionic version

**Comment by timsar2** [comment]
npm install ionic@latest
... `GitHub blocks requests without a User-Agent header`
