### ISSUE TITLE
Can't get location from response header

### ISSUE THREAD

**Issue by Rambobafet** [visionmedia/superagent#770]
Hi,

I'm trying to get the properties `location` from the response, but superagent doesn't seem to see it, in spite of the properties being set and visible from the network console.
Is it because the reponse body is empty ?

Thanks for your help :)
Bob

    # Extract from my code
    .end(function(error, response){
      console.log('response', error, response.headers);
      [...]
    })

    # Extract from Response Headers from network console :
    Date:Thu, 15 Oct 2015 12:59:30 GMT
    Expires:0
    Location:/tmp/project-pic-4730126112057571929.jpg
    Pragma:no-cache
    Server:nginx/1.6.2

    # console.log(response.headers)
    Object {
      pragma: "no-cache", 
      cache-control: "no-cache, no-store, max-age=0, must-revalidate", 
      expires: "0", 
      content-type: null
    }

**Comment by roshanraj** [comment]
Location headers received as xhr response is pre-processed (and stripped) by browser before response is passed to calling JS part (superagent in this case). The same issue has been asked on SO for jQuery.

**Comment by Rambobafet** [comment]
Oh ok :(
I change the way to pass the information by using the body.

Thanks for your answer :)

**Comment by basti1302** [comment]
Stumbled upon the same issue Location header in response visible in network tab but not in response object just now. I think the answer given by @roshanraj is not quite correct. The location header is indeed stripped away by the browser if this is a CORS request and the CORS headers of the response do not allow the location header to be exposed. The CORS header in question is `Access-Control-Expose-Headers`. If the response has `Access-Control-Expose-Headers:Location`, then the browser exposes the Location header just fine and superagent yields its value happily.

So, if you have control over the server side, you just need to set this header. If you are for example using express with the cors middleware you could do something like:

```
app.use(cors({                                                                 
  exposedHeaders:['Location'],                                                                                                                         
}));
```

Hope this helps the next person which googles for "superagent response location header" ;-)

**Comment by Rambobafet** [comment]
Oh that's nice to know :)
Thanks for your feedback <3

**Comment by roshanraj** [comment]
Oh thats cool. Thank you for correcting me.
