### ISSUE TITLE
first documentation example has broken error handling

### ISSUE THREAD

**Issue by astraw** [visionmedia/superagent#772]
The very first example at http://visionmedia.github.io/superagent/ currently shows

```
 request
   .post('/api/pet')
   .send({ name: 'Manny', species: 'cat' })
   .set('X-API-Key', 'foobar')
   .set('Accept', 'application/json')
   .end(function(err, res){
     if (res.ok) {
       alert('yay got ' + JSON.stringify(res.body));
     } else {
       alert('Oh no! error ' + res.text);
     }
   });
```

However, as noted in #760, this pattern of result checking will fail unexpectedly if there is an error in the callback passed to `.end()`. In that case, `res` is undefined and in my browser I get `Uncaught TypeError: Cannot read property 'ok' of undefined` in the line `if (res.ok) {`.

Therefore, I would suggest to update the documentation to properly perform error checking (or at least to remove the broken pseudo error check).

**Comment by rohitlodha** [comment]
Same here. Can you suggest the best way to deal with error?

**Comment by astraw** [comment]
Something like this

```
      superagent
        .get(request_href)
        .set('Accept', 'application/json')
        .end(
          function(err,res) {
            if (err || !res.ok) {
              alert('Oh no! error');
            } else {
              alert('yay got ' + JSON.stringify(res.body));
            }
          });
```
