### ISSUE TITLE
response 'error' events aren't handled by .end()

### ISSUE THREAD

**Issue by wonnage** [visionmedia/superagent#776]
We noticed this cryptic error coming from zlib:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: incorrect data check
    at Zlib._handle.onerror (zlib.js:363:17)
```

If zlib encounters an error while decompressing a stream, an error event is emitted on an internal stream object:
https://github.com/visionmedia/superagent/blob/master/lib/node/utils.js#L86

The response stream's `.on` method is then hooked up to the internal stream object:
https://github.com/visionmedia/superagent/blob/master/lib/node/utils.js#L113

So in order to handle errors on the internal stream object, we have to listen for 'error' on the response stream.

It seems like the only access to the response stream prior to stream end is inside of `Request.prototype.end` - the response will have ended by the time we reach our callback.

All this is to say, I think if zlib encounters an error decompressing a data chunk, there's no way for us to handle it, because it happens before the response 'end' event. Do you think this analysis is correct?

**Comment by gebrits** [comment]
@wonnage: 

We're seeing something similar: 

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:363:17)
```

Any luck in resolving this? 
This crashes our node-process entirely without an apparent way to catch??

**Comment by gebrits** [comment]
Possibly related to #410

**Comment by kornelski** [comment]
They are now, if you use promises
