### ISSUE TITLE
UNIX socket path in node.js

### ISSUE THREAD

**Issue by enricostano** [visionmedia/superagent#779]
Hi, is there a way for `superagent` to make a HTTP request using UNIX sockets instead of `host:port`?

Thanks!

**Comment by focusaurus** [comment]
I believe that may be technically possible but reviewing the current code I'm pretty sure it does not currently work. This would create another feature disparity between the browser and node, so there may be some objection to adding this based on that. My thought would be getting the basic mechanics working over a unix socket would be pretty straightforward but then it would get complex dealing with redirects and facets of HTTP coupled to the host:port origin like cookies etc.

**Comment by olalonde** [comment]
Personally, I wouldn't be opposed to supporting that if it's just a few lines of code.

**Comment by kanreisa** [comment]
@enricostano
Hello! I've implemented it on https://github.com/kanreisa/superagent/commit/9e57664dc130d46fcc17a47301cf8756da339a55 .
If you sure, try it and feedback please.

**Usage:**
```
http://unix:/absolute/path/to/unix.socket:/request/path
```

**Comment by enricostano** [comment]
hi @kanreisa thanks! But I finally decided to create 2 different and separate API clients, one for server side (using `request`) and another for browser side (using XHR, until fetch doesn't get stable enough).

**Comment by kanreisa** [comment]
@enricostano np ;)
