### ISSUE TITLE
Refusing install ?

### ISSUE THREAD

**Issue by honger05** [visionmedia/superagent#781]
````bash
npm install superagent
````

then, Refusing to install superagent as a dependency of itself

**Comment by zerok** [comment]
Do you get that after cloning superagent and executing `npm install superagent` inside the superagent directory? Why would you do that? 

You normally run `npm install superagent` inside a project you'd like to use superagent in if you're using for instance browserify or webpack there 🙂

**Comment by honger05** [comment]
thanks for your reply.  I did not execute `npm install superagent` inside the superagent directory. 

It's amazing,It's ok for me to execute 'npm install superagent@1.4.0'， but It's not ok without version '@1.4.0' . 

but when I run 'npm i superagent' in another directory, not the `case-superagent` that I use. It's normally.

I test many times. 

It's over!  I don't want to turn from side to side.
