### ISSUE TITLE
contributors wanted

### ISSUE THREAD

**Issue by defunctzombie** [visionmedia/superagent#785]
Ok, so it is probably evident to anyone submitting issues to this repo that I no longer have the time or interest in maintaining this package as properly as it deserves. I am looking for a few good souls to pick up the reigns and move the module forward together. Primary things we need are issue triage and PR review.

If you are interested please speak up here and list a few PRs or issues you have worked on with this project.

/cc @tj @gjohnson @jongleberry @dougwilson @visionmedia/superagent for input on who those good souls might be

**Comment by pornel** [comment]
The webapp team at Financial Times is using superagent heavily, and we already maintain our own extensions to it. We're interested in maintaining this project.

**Comment by defunctzombie** [comment]
@pornel great, I'm gonna give this a few days and then add some folks as collaborators for get stuff going again

**Comment by focusaurus** [comment]
I'm interested in helping out. I'm doing some PR review and issue triage now.

**Comment by olalonde** [comment]
Interested in helping out but only have one PR as far as I know: https://github.com/visionmedia/superagent/pull/771

**Comment by defunctzombie** [comment]
I have added all three of you as collaborators. Please work together (gets +1s from one another on issues and other things that are non trivial (like basic readme updates, obvious typo fixes etc).

Remember that the original intent of this project was/is to have a library that exposes the same (similar) API on client and server so keeping parity is usually an important thing when reviewing PRs and fixing issues.

Feel free to ping me on any specific issues if they come up or you want another vote.

I'd start with going through the PR and issue backlogs to close out anything that is stale or super old with no responses.

Please avoid making sweeping changes right out of the gate, stability of the API and users is arguably more important than any particular philosophical issue.

Thank you so much for stepping up and helping out! This module is really popular and your work will be really appreciated for all the of the folks filing issues :+1:

**Comment by pornel** [comment]
:ok_hand:

**Comment by MarkHerhold** [comment]
:clap: Thank you all!

**Comment by olalonde** [comment]
:+1: thanks

**Comment by tejasmanohar** [comment]
@defunctzombie Responded via Twitter and then saw the issue... so thought this is a better place. I'm also up for helping maintain this. I use Superagent (and its unofficial bluebird/promise wrappers) most always on client and server :)

also helping out with [koa](https://github.com/koajs), [node-schedule](https://github.com/node-schedule/node-schedule), and [boris](https://github.com/borisrepl/boris) right now (as well as personal and other small repos, of course)
