### ISSUE TITLE
Using .on('progress')

### ISSUE THREAD

**Issue by pobed2** [visionmedia/superagent#801]
We would like to use a progress listener on a POST request. A few people seem to be using `.on('progress')` (https://github.com/visionmedia/superagent/issues/535, https://github.com/visionmedia/superagent/issues/664) but it is not a feature that is documented anywhere in https://visionmedia.github.io/superagent/

```
let request = superagent('POST', /logo)
 .set({ 'Accept': 'application/json'})
 .attach('logo', data)
 .on('progress', () => {'do something'})
 .end()
```

Is this a feature that is supported and maintained?

**Comment by pornel** [comment]
Yes, we support progress (now in node too #771).

The documentation needs an update.

**Comment by pobed2** [comment]
Awesome. Thanks for the response.
