### ISSUE TITLE
Distinguish between upload and download progress events

### ISSUE THREAD

**Issue by pornel** [visionmedia/superagent#803]
As mentioned in #516 #771 the progress event doesn't contain information to distinguish between upload progress and response download progress.

**Comment by ArtskydJ** [comment]
I think this is going to be an issue for me, so I'd be willing to contribute to solve this.

Perhaps instead of this
```js
.on('progress', function (ev) {
    console.log(ev) // { loaded: 1234, total: 2468 }
})
```
it could be
```js
.on('progress', function (ev, type) {
    console.log(ev) // { loaded: 1234, total: 2468 }
    console.log(type) // 'download'
})
```
or it could be
```js
.on('progress', function (ev) {
    console.log(ev) // { loaded: 1234, total: 2468, type: 'upload' }
})
```

Any thoughts?

**Comment by pornel** [comment]
`ev.type` sounds good to me. It'll be great if you make a PR.

**Comment by focusaurus** [comment]
I like adding an extra property to the event. My only reservation is the word `type` is so broad and users could expect to see HTTP method names there, "XHR" or many things. How about something more specific like 'transferDirection' or 'transfer' or 'direction'?

**Comment by ArtskydJ** [comment]
Yeah, more specific would be better. Maybe `upload: true` for uploads, and `upload: false` for downloads?

I'll probably use `direction`, as it fits quite nicely. Hopefully I can make the PR tonight.

**Comment by pornel** [comment]
booleans don't make good APIs, so let's go for `direction:'upload'`/`direction:'download'`.
