### ISSUE TITLE
Possible inconsistent method: parse

### ISSUE THREAD

**Issue by gavacho** [visionmedia/superagent#805]
I've run into some trouble while trying to customize the way response bodies are parsed -- specifically on the client.

From [these tests](https://github.com/visionmedia/superagent/blob/master/test/node/parsers.js#L22-L74), it appears that the `parse` method of the node library is used to customize how *response* bodies are parsed.

[This test](https://github.com/visionmedia/superagent/blob/master/test/client/request.js#L720-L738) shows that the `parse` method of the client library is used to customize how *request* bodies are serialized.

Is this inconsistency intentional?  If not and a maintainer would like to specify the intended behavior, I'd be happy to open a PR.

**Comment by pornel** [comment]
I'm not sure, but it looks like unintentional inconsistency. The guiding principle is that superagent should have the same API on client and server.

**Comment by gavacho** [comment]
Yeah, the node tests predate the client tests and are also much more robust.  If I prepare a PR which changes the client library to be consistent with the node library, would that breaking change be accepted?

**Comment by pornel** [comment]
I'd rather avoid breaking if possible. How about adding `parseRequest`, `parseResponse` accordingly?

**Comment by gavacho** [comment]
Sounds reasonable.  Add those methods to both libs and deprecate the current `parse`?

**Comment by pornel** [comment]
Yes, that's what I had in mind: create new unambiguous methods for parsing that work the same client- and server-side, and leave the old confusing one for backwards compatibility and eventually remove the old one in 2.x.

I'm not entirely sure about `parseRequest` and `parseResponse` names though.

Another approach could be to add arguments to the existing parse to disambiguate? `req.parse({response:fn, request:fn})`?

**Comment by focusaurus** [comment]
Sadly, it looks like `request.parse` indeed sets a request body serializer and then `this._parse` in the browser request instance is indeed a function used for serializing request bodies. Thus I don't think the confusion is request vs. response but rather parse vs. serialize. I'd like to see a PR for the following changes:

- rename the private var `this._parser` to something more clear like `this._serializeBody` in the browser client code
- Add a new clear public API to set the request body serializer. Perhaps `req.serializeBody()` (open to more concise suggestions for the name). This can be an alias of the current `req.parse` in the client code.
- I don't see any functionality in the node code to provide a custom body serializer. It seems to all just be hard coded in `exports.serialize` which presumably can be overridden in a straightforward way if a user has read the source, but maybe we should make an explicit API to keep parity with the browser code.
- deprecate existing `request.parse` with corresponding doc updates

**Comment by pornel** [comment]
The term `serialize` is used in Superagent's codebase, so for 2.0 I suggest:

* `parse(fn)` for parsing response body only (this is a breaking change)
* `serialize(fn)` for generating data to send in the request
