### ISSUE TITLE
superagent emitter vs component-emitter dep

### ISSUE THREAD

**Issue by hoodsy** [visionmedia/superagent#822]
I recently tried to use the browser version of superagent located in ```superagent/lib/client```, but got this error:

```
Emitter(Request.prototype);
^

TypeError: Emitter is not a function
```

Looking in the package.json, the browser field is set to map emitter -> component emitter:
```
"browser": {
    "emitter": "component-emitter"
}
```
But for some reason, this wasn't working with my webpack build. Maybe this was an issue specific to my build, but replacing ```require('emitter')``` to ```require('component-emitter')``` resolved my problem.

**Comment by focusaurus** [comment]
At first glance, this seems like a webpack issue to me. superagent's use of the `browser` field seems correct from a glance at [this version of the browser field spec](https://github.com/defunctzombie/package-browser-field-spec). Maybe retry with the latest webpack and if it is still not working, report an issue with them?
