### ISSUE TITLE
.field() breaks in IE9

### ISSUE THREAD

**Issue by rbardini** [visionmedia/superagent#823]
This is a duplicate of #775, but since it has been closed without further discussion I'm opening a new issue.

When using the `.field()` method in IE9 (bundled with Webpack), an `Object doesn't support this action` error is thrown. This seems related to the FormData interface, which is [not supported by IE9](http://caniuse.com/#feat=xhr2), even though SuperAgent uses a [third-party implementation](https://github.com/form-data/form-data).

Form-Data v1.0.0-rc2 [added a shim for browser](https://github.com/form-data/form-data/pull/122), but it still just returns the native FormData, which IE9 does not have. Is a polyfill required?

**Comment by rafaferreira** [comment]
+1

**Comment by focusaurus** [comment]
@rbardini Thanks for the detailed analysis. I suspect you are right and a polyfill is necessary. PR would be welcome, especially with tests as without automated tests IE9 support could easily rot over time.

**Comment by bratva** [comment]
+1

**Comment by pornel** [comment]
I've updated the readme that it's required https://github.com/visionmedia/superagent/commit/11abecbe7272181b7c4f3b4a2f749caaee7631b1

**Comment by koenpunt** [comment]
As fas as I know there are no polyfills for FormData. If someone can recommend one that works in IE9, please tell!

**Comment by notflip** [comment]
Is this fixed or still open?

**Comment by pornel** [comment]
I'm going to close it as wontfix:

We require `FormData` polyfill for IE9, as noted in the README. This requirement won't change. 

If you still need reliable IE9 support and `FormData` polyfills aren't good enough, then use JSON or real  HTML forms instead.

**Comment by jimmywarting** [comment]
Here is a reliable FormData polyfill: https://github.com/jimmywarting/FormData

**Comment by 823844596** [comment]
@jimmywarting   i use your polyfill in my code, and run it in IE9, but the console show error like:
SCRIPT5009: 'Blob' undefined
and i found Blob support IE10 from https://developer.mozilla.org/en-US/docs/Web/API/Blob
how to solve it? thx~

**Comment by kornelski** [comment]
Blobs are used to upload files via JS, which IE9 does not support. If you get errors about `Blob` being undefined, it means your polyfill is not compatible with IE9.

**Comment by 823844596** [comment]
okays... thanks for your apply~ i will try to use other polyfill.
