### ISSUE TITLE
additional parameter for progress method

### ISSUE THREAD

**Issue by jitchavan** [visionmedia/superagent#826]
Hi,
is there any way to add additional parameter for progress event.

 files.forEach((file)=> {
                var req = request.post(ajax_url);
            req.attach('file', file);
//needed extra parameter here
            req.on('progress', function(e) {
                console.log('Percentage done: ', e.percent);
                console.log(e);                
              });
             req.end(this.callback);
        }); 

requirement is for multiple file upload for maintaining progress bar for individual image.

**Comment by jitchavan** [comment]
i am closing this issue as i got the solution.
just add any parameter to object as normal property.

files.forEach((file)=> {
var req = request.post(ajax_url);
req.attach('file', file);
//adding property to object
**req.filename= value;**//any value you want to add
req.on('progress', function(e) {
console.log('Percentage done: ', e.percent);
console.log(e);
//get the property value
console.log(**this.filename**); //this object holds the property
});
req.end(this.callback);
});

**Comment by pornel** [comment]
You can do this, or you can rely on the closure and use the `file` variable directly. Another option is to use `.bind()` on a function if the function was defined elsewhere.
