### ISSUE TITLE
Error when compiling with webpack.

### ISSUE THREAD

**Issue by OKNoah** [visionmedia/superagent#827]
I get errors like this when compiling by `webpack`. I use

    ERROR in ./~/superagent/package.json
    Module parse failed: /Users/MyUser/Documents/dev/MyProject/node_modules/superagent/package.json Line 2: Unexpected token :
    You may need an appropriate loader to handle this file type.
    | {
    |   "name": "superagent",
    |   "version": "1.6.1",
    |   "description": "elegant & feature rich browser / node HTTP with a fluent API",
     @ ./~/superagent/lib/node/index.js 25:10-39

     ERROR in ./~/superagent/~/mime/types.json
    Module parse failed: /Users/MyUser/Documents/dev/MyProject/node_modules/superagent/node_modules/mime/types.json Line 1: Unexpected token :
    You may need an appropriate loader to handle this file type.
    | {"application/andrew-inset":["ez"],"application/applixware":["aw"],"application/atom+xml":["atom"],"application/atomcat+xml":["atomcat"],"application/atomsvc+xml":["atomsvc"],
      ...
      @ ./~/superagent/~/mime/mime.js 87:12-35

    ERROR in ./~/superagent/~/form-data/~/mime-types/~/mime-db/db.json
        Module parse failed: /Users/MyUser/Documents/dev/MyProject/node_modules/superagent/node_modules/form-data/node_modules/mime-types/node_modules/mime-db/db.json Line 2: Unexpected token :
        You may need an appropriate loader to handle this file type.
        | {
        |   "application/1d-interleaved-parityfec": {
        |     "source": "iana"
        |   },
         @ ./~/superagent/~/form-data/~/mime-types/~/mime-db/index.js 11:17-37

I use [react redux starter kit](https://github.com/davezuko/react-redux-starter-kit) and have made an issue there as well: https://github.com/davezuko/react-redux-starter-kit/issues/366

**Comment by pornel** [comment]
That's because webpack doesn't support `require('.json')` by default, and like it says, you must add a loder for JSON.

**Comment by pornel** [comment]
I'm not sure what's going on, because webpack should have picked the client-side version that doesn't try to require a JSON file. 

It seems to be compiling the nodejs version. Were you intending to build a file for nodejs?

**Comment by focusaurus** [comment]
The other issue in react-redux-starter-kit has been closed. I don't think this is a superagent issue. Closing. Re-open if my cursory analysis is wrong.

**Comment by adambro** [comment]
I've got simialar error with 1.8-beta.1 version when using webpack. After downgrade to 1.7.2 everything works. The error was:
```
ERROR in ./~/mime-db/db.json
Module parse failed: /home/adam/www/openfootball/node_modules/mime-db/db.json Line 2: Unexpected token :
You may need an appropriate loader to handle this file type.
| {
|   "application/1d-interleaved-parityfec": {
|     "source": "iana"
|   },
 @ ./~/mime-db/index.js 13:17-37
```

**Comment by pornel** [comment]
@adambro it looks like you're building node-only version for web target. You should compile lib/client.js, which doesn't use mime-db.

**Comment by adambro** [comment]
Thanks @pornel for the fix!
