### ISSUE TITLE
API consistency and code sharing

### ISSUE THREAD

**Issue by focusaurus** [visionmedia/superagent#830]
There are numerous open issues noting discrepancies in either API or implementation between the browser and node codebases. I've done a comprehensive review of the public API (at least for methods if not all events). Posting here for review and discussion. Should we extract a module (commonjs file, not a separate npm package) of shared code? If so, how would the documentation work? Should we refactor code to be shared when it's 98% similar already and technically possible to do so?

- [x] `request(method, url)`: duplicated, refactor
- [x] `req.timeout(ms)`: duplicated, refactor
- [x] `req.clearTimeout(ms)`: duplicated, refactor
- [x] `req.use(fn)`: duplicated, refactor
- [x] `req.then(fn)`: duplicated. refactor
- [x] `req.parse(fn)`: duplicated, refactor
- [x] `req.set(name, value)`: slight difference, refactor to shared if possible
- [x] `req.getHeader(name)`: slight difference, refactor to shared if possible
- [x] `req.unset(name, value)`: slight difference, refactor to shared if possible
- [x] `req.field(name, value)`: slight difference, refactor to shared if possible
- [x] `req.abort()`: slight difference, extract base function and extend in subclasses
- [x] `req.withCredentials()`: browser-only API. Node could be no-op stub I think
- [x] `req.send(body)`: slight difference, refactor to shared if possible
- [x] `req.toJSON()`: node only. Refactor to shared?
- [ ] `req.query(value)`: slight difference, refactor to shared if possible
- [ ] `progress event`: see issues #807 and #803
- [ ] `req.get(url, data, fn)` and other HTTP methods: lots of duplication here. Refactor
  - node side supports a lot more HTTP verbs from the "methods" npm package
- [ ] `req.type(value)`: slight difference, refactor to shared if possible
- [ ] `req.accept(value)`: slight difference, refactor to shared if possible
  - for both `.type()` and `.accept()` the node side uses `mime` for dubious benefit
  - currently debating removing mime dependency and keeping it to the 6 aliases the client code supports, OR just leaving the code as is

The following code has been reviewed and is OK as is:

- `req.auth(user, password)`: different implementations. Slight API difference. OK.
- `request.Request(method, url)`: same API, different code, OK
- `req.attach(field, file, filename)`: same API, different code, OK
- `req.end(fn)`: same API, different code, OK
- `req.pipe(stream)`: node only, OK
- `req.write(chunk)`: node only, OK
- `req.redirects(number)`: node only, OK
- `req.agent(agent)`: node only, OK
- `req.buffer(flag)`: node only, OK
- `req.ca(cert)`: node only, OK

**Comment by ArtskydJ** [comment]
Wow, thanks for putting your time into this!

I would like the node and browser code bases to be shared (as much as possible). When they're separate, it only leads to confusion/discrepancies between them.

I don't think the shared code should be placed in an entirely separate module, just a separate file for now. There is a lot of cost in creating a separate module.

Refactoring a node/client method to use shared code is probably up to the situation. If it can be cleanly merged, I am all for it, since it reduces the amount of duplicated code. If it is impossible to cleanly merge them, then it probably means there really isn't much duplication of code.

**Comment by pornel** [comment]
Agreed we should reduce duplication.

**Comment by focusaurus** [comment]
Note I was concerned about needing to accommodate some of the jsdoc moving around in the code, but it seems our website API docs are entirely separate in docs/index.md so no need to retool any of the documentation.

**Comment by focusaurus** [comment]
@pornel there's a bunch of code (at least `.type()`, `.auth()`, and `.accept()`) that **could** be made consistent/shared except for the wrinkle that in node we use the `mime` package (which contains a huge .json data file far too large to send to the browser) whereas on the client we have a small hard-coded list of html, json, xml, and urlencoded mime types and shorthand names. Maybe that list could be extracted out via package.json `"browser"` field such that the rest of the code could be unified? Any suggestions?

**Comment by focusaurus** [comment]
Also `.auth()` has a `Buffer` in node vs `btoa` in browser issue that I think using browserify's Buffer might work OK, but not sure if that would make the client bundle bigger (if so how much) or if there's a more clever way.

**Comment by focusaurus** [comment]
OK, I'm going to close this as complete for the near-term. The remaining candidates to refactor to `request-base.js` have enough complications to warrant their own issue/PR.

**Comment by pornel** [comment]
Good job on that!
