### ISSUE TITLE
Is possible to get data output outside of a callback? 

### ISSUE THREAD

**Issue by GBeauny** [visionmedia/superagent#831]
Hi, 

I would like to to know if it's possible to get data response (body) from a request (GET, POST, whatever) outside of a callback? 

Thanks Guys.

**Comment by focusaurus** [comment]
This sounds like a general question about node callback control flow. Yes, you can get the data outside of a callback, but not until it arrives and the callback executes. Once the callback gets the data you can assign it to a variable, add it to an array, or whatever else you need to do with it. It sounds like you want to do this.

```js
var body;
request.get('/data').end(function (error, res) {
  body = res.body
})
console.log(body)
```

In which case, no you cannot do it that way.

**Comment by GBeauny** [comment]
Can we get the data of a POST inside the callback?
