### ISSUE TITLE
not throwing error?

### ISSUE THREAD

**Issue by fr-kshibata** [visionmedia/superagent#838]
```
var file = request.get(path)
  .auth(auth.user,auth.passwd)
  .end(function(err){
    if(err) throw err;
  });
```

if auth.user and auth.password is wrong it still proceeds anyways and doesn't throw errors

**Comment by pornel** [comment]
I'm unable to reproduce. You get an error when server responds with status 401. If the server rejects the password, but only prints a message without setting status code, then superagent won't know that it's an error.
