### ISSUE TITLE
File name is undefined if not explicitly set.

### ISSUE THREAD

**Issue by jisaacks** [visionmedia/superagent#843]
Using version `1.6.1` when I do:

```javascript
req.attach('image', file); // file is a File object: https://developer.mozilla.org/en-US/docs/Web/API/File
```

The filename becomes `undefined` and the file path becomes `/path/to/filename/undefined`.

However explicitly setting the filename fixes it:

```javascript
req.attach('image', file, file.name);
```

**Comment by pornel** [comment]
Yeah, we could be smarter about this. Would you like to make a PR for it?

**Comment by jisaacks** [comment]
@pornel sure, I put one together. I had an issue with adding tests though, take a look and let me know if you need it adjusted.
