### ISSUE TITLE
get request sending nested object query?

### ISSUE THREAD

**Issue by littlee** [visionmedia/superagent#849]
I am trying to send a nested query with superagent

``` js
request
.get('/my/path')
.query({
    a: '1',
    b: {
        innerA: '2',
        innerB: '3'
    }
})
```

the query will be encoded to like this:

```
a=1&b=%5Bobject%20Object%5D
```

that's not what I want, how do I fix it?

**Comment by aniss** [comment]
Same issue here.

**Comment by pornel** [comment]
Superagent supports only one level of nesting, so you'll have to create flattened keys yourself, e.g.

```js
.query({
    a: '1',
    'b[innerA]': '2',
    'b[innerB]': '3',
})
```
