### ISSUE TITLE
Get Raw Request to debug

### ISSUE THREAD

**Issue by srohde** [visionmedia/superagent#85]
Is there a way to get the raw request data?
I've got a problem where a post works with restler but not with superagent and I am looking for an easy way to debug it.

**Comment by robotlovesyou** [comment]
In case anybody else ends up here you can use
```
.end(function (error, result) {
   console.log(result.req);
});
```

Although the request is a pretty big graph so you'll probably just want to look at one or two properties

**Comment by davidhq** [comment]
Thank you @robotlovesyou, that was useful!

**Comment by kennethklee** [comment]
closest i could get was

```
console.log(result.req._header + JSON.stringify(json))
```

where `json` was the body I sent.
