### ISSUE TITLE
Fake Promise is a breaking API change

### ISSUE THREAD

**Issue by rooftopsparrow** [visionmedia/superagent#852]
The fake promise that was introduced in #709 is a **BREAKING** change and not backwards compatible.

I wrote a little scenario involving an async action via a promise. Before this change was made, this was perfectly valid until the fake promise was added to the library. For this scenario, I used native promises but have also tested with a promise library with the same result.

```js
var http = require('http')
var fs = require('fs')
var superagent = require('superagent')
var dest = fs.createWriteStream('response.txt')

// stand up a simple http server
var server = http.createServer(function(req, res) {
  console.log('got request')
  res.end('hello superagent!')
})

// Start listening
server.listen(1234, function() {

  console.log('server listening')
  
  // Generate dummy data
  var promise = new Promise(function(resolve, reject) {
    
    resolve({ hello: 'superagent' })
    
  }).then(function(data) {
    
    // generate a dummy request
    return superagent.post('http://localhost:1234').send(data)
    
  }).then(function(res) {
    // At this point, we should have a request
   // that hasn't been fired yet, based on the docs.

    // Pipe to the dest, fires the request and streams to the file
    res.pipe(dest)
    // kill the program
    dest.once('close', function() {
      console.log('wrote response')
      process.exit()
    })
    
  })
  
})
```

With `superagent@<1.3.0`, the code works as expected and you will see a `wrote response` and the `response.txt` will have the correct text `hello superagent!`. 

The problem with `superagent@^1.3.0` the request ( that should not have fired based on the docs ) is seen as a "thenable" and so the promise chain will call the `then()` method which fires off the request and returns the buffered response to the next promise chain call. Because of this, the pipe method will not work because the stream has already been exhausted, the program will never end, and the `response.txt` will have no content.

**Comment by pornel** [comment]
I agree this does change behavior indeed. I'm not sure if we can do anything about this? Reverting this change now will be another backwards-compatibility break.

**Comment by focusaurus** [comment]
Yeah this is unfortunate. If we do anything, I'd vote to remove the fake promise API entirely and bump semver major. I'd personally rather stick with a callback API that follows node core conventions and let folks do something like `Promise.promisifyAll(request.prototype)` (with bluebird) if they want Promises.

**Comment by pornel** [comment]
If we bump major semver #854, we could as well upgrade thenable to a native Promise API.
