### ISSUE TITLE
Using both `attach` and `send` incorrectly results in multipart data being sent as JSON

### ISSUE THREAD

**Issue by joepie91** [visionmedia/superagent#859]
While helping out @devJunkORG on IRC with a strange issue, we ran into this issue: when using both `.attach` and `.send` in a request, the request header will indicate `application/json` as `Content-Type`, but the payload will contain multipart-formatted data (with boundaries and all).

The following is example code:

``` js
files.forEach((file) => {
    req.attach(file.name,file);
});

req.send({ id: 12345 })

req.end((err,res) => {
    // ...
});
```

The following is a (redacted) snippet of the HTTP request that is made:

```
POST /upload HTTP/1.1
Connection: upgrade
Host: <redacted>
Content-Length: 476885
Origin: <redacted>
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36
Content-Type: application/json
Accept: */*
Referer: <redacted>
Accept-Encoding: gzip, deflate
Accept-Language: es-ES,es;q=0.8,en-US;q=0.6
Cookie: _<redacted>

------WebKitFormBoundaryahUn9Gpiz9X7ii4e
Content-Disposition: form-data; name="sample.png"; filename="undefined"
Content-Type: image/png
```

The cause of this issue is that superagent does not prevent a user from using both `attach` and `send`, even though that is invalid and the user should be using `field` instead. Thus, the following happens:
1. [`this._formdata` is set](https://github.com/visionmedia/superagent/blob/8b10519376114ee5df6e0c77ef6adc77992f1259/lib/client.js#L793-L794)
2. [`this._data` is set](https://github.com/visionmedia/superagent/blob/8b10519376114ee5df6e0c77ef6adc77992f1259/lib/client.js#L858)
3. The `content-type` [is set to `application/json`](https://github.com/visionmedia/superagent/blob/8b10519376114ee5df6e0c77ef6adc77992f1259/lib/client.js#L862), leading to the header indicating JSON.
4. When sending, [`this._formData` is prioritized over `this._data`](https://github.com/visionmedia/superagent/blob/8b10519376114ee5df6e0c77ef6adc77992f1259/lib/client.js#L941), leading to the payload containing multipart-encoded data.

While I understand that `attach` and `send` should not be used together, this is apparently not obvious to users - the library should error out in this case, and instruct the user on where to look instead, rather than creating an inconsistent internal state.

**Suggested resolution:** Make `send` error when `this._formData` is set and point at `field`, and similar for `field` and `attach` erroring out when `this._data` is set.

**Comment by pornel** [comment]
That sounds like a sensible usage. Perhaps we can make it work by translating such .send() into .field() calls?

**Comment by devjunkORG** [comment]
What @pornel suggests would be ideal, I think. I ran into this problem by not reading deep enough into the docs and I'm convinced that I can't be the only one.

But at least reporting the proper error would be enough. In my case what happened and what made it so hard to find the error was that the message I was receiving was related to the size of the payload, since the PNG was being interpreted as JSON data by nginx, thus exceeding the max body size.

**Comment by joepie91** [comment]
To clarify - the message that @devjunkORG was seeing was being sent by either NGINX or their body-parsing middleware, and not by superagent.

@pornel That seems like a better solution. I was assuming that the split between `field` and `send` was intentional for some reason, hence suggesting the error approach.
