### ISSUE TITLE
superagent way to do ajaxStar and ajaxStop

### ISSUE THREAD

**Issue by littlee** [visionmedia/superagent#861]
In jquery
there is ajaxStar and ajaxStop to listen the ajax event.

how to do that with superagent?

because I'm using React, so I give up jquery, though it has ajax hepler, I do not need any dom manipulation, including jquery looks a kind of waste

**Comment by vicanso** [comment]
http://visionmedia.github.io/superagent/#aborting-requests

You may read the api first.

**Comment by littlee** [comment]
Seems I did not make myself clear.
the link you show me is just a sentence.
![2016-01-20_233530](https://cloud.githubusercontent.com/assets/7534668/12453505/85ce433e-bfce-11e5-9705-34aa5062b1fd.png)

what can this .abort method do with ajaxStar/Stop?

can you look this question in stackoverflow?
http://stackoverflow.com/questions/33219794/superagent-equivalent-of-jquerys-ajaxstart-ajaxstop

the question author is faced with the same problem with me.

**Comment by vicanso** [comment]
I am sorry. I made a mistake.

```js
function stats(req) {
  req.once('request', function(){
    // ajaxstart
    req._startedAt = Date.now();
  });
  req.once('error', function(){
    // an error，the request fail
  });
  req.once('end', function(){
    // ajaxstop
    var use = Date.now() - req._startedAt;
  });
}

function get(url) {
  return request.get(url)
    .use(stats);
}

Request.prototype._end = Request.prototype.end;
Request.prototype.end = function(fn) {
  this.emit('request');
  this._end(fn);
}
```

**Comment by littlee** [comment]
wow~

**Comment by focusaurus** [comment]
In current superagent, the equivalent functionality would be:

1. listen for the `'request'` event in place of `ajaxStart`
2. Use the `.end()` callback in place of `ajaxStop`

I would consider a PR to have superagent emit an `end` event (for responses, aborts, and errors) in the same place we invoke the `.end()` callback so there's a consistent event model without having to mix event handler and callbacks.
