### ISSUE TITLE
Auto add '=' to query

### ISSUE THREAD

**Issue by brickyang** [visionmedia/superagent#870]
I need to get data from `http://hostname.com?exif`. I used `request.get('http://hostname.com?exif')` but superagent will auto add '=' to the query. So the url is actually `http://hostname.com?exif=`.

The url is a third part API, I can't help with it. So how can I avoid superagent to auto add the '='?

**Comment by efegurkan** [comment]
Is this still happening, I couldn't reproduce it locally on master. Maybe it fixed since the issue opened?

**Comment by pornel** [comment]
We've changed a few things around this functionality, so it could have been fixed. Please reopen if you find this happening.

**Comment by brickyang** [comment]
@pornel Sorry I just come back from London to Beijing so I haven't tested it yet. Will report after my test. Thanks
