### ISSUE TITLE
on("error", fn) event does not catch 4xx, 5xx errors

### ISSUE THREAD

**Issue by gutenye** [visionmedia/superagent#872]
Given

``` javascript
request
  .get(url)
  .on("error", handleErrors)
  .end()
```

The `handleErrors` method is missing 4xx, 5xx errors, they only exist on `end()` method, then how to write a plugin for this case? (plugin can not hook into `end()` method)

Is there a particular reason not passing 4xx, 5xx errors to `on("error", fn)` event?

**Comment by pornel** [comment]
This should be fixed in 3.1+
