### ISSUE TITLE
Fails to parse JSON, doesn't give us the statusCode

### ISSUE THREAD

**Issue by mattdell** [visionmedia/superagent#876]
I am attempting to interact with an API that returns 403, a content-type header of `application/json`, but a response body of `Forbidden`.

Because the error response `Forbidden` cannot be parsed it falls into the following case:

```
try {
  res = new Response(self);
} catch(e) {
  err = new Error('Parser is unable to parse the response');
  err.parse = true;
  err.original = e;
  // issue #675: return the raw response if the response parsing fails
  err.rawResponse = self.xhr && self.xhr.responseText ? self.xhr.responseText : null;
  return self.callback(err);
}
```

Since we have the xhr object here, could we add the statusCode as well? I need to handle logic for either a 403, 404, 422, and 500 regardless of the response body.

**Comment by pornel** [comment]
Should be fixed now
