### ISSUE TITLE
Response status sugar

### ISSUE THREAD

**Issue by Risto-Stevcev** [visionmedia/superagent#880]
I wanted to make some suggestions on improving Response Status sugar according to the [HTTP/1.1](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html) spec.

`res.ok = 2 == type;` should really be called `res.successful`. `res.ok` should be reserved for status code [200: OK](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.2.1).

`res.created = 201 == status;` should be added. When a new resource is created using POST, a RESTful API should return [201: Created](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.2.2)

`res.redirection = 3 == type;` should be added. Some 3xx status codes are critical for a proper REST API, such as 301 and 304.

`res.movedPermantently = 301 == status;` is used when a resource is assigned a [new URI](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.3.2).

`res.notModified = 304 == status;` is used to respond to [cache validation](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.3.5), stating that the resource is not modified and therefore not including it in the body of the request. See also [section 13.3.3](https://www.w3.org/Protocols/rfc2616/rfc2616-sec13.html#sec13.3.3).

`res.internalServerError = 500 == status` is used to indicate some [internal error](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.5.1), which is useful because it tells the client that the error is server-side (as opposed to a client-side error, or 400: Bad Request).

If these changes to the sugar are approved, then I can offer work on adding these and submitting a pull request since it's just sugar and shouldn't take that long.

**Comment by pornel** [comment]
`res.successful` is much longer and typo-prone than `res.ok`. 

I'm not sure other statuses are checked commonly enough to need sugar. Redirects are simply followed most of the time. In the browser the 304 is handled transparently. Usually if you get 400, your app, or its user, can't do anything more about it than about 500 or 503.

**Comment by Risto-Stevcev** [comment]
@pornel I use superagent to test my API, and so I think it's pretty normal to add a test to check that if a resource is moved that my server will send a 301. 
The validation check request is sent by modern browsers automatically (using `If-Match` and/or `If-Modified-Since` headers), but the server is supposed to correctly respond with 304 if the resource isn't modified, and I'm using superagent to test my API. But I agree with you about 500 though, it might not be common enough.

**Comment by pornel** [comment]
For testing, perhaps it could be added to https://www.npmjs.com/package/should-http? 

I'm not convinced it's important for superagent, so I'm closing this issue.
