### ISSUE TITLE
WebDAV support

### ISSUE THREAD

**Issue by fr-kshibata** [visionmedia/superagent#882]
Is there any plan for webdav support?

**Comment by focusaurus** [comment]
I believe all the HTTP verbs from WebDAV are supported as they are included in the `methods` module that is our full list of supported methods. Is there anything specifically beyond that you had in mind?

**Comment by fr-kshibata** [comment]
Can you teach me how to use MOVE method? with basic auth 'admin' 'adminpass'

**Comment by fr-kshibata** [comment]
curl --user 'user:pass' -X MOVE --header 'Destination: http://10.184.19.243:4502/content/dam/phase1/publish/22ss' http://10.184.19.243:4502/content/dam/phase1/publish/11ss/abdcd --verbose

**Comment by focusaurus** [comment]
Try this:

    request.move('http://10.184.19.243:4502/content/dam/phase1/publish/11ss/abdcd')
      .auth('user', 'pass')
      .set('Destination', 'http://10.184.19.243:4502/content/dam/phase1/publish/22ss')
      .end(yourCallback)

**Comment by fr-kshibata** [comment]
Works like magic thanks! @focusaurus

**Comment by fr-kshibata** [comment]
Sorry to reopen this but I think it would be helpful to add a documentation for web dav as well. 
Also how do we send delete request using webdav? (not to be confused by del)

**Comment by focusaurus** [comment]
I think we'd surely consider a pull request with some documentation around WebDAV. The file to edit is `docs/index.md`. I'd just want to be sure it was clear what can be expected to work in browsers (to my knowledge mostly GET and POST only) vs what works in node.

I don't know if any of the collaborators are actively working with WebDAV so I'd think we are probably not in a good position to document the details of the situation accurately.
