### ISSUE TITLE
Can DELETE send an entity body?

### ISSUE THREAD

**Issue by shnode** [visionmedia/superagent#886]
or what is the REST-ful way of deleting multiple items with superagent.

**Comment by pornel** [comment]
As far as HTTP is concerned `DELETE` can contain a body, but the request is for the URI, and the body is not supposed to be semantically meaningful.

**Comment by focusaurus** [comment]
I don't believe REST addresses bulk delete (or really bulk operations of any kind), at least I'm not aware of any convention. In practice I have seen RPC style endpoints like `DELETE /api//books/bulk` sending an array of ids as the request body.
