### ISSUE TITLE
jsonp support?

### ISSUE THREAD

**Issue by inadarei** [visionmedia/superagent#89]
Thank you for a lovely API.

I have one question however: how would you handle jsonp elegantly with superagent? in jQuery if you pass "function=?" it knows to invoke the anonymous callback on response. Was not sure how the equivalent flow would be done in superagent?

Thank you.

**Comment by ntucker** [comment]
I couldn't find any plugin for JSONP, so I wrote one here: https://ntucker.true.io/ntucker/jsonp-plugin-for-superagent/
