### ISSUE TITLE
provide a browser-friendly alternative to form-data module used by lib/request-base.js

### ISSUE THREAD

**Issue by iambumblehead** [visionmedia/superagent#894]
provide a browser-friendly alternative to form-data module used by lib/request-base.js

form-data requires these node-specific files
```javascript
var util = require('util');
var path = require('path');
var http = require('http');
var https = require('https');
var parseUrl = require('url').parse;
var fs = require('fs');
var mime = require('mime-types');
var async = require('async');
```

I'm not sure how browserify manages these. My build tool produces a broken script using these newest superagent sources.

**Comment by iambumblehead** [comment]
[This change][0] breaks superagent for me

[0]: https://github.com/visionmedia/superagent/commit/d807eb54a9bb2226ce53c7a9882852f2d32e9c54

**Comment by focusaurus** [comment]
Are you building via `make`?

**Comment by pornel** [comment]
We've had some reports of Webpack picking incompatible type of module when building #672 #827 

Are you using Webpack as well?

**Comment by iambumblehead** [comment]
I'm using this tool I wrote https://github.com/iambumblehead/scroungejs

If 'form-data' defined a browser index exporting window.FormData this would work. Maybe I should update my build tool.
