### ISSUE TITLE
Absolute Url

### ISSUE THREAD

**Issue by andrehrf** [visionmedia/superagent#895]
Hello everyone how not found any solution to change relative links of the request returns, created a plugin for this available in https://github.com/andrehrf/superagent-absoluteurl would like to ask everyone to look at the code and will improve increasingly =)

**Comment by focusaurus** [comment]
You might consider coding this as a superagent plugin that works with `request.use(absoluteUrlPlugin)` and then submitting a PR to add your plugin to the superagent README.

Aside: I think your module might need to support the obscure HTML `<base>` tag to correctly handle the (rare) pages that make use of it.

Aside: Your repo has misspelled "examples" in the directory name.

Looks like a neat plugin!

**Comment by Valeronlol** [comment]
https://gist.github.com/Valeronlol/eac4fca14d485592070904c02629ad33
