### ISSUE TITLE
how can i get the base64 of web image using superage

### ISSUE THREAD

**Issue by zxyah** [visionmedia/superagent#897]
the code:
`
superagent.get('http://image.jpg')
            .end(function (err, res) {
                console.log(res);
            })
`
i want transfer response body to base64 using Buffer(response.body).toString('base64')
but the response body is null
i transfer response.text to base as Buffer(response.text).toString('base64')
but it is not right

**Comment by pornel** [comment]
We don't have buffer output yet: #871

**Comment by zxyah** [comment]
will add the feature?

**Comment by pornel** [comment]
Sorry, correction. We do have buffer output *if* Content-Type of the response is `image/`-something. In that case `response.body` will be a buffer.

If MIME type is not right, it gets complicated: #950

**Comment by zxyah** [comment]
Thanks, I Have Solve The Problem By Other Way, Not Get The base64 Of Image
