### ISSUE TITLE
webpack error with fs and json

### ISSUE THREAD

**Issue by p4bloch** [visionmedia/superagent#902]
I get this when trying to compile, with superagent being used only in the client side.

```
ERROR in ./~/superagent/~/form-data/lib/form_data.js
Module not found: Error: Cannot resolve module 'fs' in /Users/me/project/node_modules/superagent/node_modules/form-data/lib
 @ ./~/superagent/~/form-data/lib/form_data.js 7:9-22

ERROR in ./~/superagent/~/form-data/~/mime-types/~/mime-db/index.js
Module not found: Error: Cannot resolve module 'json' in /Users/me/project/node_modules/superagent/node_modules/form-data/node_modules/mime-types/node_modules/mime-db
 @ ./~/superagent/~/form-data/~/mime-types/~/mime-db/index.js 11:17-37
```
I tried both solutions proposed in the [Superagent for Webpack](https://github.com/visionmedia/superagent/wiki/Superagent-for-Webpack) document without success. The file being loaded is `superagent/lib/client.js`, as specified in my webpack alias

```
resolve: {
    alias: {
      'superagent': 'superagent/lib/client'
    }
  }
```

Any other solutions I can look at?

**Comment by p4bloch** [comment]
Actually my version constraint was in `latest`. Specifying `superagent@1.7.2` solved this.

**Comment by ianks** [comment]
I experience the same issues with superagent ^1.8.0

**Comment by pornel** [comment]
We specify in package.json:

```js
 "browser": {
    "./lib/node/index.js": "./lib/client.js",
    "emitter": "component-emitter",
    "reduce": "reduce-component",
    "./test/support/server.js": "./test/support/blank.js"
  },
```

which should tell WebPack to use the browser-compatible `./lib/client.js` instead of `./lib/node/index.js`, but it looks like Webpack is ignoring this.

I think it should work. I don't know if there's anything else that we can do, so I won't be able to fix this.

Please file a bug in Webpack instead.

**Comment by qingemeng** [comment]
Is it fixed in the latest version? It still happens in 3.0.0
