### ISSUE TITLE
qs dependency is REALLY outdated

### ISSUE THREAD

**Issue by clayreimann** [visionmedia/superagent#908]
Current `qs` dependency does not correctly encode `'` in query strings. but current version does. 

After further investigation it would appear that `qs` itself is inconsistent between the browser and node. Output in [the browser](https://tonicdev.com/56d5fffd67c99d0d00e23fbc/56d62322aa56a10d00254857) does not match output in node. 
![image](https://cloud.githubusercontent.com/assets/930039/13445575/a4a2407a-dfd2-11e5-828d-5ac5cd0ea4c9.png)

**Comment by pornel** [comment]
I wasn't aware it's that bad. Our tests expect qs to handle UTF-16, and the version we use did it better than the latest.

**Comment by clayreimann** [comment]
Version 2.x of `qs` doesn't percent encode `'` per RFC 3986. And [as far as I can tell](https://github.com/visionmedia/superagent/blob/master/test/node/query.js#L30) your tests just expect `qs` to fail in a very specific way when you provide UTF-16 strings as input.
