### ISSUE TITLE
use beta as stable version?

### ISSUE THREAD

**Issue by sinkcup** [visionmedia/superagent#920]
now if you run `npm install superagent`, it will be "superagent@1.8.0-beta.2".

but in usual, it should be stable version like "superagent@1.7.0".

is there some settings wrong?

**Comment by pornel** [comment]
Try `npm i superagent@1`. I didn't expect npm to pick a beta version by default :/

**Comment by sinkcup** [comment]
maybe you need this:

https://coderwall.com/p/l_7acq/publish-beta-versions-of-npm-modules

**Comment by pornel** [comment]
We have a stable 1.8 now. I'll keep beta tag in mind next time.
