### ISSUE TITLE
Docs for attachCookies

### ISSUE THREAD

**Issue by jifeon** [visionmedia/superagent#921]
Just found a method to [attach cookies](https://github.com/visionmedia/superagent/blob/324c97a9cee73c3dc53c424618daaadc3ea06317/lib/node/agent.js#L50) in source code. Why it's not in docs? Can I use it, or it's private and can be changed? Or it's not documented because it's not isomorphic?

**Comment by pornel** [comment]
Yes, methods with `@api private` in the doccomment are private and not supposed to be used outside superagent's own code (since they're subject to change and can disappear at any time).

**Comment by jifeon** [comment]
ok thx

**Comment by pornel** [comment]
#922
