### ISSUE TITLE
update all dependencies

### ISSUE THREAD

**Issue by focusaurus** [visionmedia/superagent#929]
When we get ready for 2.0 semver major, we should probably do a comprehensive review of our dependencies and make sure they are all current. I would recommend going semver and specifying them just by the current major version, for example: `"extend": "3"` as I think this is the correct thing to do in a library, but if the collaborators prefer another approach, that's OK I'd just like it to be consistently adhering to a clearly-defined rationale.

**Comment by pornel** [comment]
Agreed

**Comment by focusaurus** [comment]
OK, I started testing. The tests pass with the latest versions of most things, with the following exceptions:

- should.js need to refactor `res.should.have.status(200)` to `res.should.have.property('status', 200)` as of should v4 (I think. Latest is v8)
- `form-data` needs to ship 1.0.0 without release candidate

**Comment by pornel** [comment]
Looks like we're up to date now
