### ISSUE TITLE
1.8.0 relies on a `form-data`, that expects window.FormData to exist. Throws otherwise

### ISSUE THREAD

**Issue by ponelat** [visionmedia/superagent#933]
The recent bumped version `1.8.0` broke our CI server...
I don't have too much time to go into details, but this test (with a webpack builder) fails with...

details:
Using  `webpack` + `karma` + `jsdom`

`FormData is not defined <- webpack:///~/form-data/lib/browser.js:1:0`

```js
// Code
import request from 'superagent'
import { expect } from 'chai'

describe('superagent is broke', function(){
  it('should work', function(done){
    request.get('google.com').end(function (err, res) {
      expect(res.test).to.match(/google/)
      done()
    })
  })
})
```

Running a similar test works in node.js

I changed to `1.7.2` and all is well.

**Comment by pornel** [comment]
In 1.8 we use `form-data` module that seems to require a browser that doesn't support `FormData`

`window.FormData = false` may be a workaround.

**Comment by bmatto** [comment]
I'm seeing this issue as well in IE9 - Was particularly confusing because we have a module elsewhere called FormData :8ball: 

:+1:

**Comment by ponelat** [comment]
@pornel thanks for filing the form-data issue (and creating a PR I see).

**Comment by ponelat** [comment]
I updated the issue title, to be something more useful.

**Comment by ponelat** [comment]
thanks for the fix !
