### ISSUE TITLE
Add listener for formData error event

### ISSUE THREAD

**Issue by scriptype** [visionmedia/superagent#939]
When sending multipart data, if I give a non-existent path or some filesystem error happens in readStream, `request.on('error')` doesn't receive any error. This causes process to exit non-zero.

If anyone could confirm that this should be fixed/improved, I'm going to open a pull request.

**Comment by pornel** [comment]
You mean there's an uncaught exception? We definitely should catch and pass these on.

**Comment by scriptype** [comment]
Yes. There are no error handlers for formData, which happens to handle fs-level read.
