### ISSUE TITLE
Allow not define an URL on methods

### ISSUE THREAD

**Issue by piranna** [visionmedia/superagent#944]
When calling `.post()` without an argument it fails because there's no url to parse, but when using an empty string it works. I think this should be the default value since sometimes you are not interested on process the url, for example when you know that the process function will be in a specific endpoint. The same would be done when you don't mind about a particular HTTP method, so I would make the `.post()` and `.get()` methods optional.

**Comment by pornel** [comment]
Sorry, I don't follow. Could you give an example what would you use it for?

Every HTTP request needs to have a URL, so something like `request.post()` wouldn't know where to send data to. 

The fact that `request.post('')` is an accident, and ends up being same as `request.post('http://localhost/')` (at least in node version).

**Comment by piranna** [comment]
> The fact that request.post('') works is an accident, and ends up being same as request.post('http://localhost/') (at least in node version).

That's the point, what I'm asking for is that `request.post()` to have the same behaviour than `request.post('')`, it's said, that the empty string to be the default value. Don't know if it's an accident, but I think it's a good default value to have...

**Comment by pornel** [comment]
Sorry, I still don't understand usefulness of this. Why should there be special convenient shortcut for posting to `http://127.0.0.1/`? Who does that?

**Comment by piranna** [comment]
> Sorry, I still don't understand usefulness of this. Why should there be special convenient shortcut for posting to http://127.0.0.1/? Who does that?

I'm not interested on testing the URL path, since I know before hand the exact location where the middleware will be listening for, so whatever path you put on `.post()` it doesn't matter. That's just why the empty string is a valid case the same way it does not setting it at all: I don't care (in the test) where I'm posting to, only that I'm receiving a POST request.

**Comment by pornel** [comment]
Are you sure you mean superagent, and not supertest? 

Superagent is a library for making real HTTP calls over the Internet, not a test mock, so it absolutely doesn't make sense for it to ignore the path.

**Comment by piranna** [comment]
Ok... maybe you are right, it's `supertest` :-P Since it uses `superagent` as dependency and the names are a bit similar, probably when following the code to see why it was not working for me I wrong the repo when opening the issue :-P

**Comment by pornel** [comment]
Good to have this clarified! Thanks

**Comment by piranna** [comment]
You are welcome :-) [I've open a new issue on supertest](https://github.com/visionmedia/supertest/issues/323) for this :-)
