### ISSUE TITLE
Delete Response issue

### ISSUE THREAD

**Issue by harshu108** [visionmedia/superagent#945]
When I use:

supergaent
.del(url)
.end(function(err,res))
{
if(err)
console.log(err)
else
console.log(res)
}

It throws below error:

{ [Error: unexpected end of file] errno: -5, code: 'Z_BUF_ERROR', response: null }

**Comment by pornel** [comment]
Is your server sending `Content-Encoding: gzip`/`Transfer-Encoding: gzip` and does not return any bytes?

**Comment by harshu108** [comment]
Yes server sends `content-encoding: gzip` and does not return any content

**Comment by pornel** [comment]
It should be fixed in 1.8.2

**Comment by hustcer** [comment]
I got the same error in 2.2.0

**Comment by pornel** [comment]
Please submit tcpdump or a unit test that reproduces the problem.
