### ISSUE TITLE
Unbuffered parsers are tricky to use

### ISSUE THREAD

**Issue by kornelski** [visionmedia/superagent#950]
Callback is fired in: https://github.com/visionmedia/superagent/blob/2910a198b7ca61c83eb308f67aba793d98d44ef8/lib/node/index.js#L803

which happens **before** async parsers set the body: https://github.com/visionmedia/superagent/blob/2910a198b7ca61c83eb308f67aba793d98d44ef8/lib/node/index.js#L787

so `res.body` in the callback ends up being the default `{}`. 

The parsers listen to `end` event. I suspect this may also cause race conditions with other code that listens to the `end` event and wants to use parsed body.

I think the right solution would be to wait with the callback until async parser is done (users who want to see response early can listen for the `response` event).

BTW: node code for choosing the right parser seems to be unnecessarily complicated (and uses both `parse` & `parser` variables).

**Comment by pornel** [comment]
I think buffered responses should be the default, and unbuffered responses should be only opt-in. 

Having buffering mime-dependent is weird, especially that unknown types get unbuffered behavior. 

BTW, currently node and browser have different interfaces for parsers. There may be a possibility of unifying them, while sorting out buffering in the new parser API.
