### ISSUE TITLE
GET request working in localhost but not in server

### ISSUE THREAD

**Issue by Rexota** [visionmedia/superagent#951]
```
request
	   .get('https://eksisozluk.com/debe')
	   .end(function(err, result){

})
```

I'm requesting that website like this, but it's not giving any result in my server. 

```
err.status is null
err.response ETIMEOUT
```

(As I said working as expected in localhost.)

**Comment by focusaurus** [comment]
This is likely a networking issue on your server. Try from your server's command line: `curl -v https://eksisozluk.com/debe`. If that also fails, it's a networking issue, most likely an outbound firewall dropping outbound traffic resulting in ETIMEOUT. If the curl version does work, we can look further into node/superagent.

**Comment by Rexota** [comment]
```
$ url -v https://eksisozluk.com/debe
* Hostname was NOT found in DNS cache
*   Trying 176.53.43.6...
```

It got stuck like that. (Thanks for your help)

**Comment by Rexota** [comment]
I resolved the issue by creating three more droplets in digitalocean. Third one worked.
