### ISSUE TITLE
TypeError: 'POST' is not a constructor (evaluating 'new RequestConstructor('GET', method)')

### ISSUE THREAD

**Issue by alioygur** [visionmedia/superagent#955]
I am getting this error on QtWeb Internet Browser http://www.qtweb.net/

```
TypeError: 'POST' is not a constructor (evaluating 'new RequestConstructor('GET', method)')
```

**Comment by focusaurus** [comment]
How about posting the code snippet that is generating the error?

**Comment by pornel** [comment]
Please reopen if it still happens in the latest version.
