### ISSUE TITLE
Mention async/await usage somewhere in the docs?

### ISSUE THREAD

**Issue by taoeffect** [visionmedia/superagent#957]
I think folks would be interested to know that you can already using `superagent` with async/await like so:

```js
async function () {
  try {
    var response = await request.post('/user/').send({foo: 4}).end()
  } catch (err) {
    // do something with err...
  }
}
```

Just use bluebird:

```js
var Promise = global.Promise = require('bluebird')
var superagent = require('superagent')
superagent.Request.prototype.end = Promise.promisify(superagent.Request.prototype.end)
```

**Comment by crookedneighbor** [comment]
That doesn't seem like something inherent to superagent. You're using bluebird to promisify the callback, and any promise can be used with `async/await`. Following that logic, you'd include a note about using `async/await` in _any_ callback based library, which seems unnecessary.

**Comment by pornel** [comment]
In 2.0 we support real promises in `.then()`, so there's no need to wrap `.end()`:

```js
const response = await request.post('/foo');
```

should just work. I don't mind adding that to the documentation.

**Comment by crookedneighbor** [comment]
May I ask what the point of adding the documentation would be? If you're using `async/await`, you should see that superagent can return a promise and know that you can use `async/await` on it. If you're not using it, and aren't familiar with `async/await`, the documentation would be confusing unless you also mention that you need to transpile code from es7 to use it. Seems like more trouble than it is worth IMO.

**Comment by taoeffect** [comment]
> May I ask what the point of adding the documentation would be?

The point would be to help and encourage people to switch their codebases over to await/async syntax.

**Comment by crookedneighbor** [comment]
IMO, that doesn't seem like a concern of this module.

**Comment by taoeffect** [comment]
Providing examples at all isn't a concern of this module, but it's a good thing to do. I'm surprised at how this small (and helpful, I thought) suggestion seems to be upsetting you @crookedneighbor. It was not my intent to upset you. If you feel strongly this small example usage is an existential threat of some sort, by all means let me know and I can close this issue, I wouldn't want to cause you harm though it.

**Comment by taoeffect** [comment]
FWIW, @pornel's example is great too, it's just that until then I think superagent doesn't support it, so this could work in its place in the meantime.

**Comment by crookedneighbor** [comment]
Sorry to convey being upset. Not upset, just have strong opinions :smile: 

It just seems out of scope to me. Especially for a language feature that is still stage 3, not stage 4. (If it has transitioned to stage 4, please share a link, cause that's very exciting news!)

**Comment by pornel** [comment]
Let's wait for superagent 2.0 and es7 finalizing the feature.

**Comment by niftylettuce** [comment]
For anyone that wants to go bleeding edge and not use stable releases of Superagent... here's a promise implementation (uses ES6/ES7 async/await too, with ES6's new `fetch()` method) https://github.com/glazedio/frisbee

**Comment by crookedneighbor** [comment]
Looks like this has been added to the docs:

![screen shot 2016-08-03 at 1 16 55 pm](https://cloud.githubusercontent.com/assets/2916945/17376780/a8e2fdcc-597c-11e6-9052-fb5ab42620cc.png)

**Comment by dschinkel** [comment]
example is here: https://github.com/thenables/requisition

**Comment by reyou** [comment]
I came here by google searching "superagent async/await example", and I would rather to land in documentation, rather than this issue page. Well thought @taoeffect

**Comment by kornelski** [comment]
I can't help the fact that Google likes to dig out closed issues instead of showing actual docs. I've edited the description to redirect lost googlers.

**Comment by taoeffect** [comment]
@kornelski I looked at the docs you linked to, and I don't see a single example of using `async`/`await`. :-\

**Comment by taoeffect** [comment]
FWIW I no longer use `superagent` and now use the [native `fetch` API.](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API)
