### ISSUE TITLE
`superagent` should not escape apostrophes, quotes, etc. in the URL

### ISSUE THREAD

**Issue by kadishmal** [visionmedia/superagent#958]
As stated in http://stackoverflow.com/a/18251730/556678, quotes, apostrophes, and few others should not be escaped.

	request(app)
		.get("/alerts?filter=title:invalid'title")
		.expect(200, function (err, res) {

		});

The URL that is sent becomes `/alerts?filter=type:invalid%27type`.

Calling `encodeURIComponent("invalid'title")` produces the proper result `invalid'title` where apostrophe is not escaped.

**Comment by pornel** [comment]
We use encodeURIComponent  https://github.com/visionmedia/superagent/blob/d4fb001df6ce6862e3dbdb4999c1ff82b54a4bad/lib/client.js#L99

but XHR in the browser does not allow unencoded `'`. `xhr.open('GET', "/'")` will send `GET /%27 HTTP/1.1` on the wire.

**Comment by kadishmal** [comment]
Currently I have to do:

    ('/alerts?filter=' + encodeURIComponent(filter).replace("'", '%27'));
