### ISSUE TITLE
How to find out once request opens to trigger a callback

### ISSUE THREAD

**Issue by Robinnnnn** [visionmedia/superagent#965]
I'd like to know if it's possible to know exactly when a request begins.

I want to do this so I can expose the function to `abort` a file upload if the user decides to cancel at any time. This is what my request looks like currently:
```
let req = request
    .put(signedURL)
    .set('X-AMZ-ACL', 'public-read')
    .send(pano);

return req
    .on('progress', ...)
    .then(response => ...)
    .catch(error => ...)
```

But it'd be ideal if I could add something like this:
```
return req
    .on('open', () => dispatch(exportUploadAborter(req.abort, panoId))) // makes cancellation available to user
    .on('progress', ...)
```

**Comment by focusaurus** [comment]
Listen for the `'request'` event.
