### ISSUE TITLE
There is no text or body on 503

### ISSUE THREAD

**Issue by Redsandro** [visionmedia/superagent#969]
Currently (superagent `1.8.x`), when Superagent encounters a `503`, it throws an error: `Service Unavailable`. Older versions return with `res`, `res.ok` being `false`, `res.error` being `Error: cannot POST / (503)`.

However, there is no `res.text` or `res.body` even though the server actually returns data. I've encountered this, and it took me a while before I figured that Superagent ignores the body:

`Status: 503`

```
<html>
    <head>
        <title>Server Too Busy</title>
    </head>
    <body>
          Server Too Busy. Spread your requests:
          - server1.domain.com
          - server2.domain.com
          - server3.domain.com
          - server4.domain.com
     </body>
</html>
```

**Comment by pornel** [comment]
It should be in `err.response.body`. We also have `.ok(() => true)` now to catch all error pages.
