### ISSUE TITLE
how to get timeout error code

### ISSUE THREAD

**Issue by allces** [visionmedia/superagent#970]
how to get timeout error code,thanks
`req.on('end', () => {
        console.log('end');
    });`
is not work when timeout

**Comment by pornel** [comment]
We fire an `abort` event when the request is aborted due to a timeout. If I remember correctly, you should also see the `end` event with an error.

**Comment by allces** [comment]
`.on('abort', (err) => {
                console.log('error');
            })`
is work, thanks

**Comment by pornel** [comment]
What information do you need from `err`?

**Comment by allces** [comment]
distinguish abort type. (timeout or unknown reason)

**Comment by pornel** [comment]
The `abort` event already tells you that. You can do:

```js
.on('abort', () => {throw Error("abort")})
```
