### ISSUE TITLE
1.8+ breaks tests running with phantomJS

### ISSUE THREAD

**Issue by ddperdue** [visionmedia/superagent#971]
This line (463 in superagent.js) breaks jasmine/karma unit tests we're running with phantomJS:
`require('./request').bind(null, Request);`

We get this error:
`TypeError: 'undefined' is not a function (evaluating 'require('./request').bind(null, Request)')`

Apparently phantomJS does not support .bind() so I'm not sure if this is really a superagent issue or a phantomjs issue but I figured I'd report the issue.

**Comment by pornel** [comment]
PhantomJS 1 is stuck with a very old and oddly incomplete JS engine. If you have to use it, then polyfill `.bind()`, but I suggest switching to anything else.
