### ISSUE TITLE
how to compute progress percent of request in superagent

### ISSUE THREAD

**Issue by shreychaturvedi123** [visionmedia/superagent#977]

**Comment by pornel** [comment]
The `progress` event gives an object as an argument which includes information like amount downloaded and total size.

**Comment by shreychaturvedi123** [comment]
can you show me a snippet?

**Comment by pornel** [comment]
```js
superagent.get('https://example')
.on('progress', function(e){
   console.log(e.direction,"is done",e.percent,"%");
})
.end();
```

Note that we support *download* progress only in browser, and *upload* progress only in node (it's weird, I know).

**Comment by fisch0920** [comment]
@pornel where in the world is this documented?? I've been looking through docs for the past few hours and just happened to stumble on this issue which is the only place I've clearly found this distinction.

Why isn't upload progress supported in the browser?

**Comment by pornel** [comment]
Documentation for it is missing. I'd be helpful if you made a pull request adding it!

Upload progress in browsers is just not implemented. I think with XHR2 it should be possible to add it.

**Comment by fisch0920** [comment]
Okay; I'd be glad to look into adding support, but I'm not sure I understand why it doesn't work as-is, given that `lib/client.js` includes a progress handler and bindings for `xhr.onprogress` and `xhr.upload.onprogress`.

Do you have any insight or resources that would explain why this approach isn't currently working?

Thanks!

**Comment by fisch0920** [comment]
Also, it looks like the progress handler is called several times on Chrome in a few tests I've run, but only at like 98% and 100% and never consistently.

**Comment by halt-hammerzeit** [comment]
@fisch0920 So, does browser file upload progress work?
It's surely supported, and has been so for a long time.

**Comment by pornel** [comment]
Please note that for small files you may not get any events or get nonsense progress. That's simply due to how TCP/IP and buffering works — until all buffers in your browser/os/router are full, the sending appears to be instant, but it's not known how much reached the other end until there's a response from the other side.
