### ISSUE TITLE
Actual pass raw query string

### ISSUE THREAD

**Issue by theSmallNothing** [visionmedia/superagent#979]
I'm using a weird API that I have no control over and which I have to send a base64 encoded query string to with the catch being it can't be url encoded.
`http://someapi.com/call?<base64 including '/+='>`

With `superagent` if I pass the query string as part of the url or using the `query` function it gets url encoded, I have not as yet been able to pin down the exact point this happens though.

The weird thing is its possible to send these requests in many browsers reliably, I was wondering if there was a way (other than what I mentioned) to send a raw query string?

**Comment by theSmallNothing** [comment]
Was using an older version on `npm`, `query` works perfectly.

**Comment by harshu108** [comment]
`describe('Connecting Tests',function(){
  // before executing each test case, set above as false
  beforeEach(function(){
    servicenowDs.connected = false;
    servicenowDs.connecting = false;
  });
//test case for all method
  it('should find all the incidents', function(done) {
    //stub send request
    var all_stub = sinon.stub(servicenowDs.connector, 'sendRequest', function(req, callback) {
    //  console.log(req);
        var output = {
            body: JSON.stringify({
                "result": [{
                    "number": "string",
                    "sys_id": "1e2c56e90f1a5600a919cd8ce1050edb"
                }]
            })
        };
        return callback(null, output);
    });
    //call all method
      servicenowDs.connector.all('Incident', '', function(err, result) {
          var expected = 'string';
          expect(result[0].number).to.be.equal(expected);
          all_stub.restore();
          done();
      });
      // If your connect method has code that talks to endpoint, stub connect method over here.
      //call connect of the datasource.
      servicenowDs.connect(function(err,res){

      });
 });
 });`

**Comment by harshu108** [comment]
some comment
`describe('Connecting Tests',function(){
  // before executing each test case, set above as false
  beforeEach(function(){
    servicenowDs.connected = false;
    servicenowDs.connecting = false;
  });
//test case for all method
  it('should find all the incidents', function(done) {
    //stub send request
    var all_stub = sinon.stub(servicenowDs.connector, 'sendRequest', function(req, callback) {
    //  console.log(req);
        var output = {
            body: JSON.stringify({
                "result": [{
                    "number": "string",
                    "sys_id": "1e2c56e90f1a5600a919cd8ce1050edb"
                }]
            })
        };
        return callback(null, output);
    });
    //call all method
      servicenowDs.connector.all('Incident', '', function(err, result) {
          var expected = 'string';
          expect(result[0].number).to.be.equal(expected);
          all_stub.restore();
          done();
      });
      // If your connect method has code that talks to endpoint, stub connect method over here.
      //call connect of the datasource.
      servicenowDs.connect(function(err,res){

      });
 });
 });`

**Comment by harshu108** [comment]
```
describe('Connecting Tests',function(){
  // before executing each test case, set above as false
  beforeEach(function(){
    servicenowDs.connected = false;
    servicenowDs.connecting = false;
  });
//test case for all method
  it('should find all the incidents', function(done) {
    //stub send request
    var all_stub = sinon.stub(servicenowDs.connector, 'sendRequest', function(req, callback) {
    //  console.log(req);
        var output = {
            body: JSON.stringify({
                "result": [{
                    "number": "string",
                    "sys_id": "1e2c56e90f1a5600a919cd8ce1050edb"
                }]
            })
        };
        return callback(null, output);
    });
    //call all method
      servicenowDs.connector.all('Incident', '', function(err, result) {
          var expected = 'string';
          expect(result[0].number).to.be.equal(expected);
          all_stub.restore();
          done();
      });
      // If your connect method has code that talks to endpoint, stub connect method over here.
      //call connect of the datasource.
      servicenowDs.connect(function(err,res){

      });
 });
 });
```
