### ISSUE TITLE
HTTP/2 support

### ISSUE THREAD

**Issue by warrenseine** [visionmedia/superagent#980]
AFAIK, `superagent` relies on the standard Node module HTTP/HTTPS, which, AFAIK again, is not HTTP/2-compatible. Therefore, performing HTTP/2 requests with `superagent` is not possible for now.

Technically, the [`node-http2`](https://github.com/molnarg/node-http2) module could be used to support HTTP/2 without rewriting the whole thing. Is this part of a roadmap? Could there be an alternative I didn't think of?

**Comment by pornel** [comment]
It hasn't been on my radar.

With `request-base` we've done some work to make code more reusable between browser and node, so this approach could be used to write a node-http2-based version as well.

Alternatively, if you had a node module that has the same interface as the built in `require('https')` module, you could swap these.

**Comment by harshu108** [comment]
```
describe('Ping related', function() {
              
//make connect related variables as false.
               before(function(){
                     mailchimpDS.connected = false;
                      mailchimpDS.connecting = false;
                    
//Stub connect method here
                     connect_stub = sinon.stub(mailchimpDS.connector,'connect',function(callback){
                            
                            var someFunc = function(){
                                   callback(null);
                            }
                            process.nextTick(someFunc);
                     })
                  });
//restore connect stub
                  after(function(){
                     connect_stub.restore();
                 });

                  
         it('should successfully test connection', function(done) {
//stub send request
              create_stub_ping = sinon.stub(mailchimpDS.connector, 'sendRequest', function(req, callback) {
                  var output = {
                      "statusCode": 200,
                      "account_id": "8ba087e5f225fdd80ade5e36c",
                      "account_name": "persistent",
                      "email": "sonia_targe@persistent.co.in",
                      "role": "owner"
                  };
                  return callback(null, output);
              });
              
              
              mailchimpDS.connector.ping(function(err, body) {        
                  if (err) {
                      expect(err).to.not.be.null;
                  } else {
                      expect(body).to.be.undefined;
                  }
                  create_stub_ping.restore();
                 
                  done();
              });  
//Call connect
              mailchimpDS.connect(function(err, res) {});
            
          });
)};
```

**Comment by warrenseine** [comment]
Thanks for the feedback. I'll try that.

In case this worked by swapping the modules, would a PR adding a [protocol](https://github.com/visionmedia/superagent/blob/master/lib/node/index.js#L71) and a new dependency would be considered?

**Comment by pornel** [comment]
A new dependency for node is OK.

HTTP/2 didn't add a new URL scheme, so it can't be just dropped in as a new type of URL.

I'd prefer it to work in node the same way it works in browsers — transparently via ALPN when HTTPS is used.

**Comment by leaves4j** [comment]
`http2` is ready, is there a plan to support it?
