### ISSUE TITLE
request.post sends get request

### ISSUE THREAD

**Issue by hallettj** [visionmedia/superagent#983]
This is in Chrome 50, using superagent 1.8.3. Superagent is installed via npm.

This is a simplified version of what I am doing:

```js
var request = require('superagent');
request.post('/api').send({ signed_data: '...', signature: '...' }).then(function() {});
```

Looking at requests in Chrome's network inspector, I see that GET requests are going out instead of POST requests.

I am using Webpack to bundle superagent with my application code.

Maybe I should be using a different superagent package for browser use. The use case is a library that I want users to be able to load in node or in the browser. Superagent looked like a nice option for a library that can handle either case transparently.

**Comment by pornel** [comment]
Is it possible that your API sends a HTTP redirect?

**Comment by hallettj** [comment]
Yes, the problem was on my end. I'm very sorry to open a frivolous ticket!

**Comment by pornel** [comment]
No problem
