### ISSUE TITLE
Uncaught Error: INVALID_STATE_ERR: DOM Exception 11:356

### ISSUE THREAD

**Issue by RajeshSivanesan** [visionmedia/superagent#985]
Invoked https cross domain call, which resulted in 404 status code. The same with 200 response working properly. But i got this error as an unhandled exception and unable to proceed.

Can you please look into this ?

**Comment by pornel** [comment]
It may be access denied to the response, because 404 page doesn't include CORS headers.

**Comment by RajeshSivanesan** [comment]
This issue is happening only in Stock Browser (4.3 Android) Samsung GT-i9300 phone S |||.

Its working properly in Android 4.4+ mobiles & chrome browser.

**Comment by pornel** [comment]
Oh, the Samsung 4.3 browser is awful. Sorry, we can't support it. It doesn't even have remote debugging, so it's very hard to check what's going on.

**Comment by RajeshSivanesan** [comment]
I found out where it was exactly crashing with this error by adding try / catch block, in the 'end' event of Request function.

Accessing status / statusText properties in the end event could have caused this problem.

As of now i wrapped the block with try / catch and invoked callback with error as empty and data as empty object.

Code Snippet:

try {
  		if (err) {
  			return self.callback(err, res);
  		}

  		if (res.status >= 200 && res.status < 300) {
  			return self.callback(err, res);
  		}

  		var new_err = new Error(res.statusText || 'Unsuccessful HTTP response');
  		new_err.original = err;
  		new_err.response = res;
  		new_err.status = res.status;

  		self.callback(err || new_err, res);
  	} catch (e) {
// In Samsung s3, reading property like status / statusText if invalid http readyState	                  
// result in the error "Invalid DOM Exception: Internal state error"
// Raising the callback as successful response since its an exception occured for 404 status
// of https CORS request.
  		self.callback(null, {});
  	}

Please have a look and let me know if there are any issues. Can you also think about adding this to master code base ?

**Comment by pornel** [comment]
`self.callback(null, {});` reports it was a success, so this is wrong to do that when an error happened. It will break other people's code.

Can you quote what error did you get exactly? Is `res` undefined? Is `res` an object, but `res.status` throws?

**Comment by RajeshSivanesan** [comment]
when i try to access res in the catch block to know the value, I am getting the same exception "Internal State Err: DOM Exception".

I think accessing the variable drives this problem. To get rid of this problem i thought of changing the library from superagent to x. Can you please identify the problem and add the same in the latest version ?

**Comment by pornel** [comment]
Thanks @RajeshSivanesan. Please try superagent 2.0.0-alpha.3

**Comment by RajeshSivanesan** [comment]
Thanks pornel.
