### ISSUE TITLE
Date parsing

### ISSUE THREAD

**Issue by halt-hammerzeit** [visionmedia/superagent#986]
As far as I can see currently you only parse dates as strings:
https://github.com/visionmedia/superagent/blob/b91a26fb4d8acf28534ac2cdd0bb3ce4a6f17498/lib/node/parsers/json.js#L8
```
	      var body = res.text && JSON.parse(res.text);
```

This code can't handle Dates properly.

What if I add a second parameter to JSON.parse() to handle Dates properly?
https://github.com/halt-hammerzeit/react-isomorphic-render/blob/249723de77323071517a07a3774cdcf4f14d6413/source/page-server/html.js#L123

It could be an option say `parseDates: true`

**Comment by halt-hammerzeit** [comment]
Ok, I found a workaround for the issue.

On a client:

```js
var request = require('superagent')
request.parse['application/json'] = text => JSON.parse(text, date_parser)
```

On a server:

```js
var request = require('superagent')
request.parse['application/json'] = function parseJSON(res, fn){
  res.text = '';
  res.setEncoding('utf8');
  res.on('data', function(chunk){ res.text += chunk;});
  res.on('end', function(){
    try {
      var body = res.text && JSON.parse(res.text);
    } catch (e) {
      var err = e;
      // issue #675: return the raw response if the response parsing fails
      err.rawResponse = res.text || null;
      // issue #876: return the http status code if the response parsing fails
      err.statusCode = res.statusCode;
    } finally {
      fn(err, body);
    }
  });
};
```

**Comment by pornel** [comment]
There is no date datatype in JSON, so I think superagent's behavior is correct. Your solution is fine.
