### ISSUE TITLE
.timeout() bug

### ISSUE THREAD

**Issue by willin** [visionmedia/superagent#987]
``` js
const time1 = new Date();
console.log(time1);
// timeout 5s, and the server avg response time is about 5s too.
request('xxx').timeout(5000).end(function(err,res){
      const time2 = new Date();
      console.log(time2);
      console.log(time2 - time1, time2 - time1 > 5000); // true for several times, about 5%
});
```

superagent: 1.8.3
node: 6.1.0

**Comment by pornel** [comment]
How bit is the delay?

Some delay is expected, as `setTimeout` in JS isn't exact, especially if there are many other things happening on the main event loop.

**Comment by willin** [comment]
server side i use superagent to request remote api. timeout 5s
client(browser) side i use superagent to request local api ⬆️. timeout 10s

client side exceed timeout several times, and i have no idea about why it goes like this.

**Comment by pornel** [comment]
I don't see what I can do about it. Please make a pull request if you think it needs a fix.
