### ISSUE TITLE
redirect with 300 response(statuscode: 300)

### ISSUE THREAD

**Issue by haocs** [visionmedia/superagent#993]
Currently, super agent supports auto redirect with response [301, 302, 303, 305, 307, 308] but response with 300 is not redirected. Is there a reason not supporting 300?

**Comment by pornel** [comment]
Yes, because 300 is not a redirect, but application-specific list of available choices to choose from manually.

**Comment by haocs** [comment]
@pornel - I see, thank you for the clarification. Is there a way to config super agent to follow 300 redirect?

**Comment by pornel** [comment]
No, sorry, there isn't. You'll have to read the location header and make another request yourself.
