### ISSUE TITLE
Where does the hasListeners method come from?

### ISSUE THREAD

**Issue by tomprats** [visionmedia/superagent#995]
I'm getting an error due to `hasListeners` 

> this.hasListeners is not a function

It's coming from client.js on line 785
https://github.com/visionmedia/superagent/blob/master/lib/client.js#L785

I'm wondering where this is supposed to be defined, if through a dependency or the browser. Any help would be appreciated!

**Comment by pornel** [comment]
This is added by `Emitter(Request.prototype);`
