### ISSUE TITLE
"Access-Control-Allow-Origin"  Error

### ISSUE THREAD

**Issue by lioralt** [visionmedia/superagent#996]
Hi
i'm getting the following error:

XMLHttpRequest cannot load '<api endpoint>' . No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin '<application entry point url>' is therefore not allowed access.

what can i do in order to solve it ?

Thanks!

**Comment by focusaurus** [comment]
You need to configure [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) properly on your server and browser code. Closing this issue as it is not a superagent bug.

**Comment by lioralt** [comment]
Once configuring CORS on my server side, do i need to change something on my superagent side for it to work ?

**Comment by focusaurus** [comment]
No. Most client side CORS behavior is implemented in the browser itself.
